src/database/DataTypes/Item.js
src/database/DataTypes/ItemBatch.js
src/database/utilities/index.js
src/database/utilities/utilities.js

Refactors dailyUsage as described in #406.
fixes #406

#406 usage aggregation logic fix

---

src/dataMigration.js

See https://github.com/sussol/mobile/pull/480/files for the reason this is required

Add all finalised data to sync queue on data migration

---

src/globalStyles/loadingIndicatorStyles.js

Make sure loading indicator displays over the top of the finalise modal

---

src/pages/CustomerInvoicesPage.js
src/pages/SupplierInvoicesPage.js

Now we have multiple suppliers across invoices, it is very helpful to
see which invoice is from which supplier

Add 'Supplier' column to supplier invoices page

---

src/sync/incomingSyncUtils.js

Refactor a little bit of redundant code in sync

---

package.json
src/main.js
src/sync/reducer.js
yarn.lock

See https://github.com/edmofro/redux-persist-error-handler

Use redux-persist-error-handler to avoid infinite crash loop

---

src/main.js

Fix pages with complex nav state becoming unresponsive due to redux-persist

---

src/pages/RealmExplorer.js

* Can now filter selected table

Filtering in realm explorer

---

package.json
src/sync/outgoingSyncUtils.js

From Issue: https://github.com/sussol/mobile/issues/530

#530 fix undefined otherStoreName in requisition

---

package.json
src/mSupplyMobileApp.js
src/pages/CustomerInvoicePage.js
src/pages/CustomerInvoicesPage.js
src/pages/CustomerRequisitionPage.js
src/pages/CustomerRequisitionsPage.js
src/pages/StockPage.js
src/pages/StocktakeEditPage.js
src/pages/StocktakeManagePage.js
src/pages/StocktakesPage.js
src/pages/SupplierInvoicePage.js
src/pages/SupplierInvoicesPage.js
src/pages/SupplierRequisitionPage.js
src/pages/SupplierRequisitionsPage.js
src/pages/expansions/StocktakeEditExpansion.js
src/sync/PostSyncProcessor.js
src/sync/Synchroniser.js
src/widgets/ExpiryTextInput.js

#538 remove autobind, refactor functions to arrow notation methods

---

src/database/DataTypes/Transaction.js
src/database/index.js
src/database/utilities/index.js

#521 Refactor and add supplier inv number reuse

---

src/mSupplyMobileApp.js
src/sync/SyncModal.js

Fixes hardware back button navigating/closing app rather than dismissing modal #355 #516 
Shows waiting sync count #346

#355 modal fixes

---

src/database/DataTypes/Name.js
src/database/DataTypes/Transaction.js
src/pages/index.js

fixes #532 
Can check commit wise to avoid prettier changes. Will comment on actual changes.
Got borken somewhere in in #430 merge.

#532 customer invoice prune and validation

---

src/localization/modalStrings.js
src/localization/navStrings.js
src/localization/pageInfoStrings.js
src/pages/StocktakeEditPage.js
src/pages/StocktakeManagePage.js
src/pages/StocktakesPage.js

Can add comment and edit name in stocktake edit page

Add comment to stocktake

---

src/database/DataTypes/StocktakeItem.js
src/pages/StockPage.js

Fixes https://github.com/sussol/mobile/issues/579
Fixes https://github.com/sussol/mobile/issues/573

#579-and-#573

---

src/sync/outgoingSyncUtils.js

Fixes https://github.com/sussol/mobile/issues/584

#584 fix one day bug

---

src/pages/SupplierInvoicePage.js
src/pages/expansions/StocktakeEditExpansion.js

Fixes https://github.com/sussol/mobile/issues/588

#588 fix expiry dat glitches

---

src/database/DataTypes/Stocktake.js
src/database/DataTypes/StocktakeItem.js

Fixes https://github.com/sussol/mobile/issues/601

#69-Allow-Finalising-of-zero-difference-stockake

---

package.json
src/dataMigration.js
src/widgets/OnePressButton.js
src/widgets/index.js
src/widgets/modals/ConfirmModal.js

This PR has migration code to fix inventory adjustments with duplicate TransactionBatches (i.e. having the same ItemBatch)

#574 Restrict Confirm Modal Button To One Press

---

package.json
src/database/DataTypes/Stocktake.js
src/widgets/modals/FinaliseModal.js
yarn.lock

Sort of a fix for #629 
Stops it finalising but still a problem with race condition. Potential for a big refactor to fix it properly.

#629 Throw errors on erroneous finalise

---

src/mSupplyMobileApp.js
src/pages/GenericPage.js

#xxxx tablet re-render optimisation

---

package.json
src/dataMigration.js
src/utilities/compareVersions.js
src/utilities/index.js

I’ve checked, migration code works, rc1 to rc10

Update data migration

---

src/database/UIDatabase.js

filter out own store's name ID

---

src/sync/incomingSyncUtils.js

fixed with isNaN check
fixes #780

#780 Sync Error: Value not convertible to a number

---

src/database/utilities/mergeRecords.js

Fixes #779 
Fixed TransactionBatches not merging correctly (and prettier formatting..). Actual addition are lines 113-119.

Add TransactionBatch merging fix

---

src/database/DataTypes/Transaction.js

Fixes #783 
- Customer Invoice > Add Master List Items 
- Exclude Items from combined MasterList that are not visible in the store
- Done as per discussion with @ujwalSussol

Customer Invoice - Add Master List Items - Exclude Items from combined MasterList that are not visible in the store

---

src/sync/incomingSyncUtils.js

Fixes #786
- Since the original code seems to be a typo.

#786 Incoming sync sets cost price based on sell price on item batch

---

package.json
yarn.lock

fixes #624 
via https://github.com/sussol/react-native-generic-table-page/pull/15

use latest react-native-generic-table-page

---

src/database/DataTypes/Transaction.js

#808 fix item.batches undefined on sync initialisation

---

src/database/DataTypes/MasterList.js
src/database/DataTypes/Period.js
src/database/DataTypes/PeriodSchedule.js
src/database/DataTypes/Requisition.js
src/database/schema.js
src/sync/createInternalRecord.js
src/sync/incomingSyncUtils.js
src/sync/outgoingSyncUtils.js
src/sync/syncTranslators.js

Fixes #824 
Adds additional sync logic, schema update and setters/getters for new IC tables.

#824 getters and setters

---

src/database/DataTypes/ItemBatch.js
src/database/DataTypes/TransactionBatch.js
src/database/schema.js
src/database/utilities/createRecord.js
src/sync/incomingSyncUtils.js
src/sync/outgoingSyncUtils.js

Fixes #832.
Tested working with latest desktop structure (RC50).

#832 handle donors

---

src/sync/outgoingSyncUtils.js

#852 - fix dodgy if statement

---

src/widgets/AutocompleteSelector.js
src/widgets/modals/GenericChooseModal.js

Fixes #856 
- Adds `GenericChooseModal` component
- Updates `AutoCompleteSelector` to allow for arrays and empty arrays

#856 generic choose modal

---

src/sync/incomingSyncUtils.js

#861 fix sanity check in sync when checking cannotBeBlank fields

---

src/sync/incomingSyncUtils.js

#863 fix description field on Location and LocationType

---

src/widgets/SimpleTable.js
src/widgets/StackedTables.js
src/widgets/index.js

Fixes #871 
Just a simple table component. Can change colours etc.
Also adds a 'StackedTables' component which evenly spreads `SimpleTable` components. Could be overkill.

Simple table component

---

src/database/utilities/createRecord.js
src/pages/SupplierRequisitionsPage.js
src/settings/index.js
src/sync/incomingSyncUtils.js
src/sync/syncTranslators.js
src/widgets/withOnePress.js

Fixes #887.
Adds lead time to supplier requisition calculations.

Add lead time to daysToSupply

---

src/database/utilities/createRecord.js
src/pages/StocktakeEditPage.js
src/pages/StocktakesPage.js
src/utilities/byProgram.js
src/widgets/modals/ByProgramModal.js
src/widgets/modals/StocktakeBatchModal.js
src/widgets/withOnePress.js

@andreievg 
Fixes bugs:
- no periodScheduleName for a program
- fix incorrect prop names for generic choose modal
- creating a stocktake incorrectly

Add bug fixes

---

src/pages/SupplierInvoicePage.js

Fixes #894 
Replaces `GenericChoiceList` for `AutoCompleteSelector` for `Location` selection.

#894 SupplierInvoicePage: GenericChoiceList over AutoCompleteSelector

---

src/database/DataTypes/Location.js
src/database/DataTypes/LocationType.js
src/pages/VaccineModulePage.js
src/sync/incomingSyncUtils.js
src/utilities/modules/vaccines.js

@joshxg, this pr will have other additions, opening it so that comments can be made

#874 [Refinements] vaccine modul page

---

src/widgets/modals/ByProgramModal.js

fixes #928
PR is into 921-regimen-data-bug, as this seems to be the most stable branch atm

IC bug fix when creating general order

---

src/database/DataTypes/Item.js
src/sync/outgoingSyncUtils.js
src/utilities/modules/vaccines.js

More touchups

---

src/database/DataTypes/RequisitionItem.js

#950 customer requisition null checks 

---

src/settings/MobileAppSettings.js
src/sync/incomingSyncUtils.js

Fixes #956 
See issue for reproduction/testing

clean and validate incoming objects in JSON string

---

src/sync/incomingSyncUtils.js

Fixes #958 
Simple spelling mistake

Add fix for incomingSync

---

src/pages/StocktakesPage.js

Fix #962 condition for showing program dialog in stocktakes

---

src/database/utilities/createRecord.js
src/pages/StocktakeManagePage.js
src/pages/StocktakesPage.js

Fixes #960
**No programs on store**
**With programs on store**

#960 fix undefined stocktake name

---

src/widgets/modals/ByProgramModal.js

Fixes #949 
Simple query change

Add correct query for suppliers in byProgramModal

---

src/utilities/modules/vaccines.js

Fixes #979 
- Just simply uses either the `sensorLogs.length`, 30 or the quotient between the time now and the oldest `sensorLog` over 9 hours

Add number of datapoints logic

---

src/pages/StocktakeEditPage.js

Fixes #994 
Merged into develop accidentally (#1005)

Add correct conditional

---

src/pages/StocktakeEditPage.js
src/widgets/modals/StocktakeBatchModal.js

#1013 was merged to wrong base

#1011 fix reason saving to wrong row

---

android/app/build.gradle

Fixes #1030 
Simple downgrading of google play services due to a recent release bringing breaking changes
Need to look into managing dependencies more closely - keeping on top of releases and finding exactly what we need to do to get 100% up to date

#1030 Forced downgrade of google play services

---

src/sync/PostSyncProcessor.js

Fixes #945 
See #1052 - duplicate PR based off master

#945 Setting sync promise rejection #1052 Duplicate

---

src/database/UIDatabase.js
src/pages/MenuPage.js
src/utilities/fileSystem.js
src/utilities/index.js
src/utilities/requestPermission.js

Fixes #1038 
Please see #1038 
Duplicate PR based off master

#1038 External storage permissions #1061 Duplicate

---

src/pages/SupplierRequisitionPage.js
src/widgets/modals/ByProgramModal.js

Fixes #1081
Just fixes the backwards key/title usage on a cell lookup
N/A

#1081 Add correct key usage

---

src/widgets/DataTable/CheckableCell.js
src/widgets/DataTable/EditableCell.js
src/widgets/DataTable/Row.js
src/widgets/DataTable/TouchableCell.js

Fixes #1100 
Quick typo fix
N/A

#1100 Fixes a typo in propTypes

---

src/navigation/ReduxNavigation.js

Fixes #1122 
- Whenever `mSupplyMobileAppContainer` re-renders, `ReduxNavigator` re-renders. When `ReduxNavigator` re-renders, a new `ReduxContainer` is created and generates a new navigation stack.
- When the new navigation stack is created, all components currently in that stack are mounted, and when the old navigation stack gets garbage collected, the components in the stack are unmounted.
Example of navigating from `CustomerInvoicePage` back to `CustomerInvoicesPage`
1. Render root component (Creating a new navigation stack, re-renders due to prop changes from being subscribed to redux which passes new navigation state in props)
2. Mount a new `MenuPage` (From the new navigation stack)
3. Render the new `MenuPage`  
4. Mount a new `CustomerInvoicesPage` (From the new navigation stack) …

#1122 Navigating unmounts components

---

src/database/utilities/createRecord.js

Fixes #1151
- Reapplied return value for `createInventoryAdjustment`
N/A

#1151 Finalizing stocktakes

---

package.json

Fixes #1083 
Quick scripty
Could write a windows one too?

#1083 cache cleaning script

---

src/pages/CustomerInvoicePage.js
src/pages/CustomerInvoicesPage.js
src/pages/dataTableUtilities/actions.js
src/pages/dataTableUtilities/columns.js
src/pages/dataTableUtilities/reducer/getReducer.js
src/pages/dataTableUtilities/reducer/reducerMethods.js
src/utilities/getModalTitle.js
src/utilities/sortDataBy.js
src/widgets/DataTable/Row.js

Fixes #1125 
Refactor of customer invoices to use new data table and page reducer
**Problems that @joshxg might have done in other branches that I don't want to rework:**
- "STATUS" column needs localisation
- "ENTRY DATE" column omitted cause new code useful to it in another PR 

#1125 customer invoices page new data table

---

src/pages/SupplierInvoicePage.js
src/pages/dataTableUtilities/actions.js
src/pages/dataTableUtilities/columns.js
src/pages/dataTableUtilities/pageInfo.js
src/pages/dataTableUtilities/reducer/getReducer.js
src/pages/dataTableUtilities/reducer/reducerMethods.js
src/pages/index.js
src/utilities/finalisation.js
src/utilities/index.js
src/utilities/sortDataBy.js
src/widgets/NewExpiryDateInput.js

Fixes #1132 
- Refactors SupplierInvoicePage to use the new `DataTable`
N/A

#1132 New SupplierInvoicePage

---

src/pages/StocktakesPage.js
src/pages/SupplierRequisitionsPage.js
src/reducers/ByProgramReducer.js
src/widgets/index.js
src/widgets/modals/ByProgramModal.js

Fixes #1095 
Second part of #1095 
- Adds substantial changes to `ByProgramModal`, using `useReducer` and other hooks. I think this simplifies the logic a lot
- Also reduces the number of renders a lot, otherwise the logic should be exactly the same
- Decided not to split this into a requisition and stocktake modal, as it was around 20 lines more for both
Will be in last PR - #1098
N/A

#1095 by program refactor  2

---

src/reducers/ByProgramReducer.js
src/widgets/modals/ByProgramModal.js

Fixes #1184 
Couple of fixes
N/A

#1184 Broken byProgramModal

---

src/database/DataTypes/Requisition.js
src/database/DataTypes/StocktakeBatch.js
src/database/DataTypes/StocktakeItem.js
src/localization/modalStrings.js
src/pages/CustomerRequisitionPage.js
src/pages/StocktakeEditPage.js
src/pages/dataTableUtilities/actions/cellActions.js
src/pages/dataTableUtilities/actions/getPageActions.js
src/pages/dataTableUtilities/actions/tableActions.js
src/pages/dataTableUtilities/getColumns.js
src/pages/dataTableUtilities/getPageInfoColumns.js
src/utilities/sortDataBy.js
src/widgets/DataTable/DataTable.js
src/widgets/modals/DataTablePageModal.js
src/widgets/modals/NewStocktakeBatchModal.js
src/widgets/modals/RegimenDataModal.js

Fixes #1126 
- Refactors `CustomerRequisitionPage` to use new `DataTable`
- Simple refactor - essentially the same as `SupplierRequisitionPage`, just with different columns, buttons and no program logic!
See #1043 
N/A

#1126 CustomerRequisitionPage refactor -- 12

---

src/database/DataTypes/Requisition.js
src/database/DataTypes/StocktakeBatch.js
src/database/DataTypes/StocktakeItem.js
src/localization/modalStrings.js
src/navigation/actions.js
src/pages/CustomerRequisitionPage.js
src/pages/CustomerRequisitionsPage.js
src/pages/StocktakeEditPage.js
src/pages/dataTableUtilities/actions/cellActions.js
src/pages/dataTableUtilities/actions/getPageActions.js
src/pages/dataTableUtilities/actions/tableActions.js
src/pages/dataTableUtilities/getColumns.js
src/pages/dataTableUtilities/getPageInfoColumns.js
src/utilities/sortDataBy.js
src/widgets/DataTable/DataTable.js
src/widgets/modals/DataTablePageModal.js
src/widgets/modals/NewStocktakeBatchModal.js
src/widgets/modals/RegimenDataModal.js

Fixes #1127
- Refactors `CustomerRequisitionsPage` to use the new data table.
Very simple page - very similar to `SupplierRequisitionsPage`, without all the program stuff. Also has no creation logic (only come from sync) and no deletion logic.
See #1043

#1129 CustomerRequisitionsPage refactor -- 11

---

src/database/DataTypes/Requisition.js
src/database/DataTypes/StocktakeBatch.js
src/database/DataTypes/StocktakeItem.js
src/localization/modalStrings.js
src/navigation/actions.js
src/pages/CustomerInvoicePage.js
src/pages/CustomerInvoicesPage.js
src/pages/CustomerRequisitionPage.js
src/pages/CustomerRequisitionsPage.js
src/pages/StocktakeEditPage.js
src/pages/SupplierInvoicePage.js
src/pages/SupplierInvoicesPage.js
src/pages/SupplierRequisitionPage.js
src/pages/dataTableUtilities/actions/cellActions.js
src/pages/dataTableUtilities/actions/getPageActions.js
src/pages/dataTableUtilities/actions/tableActions.js
src/pages/dataTableUtilities/getColumns.js
src/pages/dataTableUtilities/getPageInfoColumns.js
src/pages/index.js
src/utilities/finalisation.js
src/utilities/index.js
src/utilities/sortDataBy.js
src/widgets/DataTable/DataTable.js
src/widgets/DropDownCell.js
src/widgets/ToggleBar/ToggleBar.js
src/widgets/modals/DataTablePageModal.js
src/widgets/modals/NewStocktakeBatchModal.js
src/widgets/modals/RegimenDataModal.js

Fixes #1219 
- PR fixes
- Added a `stateInitialiser` function
- Added use of `useRecordListener` custom hook
- Added use of `PageActions`
- Explicitly defined callbacks asa named functions
See #1043 
Starting to think a custom hook for all the callbacks wouldv'e been a good idea.. they're all the same, could just pass `dispatch` and `PageActions` and be passed all the callbacks needed 🤷‍♀

#1219 SupplierInvoicePage fixes -- 7

---

src/hooks/usePageReducer.js
src/pages/CustomerInvoicePage.js
src/pages/StocktakeManagePage.js
src/widgets/DataTable/Row.js
src/widgets/modals/RegimenDataModal.js

Fixes #1247 
- Just added some missing dependencies to some `useCallbacks`
See #1043 
N/A

#1247 Missing deps to useCallbacks

---

src/hooks/useSyncListener.js

Fixes #1246 
- Changes database access to `BaseDatabase` rather than `UIDatabase`
See #1043 
N/A

#1246 useSyncListener database change

---

src/database/DataTypes/Stocktake.js
src/globalStyles/newDataTableStyles.js
src/navigation/actions.js
src/pages/CustomerInvoicesPage.js
src/pages/CustomerRequisitionPage.js
src/pages/StocktakeEditPage.js
src/pages/StocktakeManagePage.js
src/pages/StocktakesPage.js
src/pages/SupplierInvoicePage.js
src/pages/SupplierInvoicesPage.js
src/pages/SupplierRequisitionPage.js
src/pages/SupplierRequisitionsPage.js
src/widgets/DataTable/DataTableRow.js

Fixes #1252 
- Add comments
- Added correct use of `SearchBar` component, removing passing default props
- Couple other small fixes from PRs
See #1043 
N/A

#1252 Small updates to DataTable branch

---

src/widgets/modals/ItemDetails.js

Fixes #1268 
- Adds a condition on the content of the modal rather than the modal itself so that the animation runs when unmounting
- Also fixed a style oopsies
See #1043 
N/A

#1268 ItemDetails modal animation

---

src/pages/index.js
src/utilities/finalisation.js
src/utilities/index.js

Fixes #1276 
- Adds back the customer requisition finalization check code
See #1043 
N/A

Add customer requisition finalise check code

---

src/pages/CustomerRequisitionsPage.js
src/pages/StockPage.js
src/pages/SupplierRequisitionsPage.js

Fixes #1273 
- Fixes requisition (plural) pages inital sort
- Fixes `StockPage` filtering
See #1043 
N/A

#1273 sorting and filtering

---

src/pages/StocktakeEditPage.js

Fixes #1274 
- Fixes using a function for `StocktakeManageButton` as if it was a variable
See #1043 
N/A

#1274 Stocktake manage button

---

src/widgets/DataTable/TouchableCell.js

Fixes #1232 
- Add wrapper to catch events before they can propogate
See #1043 
Not sure of another use case for this. If there is, Will make this a more defined component. Bit OTT to do it now

#1232 Touchable Cell event propogation

---

src/pages/dataTableUtilities/getPageInitialiser.js

Fixes #1287 
- Renamed a couple fields as per #1266 
- Added correct filtering keys to be consistent with pre-factor
maybe parameter should just be `pageObject` but it's a bit more descriptive
See #1043 
N/A

#1287 Correct filtering

---

src/widgets/icons.js

Fixes #1293 
- Change the colour of the unchecked remove icon (See issue for pics)
See #1043 
N/A

#1293 Distinctive icon colour

---

src/widgets/DataTablePageView.js

Fixes #1298 
- Wraps `DataTablePageView` with a touchable which will dismiss the keyboard if it propogates up that high
See #1043 
N/A

#1298 Keyboard dismissing

---

src/pages/CustomerInvoicePage.js
src/pages/CustomerInvoicesPage.js
src/pages/CustomerRequisitionPage.js
src/pages/StocktakeEditPage.js
src/pages/StocktakeManagePage.js
src/pages/StocktakesPage.js
src/pages/SupplierInvoicePage.js
src/pages/SupplierInvoicesPage.js
src/pages/SupplierRequisitionPage.js
src/pages/SupplierRequisitionsPage.js
src/widgets/PageButton.js
src/widgets/ToggleBar/ToggleBar.js

Fixes #1302
Adjusted all the buttons in all pages (see issue). Not completely optimized for all, taking a little balance between ugly code and minimal rendering as all of this is a pretty small optimization.
See #1043 
Would realllly like to refactor buttons in a general sense to make render optimzations a lot easier i.e. not passing a object to `ToggleBar`. Could also make a container excepting a config to make buttons and their logic as dynamic as columns/page info

#1302 Unmounting buttons

---

src/database/DataTypes/StocktakeBatch.js
src/database/DataTypes/StocktakeItem.js
src/pages/dataTableUtilities/actions/cellActions.js
src/pages/dataTableUtilities/getPageInitialiser.js
src/widgets/modals/StocktakeBatchModal.js

Fixes #1311 
- Changes logic for reasons to be correct
- Minor adjustments to `StocktakeBatchModal` - changing pageinfo/page button to be better memoized/used
One of the things I've done heaps and heaps and is hard to start over and think about it fresh, so would be interested in other ways of doing this as I hate how it's done now
See #1043 
N/A

#1311 Apply reasons broken

---

src/widgets/PageButton.js

Fixes #1323 
- Updates `PageButton` `propsAreEqual` to account for closures in button `onPress`
N/A

#1323 Periods not assigned

---

dev_scripts/deploy.sh
package.json

Fixes #1319.
Accidentally branched off data table 😢 . Since this is going into develop soon, probably better that trying to do a potentially messy rebase.
Wrote a quick script to help me test mobile changes, figured may as well add to `dev_scripts`.
N/A.

#1319 add deploy.sh

---

src/pages/SupplierRequisitionPage.js

Fixes #1338 
- Just added corrected dependency for `PageInfo` on `SupplierRequisitionPage`
N/A

#1338 SupplierRequisitionPage Months of stock

---

src/database/DataTypes/Stocktake.js
src/database/DataTypes/StocktakeBatch.js
src/database/DataTypes/StocktakeItem.js
src/pages/StocktakeManagePage.js
src/widgets/DataTable/DataTableRow.js

#1343 stocktake updates duplicate

---

src/pages/dataTableUtilities/reducer/tableReducers.js

Fixes #1402
- Just add a trim to the filtering string. Adding here is the least intrusive and explanatory imo
N/A

#1402 Trim filtering terms

---

src/database/DataTypes/RequisitionItem.js

Fixes #1407 
- Just adding the correct parameter for the query
This pricing doesn't seem right but was how I was told to do it. Can change it later when we get told it's incorrect!

#1407 add correct query parameter

---

src/sync/Synchroniser.js

Fixes #1454.
Cherry-pick of #1456 for master.
See #1456.

#1454 add headers to Synchroniser bugsnag

---

src/authentication/SyncAuthenticator.js
src/authentication/UserAuthenticator.js
src/settings/MobileAppSettings.js
src/settings/index.js
src/sync/Synchroniser.js

Fixes #1449.
Hotfix for master.
See #1452.
See #1452.
Tests should be done on a build.

#1449 hotfix remove hardware id settings

---

src/Store.js
src/navigation/actions.js
src/pages/CustomerInvoicePage.js
src/pages/CustomerInvoicesPage.js
src/pages/CustomerRequisitionPage.js
src/pages/CustomerRequisitionsPage.js
src/pages/StockPage.js
src/pages/StocktakeEditPage.js
src/pages/StocktakeManagePage.js
src/pages/StocktakesPage.js
src/pages/SupplierInvoicePage.js
src/pages/SupplierInvoicesPage.js
src/pages/SupplierRequisitionPage.js
src/pages/SupplierRequisitionsPage.js
src/pages/dataTableUtilities/actions/cellActions.js
src/pages/dataTableUtilities/actions/getPageActions.js
src/pages/dataTableUtilities/actions/pageActions.js
src/pages/dataTableUtilities/actions/rowActions.js
src/pages/dataTableUtilities/actions/tableActions.js
src/pages/dataTableUtilities/getPageInitialiser.js
src/pages/dataTableUtilities/selectors.js
src/reducers/PagesReducer.js
src/reducers/index.js

Fixes #1451 
- Changes all pages to use redux over `usePageReducer`
N/A

#1451 use redux in all pages

---

src/mSupplyMobileApp.js

Fixes #1426 
- Just adds debouncing. I've been double clicking a lot and it's super annoying 🤣 
N/A

#1426 Navigation debouncing

---

src/pages/CustomerInvoicePage.js
src/pages/CustomerRequisitionPage.js
src/pages/StocktakeManagePage.js
src/pages/SupplierInvoicePage.js
src/pages/SupplierInvoicesPage.js
src/reducers/PagesReducer.js

Fixes #1515 
- Fixes parameter mistakes in each of the pages listed in the issue
N/A

#1515 Parameter fixes

---

src/navigation/actions.js
src/pages/DispensingPage.js
src/pages/PatientsPage.js
src/pages/dataTableUtilities/getColumns.js
src/pages/dataTableUtilities/getPageInitialiser.js
src/pages/index.js

Fixes #1498 
- Adds a very basic `Patients` page, just listing patients
N/A

#1498 patients page

---

src/pages/RealmExplorer.js

Fixes #1533 
- Removes flat call
N/A

Add removal of flat

---

src/database/utilities/createRecord.js

Fixes #1567 
- Very basic initial create methods for the different `Transaction` and `TransactionBatch`'s.
- Keeping them separate for now, will reevaluate when fully implemented to see if they can be consolidated into a single method each (for `Transaction`/`Batch`).
- Still plenty of things to touch up but helpful to have something in to iterate on and make smaller focused issues/pr's - i.e. correct invoice numbers, times, linking customer credit lines to the correct trans line and any other fields that should be filled when syncing with desktop.
N/A
N/A

#1567 Create methods for rc/ps/cc and their lines

---

src/database/DataTypes/InsurancePolicy.js
src/database/DataTypes/Name.js
src/database/DataTypes/Transaction.js
src/database/UIDatabase.js

Fixes #1566 
- Adds a few `UIDatabase` cases for ease of coding later
N/A
N/A

#1565 uidatabase payment helpers

---

src/globalStyles/pageStyles.js
src/pages/CustomerInvoicePage.js
src/widgets/MultiSelectList.js
src/widgets/ResultRow.js
src/widgets/SearchBar.js

Fixes #1574 
Went a little out of scope, oops
- Added dependencies to each `useCallback` call
- Removed un-needed styles
- Added use of internal `SearchBar` component rather than the `react-native-ui-component` one
**This PR effects the `Add From MasterList` button on both the `SupplierRequisition` and `CustomerInvoice` pages**
N/A

#1574 useCallback dependencies for MultiSelect modal

---

dev_scripts/reset.sh
package.json

#1589 Added script to reset mobile app data

---

src/widgets/modals/DataTablePageModal.js

Fixes #1596 
- Fixes a merge mishap which was preventing modals (i.e. customer invoice comment edit) from opening
N/A
N/A

#1596 Merge mishap

---

src/widgets/StepsTracker.js
src/widgets/index.js

Fixes #1598 
- Simple tracker component
- Open to ideas to make this look less terrible!
N/A
Terrible name

#1598 steps tracker component

---

package.json
src/widgets/StepsTracker.js
src/widgets/TabNavigator.js
src/widgets/index.js

Fixes #1597 
- Adds a basic `TabNavigator` component
- Basis of a `Wizard` or potentially other things component
N/A
N/Aa

#1597 TabNavigator component

---

src/globalStyles/index.js
src/widgets/PopoverDropDown.js
src/widgets/index.js

Fixes #1603 
- Adds a basic `PopOverDropDown` component
Bit messy and more hard coded than I'd like. Not very flexible or dynamic but good to have a base component for when the concrete use case comes
(The surrounding border seemed more prominent in non-gif format 🤷‍♂ )
N/A
N/A

#1603 PopoverDropDown

---

package.json
src/utilities/finalisation.js

v3.1.1
#1683 
- Just includes #1681 - which is a crash on finalising requisitions

v3.1.1 Release

---

android/gradle.properties

Fixes #1679 
- Quick change to the java heap size
N/A

#1679 Java heap size

---

src/globalStyles/index.js
src/widgets/AutocompleteSelector.js
src/widgets/SearchBar.js

Fixes issue #1404
Import searchBar from internal file rather than from third part to make it more flexible on changing
Type customer's name on the search bar. check that the filter is working as expected. If it does click on its name or clear that search bar by pressing the 'x' button on the right.
The searchBar is not case sensitive, so don't know it will affect on other area where case sensitivity might be crucial across codebase.

#1404 Use of new SearchBar Component in AutoCompleteSelector

---

src/pages/MenuPage.js

Fixes #1719 
- Adds a change from #1698 
N/A

#1719 Correct MenuPage DependenciesLists

---

src/navigation/actions.js

Fixes #1699 
- Corrected route name for navigating to the dispensary from the menu page
N/A
N/A

#1699 Updated navigation action

---

src/widgets/BarChart.js

Fixes #1741
Add `BarChart` component to illustrate bar chart graphs on the dashboard. 
- It shares a similar skeleton than `LineChart`, `PieChart` and `ReportTable`

#1741 Create BarChart component

---

src/widgets/ReportChart.js
src/widgets/ReportTable/index.js
src/widgets/index.js

Fixes #1713
This component manages which is the report that is needed to be render (PieChart, BarChart, LineChart, TableReport) according to its `Type`.

#1713 Create ReportChart component

---

src/pages/PrescriptionPage.js
src/pages/dataTableUtilities/getColumns.js
src/widgets/CircleButton.js
src/widgets/DetailRow.js
src/widgets/DropdownRow.js
src/widgets/PrescriptionCart.js
src/widgets/PrescriptionCartRow.js
src/widgets/StepperInput.js
src/widgets/StepperRow.js
src/widgets/icons.js

Fixes #1738 
- Adds `PrescriptionCart` and `PrescriptionCartRow` components
- Again not great UI yet but I want to work on something else for a bit and come back a bit fresher for the UI.. I hate styling css and styling :(  🤣  
- Also a lot of callbacks are not correctly hooked up. Will be adding reducer cases and actions in a new issue without UI stuff
N/A
`PrescriptionPage` still messy. Need to sort out the `Summary`,  then can be tidied up

#1738 shopping cart component

---

src/pages/StockPage.js
src/widgets/bottomModals/index.js
src/widgets/modals/index.js

Fixes #1774 
- Just adds an index file for `bottomModals` folder
N/A

#1774 index file for bottom modals

---

src/database/DataTypes/Item.js
src/database/DataTypes/ItemDirection.js
src/database/DataTypes/TransactionItem.js
src/database/utilities/createRecord.js

Fixes #1692 
- Adds some simple getters and setters for working with abbreviations!
N/A
N/A

#1692 Direction & Abbreviation getter & setters

---

src/database/DataTypes/Item.js
src/database/DataTypes/ItemDirection.js
src/database/DataTypes/TransactionItem.js
src/database/UIDatabase.js
src/database/utilities/createRecord.js

Fixes #1811 
- Changes the query for CI's to not exclude prescriptions
N/A
- Not used anywhere else at the moment.

#1811 CustomerInvoicesPage to show prescriptions

---

src/actions/FinaliseActions.js
src/database/DataTypes/Item.js
src/database/DataTypes/ItemDirection.js
src/database/DataTypes/TransactionItem.js
src/database/UIDatabase.js
src/database/utilities/createRecord.js
src/mSupplyMobileApp.js
src/pages/PrescriptionPage.js
src/reducers/FinaliseReducer.js
src/reducers/index.js
src/widgets/PrescriptionCartRow.js
src/widgets/PrescriptionSummaryRow.js
src/widgets/Tabs/PrescriptionConfirmation.js

Fixes #1805 
- Simply changes the wrapping component to handle the gesture for scrolling correctly.
N/A
N/A

#1805 Cannot scroll prescription cart

---

src/actions/FinaliseActions.js
src/database/DataTypes/Item.js
src/database/DataTypes/ItemDirection.js
src/database/DataTypes/TransactionItem.js
src/database/UIDatabase.js
src/database/utilities/createRecord.js
src/mSupplyMobileApp.js
src/pages/PrescriptionPage.js
src/reducers/FinaliseReducer.js
src/reducers/PrescriptionReducer.js
src/reducers/index.js
src/selectors/prescription.js
src/widgets/PrescriptionCartRow.js
src/widgets/PrescriptionSummaryRow.js
src/widgets/StepperRow.js
src/widgets/Tabs/ItemSelect.js
src/widgets/Tabs/PrescriptionConfirmation.js

Fixes #1800 
- Adds a selector which checks if the current prescription has items and quantity applied.
- Adds a `createRecord` parameter to set an initial value of the `TransactionItem`.. this has been set to 1 for a prescription, and also adjusted the lower limit of the stepper.
N/A
N/A

#1800 only next with items

---

src/actions/FinaliseActions.js
src/database/DataTypes/Item.js
src/database/DataTypes/ItemDirection.js
src/database/DataTypes/TransactionItem.js
src/database/UIDatabase.js
src/database/utilities/createRecord.js
src/mSupplyMobileApp.js
src/pages/PrescriptionPage.js
src/reducers/FinaliseReducer.js
src/reducers/PrescriptionReducer.js
src/reducers/index.js
src/selectors/prescription.js
src/widgets/PrescriptionCart.js
src/widgets/PrescriptionCartRow.js
src/widgets/PrescriptionSummaryRow.js
src/widgets/StepperRow.js
src/widgets/Tabs/ItemSelect.js
src/widgets/Tabs/PrescriptionConfirmation.js

Fixes #1802 
- Adds usage of a remove items callback to remove/delete items from a prescription
N/A
N/A

#1802 Remove items from a prescription

---

src/actions/FinaliseActions.js
src/actions/PrescriberActions.js
src/database/DataTypes/Item.js
src/database/DataTypes/ItemDirection.js
src/database/DataTypes/TransactionItem.js
src/database/UIDatabase.js
src/database/utilities/createRecord.js
src/mSupplyMobileApp.js
src/pages/PrescriptionPage.js
src/pages/dataTableUtilities/getColumns.js
src/reducers/FinaliseReducer.js
src/reducers/PrescriberReducer.js
src/reducers/PrescriptionReducer.js
src/reducers/index.js
src/selectors/prescription.js
src/widgets/FlexColumn.js
src/widgets/FlexView.js
src/widgets/PrescriptionCart.js
src/widgets/PrescriptionCartRow.js
src/widgets/PrescriptionSummaryRow.js
src/widgets/SimpleTable.js
src/widgets/StepperRow.js
src/widgets/Tabs/ItemSelect.js
src/widgets/Tabs/PrescriberSelect.js
src/widgets/Tabs/PrescriptionConfirmation.js
src/widgets/index.js

Fixes #1793 
- Extracts `PrescriberSelect` to it's own file
- Adds `Searchbar ` `searchTerm` logic
- Adds `SearchBar` component
- Adds a 'create prescriber' button
N/A
N/A

#1793 Prescriber SearchBar

---

src/Store.js
src/actions/DashboardActions.js
src/actions/index.js
src/pages/DashboardPage.js
src/reducers/DashboardReducer.js
src/reducers/index.js
src/widgets/ReportSideBar/ReportSideBar.js
src/widgets/ReportSideBar/ReportSideBarItem.js

Fixes #1715 
- Adds a simple `Dashboard` reducer which just has the current reports and the current report being displayed.
- Simplifies logic and takes state out of components which don't really need it
N/A
N/A

#1715 Dashboard Reducer

---

src/Store.js
src/actions/DashboardActions.js
src/actions/index.js
src/navigation/actions.js
src/navigation/constants.js
src/pages/DashboardPage.js
src/pages/MenuPage.js
src/pages/index.js
src/reducers/DashboardReducer.js
src/reducers/index.js
src/widgets/ReportSideBar/ReportSideBar.js
src/widgets/ReportSideBar/ReportSideBarItem.js

Fixes #1817 
- Adds simple navigation from the `MenuPage` to the `DashboardPage`
- Also alphabetically sorted the page imports 🤣 
N/A
N/A

#1817 Dashboard navigation

---

src/reducers/PrescriptionReducer.js
src/sync/incomingSyncUtils.js
src/widgets/DropdownRow.js
src/widgets/PopoverDropDown.js
src/widgets/PrescriptionCart.js
src/widgets/PrescriptionCartRow.js
src/widgets/PrescriptionSummaryRow.js
src/widgets/Tabs/ItemSelect.js

Fixes #1813 
- Adds a simple directions implementation with a drop down for an items directions, and a textinput to type.
- Have created #1815 to tidy up `PrescriptionReducer.js`
- Sneaked in a fix in `incomingSyncUtils` to cast correctly.
- Added localization to issue
- Adds the correct field to display in the summary
- Adds a TextInput rather than a label for the displayed direction. Mainly this is for the simple implementation, as I dont see how this could work well when abbreviations are implemented. I think a modal would be needed which would have an additional drop down to show some directions to add, or something similar.
- The ScrollView wrap is to handle shifting the `TextInput` out of the way/above the keyboard
N/A
- Potentially better to just have `PrescriptionX` components all …

#1813 Simple directions implementation

---

src/widgets/BarChart.js
src/widgets/LineChart.js
src/widgets/PieChart.js
src/widgets/ReportChart.js
src/widgets/ReportSideBar/ReportSideBar.js
src/widgets/ReportSideBar/ReportSideBarItem.js
src/widgets/ReportTable/ReportRow.js
src/widgets/ReportTable/ReportTable.js

Fixes #1751 Fixes #1765 
- Changed up and removed a bunch of styles that weren't needed
- Tidied up propTypes removing all errors (except a key error on the table)
- Removed the multiple `onLayout` calls and passed through `width/height` props
N/A
N/A

#1751 dashboard style cleanup

---

src/pages/DispensingPage.js
src/reducers/PatientReducer.js
src/reducers/PrescriberReducer.js
src/selectors/patient.js
src/selectors/prescriber.js
src/widgets/CircleButton.js
src/widgets/DropdownRow.js
src/widgets/FlexColumn.js
src/widgets/FlexRow.js
src/widgets/FlexView.js
src/widgets/PopoverDropDown.js
src/widgets/PrescriptionCart.js
src/widgets/SimpleLabel.js
src/widgets/StepperInput.js
src/widgets/StepperRow.js
src/widgets/Tabs/PrescriberSelect.js

Fixes #1821 
- Makes the changes from the linked issue!
- Also sneaked in a bunch of prop type fixes to get rid of a lot of warnings..
- Also a missing `editPrescriber` dispatch.. soz!
N/A
N/A

#1821 dispensary review updates

---

src/globalStyles/index.js
src/widgets/PopoverDropDown.js
src/widgets/index.js

Fixes #1834
- Adds and exports `PopoverDropDown` component
N/A
N/A

#1834 PopoverDropDown

---

src/widgets/FormControl.js
src/widgets/FormDateInput.js
src/widgets/ValidationTextInput.js

Fixes #1733 
- Adds tabbing/focus logic for forms
N/A
N/A

#1733 FormControl tabbing order

---

src/widgets/FormControl.js
src/widgets/FormDateInput.js
src/widgets/Tabs/PrescriberSelect.js
src/widgets/ValidationTextInput.js

Fixes #1798 
- Adds debouncing of prescriber select
N/A
N/A

#1798 prescriber debounce

---

android/settings.gradle
package.json
src/database/utilities/createRecord.js
src/utilities/formInputConfigs.js
src/widgets/FormControl.js
src/widgets/FormDateInput.js
src/widgets/Tabs/PrescriberSelect.js
src/widgets/ValidationTextInput.js
src/widgets/icons.js
yarn.lock

Fixes #1825 
- Adds a date picker for entering date of births and corrects the validation
N/A
N/A

#1825 Patient DOB Picker

---

android/settings.gradle
package.json
src/actions/PrescriptionActions.js
src/database/utilities/createRecord.js
src/reducers/PrescriptionReducer.js
src/utilities/formInputConfigs.js
src/widgets/FormControl.js
src/widgets/FormDateInput.js
src/widgets/PrescriptionCart.js
src/widgets/Tabs/ItemSelect.js
src/widgets/Tabs/PrescriberSelect.js
src/widgets/ValidationTextInput.js
src/widgets/icons.js
yarn.lock

Fixes #1815 
- Tidies `PrescriptionReducer` extracting constants to be consistent with other new reducers.
N/A
N/A

#1815 Prescription reducer tidy

---

src/database/DataTypes/IndicatorAttribute.js
src/database/utilities/createRecord.js
src/pages/SupplierRequisitionPage.js
src/pages/dataTableUtilities/getPageInitialiser.js
src/pages/dataTableUtilities/reducer/tableReducers.js
src/utilities/getIndicatorTableData.js
src/utilities/index.js

Fixes #1848.
Add logic for initialising and dispaying indicator values.
Next steps: 
- add logic for updating indicator values. 
- add logic for outgoing sync of indicator values.

#1848 add display indicator values

---

src/localization/generalStrings.json
src/localization/navStrings.json
src/navigation/actions.js
src/pages/MenuPage.js
src/widgets/ReportSideBar/ReportSideBar.js

Fixes #1711
Some needed localized strings were added to the corresponding localization files. Same as the rest of strings, the idea is to remove hardcoded texts and replace them for reusable strings.
Further testing will be taking when the dashboard feature is ready.
Just done in English, but French also translations will be necessary. @alainsussol Would you like to give us a hand with this translations? There is a couple of them added to `navStrings.json` and one in `generalStrings.json`. Will be highly appreciated :-)

#1711 Dashboard localization

---

src/database/DataTypes/TransactionBatch.js
src/selectors/patient.js

Fixes #1868 
- Correctly filters out cash in and cash out batches for patient history
N/A
I don't see anywhere else where this sort of check is needed, but will continue to keep looking as there is surely somewhere..!

#1868 patient history including cash batches

---

src/actions/PaymentActions.js
src/database/DataTypes/Transaction.js
src/database/UIDatabase.js
src/reducers/PaymentReducer.js
src/widgets/PaymentSummary.js
src/widgets/Tabs/PrescriptionConfirmation.js

Fixes #1860 
- Add a payment type drop down
- Offroad: changed the insurance selection to actually apply the insurance policy correctly to the transaction which I forgot about.
- offroad: parameter change in the call to `pay` to correctly pass the value not the currency object
N/A
N/A

#1860 Payment Type selection

---

src/actions/PaymentActions.js
src/database/DataTypes/Transaction.js
src/database/UIDatabase.js
src/reducers/PaymentReducer.js
src/selectors/patient.js
src/selectors/payment.js
src/widgets/PaymentSummary.js
src/widgets/Tabs/PrescriptionConfirmation.js

Fixes #1862 
- Add a insurance selection drop down. This alters the total based on insurance discount.
N/A
This is using a native drop down rather than the rubbish I wrote. I think this is a far better option as it is more fluid and efficient and already handles a few cases that I hadn't implemented yet - i.e. scrolling.

#1862 insurance selection

---

src/actions/PaymentActions.js
src/database/DataTypes/InsurancePolicy.js
src/database/DataTypes/InsuranceProvider.js
src/database/DataTypes/Transaction.js
src/database/UIDatabase.js
src/reducers/PaymentReducer.js
src/selectors/patient.js
src/selectors/payment.js
src/sync/SyncQueue.js
src/sync/incomingSyncUtils.js
src/sync/outgoingSyncUtils.js
src/sync/syncTranslators.js
src/widgets/PaymentSummary.js
src/widgets/Tabs/PrescriptionConfirmation.js

Fixes #1854 
- Adds `InsurancePolicy` to outgoing sync
- Adds `InsurancePolicy`/`InsuranceProvider` to outgoing sync
N/A
N/A

#1854 insurance sync

---

src/Store.js
src/actions/InsuranceActions.js
src/actions/PaymentActions.js
src/pages/DispensingPage.js
src/reducers/InsuranceReducer.js
src/reducers/PaymentReducer.js
src/reducers/index.js
src/selectors/payment.js
src/utilities/formInputConfigs.js
src/widgets/FormControl.js
src/widgets/PaymentSummary.js

Fixes #1735 
- Adds basic insurance form control with just a policy number for family and person. Other fields require new form inputs - toggles and sliders!
N/A
N/A

#1735 add edit insurance modal

---

src/sync/syncTranslators.js

Fixes #1885 
Not much, just add Report to RECORD_TYPES. 😄
Further testing will be taking place when the dashboard feature is ready.

#1885 Add Report to RECORD_TYPES

---

src/utilities/getIndicatorTableData.js

Fixes #1903. Branches off #1877.
Use indicator column codes (see desktop PRs #5031, #5106).
Functional changes only.
N/A.

#1903 update indicators column codes

---

src/actions/PrescriberActions.js
src/actions/PrescriptionActions.js
src/pages/dataTableUtilities/constants.js
src/pages/dataTableUtilities/getColumns.js
src/reducers/PrescriberReducer.js
src/selectors/prescriber.js
src/widgets/DataTable/DataTableRow.js
src/widgets/DataTable/TouchableCell.js
src/widgets/FlexColumn.js
src/widgets/FlexRow.js
src/widgets/PrescriptionInfo.js
src/widgets/SimpleLabel.js
src/widgets/Tabs/PrescriberSelect.js

Fixes #1893 
- Updates the `PrescriptionInfo` component
- Adds sorting and a select column to `PrescriberSelect`
N/A
N/A

#1893 select prescriber icon

---

src/actions/PaymentActions.js
src/actions/PrescriberActions.js
src/actions/PrescriptionActions.js
src/pages/dataTableUtilities/constants.js
src/pages/dataTableUtilities/getColumns.js
src/reducers/PrescriberReducer.js
src/selectors/patient.js
src/selectors/prescriber.js
src/widgets/DataTable/DataTableRow.js
src/widgets/DataTable/TouchableCell.js
src/widgets/FlexColumn.js
src/widgets/FlexRow.js
src/widgets/PaymentSummary.js
src/widgets/PrescriptionInfo.js
src/widgets/SimpleLabel.js
src/widgets/Tabs/PrescriberSelect.js

Fixes #1889 
- Displays the patients available credit
N/A
N/A

#1889 Display available credit

---

src/actions/PaymentActions.js
src/actions/PrescriberActions.js
src/actions/PrescriptionActions.js
src/pages/dataTableUtilities/constants.js
src/pages/dataTableUtilities/getColumns.js
src/reducers/PrescriberReducer.js
src/selectors/patient.js
src/selectors/prescriber.js
src/widgets/DataTable/DataTableRow.js
src/widgets/DataTable/TouchableCell.js
src/widgets/FlexColumn.js
src/widgets/FlexRow.js
src/widgets/PaymentSummary.js
src/widgets/PrescriptionInfo.js
src/widgets/SimpleLabel.js
src/widgets/Tabs/ItemSelect.js
src/widgets/Tabs/PrescriberSelect.js

Fixes #1895 
- Just sorts the items in the item select component
N/A
N/A

#1895 Sort items in ItemSelect

---

src/actions/InsuranceActions.js
src/actions/PaymentActions.js
src/actions/PrescriberActions.js
src/actions/PrescriptionActions.js
src/database/DataTypes/InsurancePolicy.js
src/database/utilities/createRecord.js
src/pages/dataTableUtilities/constants.js
src/pages/dataTableUtilities/getColumns.js
src/reducers/PaymentReducer.js
src/reducers/PrescriberReducer.js
src/selectors/patient.js
src/selectors/prescriber.js
src/widgets/DataTable/DataTableRow.js
src/widgets/DataTable/TouchableCell.js
src/widgets/FlexColumn.js
src/widgets/FlexRow.js
src/widgets/PaymentSummary.js
src/widgets/PrescriptionInfo.js
src/widgets/SimpleLabel.js
src/widgets/Tabs/ItemSelect.js
src/widgets/Tabs/PrescriberSelect.js

Fixes #1908 
- Just updated the create record case to how it will be used
- Added proper expiry date from the validity days of the provider
N/A
N/A

#1908 create record insurance policy

---

src/actions/InsuranceActions.js
src/actions/PaymentActions.js
src/actions/PrescriberActions.js
src/actions/PrescriptionActions.js
src/database/DataTypes/InsurancePolicy.js
src/database/utilities/createRecord.js
src/pages/dataTableUtilities/constants.js
src/pages/dataTableUtilities/getColumns.js
src/reducers/PaymentReducer.js
src/reducers/PrescriberReducer.js
src/selectors/insurance.js
src/selectors/patient.js
src/selectors/payment.js
src/selectors/prescriber.js
src/widgets/CurrencyInputRow.js
src/widgets/DataTable/DataTableRow.js
src/widgets/DataTable/TouchableCell.js
src/widgets/FlexColumn.js
src/widgets/FlexRow.js
src/widgets/NumberLabelRow.js
src/widgets/PaymentSummary.js
src/widgets/PrescriptionInfo.js
src/widgets/SimpleLabel.js
src/widgets/Tabs/ItemSelect.js
src/widgets/Tabs/PrescriberSelect.js

Fixes #1888
- Now shows the insurance amount and discount amount in the payment summary:
- Most of the code is related to updating the UI when you: change the insurance selection, create a new one or edit a policy
- Also added the paymentAmount updating when you change insurance policy to reflect the total auto-input
N/A
N/A

#1888 display insurance discount amount

---

src/pages/dataTableUtilities/actions/cellActions.js
src/pages/dataTableUtilities/getIndicatorTableData.js
src/pages/dataTableUtilities/getPageInfoColumns.js
src/pages/dataTableUtilities/getPageInitialiser.js
src/pages/dataTableUtilities/index.js
src/pages/dataTableUtilities/reducer/cellReducers.js
src/pages/dataTableUtilities/reducer/tableReducers.js
src/utilities/index.js

Fixes #1901.
Fixes indicator (and related) dependency cycles.
Functional changes only, no need to test.
N/A.

#1901 move indicator helpers

---

src/pages/dataTableUtilities/actions/cellActions.js
src/pages/dataTableUtilities/getIndicatorTableData.js
src/pages/dataTableUtilities/reducer/cellReducers.js

Fixes #1915. Branches off #1901.
Just a tidy up of indicators utilities for readability.
Functional changes only.
N/A.

#1915 tidy up indicator utilities

---

src/database/DataTypes/Report.js
src/pages/DashboardPage.js
src/widgets/BarChart.js
src/widgets/LineChart.js
src/widgets/PieChart.js
src/widgets/ReportChart.js
src/widgets/ReportSideBar/ReportSideBar.js
src/widgets/ReportSideBar/ReportSideBarItem.js
src/widgets/ReportTable/ReportCell.js
src/widgets/ReportTable/ReportRow.js
src/widgets/ReportTable/ReportTable.js

Fixes #1745 
Docs strings were added to new files related with the brand new Dashboard feature.

#1745 Add docs strings for feature/dashboard new files

---

src/actions/PrescriptionActions.js
src/database/DataTypes/TransactionItem.js
src/pages/PrescriptionPage.js
src/reducers/PrescriptionReducer.js
src/widgets/CircleButton.js
src/widgets/DropDown.js
src/widgets/DropdownRow.js
src/widgets/PrescriptionCart.js
src/widgets/PrescriptionCartRow.js
src/widgets/StepperRow.js
src/widgets/Tabs/ItemSelect.js
src/widgets/icons.js

Fixes #1896 
- More offroad: Basically made abbreviations work, such that when you're typing if you type an abbreviation it will transform into the extension.
- Can also use the drop down to add default directions for that item
- Minor performance changes
N/A
N/A

#1896 directions to use new dropdown

---

src/Store.js
src/actions/DispensaryActions.js
src/actions/InsuranceActions.js
src/actions/PatientActions.js
src/actions/PrescriberActions.js
src/actions/PrescriptionActions.js
src/database/DataTypes/TransactionItem.js
src/pages/DispensingPage.js
src/pages/PrescriptionPage.js
src/pages/dataTableUtilities/actions/pageActions.js
src/pages/dataTableUtilities/getColumns.js
src/pages/dataTableUtilities/reducer/pageReducers.js
src/reducers/DispensaryReducer.js
src/reducers/PrescriptionReducer.js
src/reducers/index.js
src/selectors/dispensary.js
src/selectors/insurance.js
src/selectors/patient.js
src/selectors/prescriber.js
src/utilities/formInputConfigs.js
src/widgets/CircleButton.js
src/widgets/DropDown.js
src/widgets/DropdownRow.js
src/widgets/FormDateInput.js
src/widgets/PrescriptionCart.js
src/widgets/PrescriptionCartRow.js
src/widgets/StepperRow.js
src/widgets/Tabs/ItemSelect.js
src/widgets/icons.js

Fixes #1780 
- Added `DispensaryReducer` and removed the use of `PageReducer` for `DispensaryPage`. 
- Added in custom filtering logic and removed the data set action/reducer cases for toggling a dataset for `PageReducer`
- Also offroad tidying up in `DispensingPage`
N/A
N/A

#1780 Patient query syntax

---

src/actions/PrescriptionActions.js
src/reducers/PrescriptionReducer.js
src/selectors/patient.js
src/selectors/prescription.js
src/widgets/PrescriptionInfo.js
src/widgets/Tabs/ItemSelect.js

Fixes #1947 
- Adds filtering and a search bar to the item selection in a script
- Also shift some logic to selectors
N/A
N/A

#1947 item select searchbar

---

src/pages/CustomerRequisitionPage.js
src/pages/SupplierRequisitionPage.js

Fixes #1973.
Dropdown component was nested inside a `useCallback` without the correct deps.
N/A.

Fix indicator dropdown useCallback deps

---

src/database/DataTypes/RequisitionItem.js

Fixes #1990 
- Rather than returning null when a `RequisitionItem` has no `TransactionItem`, create one
*Datafile must have a `RequisitionItem` with no `TransactionItem`, where the `RequisitionItem` is for an unfinalised `RequisitionItem`, and the underlying `Item` has stock on hand greater than 0 -- This was originally found on the Medical Action Myanmar datafile - using the latest backup and the HTY A store*
I have no idea how this is possible - when a `CustomerRequisition` is synced, a `CustomerInvoice` is created and all the `TransactionItems`, for each `RequisitionItem` in the `CustomerRequisition`, straight afterward. Only thing I can imagine is a crash between creating the `Transaction` and the `TransactionItems`, or some editing of records which weren't meant to be edited on the …

#1990 RequisitionItems with no TransactionItems

---

src/actions/PrescriberActions.js
src/database/DataTypes/StocktakeBatch.js
src/database/DataTypes/TransactionBatch.js
src/database/DataTypes/TransactionItem.js
src/localization/currency.js
src/pages/dataTableUtilities/actions/cellActions.js
src/reducers/PaymentReducer.js
src/selectors/patient.js
src/selectors/payment.js
src/settings/MobileAppSettings.js
src/widgets/CurrencyInputRow.js
src/widgets/FormDateInput.js
src/widgets/PrescriptionCartRow.js
src/widgets/modals/LoginModal.js

Fixes #1957 
- Adds a wrapper around the `currency` object to be able to use and set some configs passed on the current language
N/A
N/A

#1957 Localized Currency

---

dev_scripts/upload.sh
package.json
src/database/DataTypes/RequisitionItem.js
src/pages/dataTableUtilities/actions/cellActions.js
src/widgets/modals/StocktakeBatchModal.js

Fixes #1979 
- Fixed a bug where a Customer Requisition line could sometimes be uneditable - #1990 
- Fixed a bug where navigating and editing a cell could sometimes crash the app - #1992 
- Fixed a bug where a Stocktake line would sometimes not update after editing a batch - #1994

3.2.1 Patch Release

---

src/utilities/modules/dispensary/pay.js

Fixes #2015 
- Removes overpayments from payments
N/A
Just in issue

Add remove overpayments from pay

---

src/widgets/DataTable/DataTableRow.js

Fixes #2033 
- Disables the row debug prop (default is false)
N/A
N/A

#2033 Disable row debug prop

---

src/pages/DispensingPage.js
src/widgets/PaymentSummary.js

Fixes #2011 
- Use the existing variable which is already hiding the policy selector to also hide the text
N/A
N/A

#2011 Hide insurance when not defined

---

src/context/LoadingIndicatorContext.js
src/hooks/useLoadingIndicator.js
src/mSupplyMobileApp.js
src/pages/DispensingPage.js
src/utilities/modules/dispensary/pay.js
src/widgets/PaymentSummary.js
src/widgets/Tabs/PrescriptionConfirmation.js

Fixes #2013 
- The issue just needed the condition check for `canConfirm`
- Added the loading indicator context as that was an easy way to access the function rather than handing down the method through like 5 components. Can also be used elsewhere
- Don't like the context as it's probably nicer to control the component (spinner) through redux decoratively, but it's a quick and dirty solution that isn't too bad.
- Custom hook is because it's nicer. Was considering creating a home-made cache and passing functions in which would be wrapped and memoized but was a bit too hard basket and decided not too 
N/A
N/A

#2013 Non cancelled finalise button

---

src/actions/PatientActions.js
src/actions/PrescriberActions.js
src/context/LoadingIndicatorContext.js
src/database/utilities/createRecord.js
src/hooks/useLoadingIndicator.js
src/mSupplyMobileApp.js
src/pages/DispensingPage.js
src/utilities/modules/dispensary/pay.js
src/widgets/PaymentSummary.js
src/widgets/Tabs/PrescriptionConfirmation.js

Fixes #2017 
- Alters both in the same way - uses a `createRecord` case for creation and correctly creates and updates an  `Address` object.
N/A
N/A

#2017 patient prescriber address'

---

src/actions/PatientActions.js
src/actions/PrescriberActions.js
src/context/LoadingIndicatorContext.js
src/database/DataTypes/TransactionItem.js
src/database/utilities/createRecord.js
src/hooks/useLoadingIndicator.js
src/mSupplyMobileApp.js
src/pages/DispensingPage.js
src/utilities/modules/dispensary/pay.js
src/widgets/PaymentSummary.js
src/widgets/Tabs/PrescriptionConfirmation.js

Fixes #2028 
- Correctly pass a parameter for `TransactionBatch` creation
N/A
N/A

#2028 Add corrected TransactionItem batch creation

---

src/actions/PatientActions.js
src/actions/PrescriberActions.js
src/context/LoadingIndicatorContext.js
src/database/DataTypes/TransactionItem.js
src/database/utilities/createRecord.js
src/hooks/useLoadingIndicator.js
src/localization/currency.js
src/mSupplyMobileApp.js
src/pages/DispensingPage.js
src/utilities/modules/dispensary/pay.js
src/widgets/CurrencyInputRow.js
src/widgets/NumberLabelRow.js
src/widgets/PaymentSummary.js
src/widgets/Tabs/PrescriptionConfirmation.js

Fixes #2012 
- Removes currency symbols from the interface
N/A
🤷‍♂

#2012 remove currency symbols

---

src/actions/PrescriptionActions.js
src/localization/utilities.js
src/mSupplyMobileApp.js
src/navigation/actions.js
src/reducers/PagesReducer.js
src/reducers/PaymentReducer.js
src/reducers/PrescriptionReducer.js
src/selectors/prescription.js
src/settings/MobileAppSettings.js
src/utilities/underscoreMethods.js
src/widgets/DataTable/DataTableRow.js
src/widgets/PrescriptionCart.js
src/widgets/PrescriptionSummary.js
src/widgets/Tabs/ItemSelect.js
src/widgets/Tabs/PrescriberSelect.js
src/widgets/Tabs/PrescriptionConfirmation.js
src/widgets/modals/LoginModal.js

Fixes #2046 
- Adds a function to set the date locale of `moment` when changing the language of the app.
N/A
N/A

#2046 localize dates

---

src/actions/PrescriptionActions.js
src/database/DataTypes/Transaction.js
src/database/UIDatabase.js
src/localization/modalStrings.json
src/localization/utilities.js
src/mSupplyMobileApp.js
src/navigation/actions.js
src/reducers/ModulesReducer.js
src/reducers/PagesReducer.js
src/reducers/PaymentReducer.js
src/reducers/PrescriptionReducer.js
src/selectors/modules.js
src/selectors/prescription.js
src/settings/MobileAppSettings.js
src/settings/index.js
src/sync/incomingSyncUtils.js
src/sync/outgoingSyncUtils.js
src/utilities/underscoreMethods.js
src/widgets/DataTable/DataTableRow.js
src/widgets/PaymentSummary.js
src/widgets/PrescriptionCart.js
src/widgets/PrescriptionExtra.js
src/widgets/PrescriptionSummary.js
src/widgets/Tabs/ItemSelect.js
src/widgets/Tabs/PrescriberSelect.js
src/widgets/Tabs/PrescriptionConfirmation.js
src/widgets/modals/LoginModal.js
src/widgets/modals/ModalContainer.js

Fixes #2038 
- Adds `user1` to `Transaction` 🤷‍♂ 
- Adds an 'extra info' component housing the patient type, 
- Adds a few more module fields - most likely a `PreferencesReducer` will be needed soon. I wouldn't mind some sort of state which 'checks' for existence of records - i.e. when reasons are defined or programs then programs are enabled etc. having Preferences/modules and then I dunno what to call the last one - but it would be nice to be able to check a field, rather than query the length of some objects every time
- Top left thing here - needs work on styles will make a new issue this is big enough!
N/A
N/A

#2038 Comment, service type, patient type

---

src/utilities/modules/dispensary/pay.js
src/widgets/Tabs/PrescriptionConfirmation.js

Fixes #2054 
- Adds a parameter with the script total amount rather than trying to use from the script as it's not set yet.
N/A
N/A

#2054 incorrect payment values

---

src/database/DataTypes/TransactionBatch.js
src/utilities/modules/dispensary/pay.js
src/widgets/Tabs/PrescriptionConfirmation.js

Fixes #2052 
- old bug
N/A
N/A

#2052 Corrected batch prices

---

src/database/DataTypes/NumberSequence.js

Fixes #2060 
Not the correct fix - need to do something about creating a number from the highest invoice after initialising
N/A
N/A

#2060 Remove error throwing

---

dev_scripts/deploy.sh
dev_scripts/upload.sh
package.json
src/widgets/DataTable/DataTable.js
yarn.lock

Fixes #2075 
- I don't know what happened but some changes in master that weren't in develop -- 🤷‍♂ ?
- Missing yarn.lock from #1982 pr
N/A

#2075 broken develop

---

src/database/DataTypes/Transaction.js
src/sync/outgoingSyncUtils.js
src/utilities/modules/dispensary/pay.js
src/widgets/DetailRow.js
src/widgets/Tabs/PrescriberSelect.js
src/widgets/Tabs/PrescriptionConfirmation.js

Fixes #2098 
- Parse insurance policy `isActive`
N/A
N/A

#2098 Parse isActive

---

src/database/DataTypes/Transaction.js
src/sync/outgoingSyncUtils.js
src/utilities/modules/dispensary/pay.js
src/widgets/DetailRow.js
src/widgets/Tabs/PrescriberSelect.js
src/widgets/Tabs/PrescriptionConfirmation.js

Fixes #2097 
- I think this has to do with using `moment` to set the date. 
N/A
N/A

#2095 Format DateOfBirth

---

src/database/DataTypes/Transaction.js
src/sync/outgoingSyncUtils.js
src/utilities/modules/dispensary/pay.js
src/widgets/DetailRow.js
src/widgets/Tabs/PrescriberSelect.js
src/widgets/Tabs/PrescriptionConfirmation.js

Fixes #2095 
- Sync `customer` field
N/A
N/A

#2095 Customer field to outgoing sync

---

src/database/DataTypes/Transaction.js
src/localization/dispensingStrings.json
src/sync/outgoingSyncUtils.js
src/utilities/modules/dispensary/pay.js
src/widgets/DetailRow.js
src/widgets/Tabs/PrescriberSelect.js
src/widgets/Tabs/PrescriptionConfirmation.js
src/widgets/modals/PatientHistory.js

Fixes #2009 
- Adds a placeholder component for when the patient has no history. I think this is better than just disabling the button? Generally it would be quite rare?
N/A
N/A

#2009 PatientHistory placeholder

---

src/database/DataTypes/Transaction.js
src/localization/dispensingStrings.json
src/pages/DispensingPage.js
src/reducers/DispensaryReducer.js
src/sync/outgoingSyncUtils.js
src/utilities/modules/dispensary/pay.js
src/widgets/DetailRow.js
src/widgets/Tabs/ItemSelect.js
src/widgets/Tabs/PrescriberSelect.js
src/widgets/Tabs/PrescriptionConfirmation.js
src/widgets/modals/PatientHistory.js

Fixes #2087 
- Adds placeholders for search bars
N/A
N/A

#2087 search bar placeholders

---

src/database/DataTypes/Transaction.js
src/database/utilities/createRecord.js
src/globalStyles/pageStyles.js
src/localization/dispensingStrings.json
src/pages/DispensingPage.js
src/reducers/DispensaryReducer.js
src/sync/outgoingSyncUtils.js
src/utilities/modules/dispensary/pay.js
src/widgets/DetailRow.js
src/widgets/Tabs/ItemSelect.js
src/widgets/Tabs/PrescriberSelect.js
src/widgets/Tabs/PrescriptionConfirmation.js
src/widgets/modals/PatientHistory.js

Fixes #2085 
- Adds `name.name` to be a full name of a patients `lastName, firstName` - the same as desktop
N/A
N/A

#2085 patient full name

---

src/database/DataTypes/Transaction.js
src/database/utilities/createRecord.js
src/globalStyles/pageStyles.js
src/localization/dispensingStrings.json
src/pages/DispensingPage.js
src/reducers/DispensaryReducer.js
src/selectors/dispensary.js
src/selectors/prescriber.js
src/sync/outgoingSyncUtils.js
src/utilities/modules/dispensary/pay.js
src/widgets/DetailRow.js
src/widgets/Tabs/ItemSelect.js
src/widgets/Tabs/PrescriberSelect.js
src/widgets/Tabs/PrescriptionConfirmation.js
src/widgets/modals/PatientHistory.js

Fixes #2084 
- Adds corrected query order for `Patients` and `Prescribers` - `lastName` then `firstName`
- Adds date of birth filtering - i.e. `g, j -d 1980` for Joshua Griffin born 1980 or later
- Adds prescriber querying in `PrescriberSelect`
N/A
N/A

#2084 backward patient querying

---

src/database/DataTypes/Transaction.js
src/database/utilities/createRecord.js
src/globalStyles/pageStyles.js
src/localization/dispensingStrings.json
src/pages/DispensingPage.js
src/reducers/DispensaryReducer.js
src/selectors/dispensary.js
src/selectors/prescriber.js
src/sync/outgoingSyncUtils.js
src/utilities/modules/dispensary/pay.js
src/widgets/DetailRow.js
src/widgets/Tabs/ItemSelect.js
src/widgets/Tabs/PrescriberSelect.js
src/widgets/Tabs/PrescriptionConfirmation.js
src/widgets/modals/ModalContainer.js
src/widgets/modals/PatientHistory.js

Fixes #2086 
- Just adjusts the top margin of modals
N/A
N/A

#2086 Modal height

---

src/mSupplyMobileApp.js

Fixes #2109 
- Adds a condition for being in development environment (React native sets this global)
N/A
N/A

#2109 Development environment condition

---

src/pages/dataTableUtilities/constants.js

Fixes #2111 
- Gives `PAYMENT_NAME` column name a unique value
N/A
N/A

#2111 Corrected PaymentName column name

---

src/selectors/prescription.js
src/widgets/Tabs/PrescriptionConfirmation.js

Fixes #2094 
- Disabled the cancel button in a finalised prescription
N/A
N/A

#2094 cancel button not disabled

---

src/actions/PrescriptionActions.js
src/selectors/prescription.js
src/widgets/PrescriptionCart.js
src/widgets/PrescriptionInfo.js
src/widgets/PrescriptionSummary.js
src/widgets/StepperInput.js
src/widgets/Tabs/PrescriptionConfirmation.js

Fixes #2122 
- Fixes some prop type errors
N/A
N/A

#2122 PropType errors

---

src/actions/PrescriptionActions.js
src/selectors/prescription.js
src/widgets/PrescriptionCart.js
src/widgets/PrescriptionInfo.js
src/widgets/PrescriptionSummary.js
src/widgets/StepperInput.js
src/widgets/Tabs/PrescriptionConfirmation.js

Fixes #2120
- Parses `StepperInput` input value to not allow an invalid state, will default to 0 when it might occur
N/A
Obviously this means the input is only good for positive integers now... 🤷‍♂

#2120 Invalid StepperValues

---

src/actions/PrescriptionActions.js
src/database/DataTypes/TransactionItem.js
src/localization/dispensingStrings.json
src/selectors/prescription.js
src/widgets/PrescriptionCart.js
src/widgets/PrescriptionInfo.js
src/widgets/PrescriptionSummary.js
src/widgets/StepperInput.js
src/widgets/StepperRow.js
src/widgets/Tabs/ItemSelect.js
src/widgets/Tabs/PrescriptionConfirmation.js

Fixes #2118 
- Doesn't set the initial value of an item to 1 anymore
- Shows a toast when trying to proceed and you can't. Gives feedback rather than just a disabled button which is nice, but also means when updating the lines through the stepper, don't have to propogate the state change which would cause performance problems
N/A
N/A

#2118 prescription lines from 1

---

src/actions/PrescriptionActions.js
src/actions/SupplierCreditActions.js
src/database/DataTypes/TransactionItem.js
src/localization/dispensingStrings.json
src/selectors/prescription.js
src/widgets/PrescriptionCart.js
src/widgets/PrescriptionInfo.js
src/widgets/PrescriptionSummary.js
src/widgets/StepperInput.js
src/widgets/StepperRow.js
src/widgets/Tabs/ItemSelect.js
src/widgets/Tabs/PrescriptionConfirmation.js

Fixes #2116 
After trying to figure out what was happening for a couple of hours................
- Resaves the SC after creating it's lines so that it goes to the top of the SyncQueue. If the server doesn't have the lines, it doesn't add them to the CC when receiving the SC.
N/A
N/A

#2116 CustomerCredits with no lines

---

src/globalStyles/pageStyles.js
src/selectors/dispensary.js
src/widgets/Stepper.js
src/widgets/Tabs/PrescriberSelect.js
src/widgets/Wizard.js

Fixes #2124 
Added some padding. It has pushed things down a bit, and somehow I've made the data rows too high. Will have a look at that.
Slight off-road in correcting the DOB patient filter default (the current `new Date(null)` == 1 Jan 1970. I've changed to 1 Jan 1900)

adding padding; correct DOB filter

---

src/widgets/SimpleTable.js
src/widgets/Tabs/ItemSelect.js
src/widgets/Tabs/PrescriptionConfirmation.js
src/widgets/Wizard.js

Fixes #2135 
Some style tweaks to the Item select and Prescription confirmation screens.
Will look at putting the prescription info in a separate box next

item select and prescripton confirmation UI tweak

---

src/selectors/dispensary.js

Fixes #2149 
- Changes the query for filtering so that you can search by last name and dob
- Defensive against an invalid date
N/A
N/A

#2149 Filtering DOB Crash

---

src/utilities/formInputConfigs.js

Fixes #2151 
- Adjusts some form config invalid messages
N/A
N/A

#2151 Address invalid message

---

src/widgets/Tabs/PrescriptionConfirmation.js

Fixes #2167 
- Add navigation backwards after confirming a prescription
N/A
Pretty ugly code here :(

#2167 Navigate back

---

src/database/DataTypes/TransactionItem.js
src/widgets/PrescriptionCartRow.js

Fixes #2154 
- Changes the price to be that of the total price of the transaction item
N/A
N/A

#2154 Prescription item prices

---

src/widgets/StepperInput.js

Fixes #2153 
- slight adjustment to the interval
N/A
N/A

#2153 stepper incrementing

---

src/database/UIDatabase.js
src/pages/dataTableUtilities/actions/getPageActions.js
src/pages/dataTableUtilities/getColumns.js

Fixes #2141
- Merge regression in `UIDatabase` making positive and negative inventory adjustments return insurance policies.. !
- Missing override to be able to trigger reasons
N/A
The override concept is pretty stupid and needs to be removed!

#2141 Reasons not applying

---

src/database/UIDatabase.js

Fixes #2194 
- Filter out patients for customers
N/A
N/A

#2194 customers not filtered

---

src/database/DataTypes/Requisition.js
src/utilities/dailyUsage.js

Fixes #2204 
- Adds program daily usage which uses the usage from the end of the period + 1 day and -X months(defaults to 3)
N/A
N/A

#2204 Program daily usage

---

src/database/DataTypes/Requisition.js
src/sync/outgoingSyncUtils.js
src/utilities/dailyUsage.js

Fixes #2202 
- Delete orphaned sync outs
- This will still throw the error - but it'll get bugsnagged and minimal changes, just need to start sync again 🤷‍♂ 
N/A
N/A

#2202 orphan sync out

---

src/database/DataTypes/ItemBatch.js
src/pages/dataTableUtilities/constants.js
src/pages/dataTableUtilities/getColumns.js
src/reducers/SupplierCreditReducer.js
src/utilities/sortDataBy.js
src/widgets/CurrencyInputRow.js
src/widgets/modalChildren/SupplierCredit.js

Fixes #2226 Fixes #2247 
- Add Item code and expiry date columns to supplier credit
N/A

#2226 item code and expiry date columns

---

src/utilities/modules/dispensary/pay.js

Fixes #2262 
- Adds correct line creation
N/A

#2262 Add correct line creation

---

src/database/utilities/createRecord.js
src/pages/dataTableUtilities/getColumns.js
src/selectors/cashRegister.js
src/selectors/dispensary.js
src/utilities/modules/dispensary/pay.js

Fixes #2250 
- Case insensitive filtering
- Slight offroad flex adjustment to columns - was being cut off in french
N/A

#2250 filtering not case insensitive

---

src/localization/pageInfoStrings.json
src/pages/CashRegisterPage.js
src/pages/CustomerRequisitionPage.js
src/pages/dataTableUtilities/getPageInfoColumns.js
src/pages/dataTableUtilities/getPageInitialiser.js
src/selectors/cashRegister.js

Fixes #2244.
Tidies up the cash register UI and makes consistent with other pages.
No functional changes.
N/A.

Add cash register page info columns

---

src/utilities/dailyUsage.js

Fixes #2267
As per issue
@andreievg  TODO

#2267 look back denominator for program based amc to be aligned with desktop

---

src/database/DataTypes/Transaction.js
src/widgets/ResultRow.js
src/widgets/bottomModals/BottomCurrencyEditor.js
src/widgets/bottomModals/BottomTextEditor.js
src/widgets/modals/CashTransactionModal.js

Fixes #2269 
- Minor style adjustments to stop the keyboard spazzing things out
N/A
N/A

Add CashTransactionModal adjustments

---

src/widgets/StepperInput.js

Fixes #2271 
- Correctly trigger the update when manually editing
N/A
N/A

#2271 Add correctly trigger onChangeText when manually updating

---

src/localization/dispensingStrings.json
src/pages/CashRegisterPage.js
src/pages/dataTableUtilities/actions/pageActions.js
src/pages/dataTableUtilities/getPageInitialiser.js
src/pages/dataTableUtilities/reducer/pageReducers.js
src/selectors/cashRegister.js
src/widgets/modals/CashTransactionModal.js

Fixes #2289 
- Puts a drop down for filtering by payment type
- Disallows creating a cash in if the balance of the particular payment type will become 0
N/A
N/A

#2289 Prevent more cash withdrawal than balance

---

src/localization/dispensingStrings.json
src/localization/tableStrings.json

Fixes #2282 
- Some string adjustments
N/A
N/A

#2282 GTT translations

---

src/localization/navStrings.json
src/localization/pageInfoStrings.json
src/localization/tableStrings.json
src/navigation/actions.js
src/pages/dataTableUtilities/getPageInfoColumns.js
src/pages/dataTableUtilities/getPageInitialiser.js

Fixes #2313 
- Uses corrected page info
- corrects the title
- adds some strings!
N/A
N/A

#2313 supplier credit details

---

src/database/DataTypes/Requisition.js
src/database/utilities/getIndicatorData.js

Fixes #2317 
- Adds the code from PR [# link here]
N/A

#2317 Defensive CustomerRequisitionPage

---

dev_scripts/upload.sh
package.json
src/database/DataTypes/Requisition.js
src/database/utilities/getIndicatorData.js
src/pages/dataTableUtilities/actions/cellActions.js
src/sync/outgoingSyncUtils.js
src/widgets/modals/StocktakeBatchModal.js

Fixes #2319 
- See linked issue
See :
#2320 
#2321 
#2322 
N/A

Release v3.2.3

---

src/reducers/PaymentReducer.js

Fixes #2290 
- Correctly resets the payment state
**Note: Repro steps in issue**
N/A

#2290 Reset payment state

---

src/selectors/prescriber.js

Fixes #2237 
- Make the number of prescribers a parameter to the selector so that it recalculates if it changes
N/A

#2237 Number of Prescribers as a parameter to selectors

---

src/selectors/prescription.js
src/widgets/PaymentSummary.js

Fixes #2292 
- Sorts prescription categories drop down
- Sorts payment type drop down
N/A

#2292 Sorted PrescriptionCategories 

---

src/widgets/FormDateInput.js

Fixes #2252 
- Adds use of the `maximumDate` to RNDatePicker
N/A

#2252 Maximum date to date picker

---

src/widgets/DataTable/DataTableRow.js

Fixes #2334 
- Adds a `N/A` for invalid dates in cells
N/A
N/A

#2334 Placeholder for invalid dates

---

src/reducers/SupplierCreditReducer.js

Fixes #2335 
- Filters batches to ensure they have a supplier. Query is probably a bit much but I'm not 100% on the rules of the 'misc names' yet - will find out!
N/A
N/A

#2335 Filtering by having a supplier

---

src/widgets/modals/DemoUserModal.js

Fixes #2366 
- Uses the corrected strings
For easy reference! https://github.com/openmsupply/mobile/blob/master/src/localization/demoUserModalStrings.json
N/A

#2366 Corrected string keys

---

dev_scripts/upload.sh
package.json
src/sync/incomingSyncUtils.js
src/widgets/modals/DemoUserModal.js

Release v3.2.5

---

src/database/utilities/createRecord.js

Fixes #2249 
- Edge case when switching an existing desktop site to a mobile site 
N/A
N/A

#2249 Shortcutting when reusing a reused number

---

src/pages/dataTableUtilities/getIndicatorTableData.js

Fixes #2363
- As described!
N/A
N/A

#2362 Switch order of indicator description and code

---

src/authentication/SyncAuthenticator.js
src/authentication/UserAuthenticator.js
src/localization/authStrings.json
src/mSupplyMobileApp.js
src/sync/constants.js

Fixes #2380 
- Stops syncing with servers which are not compatible!
N/A

#2380 stop syncing with incompatible servers

---

src/widgets/CurrencyInputRow.js

Fixes #2422 
- Shows only one decimal place in black rather than an odd orange looking one
N/A

#2422 two decimal places showing

---

src/pages/dataTableUtilities/getPageInitialiser.js

Fixes #2369 
- Doesn't use the old unused route
N/A

#2369 Use correct stocktake route

---

src/widgets/modals/ModalContainer.js

Fixes #2428 
- adds a couple of props and flexing
N/A

Add max number of lines and elipsis

---

src/localization/generalStrings.json

Fixes #2431 
- Updates the total price string
N/A

#2431 Total price string

---

src/localization/generalStrings.json
src/widgets/Slider.js

Fixes #2432 
- Changes styles slightly 
N/A

#2432 slider styles misaligned

---

src/widgets/Tabs/PrescriptionConfirmation.js

Fixes #2434 
- just finalise if there is no payment to be made
N/A

#2434 Receipt created everytime

---

src/utilities/formInputConfigs.js
src/widgets/FormControl.js

Reverts openmsupply/mobile#2455. A lesson to not merge when you're tired. This should have been merged into a feature branch!

Revert "#2433 fix insurance policy number editing"

---

src/utilities/formInputConfigs.js
src/widgets/FormControl.js

Fixes #2433.
See #2455 (reverted as incorrectly branched/merged into `develop`).

#2433 fix insurance policy number editing

---

src/utilities/formInputConfigs.js
src/widgets/FormControl.js

Fixes #2458.
Fixes #2458.
Branched off #2457.
Still to do:
- Prevent duplicate policy numbers.

#2458 fix insurance policy type editing

---

src/utilities/modules/dispensary/pay.js

Fixes #2496 
- wrong operator was used
N/A

#2496 Add correct operator

---

src/mSupplyMobileApp.js
src/navigation/Navigator.js
src/navigation/constants.js
src/pages/CashRegisterPage.js
src/pages/SupplierRequisitionsPage.js
src/pages/index.js

Fixes #2521 
- Tidies up `mSupplyMobileApp` and the mass amounts of page components!
N/A
N/A

#2521 Navigation tidy up

---

src/actions/FinaliseActions.js
src/hooks/useNavigationFocus.js
src/mSupplyMobileApp.js
src/navigation/Navigator.js
src/navigation/constants.js
src/navigation/utilities.js
src/pages/CashRegisterPage.js
src/pages/SupplierRequisitionsPage.js
src/pages/index.js
src/reducers/PagesReducer.js

Fixes #2519 
- Correctly refreshes the data of a page after finalising
- Correctly refreshes the data of a page after navigating back to it
N/A
N/A

#2519 useNavigationFocus broken

---

src/mSupplyMobileApp.js
src/pages/CustomerInvoicesPage.js
src/pages/SettingsPage.js
src/pages/StocktakesPage.js
src/pages/SupplierInvoicesPage.js
src/pages/SupplierRequisitionsPage.js

Fixes #2527 
- Gets `currentUser` from redux user 
N/A
N/A

#2527 current user prop not being passed

---

src/widgets/modals/CashTransactionModal.js

Fixes #2551 
Just a rename of a const

#2551 cash register error

---

dev_scripts/upload.sh
package.json
src/pages/CustomerRequisitionPage.js
src/selectors/insurance.js
src/selectors/patient.js
src/selectors/payment.js
src/widgets/PaymentSummary.js
src/widgets/modalChildren/SupplierCredit.js
src/widgets/modals/ByProgramModal.js
src/widgets/modals/CashTransactionModal.js
src/widgets/modals/DemoUserModal.js
src/widgets/modals/FinaliseModal.js

Release candidate for v4.0.2.
- Supplier requisition isVisible prop undefined: #2515
- Deactivated insurance policies displaying: #2523.
- Supplier credits list sizing: #2525.
- DemoUserModal component blocked by incorrect modal: #2546.
See v4.0.X release discussion for more info: #2444.

Release v4.0.2

---

src/widgets/PageButton.js

Fixes #2565
Just a quick fix to the page button memoisation logic.
Tests included in #2566.
Done as part of #2566, but felt like something that should be a separate PR!

#2565 add text prop to page button memo

---

src/hooks/useLayoutDimensions.js
src/widgets/VaccineChart.js

Fixes #2594 
- Adds `useLayoutDimensions` custom hook - allows for easy access to width/height
- Adds `VaccineChart` component. Basically a pull out from the old vaccine chart - just made into a function and reduced the lines a little bit. I'm sure it will need a few changes but is able to render things nicely as we had it, so at the moment a good base
N/A
N/A

#2594 vaccine chart [C2]

---

src/hooks/useLayoutDimensions.js
src/localization/navStrings.json
src/navigation/Navigator.js
src/navigation/actions.js
src/navigation/constants.js
src/navigation/utilities.js
src/pages/MenuPage.js
src/pages/VaccinePage.js
src/pages/index.js
src/widgets/VaccineChart.js

Fixes #2593 
- Adds a basic `VaccinePage` to navigate to
- Adds a button to `MenuPage`
- Adds the action to navigate to `VaccinePage`
N/A
N/A

#2593 Vaccine module page navigation [C1]

---

src/database/utilities/createRecord.js

Fixes #2601 
- Adds three new `createRecord` cases for temperature logging types
N/A
N/A

#2601 createRecord cases for logging types [D12]

---

src/database/utilities/createRecord.js

Fixes #2602 
- Adds a couple of cases for creating sensor and locations
N/A
N/A

#2602 createLocation and createSensor cases [D10]

---

src/database/DataTypes/TemperatureBreach.js
src/database/utilities/createRecord.js

Fixes #2574 
- Adds `TemperatureBreach` methods
N/A
N/A

#2574 TemperatureBreach methods [D9]

---

src/database/DataTypes/Location.js
src/database/DataTypes/TemperatureBreach.js
src/database/utilities/createRecord.js

Fixes #2575 
- Adds `Location` methods
N/A
N/A

#2575 Location methods [D8]

---

src/database/DataTypes/Location.js
src/database/DataTypes/TemperatureBreach.js
src/database/DataTypes/Transaction.js
src/database/DataTypes/TransactionBatch.js
src/database/DataTypes/TransactionItem.js
src/database/utilities/createRecord.js
src/localization/modalStrings.json

Fixes #2577 
- Adds `TransactionBatch` methods
N/A
N/A

#2576 transaction batch methods [D7]

---

src/database/DataTypes/Location.js
src/database/DataTypes/Stocktake.js
src/database/DataTypes/StocktakeBatch.js
src/database/DataTypes/StocktakeItem.js
src/database/DataTypes/TemperatureBreach.js
src/database/DataTypes/Transaction.js
src/database/DataTypes/TransactionBatch.js
src/database/DataTypes/TransactionItem.js
src/database/utilities/createRecord.js
src/localization/modalStrings.json

Fixes #2577 
- Adds `StocktakeBatch` methods
N/A
N/A

#2577 StocktakeBatch methods [D6]

---

src/database/DataTypes/ItemBatch.js
src/database/DataTypes/Location.js
src/database/DataTypes/Stocktake.js
src/database/DataTypes/StocktakeBatch.js
src/database/DataTypes/StocktakeItem.js
src/database/DataTypes/TemperatureBreach.js
src/database/DataTypes/Transaction.js
src/database/DataTypes/TransactionBatch.js
src/database/DataTypes/TransactionItem.js
src/database/utilities/createRecord.js
src/localization/modalStrings.json

Fixes #2578 
- Adds `ItemBatch` methods
N/A
N/A

#2578 ItemBatch methods [D5]

---

src/database/DataTypes/Item.js
src/database/DataTypes/ItemBatch.js
src/database/DataTypes/Location.js
src/database/DataTypes/LocationMovement.js
src/database/DataTypes/Sensor.js
src/database/DataTypes/Stocktake.js
src/database/DataTypes/StocktakeBatch.js
src/database/DataTypes/StocktakeItem.js
src/database/DataTypes/TemperatureBreach.js
src/database/DataTypes/Transaction.js
src/database/DataTypes/TransactionBatch.js
src/database/DataTypes/TransactionItem.js
src/database/DataTypes/VaccineVialMonitorStatusLog.js
src/database/utilities/createRecord.js
src/localization/modalStrings.json
src/sync/incomingSyncUtils.js
src/sync/outgoingSyncUtils.js
src/sync/syncTranslators.js

Fixes #1366 
- Adds `outgoingSyncUtils` logic for vaccines
N/A
#2619 will add the new tables to the sync out queue when they are in mSupply

#1366 vaccines outgoing sync [D1]

---

src/pages/DispensingPage.js
src/sync/incomingSyncUtils.js
src/utilities/network/lookupApi.js
src/widgets/modals/SearchForm.js

Fixes #2633.
Adds logic for handling patient/prescriber selection.
Completes the basic logic for looking up and adding a patient/prescriber. Next steps are to tidy up components and migrate logic to redux.

#2633 add lookup api on press logic

---

src/actions/DispensaryActions.js
src/pages/DispensingPage.js
src/reducers/DispensaryReducer.js
src/selectors/dispensary.js
src/utilities/formInputConfigs.js
src/widgets/FormControl.js
src/widgets/FormInputs/FormDateInput.js
src/widgets/modals/SearchForm.js

Fixes #2645.
Branches off #2633.
Sorry, got a bit carried away with this one!
Still redux thunks and bit of UI stuff to tidy up, but goes a little way to getting things in a bit better shape. Ignore the `TODO`s, they will be removed in the bugsnag PR!
No new functionality, probably more efficient to defer tests to the feature PR?
Next steps are to migrate logic to redux and add bugsnag, which should complete the lookup modal and logic. After that, need to add logic for handling data integrity, e.g. dispensing to non-local patients/prescribers, messaging logic for updating visibility, etc.

#2645 update search form components

---

src/Store.js
src/actions/TemperatureSyncActions.js
src/localization/syncStrings.json
src/reducers/TemperatureSyncReducer.js
src/selectors/temperatureSync.js
src/widgets/modalChildren/TemperatureSync.js

Fixes #2598 
- Adds `TemperatureSync` component which will be wrapped in a `ModalContainer` and used as the temperature syncing modal.
- It is more or less exactly the same as `SyncModal` - using the same styles and sub-components. Just slightly different because of showing the progress of individual sensors, rather than the process as a whole
N/A
N/A

#2598 TemperatureSync modal component

---

src/Store.js
src/actions/TemperatureSyncActions.js
src/localization/syncStrings.json
src/mSupplyMobileApp.js
src/reducers/TemperatureSyncReducer.js
src/selectors/temperatureSync.js
src/widgets/modalChildren/TemperatureSync.js

Fixes #2647 
- Adds a scheduled call for temperature syncing
- Also makes a few small adjustments to the temperature syncing actions
N/A
There is possibilities for some exceptions to be thrown - going to move forward and see if I can find them all (there are a few going to come up with the app being put into the background etc etc when the scheduling is being run n stuff)

#2647 Scheduled temperature syncing

---

src/Store.js
src/actions/TemperatureSyncActions.js
src/database/DataTypes/Sensor.js
src/globalStyles/buttonStyles.js
src/localization/syncStrings.json
src/mSupplyMobileApp.js
src/reducers/TemperatureSyncReducer.js
src/reducers/index.js
src/selectors/temperatureSync.js
src/utilities/chunk.js
src/utilities/constants.js
src/utilities/index.js
src/widgets/modalChildren/TemperatureSync.js

Fixes #2639 
- Adds actions for scanning for sensors and saving new/updating old
- Adds an initial `TemperatureSyncReducer`
N/A
There is possibilities for some exceptions to be thrown - going to move forward and see if I can find them all (there are a few going to come up with the app being put into the background etc etc when the scheduling is being run n stuff)

#2639 Temperature sync scanning

---

src/widgets/HazardPoint.js
src/widgets/index.js

Fixes #1373
- Adds `HazardPoint` component (this is an icon to display in charts)
N/A
N/A

#1373 HazardPoint component

---

src/Store.js
src/actions/BreachActions.js
src/database/DataTypes/Location.js
src/database/DataTypes/TemperatureBreach.js
src/localization/generalStrings.json
src/localization/vaccineStrings.json
src/mSupplyMobileApp.js
src/pages/VaccinePage.js
src/pages/dataTableUtilities/getPageInfoColumns.js
src/reducers/BreachReducer.js
src/reducers/index.js
src/selectors/breach.js
src/utilities/constants.js
src/utilities/formatters.js
src/widgets/BreachChart.js
src/widgets/FridgeDisplay.js
src/widgets/HazardPoint.js
src/widgets/VaccineChart.js
src/widgets/modalChildren/BreachDisplay.js

Fixes #2597 
- Adds the breach modal component. Slightly different from previous as we decided not to display the batches in a table in the modal.
N/A
- Created the `BreachChart` component because I think it's a lot neater than having a bunch of conditions on the `VaccineChart` like `minLine && .. ` etc.. and also because we need to take the colour from the breach config and not if its not a breach chart. So you end up making it easier by adding a new breach line which then you dont render anything accept for that and then you have basically a completely new component !
- the number of affected batches and affected quantity are a little heavy!
- styles not the greatest!
- little longer than what I thought it was goign to be.. sorry!

#2597 Breach modal component

---

src/Store.js
src/actions/BreachActions.js
src/actions/FridgeActions.js
src/database/DataTypes/Location.js
src/database/DataTypes/TemperatureBreach.js
src/database/UIDatabase.js
src/localization/generalStrings.json
src/localization/vaccineStrings.json
src/mSupplyMobileApp.js
src/pages/VaccinePage.js
src/pages/dataTableUtilities/getPageInfoColumns.js
src/reducers/BreachReducer.js
src/reducers/FridgeReducer.js
src/reducers/index.js
src/selectors/breach.js
src/selectors/fridge.js
src/utilities/constants.js
src/utilities/formatters.js
src/widgets/BreachChart.js
src/widgets/FlexView.js
src/widgets/FridgeDisplay.js
src/widgets/FridgeDisplayInfo.js
src/widgets/HazardPoint.js
src/widgets/VaccineChart.js
src/widgets/modalChildren/BreachDisplay.js

Fixes #1384 
- Adds `VaccinePage` component. Just rendering in a flat list each fridge component.
N/A
- The `locationType.description == 'fridge'` for a fridge is not 100% but a 'for now' type situation. I think better to make a location type in desktop startup code with a description or code something like `@@sussol/fridge` or something..?
- The activity indicator display is a bit of a hack but not too bad I think! Displays an activity indicator for a second before rendering a fridge. It's not the exact right timing but I think it's kinda nice to show that rather than etither our normal spinner popping up when navigating, or for navigating to be a bit janky/slow or for there just to show nothing
- Added dates in the reducer n stuff as I want to add some date pickers to choose a range of …

#1384 Vaccine module page

---

src/actions/PatientActions.js
src/actions/PrescriberActions.js
src/database/utilities/createRecord.js
src/sync/incomingSyncUtils.js
src/utilities/network/lookupApi.js
src/widgets/modals/SearchForm.js

Fixes #2654.
Update existing patient and prescriber actions and migrate patient API.
N/A.

#2654 add lookup record creation thunks

---

src/database/DataTypes/Name.js
src/database/DataTypes/Prescriber.js
src/selectors/insurance.js
src/selectors/patient.js
src/selectors/prescriber.js
src/widgets/PaymentSummary.js

Fixes #2543.
Branches off #2674.
Looks like most of the functionality needed is already implemented! Just added a few helpers to make things a bit more explicit.
N/A.

#2543 add isEditable helpers

---

src/hooks/useFetch.js

Fixes #2632.
Adds bugsnag calls to `useFetchHook`.
N/A.
N/A.

#2632 add bugsnagging to fetch hook

---

src/Store.js
src/actions/RowDetailActions.js
src/database/DataTypes/Item.js
src/database/DataTypes/RequisitionItem.js
src/localization/pageInfoStrings.json
src/mSupplyMobileApp.js
src/pages/StockPage.js
src/pages/SupplierRequisitionPage.js
src/pages/dataTableUtilities/getPageInfoColumns.js
src/reducers/RowDetailReducer.js
src/reducers/TemperatureSyncReducer.js
src/reducers/index.js
src/selectors/rowDetail.js
src/widgets/RequisitionItemDetail.js
src/widgets/RowDetail.js
src/widgets/bottomModals/ItemDetails.js

Fixes #2592 
- Converts the current `ItemDetails` component into a more flexible component(s) which can be used elsewhere:
- this one:
- Made a generic `RowDetails` component which is a container component with the intention being that it will wrap other components - similar to the `DataTableModal`.
- Went with this, rather than a different pattern like the how the columns are organised as I think in general the use-cases for this are more unknown and it would be good to be more flexible - This is more of a "chuck info in it so we dont have to use up column space", so it is inherently unstructed and hard to plan a generic solution for
- Made a `RequisitionItemDetails` where the intention is to have it pop up when clicking a requisition item. Currently only going to show for a vaccine …

#2592 ItemDetail for requisitions

---

src/actions/TemperatureSyncActions.js
src/database/DataTypes/Location.js
src/database/DataTypes/Sensor.js
src/database/utilities/createRecord.js
src/localization/buttonStrings.json
src/localization/modalStrings.json
src/localization/tableStrings.json
src/localization/vaccineStrings.json
src/pages/VaccineAdminPage.js
src/pages/VaccinePage.js
src/pages/dataTableUtilities/actions/cellActions.js
src/pages/dataTableUtilities/actions/tableActions.js
src/pages/dataTableUtilities/constants.js
src/pages/dataTableUtilities/getColumns.js
src/pages/dataTableUtilities/getPageDispatchers.js
src/pages/dataTableUtilities/getPageInitialiser.js
src/reducers/TemperatureSyncReducer.js

Fixes #2728 
- Adds sensor editing logic
- Adds code to scan for sensors
- Adds the ability to add a new fridge
- Adds permission checking on the admin navigation button
- Adds ability to delete sensors/locations
N/A
N/A

#2728 admin page features

---

src/hooks/useFetch.js

Fixes #2810.
- Reduces `useFetch` bugsnagging frequency.
- Prevents unintended user errors: all unrecognised error messages (e.g. `"Aborted"`) substituted with connection error message). 
Replicating the template issue tests to check if any problems remain (also if all these tests are done, I can ensure bugsnag behaviour is correct!).

#2810 update fetch hook error handling

---

src/pages/dataTableUtilities/getPageInitialiser.js

Fixes #2815.
Fixes supplier invoice filter query.
N/A.

#2815 fix error on supplier invoice filtering

---

src/actions/TemperatureSyncActions.js
src/pages/VaccineAdminPage.js
src/pages/VaccinePage.js
src/selectors/fridge.js
src/sync/SyncQueue.js
src/sync/incomingSyncUtils.js
src/sync/outgoingSyncUtils.js
src/sync/syncTranslators.js
src/utilities/getModalTitle.js

Fixes #2619 
- Adds vaccine tables to sync queue
- Made updates to incoming and outgoing sync utils to make it work
- Couple other minor bug fixes!
N/A
N/A

#2619 sync out queue additions

---

src/actions/TemperatureSyncActions.js
src/database/DataTypes/Sensor.js
src/pages/dataTableUtilities/reducer/tableReducers.js
src/sync/incomingSyncUtils.js
src/sync/outgoingSyncUtils.js

Fixes #2634
- Adds an `is_active` field onto sensor. This is mainly for future proofing with a delete mechanism
N/A
N/A

#2634 isActive to sensor

---

src/widgets/DataTable/TouchableNoFeedback.js
src/widgets/RowDetail.js
src/widgets/modalChildren/TemperatureSync.js
src/widgets/modals/ModalContainer.js

Fixes #2870 
- Updates a couple of prop types which were throwing warnings
N/A
N/A

#2870 PropType updates

---

src/database/DataTypes/ItemBatch.js
src/database/DataTypes/Stocktake.js
src/database/DataTypes/TransactionItem.js
src/database/utilities/createRecord.js
src/pages/dataTableUtilities/getColumns.js
src/widgets/DataTable/DataTableRow.js
src/widgets/DataTable/TouchableNoFeedback.js
src/widgets/DropDownCell.js
src/widgets/FridgeDisplayInfo.js
src/widgets/RowDetail.js
src/widgets/icons.js
src/widgets/modalChildren/TemperatureSync.js
src/widgets/modals/ModalContainer.js

Fixes #2868 
- Adds some new disable logic for disabling VVM Status' and Breach column for rows which are not vaccines
N/A
N/A

#2868 disabling features for non vaccine items

---

src/database/DataTypes/Item.js

Fixes #2914 
- Updates the `confirmDate` -> `entryDate`
- Off-road vial wastage fixes
N/A
N/A

#2914 lastRequisitionDate incorrect [Branched from: #2909]

---

src/database/DataTypes/Item.js
src/widgets/FridgeDisplay.js
src/widgets/FridgeDisplayInfo.js

Fixes #2909
- Adds minor UI adjustments
[Taken with 20px marginTop, rather than 10px]
N/A
N/A

#2909 Add minor FridgeDisplay UI Adjustments [Branched from: #2908]

---

src/database/DataTypes/Item.js
src/widgets/BreachChart.js
src/widgets/FridgeDisplay.js
src/widgets/FridgeDisplayInfo.js
src/widgets/modalChildren/BreachDisplay.js

Fixes #2908 
- Adjusts the domain padding/offset
- Adjusts the number of data points in a breach chart
- Adjusts the time of the spinner
N/a
N/A

#2908 BreachChart domain, data point and spinner time adjustments [Branched from: #2907]

---

src/actions/TemperatureSyncActions.js
src/database/DataTypes/Item.js
src/widgets/BreachChart.js
src/widgets/FridgeDisplay.js
src/widgets/FridgeDisplayInfo.js
src/widgets/modalChildren/BreachDisplay.js

Fixes #2907 
- Correctly casts a timestamp to a date!
N/A
N/A

#2907 Correctly cast TemperatureBreach.endTimestamp [Branched from: #2891]

---

src/actions/TemperatureSyncActions.js
src/database/DataTypes/Item.js
src/selectors/fridge.js
src/widgets/BreachChart.js
src/widgets/FridgeDisplay.js
src/widgets/FridgeDisplayInfo.js
src/widgets/modalChildren/BreachDisplay.js

Fixes #2891 
- Updates the selector to create a 2D array in all cases
N/A
N/A

#2891 2D array creation fix [Branched from: #2903]

---

src/actions/TemperatureSyncActions.js
src/database/DataTypes/Item.js
src/selectors/fridge.js
src/widgets/BreachChart.js
src/widgets/FridgeDisplay.js
src/widgets/FridgeDisplayInfo.js
src/widgets/modalChildren/BreachDisplay.js

Fixes #2887 
- Changed the breach query to correctly find the breaches in a certain time.
- Changed the selector such that the timestamp is adjusted if outside the range
N/A
N/A

#2887 Breach selector incorrect query [Branched from: #2900] 

---

src/sync/incomingSyncUtils.js

Fixes #2878 
- Correctly parsing a field in `incomingSyncUtils`
N/A
N/A

#2878 Sensor.isActive parsing

---

src/widgets/BreachChart.js

Fixes #2884
- Adds a test on the colour passed in through the `TemperatureBreachConfiguration` record before trying to use it
Regex unit tests are here: https://regex101.com/r/rMqXT8/2
N/A

#2884 Hex string regex test

---

src/selectors/temperatureSync.js

Fixes #2885 
- Corrected logic in the short circuit
- Added corrected message to match the same sync message of normal sync
N/A
N/A

#2885 TemperatureSyncStateMessage incorrect

---

src/pages/VaccinePage.js
src/widgets/FridgeDisplay.js

Fixes #2879
- Some prop type warning fixes
N/A
N/A

#2879 add propType fixes

---

src/reducers/FridgeReducer.js

Fixes #2883 
- Populates the fridges with only locations with a sensor attached
N/A
Possibly a better way to do this query here..?

#2883 FridgeReducer initialState update

---

src/actions/TemperatureSyncActions.js
src/database/DataTypes/Item.js
src/database/DataTypes/Location.js
src/database/DataTypes/TemperatureBreach.js
src/selectors/fridge.js
src/widgets/BreachChart.js
src/widgets/FridgeDisplay.js
src/widgets/FridgeDisplayInfo.js
src/widgets/modalChildren/BreachDisplay.js

Fixes #2900 
- Changed `batchesAtTime` to `batchesDuringTime`, having it receive a range rather than a single moment in time. Then changed the query such that the batch should be in the location either before the initial start time, and having left it either never, or some time after the starting time OR entered it after the start time but before the end time. This is because the old query was not capturing those batches which had entered after a breach had started, but before it had finished (primarily, for very long breaches! Some fridges in Vannuatu are just permanently breached :( )
- simplified `totalStock`
N/A
N/A

#2900 TemperatureBreach stats incorrect [Branched from: #2874] 

---

src/actions/TemperatureSyncActions.js
src/database/DataTypes/Item.js
src/database/DataTypes/ItemBatch.js
src/database/DataTypes/Location.js
src/database/DataTypes/LocationMovement.js
src/database/DataTypes/StocktakeBatch.js
src/database/DataTypes/TemperatureBreach.js
src/database/DataTypes/TransactionBatch.js
src/selectors/fridge.js
src/widgets/BreachChart.js
src/widgets/FridgeDisplay.js
src/widgets/FridgeDisplayInfo.js
src/widgets/modalChildren/BreachDisplay.js

Fixes #2874 
- Adds to the `LocationMovement.breaches` field, with more accurate query to determine if it was in a breach.
- Uses the `LocationMovement.breaches` field to determine if the batch `hasBreached`, rather than if the `Location.hasBreached`
N/A
N/A

#2874 batch in breach logic incorrect [Branched from: #2889]

---

src/reducers/FridgeReducer.js

Fixes #2886 
- Adds a case to refresh the state when navigating to it
N/A
N/A

#2886 Refresh VaccinePage state [Branched from: #2883]

---

src/actions/TemperatureSyncActions.js
src/database/DataTypes/Item.js
src/database/DataTypes/ItemBatch.js
src/database/DataTypes/Location.js
src/database/DataTypes/LocationMovement.js
src/database/DataTypes/StocktakeBatch.js
src/database/DataTypes/TemperatureBreach.js
src/database/DataTypes/TransactionBatch.js
src/selectors/fridge.js
src/widgets/BreachChart.js
src/widgets/FridgeDisplay.js
src/widgets/FridgeDisplayInfo.js
src/widgets/modalChildren/BreachDisplay.js

Fixes #2889 
- Adds a method to 'close off' a `LocationMovement` - better name, maybe?
- Correctly closes off a `LocationMovement` when creating a new one
- Corrected the logic of the check for if the `Location` is the same or not.
N/A
N/A

#2889 location movement logic [Branched from: #2888]

---

src/database/DataTypes/ItemBatch.js
src/database/DataTypes/LocationMovement.js
src/database/DataTypes/StocktakeBatch.js
src/database/DataTypes/Transaction.js

Fixes #2931 
- When finalising a `Transaction`, try to leave any locations
- When finalising a `Stocktake`, try to leave any locations
- Misc bug fixes :(
Data file: 
[VaccineTestData1.zip](https://github.com/openmsupply/mobile/files/4761308/VaccineTestData1.zip)
N/A
N/A

#2931 Exit Location on issuing last of an ItemBatch

---

src/localization/vaccineStrings.json
src/pages/VaccinePage.js
src/reducers/FridgeReducer.js
src/selectors/fridge.js
src/utilities/formatters.js

Fixes #2934
-  Misc defensive code
N/A
N/A

#2934 Add misc defensive code!

---

src/localization/vaccineStrings.json
src/pages/VaccinePage.js
src/reducers/FridgeReducer.js
src/selectors/fridge.js
src/sync/incomingSyncUtils.js
src/sync/outgoingSyncUtils.js
src/utilities/formatters.js

Fixes #2933 
- Fixes 🐛 
N/A
N/A

#2933 Vaccines sync errors

---

src/sync/incomingSyncUtils.js

Fixes #2955 
- Adds minor `canBeBlank` sync updates for better syncorizing
N/A
N/A

#2955 Minor sync updates

---

src/database/DataTypes/Item.js
src/database/DataTypes/ItemBatch.js
src/database/DataTypes/StocktakeBatch.js
src/database/DataTypes/TransactionBatch.js
src/localization/generalStrings.json
src/widgets/modalChildren/GenericChoiceList.js
src/widgets/modals/DataTablePageModal.js

Fixes #2984 
- Adds restriction of locations for items with a restricted location type
N/A
N/A

#2984 Respect LocationType restrictions

---

src/actions/TemperatureSyncActions.js
src/globalStyles/colors.js
src/globalStyles/index.js
src/selectors/fridge.js
src/utilities/index.js
src/utilities/modules/vaccines/constants.js
src/utilities/modules/vaccines/index.js
src/widgets/BreachChart.js
src/widgets/VaccineChart.js

Fixes #2923 
- Adding some constants in various places!
N/A
N/A

#2923 Vaccines constants

---

src/database/utilities/parsers.js
src/sync/lookupApiUtils.js

Fixes #3006.
Minor fix to boolean parse helper.
N/A.

#3006 fix insurance policy lookup is active field

---

src/actions/PermissionActions.js
src/actions/TemperatureSyncActions.js
src/database/DataTypes/Sensor.js
src/database/DataTypes/SensorLog.js
src/database/utilities/createRecord.js
src/reducers/TemperatureSyncReducer.js
src/selectors/fridge.js
src/widgets/modals/DataTablePageModal.js

Fixes #3011 
- Adds corrected logic to 'count' from the most recent log synced, rather than counting back from the current time 
N/A
N/A

#3011 temperature syncing and saving

---

src/reducers/TemperatureSyncReducer.js
src/widgets/TemperatureSyncState.js

Fixes #3020 
- Adds fixes for prop types
N/A
N/A

Add propType fixes

---

src/pages/dataTableUtilities/getColumns.js

Fixes #3021 
- Adds use of localized string
N/A
N/A

Add usage of localized string

---

src/actions/TemperatureSyncActions.js
src/pages/dataTableUtilities/getColumns.js

Fixes #3022 
- adds a permission request when scanning for sensors
N/A
N/A

#3022 Permission requesting

---

.eslintrc
src/actions/TemperatureSyncActions.js
src/database/DataTypes/Location.js
src/mSupplyMobileApp.js
src/reducers/FridgeReducer.js
src/utilities/constants.js
src/widgets/DateRangeSelector.js
src/widgets/FridgeDisplay.js
src/widgets/FridgeDisplayInfo.js

Fixes #3024 
- Adds conditionals around passive syncing
N/A
N/A

Add conditional on passive syncing of temperatures

---

src/database/utilities/parsers.js
src/sync/Synchroniser.js

Fixes #3041 
The problem is with the `parseBoolean` method ( as @wlthomson expected! )
Should this be bug snagged?

fix parsing error

---

src/pages/CustomerInvoicePage.js
src/pages/CustomerInvoicesPage.js

Fixes #3096.
Prevents deletion of finalised customer invoices using steps described in #3096.
N/A.

#3096 fix app crash on invoice deletion

---

src/pages/SupplierInvoicePage.js
src/pages/SupplierInvoicesPage.js

Fixes #3094.
Prevents deletion of finalised supplier invoices using steps described in #3094.
N/A.

#3094 fix app crash on invoice deletion

---

src/widgets/Step.js

Fixes #3158 
- Updated variable to refetch modal data once the data of the step has changed
Another indication a refactor needed?

#3158 Missing variable in deps list for ByProgramModal

---

src/widgets/modals/ByProgramModal.js

Fixes #3171 
- Using the customers ID, if selected, to look up name tags
N/A
N/A

#3172 using customers tag

---

src/reducers/ModulesReducer.js

Fixes #3175 
As per the issue!
N/A

#3175 add temp disabling of vaccines

---

src/utilities/sortDataBy.js

Fixes #3178
- Totes spaced out and forgot to add these 😭 
Was going to add a default sort type, but I think it would make these bugs harder to find..?

Add new column sortKeys

---

src/mSupplyMobileApp.js
src/pages/CustomerInvoicePage.js
src/pages/CustomerInvoicesPage.js
src/pages/CustomerRequisitionPage.js
src/pages/DispensingPage.js
src/pages/SettingsPage.js
src/pages/StocktakeEditPage.js
src/pages/StocktakesPage.js
src/pages/SupplierInvoicePage.js
src/pages/SupplierInvoicesPage.js
src/pages/SupplierRequisitionPage.js
src/pages/VaccineAdminPage.js
src/widgets/FormControl.js
src/widgets/PrescriptionExtra.js
src/widgets/modals/ByProgramModal.js
src/widgets/modals/DataTablePageModal.js
src/widgets/modals/DemoUserModal.js
src/widgets/modals/FinaliseModal.js
src/widgets/modals/LoginModal.js
src/widgets/modals/ModalContainer.js
src/widgets/modals/SearchForm.js
src/widgets/modals/StocktakeBatchModal.js

Fixes #3209 
- Removes `fullScreen` prop and changes styles slightly to adjust
N/A

Remove fullScreen prop making all modals full screen

---

src/sync/lookupApiUtils.js

Fixes #3215
- Adds correct return value
N/A

#3215 Add correct return value

---

src/pages/CustomerRequisitionPage.js
src/widgets/DataTable/DataTableRow.js
src/widgets/PageInfo/PageInfo.js
src/widgets/PageInfo/PageInfoColumn.js

Fixes #3210
- Memoized columns and style object of data table row
- Fixed minor page info key issue
N/A

#3210 Excessive row rendering

---

src/sync/SyncQueue.js
src/sync/outgoingSyncUtils.js

Fixes #3237 
- Adds validation to `Name` for `sync_out` records
N/a

#3237 Dont sync out non patient names

---

src/utilities/dailyUsage.js

Fixes #3243 
- some bedmas!
N/A

Add corrected order of operations

---

src/database/utilities/createRecord.js

Fixes #3251 
- Adds re-ordering 
NAH
N/A

#3251 Requisition save order

---

src/Store.js
src/navigation/RootNavigator.js

Fixes #3267 
- Adds a little bit more helper info to bugsnag notifications

Add bugsnag middleware

---

package.json
src/bluetooth/BleService.js
src/bluetooth/constants.js
yarn.lock

Fixes #3282 
- Adds `BleService` class.
- This was taken from [mSupply ColdChain](https://raw.githubusercontent.com/openmsupply/msupply-cold-chain/develop/src/common/services/Bluetooth/BleService.js) with some minor adjustments - comments mainly.
- This has never been reviewed by anyone

#3282 BleService

---

src/database/DataTypes/TemperatureBreach.js
src/database/DataTypes/TemperatureBreachConfiguration.js
src/database/DataTypes/TemperatureLog.js
src/sync/incomingSyncUtils.js
src/sync/outgoingSyncUtils.js

Fixes #3299 
- Updates schema as per the issue
- Updates sync with updating schema
*Currently not testable as desktop needs an updated schema.. :)*
N/A

#3299 Update Schema

---

src/localization/generalStrings.json
src/widgets/EditorRow.js
src/widgets/Spacer.js
src/widgets/StepperInputs/BaseStepperButton.js
src/widgets/StepperInputs/BaseStepperInput.js
src/widgets/StepperInputs/DateEditor.js
src/widgets/StepperInputs/DurationEditor.js
src/widgets/StepperInputs/StepperInputWithLabel.js
src/widgets/StepperInputs/TemperatureEditor.js
src/widgets/StepperInputs/TimeEditor.js
src/widgets/TextEditor.js
src/widgets/WithFixedDimensions.js
src/widgets/index.js

Fixes #3308
- Adds a row component for the new editing rows
Internal

#3308 EditorRow

---

src/hooks/useRepeatCallbackPress.js
src/localization/generalStrings.json
src/widgets/EditorRow.js
src/widgets/Spacer.js
src/widgets/StepperInputs/BaseStepperButton.js
src/widgets/StepperInputs/BaseStepperInput.js
src/widgets/StepperInputs/DateEditor.js
src/widgets/StepperInputs/DurationEditor.js
src/widgets/StepperInputs/StepperInputWithLabel.js
src/widgets/StepperInputs/TemperatureEditor.js
src/widgets/StepperInputs/TimeEditor.js
src/widgets/StepperInputs/index.js
src/widgets/TextEditor.js
src/widgets/WithFixedDimensions.js
src/widgets/index.js

Fixes #3308
- Adds `TemperatureEditor` and `DurationEditor` - OK they're not very different. They were when I had them as editable text inputs, but then they were both a nightmare to deal with and it was taking a bit too much time so I stopped and made them non editable and now they're pretty similar. Hm.
Internal
Will make the textinputs editable in the future, I think. Not having to deal with focus and a proper form with validation etc with having only valid inputs from the buttons is a lot less work.

#3308 Add DurationEditor & TemperatureEditor

---

src/hooks/useRepeatCallbackPress.js
src/localization/generalStrings.json
src/widgets/EditorRow.js
src/widgets/Spacer.js
src/widgets/StepperInputs/BaseStepperButton.js
src/widgets/StepperInputs/BaseStepperInput.js
src/widgets/StepperInputs/DateEditor.js
src/widgets/StepperInputs/DurationEditor.js
src/widgets/StepperInputs/StepperInputWithLabel.js
src/widgets/StepperInputs/TemperatureEditor.js
src/widgets/StepperInputs/TimeEditor.js
src/widgets/StepperInputs/index.js
src/widgets/TextEditor.js
src/widgets/WithFixedDimensions.js
src/widgets/index.js

Fixes #3308
- Adds `DateEditor` component
Internal

#3308-6 DateEditor component

---

src/actions/TemperatureSyncActions.js
src/globalStyles/colors.js
src/utilities/constants.js
src/widgets/Rectangle.js
src/widgets/SensorStatus.js
src/widgets/icons.js
src/widgets/index.js

Fixes #3307 
- Adds `SensorStatus` component
Internal

#3307  SensorStatus

---

src/navigation/Navigator.js
src/navigation/actions.js
src/navigation/constants.js
src/pages/FridgeDetailPage.js
src/pages/NewSensorPage.js
src/pages/NewVaccineModulePage.js
src/pages/SensorEditPage.js
src/pages/SettingsPage.js
src/pages/index.js

Fixes #3341 
- Simple placeholders for the vaccine module structure
Internal
N/A

#3341 Vaccine Placeholders

---

src/widgets/StepperInput.js

Fixes #3327 
- Changed keyboard type
N/A

#3327 Add correct keyboardType

---

src/actions/NewSensorActions.js
src/actions/WizardActions.js
src/localization/vaccineStrings.json
src/pages/NewSensor/BreachConfigRow.js
src/pages/NewSensor/NewSensorPage.js
src/pages/NewSensor/NewSensorStepTwo.js
src/reducers/NewSensorReducer.js
src/reducers/VaccineReducer.js
src/reducers/WizardReducer.js
src/selectors/newSensor.js
src/widgets/StepperInputs/DurationEditor.js
src/widgets/StepperInputs/StepperInputWithLabel.js
src/widgets/StepperInputs/TemperatureEditor.js
src/widgets/TextInputs/TextInputWithAffix.js

Fixes #3348 
- Adds step two!
Internal??
- Went a little against the interface design and added a 'back' button as well as the above/below around the temperature
- Really want the temps/durations to be editable..
- The 'always 2 dp' is because when you're holding down the +/- it gets really seizure-inducing
- Colors instead of just black?!.. heh
- Kind of think the 'paper' should be a consistent size througout all the tabs. Something to think about
- Navigation is a touch slow between tabs. Something to optimize when the last ones in.

#3348 New Sensor Step Two

---

src/Store.js
src/actions/SensorDetailActions.js
src/database/DataTypes/Sensor.js
src/localization/vaccineStrings.json
src/navigation/actions.js
src/pages/NewSensor/BreachConfigRow.js
src/pages/NewSensor/NewSensorStepThree.js
src/pages/NewSensor/NewSensorStepTwo.js
src/pages/SensorEditPage.js
src/pages/SettingsPage.js
src/reducers/NewSensorReducer.js
src/reducers/SensorDetailReducer.js
src/reducers/index.js
src/selectors/newSensor.js
src/selectors/sensorDetail.js
src/widgets/IconButton.js
src/widgets/Paper.js
src/widgets/PaperSection.js
src/widgets/StepperInputs/DurationEditor.js

Fixes #3349 
bit big. Soz.
- Adds sensor editing page
- 
Internal

EditSensorPage

---

src/database/utilities/createRecord.js
src/pages/SettingsPage.js
src/sync/outgoingSyncUtils.js

Fixes #3377 
- Makes sync work. Requires: https://github.com/sussol/msupply/issues/7836 branch
- Few updates to the generated data
Should extract all the code out of the component?

Add update to outgoing sync

---

src/actions/PermissionActions.js
src/actions/VaccineActions.js
src/reducers/ModulesReducer.js

Fixes #3401 
- updates `withPermission` to re-eval if permissions were granted
- Also hard enable vaccines for development!!!!
internal?
n/a

#3401 with permission should recheck permissions

---

src/reducers/NewSensorReducer.js
src/reducers/SensorDetailReducer.js
src/widgets/TextEditor.js

Fixes #3390 
- Adds simple length check on sensor code/name input
Be good to have validation feedback for the user one day ;-)

#3390 Limiting of characters

---

src/actions/Bluetooth/ScanActions.js
src/actions/VaccineActions.js
src/pages/NewSensor/NewSensorStepOne.js
src/reducers/Bluetooth/ScanReducer.js
src/reducers/Bluetooth/index.js
src/reducers/VaccineReducer.js
src/selectors/Bluetooth/bluetooth.js
src/selectors/vaccine.js

Fixes #3405 
- Similar to #3411 - extract the scan specific actions and reducers from Vaccine files.
N/A

#3405 Extract scan actions/reducers

---

src/actions/Entities/LocationActions.js
src/actions/Entities/SensorActions.js
src/actions/Entities/TemperatureBreachConfigActions.js
src/actions/Entities/index.js
src/actions/VaccineActions.js
src/database/utilities/createRecord.js
src/pages/NewSensor/BreachConfigRow.js
src/pages/NewSensor/NewSensorStepThree.js
src/pages/NewSensor/NewSensorStepTwo.js
src/reducers/Entities/LocationReducer.js
src/reducers/Entities/SensorReducer.js
src/reducers/Entities/TemperatureBreachConfigReducer.js
src/reducers/Entities/index.js
src/selectors/Entities/location.js
src/selectors/Entities/temperatureBreachConfig.js
src/widgets/StepperInputs/DateEditor.js

Fixes #3426 
- Adds `LocationReducer`
- Creates a Location when moving through the new sensor flow, which is saved after connecting and sending commands a long with temperature breach configs and the sensor iteself.
- Need to figure out what to set as the location description, how to edit location, etc?

#3426 Create a matching Location #5

---

src/pages/SettingsPage.js
src/sync/SyncQueue.js
src/sync/incomingSyncUtils.js
src/sync/outgoingSyncUtils.js

Fixes #3443?
update sync util methods to maintain relation ship between `TemperatureBreachConfig.location` and `Location`
Also updated vacc data gen to work, regressed a little due to `createRecord` changes.

#3443 fix config.location sync

---

src/database/DataTypes/Item.js
src/database/DataTypes/ItemBatch.js
src/database/DataTypes/ItemStoreJoin.js
src/database/DataTypes/StocktakeBatch.js
src/database/DataTypes/TransactionBatch.js
src/database/utilities/createRecord.js
src/pages/dataTableUtilities/actions/cellActions.js
src/pages/dataTableUtilities/actions/constants.js
src/pages/dataTableUtilities/actions/pageActions.js
src/pages/dataTableUtilities/actions/tableActions.js
src/pages/dataTableUtilities/getPageDispatchers.js
src/pages/dataTableUtilities/reducer/pageReducers.js
src/sync/incomingSyncUtils.js
src/utilities/formInputConfigs.js
src/utilities/getModalTitle.js
src/widgets/modals/DataTablePageModal.js

Fixes #3392 
- Removed a lot of uses of location type. 
- Removed a few other bits of code which aren't used anymore.
- Various code is still in which is removed in #3450 and #3451
Think that should be all the old code gone out of our LIVES

#3392 Removed usage of location type

---

src/database/DataTypes/Sensor.js
src/pages/VaccinePage.js

Fixes #3425 
- Adds a getter `mostRecentLog` - thought the name was more descriptive than `lastLog`
Internal
Realm sorted paramaters are the MOST confusing thing in the entire WORLD

#3425 Sensor.mostRecentLog getter

---

src/localization/generalStrings.json
src/localization/index.js
src/localization/reportStrings.json
src/localization/vaccineStrings.json
src/utilities/vaccineReport.js

Fixes #3459 
- Adds a bunch of localization strings
N/A

#3459 Add localized strings A2

---

src/pages/FridgeDetailPage.js
src/pages/VaccinePage.js
src/widgets/BreachManHappy.js
src/widgets/BreachManUnhappy.js

Fixes #3465 
- Adds `BreachManUnhappy` and renamed the happy breach man to `BreachManHappy` .. 🤷 
- Added into `VaccinePage`
N/A

#3465 Add empty list component to VaccinePage B2

---

src/reducers/Bluetooth/SensorDownloadReducer.js

Fixes #3478 
Added some null checks and default from the initial state

defaults for state

---

src/database/DataTypes/Sensor.js

Fixes #3487 
- Adds a field which mimics the field in the object within the SensorReducer
N/A

#3487 RSOD on editing a sensor

---

src/actions/Bluetooth/SensorDownloadActions.js

Fixes #3516 
- Shifts the action which starts the flashin'
N/A

#3516 Invalid flashing state

---

src/actions/Bluetooth/SensorDownloadActions.js
src/localization/vaccineStrings.json
src/reducers/Bluetooth/SensorDownloadReducer.js
src/selectors/Bluetooth/sensorDownload.js
src/utilities/modules/vaccines/constants.js
src/widgets/SensorHeader/LastSensorDownload.js

Fixes #3521 
- Adds error code to last download status to display to he user

#3521 display errors to user

---

src/actions/Entities/SensorActions.js
src/bluetooth/SensorManager.js
src/database/DataTypes/Sensor.js
src/selectors/Entities/sensor.js
src/selectors/fridge.js
src/sync/outgoingSyncUtils.js

Fixes #3525 
Re-committing the changes from #3538

batteryLevel optional

---

src/selectors/insurance.js
src/selectors/payment.js

Fixes #3565
Fixes the immediate problem. The confirmation screen could probably do with a more careful review, will leave that for #3564 

check for inactive on policies

---

src/actions/Bluetooth/SensorDownloadActions.js
src/bluetooth/SensorManager.test.js

Fixes #3560
- Added hopefully the correct next log timestamp
- ran tests and noticd sensormanager tests failing
Be good to test this using a physical

#3560 Logs not being saved

---

src/actions/Bluetooth/SensorUpdateActions.js

Fixes #3570 
- Corrected a field in desctructuring
I swear I touched this before 🤔

#3570 LogInterval not set correctly

---

src/pages/NewSensor/BreachConfigRow.js

Fixes #3555 
- Added prop to max value
N/A

#3555 maxValue prop in BreachConfigRow

---

src/database/DataTypes/TemperatureBreachConfiguration.js

Fixes #3549 
- Not used
N/A
N/A

#3549 Remove unused temperature breach config code

---

src/widgets/modalChildren/MultiSelectList.js

Fixes #3537 
- Uses toLowerCase and includes instead of regexp
N/A

#3537 regexp crash

---

src/widgets/ResultRow.js

Fixes #3530 
- adds an explicit font colour style to ResultRow, the component used in MultiSelectList
N/A

#3530 Explicit result row font colour

---

src/actions/Entities/SensorActions.js

Fixes #3605 
- Super small change to convert programmedDate to a date when replacing.
N/A

#3605 Set programmedDate to Date when replacing

---

package.json
src/widgets/JSONForm/JSONForm.js
src/widgets/JSONForm/JSONFormContainer.js
src/widgets/JSONForm/JSONFormContext.js
src/widgets/JSONForm/JSONFormErrorList.js
src/widgets/JSONForm/fields/AnyOf.js
src/widgets/JSONForm/fields/Description.js
src/widgets/JSONForm/fields/OneOf.js
src/widgets/JSONForm/fields/String.js
src/widgets/JSONForm/fields/Title.js
src/widgets/JSONForm/fields/index.js
src/widgets/JSONForm/templates/ArrayField.js
src/widgets/JSONForm/templates/Field.js
src/widgets/JSONForm/templates/ObjectField.js
src/widgets/JSONForm/templates/index.js
src/widgets/JSONForm/widgets/Checkbox.js
src/widgets/JSONForm/widgets/Checkboxes.js
src/widgets/JSONForm/widgets/Date.js
src/widgets/JSONForm/widgets/Radio.js
src/widgets/JSONForm/widgets/Select.js
src/widgets/JSONForm/widgets/Text.js
src/widgets/JSONForm/widgets/index.js
yarn.lock

Fixes #3611 
- Adds `rjsf/core`
- Adds some placeholder components to be overriden. Hopefully giving some structure to future work.
- Added comments and hopefully a solid base structure to move forward with
Internal
N/A

#3611  JSON Schema package

---

src/widgets/FormInputs/FormLabel.js
src/widgets/JSONForm/JSONForm.js
src/widgets/JSONForm/fields/Title.js
src/widgets/JSONForm/templates/Field.js
src/widgets/JSONForm/testJSON.js
src/widgets/JSONForm/widgets/DatePicker.js
src/widgets/JSONForm/widgets/Text.js

Fixes #3645 
- Added an update to the Field Template to handle objects and the root object differently to regular widgets.
- Removed the scrollview from focusController. If I put the form in a scrollview it does this automagically!
- Updated styles a bit cause it was annoying me
- Added tonga data to see whats up
Really I was mainly having a little play and checking things out, seeing what else needed to be done, putting the Tonga schema in to see how it was all coming together and I had some code that I thought was best to just commit.... Not sure if we should use this as the real styles
Internal

#3645 Field Template update

---

src/pages/CustomerInvoicePage.js
src/pages/SupplierInvoicePage.js

Fixes #3648 
- When columns in the SI or CI table change, update the header
Hopefully, I'm not making anything horribly un-performant 😆 seems to work ok though?

#3648 vaccine columns on invoices

---

src/selectors/Entities/temperatureBreachConfig.js

Fixes #3626 for real this time
- Kat can't do maths and had to reverse the signs for positive and negative
Hot breaches should be hotter than cold breaches no matter what type of breach 🙀

#3626 Fix +/- for Breach Threshold Input Validation

---

src/utilities/formatters.js
src/widgets/BreachChart.js
src/widgets/VaccineBarChart.js
src/widgets/VaccineLineChart.js

Fixes #3625.
Fixes vaccine plot x-axis tick formatting.
N/A.

#3625 vaccines axis ticks

---

src/actions/Entities/NameActions.js
src/actions/Entities/NameNoteActions.js
src/actions/Entities/VaccinePrescriptionActions.js
src/database/utilities/createRecord.js
src/reducers/Entities/NameNoteReducer.js
src/reducers/Entities/NameReducer.js
src/reducers/Entities/VaccinePrescriptionReducer.js
src/selectors/Entities/nameNote.js
src/widgets/FormControl.js
src/widgets/JSONForm/JSONForm.js
src/widgets/Tabs/PatientEdit.js
src/widgets/Tabs/PatientSelect.js

Fixes #3671
- Bit of a refactor of `NameNote` state/reducer/actions/selectors
- Bit of a tidy of `Name` and `VaccinePrescription` state/reducer/actions/selectors
- Made the form for editing a patient not auto focus - thoughts are that the name of a patient, and really, any of their details are unlikely to change. Arguably could have the JSONForm auto focus, that can be controlled by the `uiSchema`
N/A

#3671 Refactor of NameNote state

---

src/actions/PatientActions.js
src/database/DataTypes/Name.js
src/database/utilities/createRecord.js
src/localization/formInputStrings.json
src/utilities/formInputConfigs.js
src/widgets/DropDown.js
src/widgets/FormInputs/FormDropdown.js

Fixes #3619 
mSupply issue with footrunner code which can be run to generate required data https://github.com/sussol/msupply/pull/8196
- Adds two new conditional fields to the patient edit form control- nationality/citizenship and ethnicity
- Didn't put occupation. We need employer also, so thought to put occupation in the survey form
- Didn't put village. Dunno how we'd get that list, so we can either offer them to put it in one of the address fields or add it to the survey form.

#3619 Additional name fields

---

src/database/DataTypes/TransactionBatch.js
src/database/DataTypes/index.js
src/database/schema.js
src/sync/incomingSyncUtils.js
src/sync/outgoingSyncUtils.js
src/sync/syncTranslators.js

Fixes #3682 
- Adds medicine_admin to sync/schema
N/A

#3682 Add medicine admin to schema+sync

---

src/actions/Entities/VaccinePrescriptionActions.js
src/database/DataTypes/MedicineAdministrator.js
src/database/DataTypes/TransactionItem.js
src/database/DataTypes/index.js
src/database/schema.js
src/localization/vaccineStrings.json
src/reducers/Entities/VaccinePrescriptionReducer.js
src/selectors/Entities/vaccinePrescription.js
src/widgets/Tabs/VaccineSelect.js

Fixes #3694 
- INCLUDES Code from #3693 and #3690
- Adds ability to select a vaccinator. Defaults to the most recent vaccinator selected.
(My vaccineator has no code/first/last)

#3694 Select a vaccinator

---

src/actions/Entities/VaccinePrescriptionActions.js
src/database/DataTypes/TransactionItem.js
src/localization/generalStrings.json
src/widgets/Tabs/VaccineSelect.js

Fixes #3681 
- OK And Next feature
N/A

#3681 Add OK and Next functionality

---

src/localization/navStrings.json
src/pages/MenuPage.js
src/pages/VaccinePage.js
src/widgets/icons.js

Fixes #3698 
As per the issue, renamed and moved buttons.
Added unnecessary icons to the module buttons

#3698 update menu page

---

src/pages/MenuPage.js
src/widgets/IconButton.js

Fixes #3698
Ooops. merged with an un-pushed commit.

set underlayColor of IconButton

---

package.json
src/actions/Entities/NameNoteActions.js
src/sync/incomingSyncUtils.js
src/widgets/DropDown.js
src/widgets/FormControl.js
src/widgets/FormInputs/FormDateInput.js
src/widgets/JSONForm/JSONForm.js
src/widgets/JSONForm/widgets/Select.js
src/widgets/Tabs/PatientEdit.js
src/widgets/Tabs/PatientSelect.js
yarn.lock

Fixes #3689 
Fixes the error which is thrown if there's no schema.
Also removed a couple of warnings
- picker deprecation
- canSaveForm

#3689 error when no schema

---

src/actions/Entities/NameActions.js
src/reducers/Entities/NameReducer.js
src/reducers/Entities/VaccinePrescriptionReducer.js
src/widgets/AfterInteractions.js
src/widgets/FormControl.js
src/widgets/JSONForm/JSONForm.js
src/widgets/Tabs/PatientEdit.js
src/widgets/Tabs/PatientSelect.js
src/widgets/Tabs/VaccineSelect.js

Fixes #3670 
- Really just using after interactions to help navigate a bit quicker.
- Little bit of debouncing on inputs to prevent so many re-renders (causes a little bit of weirdness when enabling buttons as we have to wait a little bit for the debounce. Think it's OK though
- 
Think it feels a bit better

#3670 performance 

---

src/localization/generalStrings.json
src/localization/vaccineStrings.json
src/pages/VaccineDispensingPage.js
src/reducers/Entities/NameReducer.js
src/selectors/Entities/name.js
src/widgets/FormInputs/FormDateInput.js
src/widgets/FormInputs/FormTextInput.js
src/widgets/FormInputs/FormToggle.js
src/widgets/JSONForm/templates/Field.js
src/widgets/Paper.js
src/widgets/SimpleTable.js
src/widgets/Tabs/PatientEdit.js
src/widgets/Tabs/PatientSelect.js
src/widgets/Tabs/VaccineSelect.js

Fixes #3708 
- Some UI adjustments
- Still need to:
- Better handle 'search' in patient select
- Fix up the top row in step3 - specifically the vaccinator drop down

#3708 UI polish

---

src/selectors/fridge.js

Fixes #3514.
Fixes most likely candidate for where the bugsnag error in #3514 is coming from.
N/A (error is unreplicable).
To be revisited if error comes up again!

#3514 add default breach boundary temperatures

---

src/localization/vaccineStrings.json
src/widgets/Tabs/VaccineSelect.js
src/widgets/VaccinePrescriptionInfo.js

Fixes #3712 
- Adds some style updates. I am not happy but I think if I spend anymore time it'll just get worse

#3712 Vaccinator drop down

---

src/widgets/modalChildren/PatientEditModal.js

Fixes #3772 
- Forgot to update this onChange call
Typescript please 🤣

#3772 Fix validator bug in PatientEditModal

---

src/actions/Entities/VaccinePrescriptionActions.js
src/widgets/Tabs/VaccineSelect.js

Fixes #3781 
- Only use batches with stock
N/a

#3781 Use batchesWithStock

---

src/actions/Entities/NameActions.js
src/actions/Entities/NameNoteActions.js
src/actions/Entities/VaccinePrescriptionActions.js
src/actions/PatientActions.js
src/database/DataTypes/Name.js
src/database/DataTypes/NameNote.js
src/hooks/index.js
src/hooks/useFetch.js
src/hooks/useLocalAndRemotePatients.js
src/hooks/useThrottled.js
src/localization/generalStrings.json
src/pages/DispensingPage.js
src/reducers/Entities/NameReducer.js
src/reducers/PatientReducer.js
src/widgets/Tabs/PatientSelect.js
src/widgets/modalChildren/PatientEditModal.js

Fixes #3783 
- Adds online lookup to vaccine dispensing
- Lots of side effects !
- Normal dispensing edit/creation
- Vaccine dispensing edit/creation
- Errors in communicating with the server

#3783 Lookup patients online when vaccine dispensing

---

src/widgets/VaccinePrescriptionInfo.js

Fixes #3789 
- sorts vaccinators
N/a

#3789 sort MedicineAdministrators

---

src/hooks/index.js
src/hooks/useAfterInteractions.js
src/hooks/useIsMounted.js
src/hooks/useKeyboardIsOpen.js
src/hooks/useMountProtectedState.js
src/widgets/AfterInteractions.js
src/widgets/modals/LoginModal.js

Fixes #3727 
- Fixes `AfterInteractions` to not set state on an unmounted component
- Fixes `LoginModal` to not `setState` on an unmounted component by removing `onLogin` which I have no idea what it was doing 🤔 
- Fixes `useKeyboardIsOpen` to not set state on unmounted components
Internal
N/a

#3727 Remove setting of state of unmounted components

---

src/actions/DispensaryActions.js
src/database/UIDatabase.js
src/localization/tableStrings.json
src/pages/DispensingPage.js
src/pages/dataTableUtilities/constants.js
src/pages/dataTableUtilities/getColumns.js
src/reducers/DispensaryReducer.js
src/reducers/ModulesReducer.js
src/selectors/dispensary.js
src/selectors/modules.js
src/widgets/DataTable/DataTableRow.js

Fixes #3802 
- Adds a new ADR column [I really hate "if you have some of this type of record this customisation is ACTIVATED things"]
- 
internal

#3802 Add new ADR column

---

src/actions/DispensaryActions.js
src/database/DataTypes/AdverseDrugReaction.js
src/database/DataTypes/index.js
src/database/UIDatabase.js
src/database/schema.js
src/localization/tableStrings.json
src/pages/DispensingPage.js
src/pages/dataTableUtilities/constants.js
src/pages/dataTableUtilities/getColumns.js
src/reducers/DispensaryReducer.js
src/reducers/ModulesReducer.js
src/selectors/dispensary.js
src/selectors/modules.js
src/sync/SyncQueue.js
src/sync/outgoingSyncUtils.js
src/sync/syncTranslators.js
src/widgets/DataTable/DataTableRow.js

Fixes #3799 
- Adds ADR table with sync
*Ensure this pr is merged: https://github.com/openmsupply/mobile/issues/3795*
N/A

Add ADR table to schema

---

src/actions/Entities/NameActions.js
src/actions/PatientActions.js
src/hooks/useLocalAndRemotePatients.js
src/localization/generalStrings.json
src/sync/lookupApiUtils.js
src/widgets/Tabs/PatientSelect.js
src/widgets/modals/SearchForm.js

Fixes #3710 
- Note: Requires the mSupply branch https://github.com/sussol/msupply/pull/8286

#3710 Create an NSJ on the server when using a remote patient

---

src/actions/Entities/VaccinePrescriptionActions.js
src/widgets/Tabs/VaccineSelect.js

Fixes #3828 
- Adds a correct vaccinator default when there have been no batches issued previously
N/A

#3828 Corrected default vaccinator

---

src/sync/outgoingSyncUtils.js

Fixes #3834 
- Correct casing
N/A

#3834 Add corrected casing

---

src/widgets/JSONForm/JSONForm.js
src/widgets/JSONForm/widgets/Textarea.js
src/widgets/JSONForm/widgets/index.js

Fixes #3860 
For testing you may wish to look at https://github.com/sussol/msupply/pull/8368 which makes use of the textarea
Created a new widget ( copy of `Text` ) and added multiline and number of lines

add textarea

---

src/actions/Entities/VaccinePrescriptionActions.js

Fixes #3854 
- only select a vaccine item if it has stock
N/A

#3854 Add only selecting vaccine items with stock

---

src/widgets/FormInputs/FormLabel.js

Fixes #3872 
- A bit less busy
Internal
N/a

#3872 Add asterix

---

src/hooks/useLocalAndRemotePatients.js
src/localization/generalStrings.json
src/selectors/Entities/vaccinePrescription.js
src/widgets/Tabs/PatientSelect.js
src/widgets/Tabs/VaccineSelect.js

Fixes #3894 
- navigating to patient select feels a bit faster
- Search online gets disabled
- ok and next/ok buttons are one press now- could cause funny behaviour if spammed
N/A

#3894 couple of polishes for vaccines

---

src/database/UIDatabase.js

Fixes #3687 
- Sort schemas by version
Internal..
N/A

Add sorting of schema forms

---

src/sync/incomingSyncUtils.js
src/sync/outgoingSyncUtils.js

Fixes #3886 
- fixes couple of sync probs
N/A

#3886 name note sync fixes

---

src/database/DataTypes/Location.js
src/database/UIDatabase.js
src/database/schema.js
src/pages/dataTableUtilities/getPageInitialiser.js
src/pages/dataTableUtilities/reducer/tableReducers.js
src/sync/incomingSyncUtils.js
src/sync/outgoingSyncUtils.js
src/widgets/modals/DataTablePageModal.js
src/widgets/modals/StocktakeBatchModal.js

DUPLICATE OF https://github.com/openmsupply/mobile/pull/3929
I had branched from a branch which was no longer required so cherry picked onto here

Add handling of [location]hold

---

src/selectors/patient.js

Fixes #2746
- Hide non-finalised prescriptions from patient history
I didn't see any, hopefully, I didn't miss any

#2746 hide non finalised prescriptions from history

---

package.json
src/widgets/JSONForm/JSONForm.js
src/widgets/JSONForm/widgets/Radio.js
yarn.lock

Fixes #3957 
Added radio buttons
Tested with the ADR form which uses radios for string and boolean types. Haven't gone further than that.. is working for those 
Tried to make them look like the web version, so have tweaked the circle sizes and colours to make that look ok.

add radio button widget

---

package.json

Add Bump: v8.0.2

---

src/sync/SyncModal.js

Fixes #4025 
The vertical margin was causing an issue. Have also updated the button to use `authFormButton` to make it more consistent, as it is using `authFormButtonText`

update sync button style

---

android/app/build.gradle

Fixes #4036 
Revert inadvertent version # code changed with React Native upgrade.
Applies only to armeabi apk.
- Install 8.0.X versioned apk onto a tablet
- Run and verify ok
- Build 8.1.X versioned apk and install on a tablet
Not sure.

#4036 Revert build.gradle version # change

---

package.json
src/actions/Entities/NameActions.js
src/database/DataTypes/ItemBatch.js

Fixes #4051 
Merged master into develop
N/A

#4051 merge 8.0.6 into develop

---

src/widgets/PrescriptionInfo.js

Fixes #4093 
- Went the easy route rather than trying to get flex working betterer........ bad idea?
N/A

#4093 patient name cutoff

---

src/reducers/PatientReducer.js
src/widgets/PrescriptionInfo.js
src/widgets/Tabs/PrescriptionConfirmation.js

Fixes #4100
- Minor syntax correction
N/A

#4100 Add correct syntax

---

src/widgets/Tabs/PatientSelect.js

Fixes #4157 
Enable QR code patient lookup button
What does QR actually stand for? 🤔

enable button

---

src/database/DataTypes/MedicineAdministrator.js
src/database/UIDatabase.js
src/database/schema.js
src/sync/incomingSyncUtils.js

@Fixes #4158
- Filter by softly deleted
- accept is_active field
N/A

#4158 Add integration and use of [medicine_administrator]is_active

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Added a couple of default tags to issues 
- 'Bug: ????' (for bugs)
- Priority: unconfirmed (for feature requests)
Spelling 🇺🇸  -> 🇬🇧 
Not sure if I've targetted the right branch for these to take effect.

Update GitHub templates

---

src/widgets/modalChildren/MultiSelectList.js

Fixes #4150
Increase button height to stop the text from disappearing 
N/A

#4150 Increase button height slightly

---

src/pages/FridgeDetailPage.js
src/widgets/VaccineBarChart.js

Fixes #4180 
Second try at this one.. after branching from the 8.1.1. release branch
The rendering problem which was visible with the line chart is also affecting the bar chart.
Also fixed the default, which was incorrectly set to `line` while working on that one

show lines

---

src/selectors/Entities/sensor.js
src/widgets/SensorHeader/LastSensorDownload.js
src/widgets/SensorHeader/SensorHeader.js
src/widgets/SensorStatus.js

Fixes #4193 
Oops! Found a case where the id is not provided by props 🙄 
Reverted the unnecessary changes and added an undefined check when fetching sensors.

#4193 sensor undefined

---

src/reducers/Entities/VaccinePrescriptionReducer.js

Fixes #4237
- Add missed state update
N/A

#4237 Update isSupplementalDataValid state

---

src/widgets/modalChildren/AutocompleteSelector.js
src/widgets/modals/ByProgramModal.js

Fixes #4251 
- I could only replicate on the `ByProgramModal` customer/supplier search.
N/A

Add correct filtering

---

src/widgets/FormInputs/FormDOBInput.js

Fixes #4264 
Just changing the number of decimal places, as per a request from several users now.

show age as 0 dp

---

src/widgets/Tabs/PatientSelect.js
src/widgets/modals/PatientHistory.js

Fixes #4263 
- Variable rename
N/A

#4263 Hide remote non vaccinations from vaccination history

---

src/widgets/JSONForm/JSONForm.js
src/widgets/JSONForm/widgets/Checkbox.js
src/widgets/JSONForm/widgets/Checkboxes.js
src/widgets/JSONForm/widgets/DatePicker.js
src/widgets/JSONForm/widgets/Radio.js
src/widgets/JSONForm/widgets/Select.js
src/widgets/JSONForm/widgets/Text.js
src/widgets/JSONForm/widgets/Textarea.js
src/widgets/JSONForm/widgets/TimePicker.js
src/widgets/Tabs/PatientEdit.js
src/widgets/Tabs/VaccineSupplementalData.js

Fixes #4311 
- Dunno if this is good- i just removed the live validation 🤷 
🤷

#4311 better json live validation

---

src/widgets/modals/VaccinationHistory.js

Fixes #4314 
- Filters out refusals because they look ugly.
- Maybe it would be better to have them, but I dunno how to deal with the columns in that case.. 🤷 
N/A

#4314 filter out refusals

---

src/globalStyles/authStyles.js
src/pages/FirstUsePage.js
src/widgets/AuthFormView.js
src/widgets/modals/DemoUserModal.js
src/widgets/modals/LoginModal.js

Fixes #4276 
This has finally bothered me enough to actually fix it.
Adjusting the margin of the login modal, depending on the state of the soft keyboard. 

adjust layout on keyboard open

---

src/widgets/Spinner.js

Fixes #1546 
Migrate Spinner to React hooks

 #1546 Migrate Spinner to hooks

---

src/actions/PrescriptionActions.js
src/reducers/PrescriptionReducer.ts
src/selectors/prescription.js
src/widgets/Tabs/ItemSelect.js

Fixes #3771
Reloads the prescription items when the ItemSelect gets mounted. It seams like ItemSelect gets mounted whenever the DB gets updated for which reason I don't trigger a reload in PrescriptionCartRow.onChangeQuantity.

#3771 update stock list

---

src/authentication/Helpers.ts
src/authentication/SyncAuthenticator.js
src/authentication/UserAuthenticator.js

Fixes #4361 
Moved the `authenticateAsync` method from `sussol-utilities` and updated the user auth method to display errors.

bring in syncAuthenticator from sussol-utilities

---

src/actions/Entities/VaccinePrescriptionActions.js
src/database/DataTypes/Item.js
src/database/DataTypes/Transaction.js
src/database/DataTypes/TransactionItem.js

Fixes #4406
- Adds prescription details into vaccination `name_note` records
```
{
"refused": false,
"bonusDose": false,
"itemName": "COVID19 Vaccine AstraZeneca",
"itemCode": "COV1",
"batch": "batch_1",
"expiry": "2024-12-30T11:00:00.000Z",
"vaccineDate": "14/09/2021",
"vaccinator": "MA Medicine Administrator",
"refusalReason": "",
"extra": {
"prescription": {
"id": "843c3a90151c11ec98594f358ecd0458",
"serialNumber": "92",
"comment": "",
"customData": "{\"country\":\"Kiribati\"}",
"entryDate": 1631597276344,
"type": "customer_invoice",
"status": "finalised",
"confirmDate": 1631597276344,
"enteredBy": "0763E2E3053D4C478E1E6B6B03FEC207",
"theirRef": null,
"items": [
{
"id": "843cd6d0151c11ec98594f358ecd0458",
"item": {
"id": …
```

#4406 Add prescription records to vaccination name_notes

---

src/database/DataTypes/TemperatureBreach.js
src/widgets/BreachChart.js

Fixes #3697.
Just tidying up by removing some old methods. 
N/A.
N/A.

#3679 remove duplicate temperature breach methods

---

.eslintrc
src/database/UIDatabase.ts
src/mSupplyMobileApp.js
src/reducers/PrescriptionReducer.ts
src/utilities/logging/Engine.ts
src/utilities/logging/Logger.ts
src/utilities/logging/Service.ts
src/utilities/logging/index.ts
src/utilities/logging/types.ts
src/widgets/DataTable/CheckableCell.js
src/widgets/DataTable/EditableCell.js
src/widgets/DataTable/Row.js
src/widgets/DataTable/TextInputCell.js
src/widgets/DataTable/TouchableCell.js
src/widgets/ExpiryDateInput.js
src/widgets/JSONForm/JSONFormErrorList.js

Fixes #4456
Minor updates to 'fix' (or silence where appropriate) the various errors thrown by eslint.
N/A

#4456 Fix linting errors

---

src/widgets/modals/LoginModal.js

Fixes #4485
Very minor update to the password input on login (found while doing French translation updates).
N/A

#4485 Add localised placeholder string to input

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/res/xml/network_security_config.xml
package.json

For #4552
- Bumps version for release
- 8.4.2 RC2 with http allowed appears to be working well in training so time to release? 👍 
Have also merged #4579 to allow http from Android 9 and above

Release 8.4.2

---

src/actions/Entities/NameNoteActions.js
src/actions/Entities/VaccinePrescriptionActions.js

Added transact id
Fixes #4635 
Added prescription id in name note of type "PCD".
If there are any general areas of the codebase your changes might have side effects on, mention them here

Added transact id

---

src/pages/MenuPage.js

Remove flag

---

src/authentication/UserAuthenticator.js

Check if userJson is undefined or not.
Fixes #4684 
Added new error if userjson is undefined rather than "Unexpected response from server"

#4684 Need to handle undefined UserJson

---

src/widgets/Tabs/PatientSelect.js

#4792 Bug fixed

---

src/globalStyles/buttonStyles.js
src/sync/lookupApiUtils.js
src/widgets/Stepper.js
src/widgets/Tabs/PatientSelect.js
src/widgets/modals/VaccinationEvent.js

Fixes #4805 
Get patient record form the database on viewing patient's history
Test editing vaccination event again please
Everything should run like clockwork 😉😅
Some fixes made:
- Now you don't have to even sync to get the recent updates on the name notes. Just close patient history after editing, open it again right away - all the changed details are there already
- Buttons "Save changes" look better
- After you click "Edit vaccine" the correct vaccine is selected

#4805 Editing vaccination event detail is very inconsistent

---

src/actions/PatientActions.js
src/database/utilities/createRecord.js
src/localization/dispensingStrings.json
src/localization/generalStrings.json
src/localization/modalStrings.json
src/pages/DispensingPage.js
src/reducers/PatientReducer.js
src/selectors/dispensary.js
src/selectors/patient.js
src/widgets/modalChildren/PatientEditModal.js
yarn.lock

Fixes #4802
- Allow patients without any active vaccine event history to be deleted by admin
The code has language file changes.

#4802 Kiribati: Delete patient medical record

---

src/widgets/Tabs/PatientSelect.js

#4885 Disable deleted patient from being given vaccine

---

src/widgets/Tabs/VaccineSelect.js

Fixes #4886
disabled the `OK & Next` button after clicking.

#4886 App hangs/keeps on loading forever when OK&Next button is clicked multiple times while entering a vaccination event

---

src/widgets/VaccinatorDropDown.js
src/widgets/modals/VaccinationEvent.js

Fixes #4888
Fixes app crashes on tapping save changes button multiple times
Out of stock vaccine causes dropdown error
Cannot save edit of Page 3: Vaccination event

#4888 Fix app crashes on tapping save changes button multiple times

---

src/actions/Entities/NameActions.js
src/actions/Entities/NameNoteActions.js
src/actions/PatientActions.js
src/database/utilities/createRecord.js
src/utilities/checkIsObject.js
src/utilities/index.js

#4911 when new vaccine event is created all other vaccine events of the patient are updated along with it causing sync issues 

---

src/actions/Entities/NameActions.js
src/actions/Entities/VaccinePrescriptionActions.js

#4920 Patient homes store vax event error

---

README.md

Fixes #4995
Update readme and also update wiki pages with the latest changes.
NOne

#4995 update readme

---

src/actions/UserActions.js
src/dataMigration.js
src/database/utilities/constants.js
src/database/utilities/createRecord.js
src/database/utilities/index.js
src/database/utilities/numberSequence.js
src/mSupplyMobileApp.js
src/pages/MenuPage.js
src/pages/StocktakeManagePage.js
src/sync/SyncQueue.js
src/sync/incomingSyncUtils.js
src/sync/outgoingSyncUtils.js
src/sync/syncTranslators.js
src/widgets/withOnePress.js

Fixes #5004
- We have a new logic for NumberSequence object and NumberReuse object.
- Previously these tables (Number & NumberReuse) were being synced from mSupply, not anymore. So remove all of the sync logic.
- There is a logic that checks different types of records (CI, SI (SI and SC), Stocktake, Requisition request, Requisition response, Inventory adjustment) and gets the highest serial number, and record it so that we can add 1 to that number to be added as serial number for next record.
- Clear Number & NumberReuse tables when new sync site is registered or mobile version upgrade is done.

5004 number records removed from sync

---

package.json
src/localization/programStrings.json
src/pages/SupplierRequisitionPage.js
src/utilities/prediction/macroEyes.js

Fixes #5188 
- Use positive daily usage as item_filter (should result in more reliable requests to API)
- Move API Key db lookup inside request, to avoid global state not being updated correctly? - Possible improvement
- Add notification toasts to inform user of AI API interactions
*Success*
*Error*
Performance issue on old devices?

Add notifications for AI API interactions

---

src/widgets/FormControl.js
src/widgets/FormInputs/FormDOBInput.js

Fixes #5157
Even after with valid date, we weren't allowed to save the new patient. After debugging, I found out that `debouncedUpdateForm(key, value)` was causing the issue so i removed it. To my knowledge, the debounce wasn't really necessary there so I removed it.

#5157 dob bug fixed in new patient adding page
