android/app/build.gradle
So long as we don’t have more than 999 minor or 999 patch updates in a
Major release, should be good.
Will break if say beta package.json versions are set i.e. 1.1.0-beta.1
I welcome different ideas.
=> Automate Android versionCode

src/dataMigration.js
Assumes no one is upgrading from a version prior to some really early
version where we started persisting the version to disk. I think it’s
safe to assume that no one has those very early builds any more.
=> Don't migrate data on fresh install

android/app/src/main/AndroidManifest.xml
Have had a bug whereby if you press the ‘home’ button, but don’t
actually kill the app, then you reopen the app by tapping its icon, the
currentUser gets set to null (among other things that happen during the
MSupplyMobileApp constructor). This was bound to cause some nasty
issues, and is fixed by this change.
=> Fixes the mSupplyMobileApp constructing again on reopen

android/app/build.gradle, package.json
So that versions can be applied on top of each other as upgrades
=> Allow provisional rc numbers to extend build numbers

src/pages/CustomerInvoicesPage.js, src/pages/CustomerRequisitionsPage.js, src/pages/SupplierInvoicesPage.js, src/pages/SupplierRequisitionsPage.js
With entered dates now not exactly matching the order of requisitions
and transactions appearing on a given mobile device, serial numbers are
a better option for sorting so that the user always sees any new
requisitions etc. at the top of the list
=> Sort by serial number in lists

package.json, src/main.js, src/sync/reducer.js, src/utilities/createReducer.js, src/utilities/index.js, yarn.lock
Note: not using autoRehydrate, so that this is an ‘opt-in’ system,
where a reducer must provide the REHYDRATE action in order to have some
part of state persisted. This is to avoid redux-persist unexpectedly
remembering too much (e.g. we don’t want navigation persisted)
=> Use redux persist to remember last sync time and any error

src/database/DataTypes/Transaction.js
Now that stock page and maybe even stock take page displays batch name, we should assign batch name to external supplier invoice ItemBatches in similar fashion to stock take.
=> Adjust Batch name when finalising external si

src/pages/SupplierInvoicePage.js
~~Was meant to fix issue #540, but it doesn't really make sense. Doesn't seem to consistently throw the bug anymore, even if I switch back to master branch...~~
Fixes #540, I was testing with spacebar rather than backspace. Has to actually be an empty string for the bug to occur.
Changes are consistent with implementation elsewhere in app.
=> #540 Parse as int, use set method, right align value

package.json, src/database/DataTypes/Item.js, src/database/DataTypes/Requisition.js, src/database/DataTypes/Transaction.js, src/database/schema.js, src/database/utilities/createRecord.js, src/pages/CustomerInvoicePage.js, src/pages/StockPage.js, src/pages/StocktakeManagePage.js, src/pages/SupplierInvoicePage.js, src/pages/SupplierRequisitionPage.js, src/sync/incomingSyncUtils.js
fixes #622 
If existing sites have already used cross reference items and made item batches for them... it's a bit late. The most solid resolution I have is to merge the cross reference items with the items they reference, then recreate the cross reference item (as it definitely should have been the one deleted in the merge). This should sync out to mobile safely. @GaryWilletts @ujwalSussol @craigdrown @bijaySussol @andreievg @adrianwb any other ideas or caveats?
Hey you can actually tag groups @sussol/msupplyadmin 
Alternative is a more manual version of the same thing, making inventory adjustments for the real items adding the stock and deleting the stock on the cross reference items.
Cross reference item to be referred to as CRI below.
=> #xxxx item cross reference

src/database/DataTypes/Stocktake.js, src/database/DataTypes/StocktakeBatch.js, src/database/DataTypes/StocktakeItem.js
Not quite a fix for #638 
Stocktake correctly applies the difference of `counted quantity - snapshot quantity` through transaction mechanism, rather than separately editing the stock on hand directly to be counted quantity.
Also, reducing stock below minimum check is done on a batch basis. Previously it checked if item total quantity would be made negative, rather than if any individual batch quantity would be made negative.
=> #638 fix stocktake ledger issue

src/database/DataTypes/Stocktake.js, src/database/DataTypes/StocktakeBatch.js, src/database/DataTypes/StocktakeItem.js, src/globalStyles/confirmModalStyles.js, src/globalStyles/index.js, src/globalStyles/navigationStyles.js, src/localization/modalStrings.js, src/pages/StocktakeEditPage.js, src/widgets/modals/ConfirmModal.js, src/widgets/modals/FinaliseModal.js
Merge #653 first, this is branched off that. Or rebase this to that branch?
=> #638 reset out of date stocktake items

package.json, src/database/DataTypes/Transaction.js, src/database/UIDatabase.js, src/sync/PostSyncProcessor.js
Allow deleting a transaction through sync. This is gross, but should only occur when we manually send a delete record (as primary wouldn't normally allow deleting in this way).
Required at this point as a regression in mobile allowed sending customer invoices and requisitions to self (and corresponding supplier invoices), so to clean up we need to be able to run scripts on server to delete transactions.
=> #xxxx sync delete

src/localization/demoUserModalStrings.js, src/widgets/modals/DemoUserModal.js
Fixes #773 
There was a method `onDemoSubmittedModalClose` in `widgets/modals/DemoUserModal.js`, which was being called inside render rather then being bound. This would cause React to infinitely call render in a loop.
The code was compiling in older branch and I did not notice it until it crashed today. After the merge react-native would just not compile the application and would error out to a red screen.
Please look at the issue #773 for error file.
It's very minor fix.
=> #773 Fix compile error after demo branch merge to develop

src/database/utilities/mergeRecords.js
Fixes #778.  
As merge logic is relatively bound to incoming sync, it may be more suitably located in the sync folder. This would avoid the ugly '../../' import statement.
=> Import createOrUpdateRecord in mergeRecords.js

src/widgets/modals/ConfirmModal.js
- Fix #806
- Modal needs `isOpen` as one of the props, since the lint code extracted it into a constant it was no longer available in `modalProps` object, hence the modal was not opening because it never got `isOpen` prop as true.
=> Fix finalise modal not showing

src/widgets/MiniToggleBar.js
Fixes #840 
Adds a `MiniToggle` component.
'Neutral' state might be a little to bold? Can lighten - but also might need a better indicator that this should be pressed. Maybe appending a '?' to the text?
- Controlled by one onPress. Can use a key to return to control depending on which button of the toggle was pressed.
- Responsive:
Just noticed I did the on/off states opposite to what was in the example. I guess just natural that the truthy state be first? Easy to switch
Branch here to test: https://github.com/openmsupply/mobile/tree/%23840-vvn-component-example
=> #840 - VVN Component

src/database/DataTypes/TransactionBatch.js
Fixes #859 
Just adding a getter back that I removed.
Note on safeness:
- Realm list properties are always defined
- Every object must have an id
- array method is safe to run on empty lists
=> #859 transaction batch missing getter

src/database/DataTypes/Item.js, src/database/DataTypes/ItemBatch.js, src/database/DataTypes/Transaction.js
Fixes #865 
- Some of these could be slightly more efficient (e.g. `getBreachedBatches` could filter on location before breach status) for uglier code
- Some may be unnecessary e.g just getting the length. Personally I like them as they are used a bit, but I can see the argument for them not being useful.
- Not sure about the names
- The two removed getters were duplicates
=> #865 class helper methods

src/pages/ItemManagePage.js, src/widgets/ExpiryTextInput.js, src/widgets/FinaliseButton.js, src/widgets/IconCell.js
Fixes #851
Branch I developed on mainly: [#851-manage-vaccine-page-test](https://github.com/openmsupply/mobile/tree/%23851-manage-vaccine-page-test) (I need a better way to do this .. )
Just the skeleton really. Still a few things to do:
- on apply changes (the biggest part, really)
- opening breach modal.
- Navigation, but really is from the parent/prior page component
Other than just creating this component, 
- have updated `IconCell` to also be able to render *just* an icon, rather than *text+icon*. 
- `FinaliseButton` to be able to pass in some text and some font styles.
=> #851 manage vaccine item page

src/utilities/modules/vaccines.js
Fixes half of #843 
Other methods will be a part of #878 
`extractBreaches` : 
- Allows for either an array of `SensorLog` objects or a `Realm.results`. *Could* enforce that it must be a `Realm.results` so that we can use Realm sorting. Wanted to be safe for now, if it turns out we always are calling with a `Realm.Results`, I think change the method then. It is annoying to 'create' `Realm.Results` objects, imo.
- Potentially there is a different way to use `Results.filtered` by using the timestamps of the delimiter `SensorLog` objects, but this would be time consuming to find the surrounding `SensorLog` objects. Would require a similar method, but would use the timestamps of the delimiters to find all `SensorLog` between. Would then need to `find()` the first and last `SensorLog` in an …
=> #843 helper methods

src/sync/incomingSyncUtils.js
Fixes #895 
Null was being returned from `validateJson`, which caused a runtime error as `Settings` values must be a string.
- Changing `validateJson` to just return `''`
- Checking for 'undefined' earlier
Incoming `custom_data` or `tags` which are empty strings will not be set
=> #895 custom data undefined

src/database/DataTypes/Item.js, src/database/DataTypes/ItemBatch.js
Fixes #882 
Still some methods that could be removed, but think I should leave them till later.
The `Item.getTemperatureExposure` example in issue gives the temperature exposure for an Item while it was in a certain location. I don't think we should not count the exposure for certain batches while they were in different locations? Happy to change this but it doesn't seem correct to throw away that a batch has potentially been in a lower or higher temperature, just in a different location?
=> #882 refactor item getters

src/utilities/formatters.js, src/utilities/modules/vaccines.js, src/widgets/BreachTable.js, src/widgets/SimpleTable.js, src/widgets/StackedTables.js, src/widgets/index.js
Fixes #870 
[messy dev branch](https://github.com/openmsupply/mobile/tree/breach-modal)
Ended up making this very dumb.
Expectation is that data will just be passed. Data will be fetched inside of a `runWithLoadingIndicator`. (Could cache it to save time if needed?)
Title is set in the `PageContentModal` this will be wrapped in
- I really hate the `formattedDifferenceBetweenDates` method
- Could change this to fetch some data when expanding a row quite easily
- To fetch the data:
- `extractBreaches()` - passing `sensorLogs` from a `Location`, `ItemBatch` or `Item`
- `sensorLogsExtractBreaches()` passing each `breach` from `extractBreaches`
- `extractBreach()` - on return value from above
-  `aggregateLogs` - will return the chartData needed
=> #870 breach modal

src/globalStyles/colors.js, src/globalStyles/index.js, src/widgets/HazardPoint.js, src/widgets/VaccineChart.js
Fixes #896.
Test branch `#896-refactor-vaccine-chart`.
Changelog:
- `VaccineChart` graph components refactored into smaller methods.
- `VaccineChart` props updated for consistency with `aggregateLogs`.
- `VaccineChart` return value updated.
- `VaccineChart` and `HazardPoint` styles updated and tidied up
=> #896 refactor vaccine chart

src/database/DataTypes/Item.js, src/pages/CustomerInvoicePage.js, src/pages/VaccineModulePage.js, src/utilities/modules/vaccines.js, src/widgets/BreachTable.js
Fixes #909 
- Adds a Breach column to `CustomerInvoicePage`
- Small update to `vaccines.js`
- Was not filtering the `ItemBatches` by `Item` or `ItemBatch`
- Added data for the date column for a breach
- Double use of variable `Item` (Used as a parameter
I couldn't not trace it properly, but if I did not set `breachData` as state, and instead just used a `getBreachData()` method for the `BreachModal` to get it's data, on navigating back from `CustomerInvoicePage`, when the modal was open - some infinite recursion was happening? Not a fan of putting this in state, so will take another look most likely to make sure there isn't a way to not have this data in state.
=> #909 customer invoice breach column

src/pages/ManageVaccineItemPage.js, src/pages/ManageVaccineStockPage.js
Fixes #911 
- Adds `BreachTable` as a modal to each page
- `VaccineItemManagePage`
- `VaccineStockManagePage`
- `VaccineModulePage`
- Also alters the `BreachTable` modal logic on `CustomerInvoicePage`
- Alters slightly `BreachTable`
PR makes `BreachTable` accept an array of `Breaches`, which will then call the required methods to gather data needed to render in `runWithLoadingIndicator` within `componentDidMount`.
I think this is the best solution as, for example fridge hazards will have a breach already, making it unnecessary to call `extractBreaches`. By passing `BreachTable` a 2D array of `sensorLogs` (the breaches), this makes it more generic for all use cases, rather than having to pass a 'type' or use logic to work out who is passing the data.
The `runWithLoadingIndicator` is a …
=> #911 - Breach modal integration

src/database/utilities/createRecord.js, src/pages/SupplierRequisitionPage.js, src/pages/expansions/RequisitionRegimenModalTable.js
Fixes #921 .. kind of
- On editing a cell in `GenericTablePage`, `refreshData()` is called. 
- This will clear `cellsRefMap`
- `cellsRefMap` is populated when a cell is rendered
- On re-rendering the `ListView`, only objects (or rows) which have changed will be re-rendered [ using a shallow compare ]
- As we only change the reference to one object currently, all others will return true on a shallow comparison and will not re-render, not populating `cellRefsMap`
- After editing a cell `onEndEditing()` is called, which will call `focusNextCell`, attempting to access the `cellRefsMap` and throwing a runtime error.
To enable the use of `JS Objects` rather than `Realm entities`, All objects within the `regimenData` array should return false on a shallow compare, ensuring that `cellRefsMap` is …
=> #921 regimen data bug

src/database/DataTypes/Item.js, src/settings/MobileAppSettings.js, src/sync/incomingSyncUtils.js
Can now set:
`monthlyConsumptionLookBackPeriod` (string number), defaults to 3 month as per before
and
`monthlyConsumptionEnforceLookBackPeriod` (string boolean), defaults to false
PR is into 921-regimen-data-bug, as this seems to be the most stable branch 
using globals because dailyUsage is a getter and it is used by other methods which are used by other methods and it would be large amount of changes (easy to introduce bugs) to pass through `settings`
=> Ic cmm calculation

src/pages/CustomerInvoicePage.js, src/pages/SupplierInvoicePage.js, src/widgets/MiniToggleBar.js
#925 
- Disables the doses column if the `CustomerInvoice` is finalized
- Disables the VVM Status column on `SupplierInvoice` finalized
- Refactors `MiniToggleBar` Slightly to wrap in either an Opacity or View container when disabled
=> #925 disable on finalized

android/app/build.gradle
Fixes #920 
- Ensures only a 32bit build is compiled
Without this, the app fails to load on certain tablets, e.g. Lenovo. I haven't had a look yet at the Lenovo architecture so I am not sure exactly why the builds were working on other 64 bit tablets.
As per the issue, our dependencies do not currently support compiling for 64bit architectures regardless
=> #920 fix gradle

src/pages/CustomerInvoicesPage.js, src/pages/CustomerRequisitionPage.js, src/pages/StocktakeEditPage.js, src/pages/StocktakeManagePage.js, src/pages/StocktakesPage.js, src/pages/SupplierInvoicesPage.js, src/pages/SupplierRequisitionPage.js, src/pages/SupplierRequisitionsPage.js
Fixes #898 Fixes #793 
Not an elegant solution - essentially removes the unmounting animation. I don't think there is a better solution though.
Problem is from the `react-native-modalbox` library, from what I can tell.
https://github.com/maxs15/react-native-modalbox/pull/175
I think this PR fixes it on their end, but is from 2017. Either have to fork or remove the dependency.
- Fixes modals staying open after navigating
- Fixes modal state freezing on pushing enter
=> Add conditional around modals

src/database/DataTypes/SensorLog.js, src/sync/incomingSyncUtils.js
Fixes #952 
- 4D can send an empty string as `isVVMPassed`, accounting for that
- While testing sync I had a `sensorLog` with no timestamp - Not sure how this happened, but it stopped sync completely. Maybe this shouldn't be a change?
=> #952 sync touchups

src/pages/SupplierRequisitionsPage.js
Fixes #924 
- Event object was being passed, which caused the check for a parameter being passed return true, creating the requisition.
=> Add bug fix for requisitions nto being cancelled

src/database/DataTypes/Item.js, src/database/DataTypes/MasterListItem.js, src/database/DataTypes/RequisitionItem.js, src/database/DataTypes/Unit.js, src/database/DataTypes/index.js, src/database/schema.js, src/pages/SupplierRequisitionPage.js, src/sync/createInternalRecord.js, src/sync/incomingSyncUtils.js, src/sync/syncTranslators.js
Fixes #936 
- Add `Unit` table
- Add `Item.unit` field
- Add `MasterListItem.price` field
- Add Price column to a program requisition
- Add a unit column to a program requisition (?)
Could maybe? be more performant. At the moment creates the`ITEM_PRICE_MAPPING` table for all `MasterListItems` (`n`). Could potentially be faster by iterating through items for the requisition (`m`) and performing a realm query for each, finding the max price within the `MasterListItems` related. Essentially trading `n` assignments for `m` queries. I dunno if it's worth it - I think the simpler logic is best.
=> #936 price and unit columns

src/database/DataTypes/StocktakeBatch.js, src/database/DataTypes/StocktakeItem.js, src/pages/StocktakeEditPage.js, src/widgets/modals/StocktakeBatchModal.js
Fixes #969 (?)
I'm not 100% sure this issue is really fixed. I could not replicate the behavior of the reason modal opening after editing the expiry date.
The `StocktakeBatchModal` behaviour however was incorrect and opening a reason modal whenever the quantity cell `OnEndEditing` event fired, however, rather than checking if there was already an option. There would be no reason for the modal to open when `OnEndEditing` was fired for the expiry column. I deduced that this may be due to a little lag on the data table, and leaving the expiry after leaving the last quantity cell, or leaving a quantity cell just after leaving the expiry cell was opening the modal.
Have fixed/cleaned slightly this logic. I will be making another issue to clean up more around stocktakes, didn't want to clutter …
=> #969 incorrect reason conditions

src/database/DataTypes/ItemBatch.js, src/utilities/modules/temperatureSensorHelpers.js
Fixes #977 
- Adds a new full aggregation method
- Does not use the most recent 2 hours of sensor logs.
- Deletes all other pre-aggregated logs
- I think the time constants should be in their own file
- Could use the generic sensorlog create method in other methods when theyre cleaned up
- think I need to take another go over to make sure it's as defensive as possible
=> #977 full aggregation rewrite

src/pages/SupplierInvoicesPage.js
Fixes #989?
Realm crashes when using realm sorting by getters on a schema. Use JS sort instead (same way customer invoices table sorts "CUSTOMER").
Should be clean here
=> #989 Fix supplier sort crash by using standard JS sort

src/pages/StocktakeEditPage.js
Fixes #994 
- Reproduced by focusing a different row in the stocktakes data table between `onEndEditing` triggering and the reasons modal opening.
When the modal finally opens, focus is still on the cell which was last set by the user. When clicking on the modal to select a reason, focus then leaves the cell, triggering a new `onEndEditing`, which then updates the `currentStocktakeItem`. 
This still leaves a problem: If focusing a new row AND entering a value, the `currentStocktakeItem` will still update.
To resolve the second issue: Essentially required to force focus in the current cell after `onEndEditing` *if* it needs a reason. This requires a ref matrix, updated on each column sort (The react-native-data-table already creates one of these each `refreshData` I believe). I think this …
=> #994 Incorrect reasons being applied

src/database/DataTypes/StocktakeItem.js, src/pages/StocktakeEditPage.js
Fixes #1000
Change stocktakeItem `mostUsedReason` to return `option.title` rather than `option` itself. This allows string based sorting to work on the getter. Changed code using `mostUsedReason` to use `mostUsedReasonTitle`. 
A bit of rework on the choosing modal to make sure the right reason is highlighted, but should be a bit better using the realm result of reasons saved in state rather than querying the db for them every time the modal was rendered. I think in the old implementation the modal choices wouldn't have been filtered by just stocktakeReason either.
Pretty sure I covered them all. If you're really keen, test stocktakes without reasons too.
=> #1000 Fix stocktake reason sort crash

src/pages/StocktakeEditPage.js, src/widgets/modals/StocktakeBatchModal.js
Fixes #1011
TL;DR: Small tweak. Basically stops the the `currentStocktakeItem` from changing when the reason modal is already up.
After editing a row to have a diff, hitting next or selecting the next row changes focus from the edited row and triggers endEditing. This will show the reason modal. Pressing anywhere on modal to change focus from _next row_ would trigger endEditing on next row. Modal is already up but the currentStocktakeItem would update to be the next row. Selecting a reason therefore updates that row erroneously.
- There is also a state variable `stocktakeItem`. Seems a bit redundant. Bunch of the logic around reason modal and `assignReason()` seems a bit more spaghetti than needed but not refactoring today.
=> #1011 fix reason saving to wrong row

src/database/utilities/createRecord.js
Fixes #999
If `maxMOS` is undefined, doing arithmetic on it results in `NaN`. This is the only way that I can see a `NaN` result anywhere in this method. Please check to see if you can see one!
This solution is defensive against `maxMOS` being `undefined`, `null` or `0`.. I did use a default value in the destructuring, but that does not protect against `0` or `null`.
From what I can tell, if any other `orderType` fields are `undefined` then we are covered by default realm fields and optional fields.
I could only reproduce this error by having `maxMOS` be undefined. So:
Please do check if there is anyway, other than from `maxMOS` that a `NaN` error could be thrown in `createRequisition`
=> #999 Uncaught NaN error in createRecord

src/pages/SupplierRequisitionPage.js
Fixes #1002
Simple fix that has been done before. I will check for anymore of these errors in other pages also.
I need to also check all the other pages for this type of error. Would be good to double check that this is sufficient though, before I go looking
=> #1002 Supplier requisition sorting error

src/main.js, src/pages/SupplierRequisitionPage.js
Fixes things maybe.
Fixes #1018
Fixes #1017 
Fixes #996 
**For the memory leaks** the bugsnag trace isn't too useful and we haven't found out how to reproduce the bug yet. There are hints https://github.com/realm/realm-js/issues/1669 and https://github.com/realm/realm-js/issues/630
Could be excessively large write transactions, or some ability to continue using the app and starting new writes while old writes are still going. Or maybe a write within a write (if that's possible?).
One variable that changed was `Realm.copyBundledRealmFiles();`. Just an idea, a stab in the dark, to remove it and see if the next patch continues getting errors #1018 and #1017. If it does, bugsnag will reopen. 
@andreievg do FYI I've pulled this out for now. I wonder if we can have an env variable file or …
=> #1018 #1017 #996 Remove realm copy and coerce threshold mos

src/mSupplyMobileApp.js, src/pages/CustomerInvoicePage.js, src/pages/CustomerInvoicesPage.js, src/pages/CustomerRequisitionPage.js, src/pages/FirstUsePage.js, src/pages/PageContainer.js, src/pages/StocktakeEditPage.js, src/pages/StocktakeManagePage.js, src/pages/StocktakesPage.js, src/pages/SupplierInvoicePage.js, src/pages/SupplierInvoicesPage.js, src/pages/SupplierRequisitionsPage.js, src/widgets/SequentialSteps.js, src/widgets/TextEditor.js, src/widgets/index.js, src/widgets/modals/ByProgramModal.js, src/widgets/modals/DemoUserModal.js, src/widgets/modals/FinaliseModal.js, src/widgets/modals/GenericChooseModal.js, src/widgets/modals/LanguageModal.js, src/widgets/modals/LoginModal.js, src/widgets/modals/StocktakeBatchModal.js, src/widgets/modals/index.js
Fixes #1004 
- Fixes the TextEditor require cycle through a simple import change
- Fixes the modal require cycles through having each modal be imported through the index in `widgets/modals` and each modal importing a secondary modal it may use directly from the modal file
Could have gotten rid of the `widgets/modals` index and have everything import from the `widgets` index. Felt this was better
=> #1004 Require cycle warnings

src/pages/SupplierRequisitionPage.js
Fixes #983.
Open and closed vial wastage is calculated from CIs and SCs (inventory adjustments) since latest requisition for given vaccine item. If no such requisition exists, no date constraints are applied.
Test file: [vaccines.zip](https://github.com/openmsupply/mobile/files/3210088/vaccines.zip).
=> #983 Update vaccine expansion logic

.eslintrc, src/sync/Synchroniser.js
Fixes #1025
https://github.com/openmsupply/mobile/issues/1025#issuecomment-504264134
- Adds a wrapper around `fetch` in `synchronizer.js`
- consistent handling of common http status codes
- Consistent handling of error handling and bugsnag notifying
This will need to be merged into all versions that are having sync issues:
* Loas - ??
* IC (2.3.4 .. should go to 2.3.5)
* Kiribati - ??
* Vanuatu - (vaccine-special)
=> #1025 Sync to have logging

src/database/DataTypes/Transaction.js, src/database/schema.js, src/pages/CustomerInvoicePage.js, src/pages/CustomerInvoicesPage.js, src/pages/SupplierInvoicePage.js, src/pages/SupplierInvoicesPage.js
Fixes #987.
Hotfix for transact sync bug. 
Not the most elegant, but at this stage just designed to handle buggy transaction records. Could be made a bit more tidy by incorporating similar logic into existing date conversion methods (but only when/if we want this logic to extend to other records).
Sync to desktop is handled by existing date conversion logic (already maps `null` values to ISO date `0000-00-00T00:00:00`).
Update realm schema to make `transact.entry_date` optional. 
N/A.
=> #987 handle incorrectly formatted transact entry dates

package.json, src/database/migration/v2.js, src/sync/incomingSyncUtils.js
Fixes #1102 
It's hard to identify the 'first' transaction (since confirmDate lacks the time if tablet was reinitialised or created from desktop site)
So instead, look at all of the transactionBatches for an itemBatch:
* If we find one that belongs to supplier invoice, then don't delete
* Look at all of the addition inventory adjustments
* If inventory adjustment doesn't have stock take, don't delete (Mobile site must have been created from a desktop site, and stock was increased with just inventory adjustments, take not that mobile does not integrate foreign transactions)
* If inventory adjustment does have a stock take, find StocktakeBatch that references current itemBatch and see if it's an increasing record from 0 snapshot, if so then don't delete
* Delete every ItemBatch that wasn't …
=> #1102 foreign item lines IC special

src/pages/CustomerInvoicePage.js, src/utilities/index.js, src/utilities/sortDataBy.js, src/utilities/underscoreMethods.js, src/widgets/DataTable/HeaderCell.js
Fixes #1110 
~~#### BRANCHED FROM #1090 - Should be merged before this~~ done
- Adds a debounce method stolen from `underscore.js`
- Adds sorting functionality
- I found layouts were a fraction faster/the same as using realm for up to 100 records, with realm starting to pull slightly ahead after that, for non-getter fields. The same for getter fields. Didn't think the performance gain of a few miliseconds was worth the complexity increase. However, very easy to refactor if we do think it is worth it.
- Rename sorting method when integrating this feature into develop
- Different way to steal `underscore.js` methods?
=> #1110 New CustomerInvoicePage sorting feature

android/app/build.gradle
Fixes #1107 
@Chris-Petty made a solid point that double the size of the APK is not an insignificant problem when dealing with users in remote locations. Solution is to build a separate APK for x86 and ARMv7a AND a universal APK.
- Currently develop is creating a single APK for both 32 and 64 bit as well as x86 and ARMv7a architectures. This has an APK size of around 33Mb. This was an increase over the previous APK size of aaround 15mb, which was only creating a 32bit APK.
- This PR edits our gradle config to build 5 APKs - one for 32/64bit x86 and ARMv7a architectures AND a universal APK.
- The universal APK:
- Individual architecture APKs:
All APKs generated:
Build process output json: 
[output.json.zip](https://github.com/openmsupply/mobile/files/3511630/output.json.zip)
Figured may …
=> #1107 Separate CPU Architecture APKs

src/pages/CustomerInvoicePage.js
Fixes #1111
**Forgot to rename this branch before publishing, oopsies**
- Adds a simple filtering mechanism
- Went with the simple approach, using realm to query a `backingData` in state, returning a filtered version of that.
- Could add realm sorting on top, but would also have to determine if the field is a getter/setter etc etc - just doing it simple
As above - dealing with sorting while filtering. I think keeping this simple for now is a good option, personally - just removing the sorting. Hard to know if the added complexity is really actually worth it. I don't see adding a filter then pushing a sort button to be odd
=> #1111 New CustomerInvoicePage filtering feature

src/database/DataTypes/Transaction.js, src/globalStyles/newPageStyles.js, src/hooks/usePageReducer.js, src/pages/CustomerInvoicePage.js, src/pages/dataTableUtilities/actions.js, src/pages/dataTableUtilities/pageInfo.js, src/pages/dataTableUtilities/reducer/getReducer.js, src/pages/dataTableUtilities/reducer/reducerMethods.js, src/utilities/getModalTitle.js, src/utilities/index.js, src/widgets/DataTable/DataTableHeaderRow.js, src/widgets/DataTable/index.js
Fixes #1136
- Put modal logic in the reducer
- Put selection logic in the reducer
- Extracted page info columns out, similar to columns/reducer methods. This will inject the `tableState` with a *method* (Require dispatch) to call which will return the page info columns for a page.
- Put `pageObject` in state (transaction for customerInvoice page)
- Adding items logic as reducer methods (including from master list. Requisition add from masterlist might need to change this logic a bit as it needs a store, simple change though.)
- Deleting items logic as reducer methods
- Added a wrapper around `HeaderRow` and `HeaderCell`
- Fixed `topLeftSection` styles
*Internal changes, not really testable?*
Note that the reducer can sometimes be called a couple of times for *any* dispatch (from what I …
=> #1136 New CustomerInvoicePage refactor two

src/widgets/DataTable/Row.js
Fixes #1145
- Adds a simple `onPress` props to `Row`
As in the docstring, the behaviour is odd when you have a cell which is `Touchable` and the `Row`, as both events will be fired. I cannot find a way to cancel the propogation of a native event being fired on a child component. I think the solution is to wrap each non-touchable cell in a `Touchable` which would trigger the `Row` `onPress`. This would require a bit more refactoring and the use-case isn't needed right now.
Note that this is a bit weird because `EditableCell` uses an `onPress`
I wouldn't be opposed to having a `mSupplyRow` component which would do a lot of the rendering of cells as well as handling logic related to having clickable rows and adding an icon indicating that a row is clickable!
=> #1145 onPress prop to Row component

src/pages/CustomerInvoicePage.js, src/widgets/DataTable/Cell.js, src/widgets/DataTable/CheckableCell.js, src/widgets/DataTable/DataTable.js, src/widgets/DataTable/EditableCell.js, src/widgets/DataTable/Row.js, src/widgets/DataTable/TouchableCell.js
Fixes #1140 
- debug prop to enable Row/Cell logging (default `false)
- getItemLayout based on height in styles (45). This allows the scrollbar to be scaled correctly from the start, rather than dynamically shrinking as you scroll. Can get ahead of row rendering but fills in very promptly. But you can scroll immediately to bottom of list without rebounding.
- initialNumToRender 20: 20 rows will be more than enough rows to fill the viewport in one render
- removeClippedSubviews true: magic faster row rendering wow
- windowSize 11: still snappy and in most use means not catching up to rows yet to render.  
initialNumToRender and maxToRenderPerBatch tweaks didn't feel better, so left defaults.
=> #1140 data table default props optimisations

src/database/BaseDatabase.js, src/database/UIDatabase.js, src/database/index.js, src/mSupplyMobileApp.js, src/settings/MobileAppSettings.js
Fixes #1144 
~~## NOTE: Branched from #1142~~
- Created a file `BaseDatabase.js` which exports an instance of `react-native-database`. Should be the single instance of this in the entire app.
- Created a method `getUIDatabaseInstance` in `UIDatabase.js` and exported that - removed the export of `UIDatabase`. Because of require cycles when importing `UIDatabase` into a realm data type (i.e. `Transaction` -> `schema` -> `BaseDatabase` -> `UIDatabase` -> `Transaction`), the database being wrapped needed to be injected. 
- Exported a single instance of `UIDatabase` from `database/index.js`, and trying to import `UIDatabase` will pass the same instance when the method is called (basically using a *slightly more* standard singleton pattern here).
- Added an import of `UIDatabase` to `Settings` …
=> #1144 database settings singletons

src/sync/incomingSyncUtils.js
Fixes #1062 
- Rejects any `ItemBatch` incoming records with a `storeID` different from the app's `storeID`
- See: https://github.com/openmsupply/mobile/issues/1062#issuecomment-516368874 for a way to do this from desktop
- Alternatively, hack `integrateRecord` with (I think, I didn't test this way just might be easier!):
```
if (internalRecordType === 'ItemBatch') {
syncRecord.store_ID = 'not this store!';
}
```
I think this is fine for now, but potentially better solutions for better general defensive sync:
- List of all record types of store data which shouldn't be sent. Check storeID's of everything, ensuring it is for this store (and exists). Bugsnag anything caught.
Seems like this is a basic sanity check, but would need to compile a list of exactly what records shouldn't be getting …
=> #1062 Rejecting ItemBatches not for the mobile store

src/pages/CustomerInvoicePage.js, src/pages/CustomerInvoicesPage.js, src/pages/SupplierInvoicePage.js, src/pages/dataTableUtilities/utilities.js
Fixes #1170 
- Adds `getItemLayout` and `keyExtractor` to a utilities file.
Not the greatest factoring, but might prevent a mistake in the future
*internal change can't test?*
N/A
=> #1170 Extract key extractor & item layout functions

src/database/utilities/createRecord.js, src/pages/StocktakesPage.js, src/pages/SupplierRequisitionsPage.js
Fixes #1095 
Last PR for refactor
- Hooks up the new `ByPRogramModal` to `SupplierRequisitionsPage` and `StocktakesPage`
- Tried to make minimal changes as possible, even though the logic in these is pretty spaghetti, as it should be getting change in `DataTable` rewrite
**Creating a program requisition:**
**Creating a stocktakes requisition:**
=> #1095 by program refactor 3

src/hooks/useNavigationFocusRefresh.js, src/pages/CustomerInvoicesPage.js, src/pages/PageContainer.js, src/pages/dataTableUtilities/reducer/getReducer.js
Fixes #1172 
- Adds a hook which will listen to navigation `willFocus` event, which will fire a `refreshData` dispatch on a screen being refocused
*create a customer invoice, unfinalised, navigate back*
N/A
=> #1172 useNavigationFocusRefresh custom hook

src/hooks/useDatabaseListener.js
Fixes #1112
- Adds a simple database listener 
**NOTE:** Currently when sync occurs, `mSupplyMobileAppContainer` re-renders, re-rendering the entire app (and for some reason also unmounting like, everything). So, without actually plugging this into the page, the data table will refresh on syncing a synchronized data type .. or, all data types. So it is not actually hooked up. I think it is a reasonably large refactor to fix this problem, so I've not done it yet. I had already written this hook, though, so I figured I'd PR it in. 
Have tested and it was triggering the event on the correct data types. Quite simple to hook up - just need a `useDatabaseListener( .. )` and a `callback` which sends a `dispatch` ....... `refreshData` 🤣 - could use a better action, which finds the rows the sync …
=> #1112 New CustomerInvoicePage data types shnychronizationh feature

src/pages/CustomerInvoicePage.js, src/pages/SupplierInvoicePage.js, src/widgets/DataTable/DataTable.js, src/widgets/DataTable/DataTableRow.js, src/widgets/DataTable/RefContext.js, src/widgets/DataTable/Row.js, src/widgets/DataTable/TextInputCell.js, src/widgets/NewExpiryDateInput.js
Fixes #1181 
- Adds scrolling to top logic for a row when focused
- Adds focus next logic for cells
See #1043 
- At the time of this PR, only two pages `SupplierInvoice` and `CustomerInvoice` had been completed. Possibly breaking change on any new pages after that.
- This decreases the size of the tables viewport. I think this is a good tradeoff as the currently edited area is far more responsive while trading for scrolling behaviour (hiding rows which aren't in the viewport for a second or so when scrolling). This also means we don't need to use the hack for react-native rendering 100+ text inputs and crashing.
- Remove hack-editable cell for above area and focus cell/focus next reducer logic? Keep it because why not?
=> #1181 New DataTable auto-scroll and focus logic

src/hooks/useNavigationFocusRefresh.js, src/hooks/usePageReducer.js, src/navigation/actions.js, src/pages/CustomerInvoicesPage.js, src/pages/dataTableUtilities/columns.js, src/utilities/getModalTitle.js, src/widgets/DataTable/DataTableRow.js
Fixes #1167 
- Added columns: expiry date, status
- Added use of `DataTableRow` and `DataTablePageModal`.
- Added use of redux for navigation.
- Added `useNavigationFocusListener` with a couple of changes to make it safer.
See #1043 
Memoizing on press handlers: Memoizing all of these is basically memoizing everything and defeats the purpose. The press handlers which aren't memoized ARE causing re-renders, but only on smaller components - `SearchBar`, buttons etc. [ row onPress is handled by `DataTableRow` and doesn't cause re-renders - using a binding or closure means no memoizing].
This is a pretty good case to use class based components for pages, rather than functional. That means no hooks - but I don't know if that's a good enough reason to use functional components for these larger …
=> #1167 CustomerInvoicesPage fixes

src/pages/dataTableUtilities/getColumns.js, src/widgets/DataTable/DataTable.js, src/widgets/modals/DataTablePageModal.js, src/widgets/modals/RegimenDataModal.js
Fixes #1228 
- Refactors regimen data modal to use the new `DataTable`
- Just made a new component, will delete the old one when everything else is deleted.
- Used a reducer as cells are expecting a `dispatch` and an `action` ..
See #1043 
I think this highlights that we should pass a callback to cells rather than `dispatch` and an `action`/`actions` - or at least have both options available. A callback, though, is essentially a superset of all things that a `dispatch` and `action` can do - they can do nothing a callback can't whereas the otherway is not true.
Also highlights how having `customData` as a string is pretty annoying. Makes what should be a simple component not so simple
=> #1228 RegimenDataModal refactor -- 14

src/database/DataTypes/StocktakeBatch.js, src/database/DataTypes/StocktakeItem.js, src/localization/modalStrings.js, src/pages/StocktakeEditPage.js, src/pages/dataTableUtilities/actions/cellActions.js, src/pages/dataTableUtilities/actions/getPageActions.js, src/pages/dataTableUtilities/actions/tableActions.js, src/pages/dataTableUtilities/getColumns.js, src/pages/dataTableUtilities/getPageInfoColumns.js, src/utilities/sortDataBy.js, src/widgets/DataTable/DataTable.js, src/widgets/modals/DataTablePageModal.js, src/widgets/modals/NewStocktakeBatchModal.js
Fixes #1138 
- Refactors stocktake batch modal to use the new data table.
- Added getters to `StocktakeBatch` and modified some in `StocktakeItem` to be consistent with each other.
I don't really like this modal in general, I don't think it should be a modal. Don't really like having it so stateful, but I don't think there's really an option. Definitely open to suggestions - but resisted the urge to make this not a modal heh
See #1043 
Would be good to go through the `Realm` models and really clean them up soon
=> #1138 StocktakeBatchModal refactor -- 13

src/database/DataTypes/Requisition.js, src/database/DataTypes/StocktakeBatch.js, src/database/DataTypes/StocktakeItem.js, src/localization/modalStrings.js, src/navigation/actions.js, src/pages/CustomerRequisitionPage.js, src/pages/CustomerRequisitionsPage.js, src/pages/StocktakeEditPage.js, src/pages/SupplierInvoicesPage.js, src/pages/dataTableUtilities/actions/cellActions.js, src/pages/dataTableUtilities/actions/getPageActions.js, src/pages/dataTableUtilities/actions/tableActions.js, src/pages/dataTableUtilities/getColumns.js, src/pages/dataTableUtilities/getPageInfoColumns.js, src/pages/index.js, src/utilities/finalisation.js, src/utilities/index.js, src/utilities/sortDataBy.js, src/widgets/DataTable/DataTable.js, src/widgets/modals/DataTablePageModal.js, src/widgets/modals/NewStocktakeBatchModal.js, src/widgets/modals/RegimenDataModal.js
Fixes #1133 
- Refactor of the `SupplierInvoicesPage` to use the new DataTable page.
- Very simple page - basically a replica of `CustomerInvoicePage`, with new modal keys.
- Also added back the finalistation logic for `StocktakeEditPage` which I forgot to add in #1217 
See #1043 
These pages are so similar, it would be quite easy to just have one `Page` component 🤣
=> #1133 SupplierInvoicesPage refactor -- 10

src/database/DataTypes/Requisition.js, src/database/DataTypes/StocktakeBatch.js, src/database/DataTypes/StocktakeItem.js, src/localization/modalStrings.js, src/navigation/actions.js, src/pages/CustomerInvoicePage.js, src/pages/CustomerRequisitionPage.js, src/pages/CustomerRequisitionsPage.js, src/pages/StocktakeEditPage.js, src/pages/SupplierInvoicesPage.js, src/pages/SupplierRequisitionPage.js, src/pages/dataTableUtilities/actions/cellActions.js, src/pages/dataTableUtilities/actions/getPageActions.js, src/pages/dataTableUtilities/actions/tableActions.js, src/pages/dataTableUtilities/getColumns.js, src/pages/dataTableUtilities/getPageInfoColumns.js, src/pages/index.js, src/utilities/finalisation.js, src/utilities/index.js, src/utilities/sortDataBy.js, src/widgets/DataTable/DataTable.js, src/widgets/DropDownCell.js, src/widgets/ToggleBar/ToggleBar.js, src/widgets/modals/DataTablePageModal.js, src/widgets/modals/NewStocktakeBatchModal.js, src/widgets/modals/RegimenDataModal.js
Fixes #1218 
- Added a `stateInitialiser` function
- Added use of `PageActions` for actions
- explicitly defined all callbacks
- Fixed a minor issue with toggle bar/page button alignment
- Fixed an issue with `DropDownCell` placeholder prop
- Added the use of `useRecordListener` custom hook to listen for being finalised
See #1043 
- I think a container component which would do all alignment in a consistent way for buttons would be good. Similar to `DataTableRow`, could also be good. Passing some array of button keys as a selection and it just rendered them correctly in the right positions. i.e.
pass: `[[ADD_ITEM, ADD_FROM_MASTER_LIST], [USE_SUGGESTED_QUANTITES, CREATE_AUTOMATIC_ORDER']]`
And the component would render a 2x2 of the buttons in that order. Really should just be able to pass …
=> #1218 CustomerInvoicePage  fixes -- 9

src/database/DataTypes/Stocktake.js, src/database/DataTypes/StocktakeItem.js, src/hooks/usePageReducer.js, src/navigation/actions.js, src/pages/CustomerInvoicesPage.js, src/pages/StocktakeEditPage.js, src/pages/StocktakeManagePage.js, src/pages/StocktakesPage.js, src/pages/SupplierInvoicePage.js, src/pages/SupplierRequisitionPage.js, src/pages/SupplierRequisitionsPage.js, src/pages/dataTableUtilities/actions/cellActions.js, src/pages/dataTableUtilities/actions/getPageActions.js, src/pages/dataTableUtilities/actions/pageActions.js, src/pages/dataTableUtilities/actions/rowActions.js, src/pages/dataTableUtilities/actions/tableActions.js, src/pages/dataTableUtilities/getColumns.js, src/pages/dataTableUtilities/getPageInfoColumns.js, src/pages/index.js, src/widgets/DataTable/DataTable.js, src/widgets/DataTable/DataTableRow.js, src/widgets/DataTable/Row.js, src/widgets/DropDownCell.js, src/widgets/GenericChoiceList.js, src/widgets/modals/DataTablePageModal.js, src/widgets/modals/ModalContainer.js
Fixes #1220 
- Added use of custom hooks: `useNavigationFocus` and `useSyncListener` to refresh on incoming sync (if a traansaction comes in) as well as on re-focusing the screen
- Added use of `PageActions` for actions
- Explictly defined functions for callbacks
See #1043 
N/A
=> #1220 CustomerInvoicesPage fixes -- 8

src/database/DataTypes/RequisitionItem.js, src/database/DataTypes/Transaction.js, src/database/UIDatabase.js, src/pages/dataTableUtilities/constants.js, src/pages/dataTableUtilities/getColumns.js
Fixes #1248 
- Added pass through of `get` from `UIDatabase` so we can use it now
- Added new call `getSetting` to `UIDatabase` as because all of the many layers on the database there are many dependency cycles - easier to just import `UIDatabase`
- Added pricing algorith mfor requisition items - max price of all master list items for this store
See #1043 
N/A
=> #1248 Price/Unit Columns

src/pages/StocktakesPage.js, src/pages/dataTableUtilities/actions/constants.js, src/pages/dataTableUtilities/actions/tableActions.js, src/pages/dataTableUtilities/reducer/tableReducers.js
Fixes #1267 
- Adds back the toggle I forgot about
See #1043 
Conflicts with #1266 
Note that this messes up the back navigation a little bit. When navigating back `refreshData` is called which will just display everything. This needs to change with changes made in #1266 such that the state is re-init, rather than `refreshData`
=> #1267 Missing StocktakesPage toggle

src/pages/dataTableUtilities/getPageInfoColumns.js
Fixes #1275 
- Switches the `pageInfo` used in `SupplierRequisition` and `SupplierRequisitionWithPrograms` such that a non-program requisition months to supply is editable, where as a program requisition is not (it is set by the max MOS of the order type chosen on creation)
See #1043 
Defining constants for page info isn't overkill right?
=> #1275 MonthsToSupply Pageinfo switcheroo

src/pages/dataTableUtilities/constants.js, src/pages/dataTableUtilities/getColumns.js, src/widgets/DataTable/DataTableRow.js
Fixes #1277 
- Column type of expiry date was `editableExpiryDate` but `DataTableRow` was trying to render `EDITABLE_DATE` - corrected this
- Also changed types to be in the form `EDITABLE_XX` from `XX_EDITABLE` just to match the actual scalar value `editableXXX` cause I was getting confused
See #1043 
N/A
=> #1277 Expiry date column key

src/hooks/useRecordListener.js
Fixes #1285 
- Fixes unsubscribing by using a ref rather than a state object to ensure the correct current subscription is fetched despite any closures etc
N/A
=> #1285 use record listener unsubscribe

src/hooks/usePageReducer.js, src/pages/CustomerInvoicePage.js, src/pages/CustomerInvoicesPage.js, src/pages/CustomerRequisitionPage.js, src/pages/CustomerRequisitionsPage.js, src/pages/StockPage.js, src/pages/StocktakeEditPage.js, src/pages/StocktakeManagePage.js, src/pages/StocktakesPage.js, src/pages/SupplierInvoicePage.js, src/pages/SupplierInvoicesPage.js, src/pages/SupplierRequisitionPage.js, src/pages/SupplierRequisitionsPage.js, src/pages/dataTableUtilities/getPageInitialiser.js, src/pages/dataTableUtilities/index.js, src/widgets/modals/NewStocktakeBatchModal.js
Fixes #1249.
Simplifies page logic by moving initialisation logic into a dedicated file and updating the `usePageReducer` hook signature to more closely resemble the standard React `useReducer` hook. 
Updated initialisation naming to UK English 🇬🇧 style (both US and UK were being used in different contexts). If people prefer US 🇺🇸 naming, can update with a quick find/replace.
=> #1249 extract state initialisers

src/widgets/DataTable/DataTable.js
Fixes #1288 
- When you get to the end of the list of items in a table, dismiss the keyboard on submitting
See #1043 
N/A
=> #1288 Keyboard dismissal on last cell

src/pages/CustomerInvoicePage.js, src/pages/CustomerInvoicesPage.js, src/pages/CustomerRequisitionPage.js, src/pages/CustomerRequisitionsPage.js, src/pages/StocktakeEditPage.js, src/pages/StocktakeManagePage.js, src/pages/StocktakesPage.js, src/pages/SupplierInvoicePage.js, src/pages/SupplierInvoicesPage.js, src/pages/SupplierRequisitionPage.js, src/pages/SupplierRequisitionsPage.js, src/pages/dataTableUtilities/actions/constants.js, src/pages/dataTableUtilities/actions/getPageActions.js, src/pages/dataTableUtilities/actions/tableActions.js, src/pages/dataTableUtilities/getPageInitialiser.js, src/pages/dataTableUtilities/reducer/tableReducers.js, src/widgets/PageButton.js, src/widgets/ToggleBar/ToggleBar.js, src/widgets/modals/DataTablePageModal.js
Fixes #1294  & Fixes #1300 
- Adds a Past/Current toggle, the same as in `StocktakesPage` to all plural pages
- Fixed filtering on a program requisition page regaarding show/hide over stocked
- Little fix of `ByProgramModal` to correctly open the right one
- Adjustments to init methods
See #1043 
N/A
=> #1294 sorting performance

src/widgets/DataTable/DataTable.js, src/widgets/DataTable/Row.js, src/widgets/DataTable/TouchableCell.js, src/widgets/DataTable/TouchableNoFeedback.js, src/widgets/DataTable/index.js
Fixes #1309 
- Add `TouchableNoFeedback` component as it's now used in two places
- Add use of `TouchableNoFeedback` on a row when no `onPress` is used. This captures the event, preventing propgation and allows scrolling
See #1043 
N/A
=> #1309 Broken scrolling

src/widgets/modals/ByProgramModal.js
Fixes #1317.
Not sure if correct branch, let me know if should be PRed into `develop` or another branch.
Small variable assignment fix.
None that I'm aware of.
=> Fix incorrect ByProgramModal thresholdMOS

src/widgets/DataTable/TouchableNoFeedback.js
Fixes #1327, #1340.
- Correctly overrides `onPress` for `TouchableNoFeedbacl` to be a no op onPress
Not getting a crash on pressing `Use Suggested Quantities` button
=> #1327 OnPress Crash

src/navigation/actions.js
Fixes #1337 
- Just updated the title on `StocktakeMangagePage`
N/A
=> #1337 StocktakeManagePage title

src/database/DataTypes/Period.js
Fixes #1341.
A small UX change. Feedback welcome if you prefer the existing formatting.
N/A.
=> #1341 update period toInfoString formatting

src/pages/dataTableUtilities/getPageInitialiser.js, src/utilities/sortDataBy.js
Fixes #1344 
- Updated sorting logic to fix the stocktakes page sorting issues
- Updated initial state of `CustomerRequisitionsPage`
N/A
=> #1344 Incorrect initial state

src/navigation/actions.js, src/pages/StocktakeEditPage.js, src/pages/StocktakeManagePage.js, src/pages/dataTableUtilities/actions/pageActions.js, src/pages/dataTableUtilities/getPageInfoColumns.js, src/pages/dataTableUtilities/reducer/pageReducers.js, src/utilities/getModalTitle.js, src/widgets/modals/DataTablePageModal.js
Fixes #1335 
- Added updating of name from stocktake manage page via redux
- Added onpress event for the name page info on `StocktakeEditPage`
Note: This does fix the page info problem described in #1343 also, as  it was easier to just do it here
Seems I just completely forgot about this..
N/A
=> #1335 Stocktakename cant be updated

src/widgets/SearchBar.js
Fixes #1324 
-  Updated memoization, closure wasn't updating
N/A
=> #1324 SearchBar not dismissing details on StockPage

src/pages/FirstUsePage.js
Fixes #1350.
Disables autocorrect for primary server URL. 
N/A.
=> #1350 disable autocorrect for server url

src/database/DataTypes/Stocktake.js, src/database/DataTypes/StocktakeBatch.js, src/database/DataTypes/StocktakeItem.js, src/pages/StocktakeManagePage.js, src/widgets/DataTable/DataTableRow.js
Fixes #1343 
- Correctly using placeholders and not counted state for rows in a stocktake
- Made the bottom modal thing in `StocktakeManagePage`  always open
- Corrected logic for remove items from a `Stocktake`
- Corrected logic for the keyboard type for editable cells
`DataTableRow` getting pretty messy at this point. Could refactor soon!
=> #1343 stocktake updates

src/localization/programStrings.js
Fixes #1356.
Fixes incorrect French localisation for program stocktakes. Whitespace added to ensure correct centering (adding formatting to localisation strings seems hacky, but seems to be consistent with the way mobile currently handles this).
N/A.
=> #1356 fix french program stocktake

src/pages/dataTableUtilities/getColumns.js
Fixes #1399 
- Removed sortable status of status column
- Reordered a couple of pages columns to make all of the sortable columns at the end. Also makes it more consistent on all pages where entry date is before status
N/A
=> #1399 Sortable status column

src/widgets/DataTable/DataTableRow.js
Fixes #1367.
I think that, as the column is read-only, using the standard style looks good (as opposed to the placeholder style). Feedback appreciated whether you agree or not.
Figured I'd follow the open-close principle and avoided changing existing `Cell` behaviour.
Rubber ducking 🦆 .
Think this is a good way of fixing the problem, but introduces the question of how much data manipulation should be handled by `DataTableRow` and how much by `Cell`, `EditableCell`, etc.
IMO, an ideal situation would be to leave `Cell` etc. as dumb as possible, and do all data parsing, validation, manipulation etc. in `DataTableRow`. That seems like a good way to respect SRP and also makes it easy to debug columns as all logic is in one place …
=> #1367 fix stocktake difference for uncounted quantities

src/localization/programStrings.js, src/widgets/Step.js
Fixes #1406 
- Adjust styles to use the correct property
- Gave program order french string a `\n` to have it fit more nicelyer
N/A
=> #1406 Handle long text in ByProgramModal

src/utilities/getModalTitle.js, src/widgets/modals/LoginModal.js
Fixes #1403 
- Adds a modal title to both select months of stock modal and language modal (I realised this was missing one also while working on issue)
N/A
=> #1403 months stock modal title

src/database/DataTypes/StocktakeBatch.js, src/database/DataTypes/StocktakeItem.js, src/database/UIDatabase.js, src/navigation/actions.js, src/pages/dataTableUtilities/actions/cellActions.js, src/sync/incomingSyncUtils.js, src/widgets/modals/DataTablePageModal.js, src/widgets/modals/StocktakeBatchModal.js
Fixes #1336 
- Makes sync adjustments for options
- changes some logic in `StocktakeItem` and `StocktakeBatch` to aid in the logic for applying reasons
- Changes some logic in the actions for applying reasons
**With reasons defined**
Overall I think this is extremely annoying and it's also pretty unintuitive for a user. I think changing `Stocktakes` to just be a list of batches, like it is in desktop would be a lot better for the overall app. I wonder how users really do stocktakes on mobile and if having it NOT by batch is actually helpful
=> #1336 Stocktake reason changes

src/pages/StockPage.js, src/widgets/DataTablePageView.js
Fixes #1410
- Add a prop to disable/enable gesture handling of `DataTablePageView`
- Disabled gesture handling in `DataTablePageView`
N/A
=> #1410 scrolling item details

src/pages/dataTableUtilities/getColumns.js
Fixes #1408 
- Removed the `remove` column and adjusted widths
N/A
=> #1408 Removing items from program requisitions

src/widgets/DataTable/Cell.js
Fixes #1405 
- Adds a `maxLines` prop to `Cell`, default of 2
N/A
have updated PR for `react-native-data-table`: https://github.com/sussol/react-native-data-table/pull/57
=> #1405 Multiline Cell component

src/database/DataTypes/PeriodSchedule.js, src/localization/programStrings.js, src/widgets/modals/ByProgramModal.js
Fixes #1409 
- Add a change to the method which returns the periods for a program and order type for emergency order types
- Add possible french translation and some changes to strings for emergency orders
N/A
=> #1409 emergency order types

src/navigation/actions.js, src/pages/StocktakeEditPage.js, src/pages/StocktakesPage.js
Fixes #1425 
- Changes a couple of navigation actions to fix the bug as per the issue
- When creating a `Stocktake`, 3 invocations
- Creating a program stocktake: create and go to `StocktakeEditPage`
- Creating a normal stocktake with programs defined - create and go to StocktakeManagePage
- Creating a normal stocktake with no programs defined: Already on `StocktakeManagePage`, with a list of items selected - go to `StocktakeEditPage`
- When navigating to `StocktakeEditPage`, two invocations
- Navigating from `StocktakesPage` [When creating a program stocktake]
- Navigating from `StocktakeManagePage` [all others]. Don't want to navigate back to `StocktakeManagePage` from `StocktakeEditPage`, so pop and push the stack
N/A
=> #1425 Stocktake navigation

src/pages/MenuPage.js, src/widgets/Spinner.js, src/widgets/modals/BottomModal.js, src/widgets/modals/DemoUserModal.js, src/widgets/modals/LoginModal.js
Fixes #1398.
- Used `react-codemod` script to update unsafe lifecycle methods.
- Updated pages: `MenuPage`.
- Updated widgets: `Spinner`
- Update modals: `BottomModal`, `DemoUserModal`, `LoginModal`.
- Disabled eslint rules `camelcase` and `react/sort-comp` where needed.
N/A.
=> #1398 rename unsafe lifecycle methods

src/pages/CustomerInvoicePage.js, src/pages/CustomerInvoicesPage.js, src/pages/CustomerRequisitionPage.js, src/pages/CustomerRequisitionsPage.js, src/pages/StockPage.js, src/pages/StocktakeEditPage.js, src/pages/StocktakeManagePage.js, src/pages/StocktakesPage.js, src/pages/SupplierInvoicePage.js, src/pages/SupplierInvoicesPage.js, src/pages/SupplierRequisitionPage.js, src/pages/SupplierRequisitionsPage.js, src/widgets/DataTable/CheckableCell.js, src/widgets/DataTable/DataTableHeaderRow.js, src/widgets/DataTable/DataTableRow.js, src/widgets/DataTable/HeaderCell.js, src/widgets/DataTable/TextInputCell.js, src/widgets/DataTable/TouchableCell.js, src/widgets/DropDownCell.js, src/widgets/ExpiryDateInput.js, src/widgets/modals/RegimenDataModal.js, src/widgets/modals/StocktakeBatchModal.js
Fixes #1446 
This does exactly as described in the issue. Looks like a lot but it it just changing `dispatch` + `action` prop to be a combined callback.
*The way of invocation has been changed, but no actual logic. As long as the following columns can be used, then this does what it should - if the cell isn't hooked up correctly, it will just throw an error and crash the app. The following is a list of all effected cells*
N/A
=> #1446 cells use dispatch not callbacks

src/widgets/DataTable/DataTable.js
Fixes #1467 
- Adds a footer to `DataTable`
N/A
=> #1467 Footer to DataTable

src/navigation/actions.js
Fixes #1464
- Updates navigation to `StocktakeManagePage` such that when navigating from the `StocktakeEditPage`, `StocktakeEditPage` is replaced, so that stack stays valid
N/A
=> #1464 Add update to stocktake manager navigation to replace

src/widgets/modals/StocktakeBatchModal.js
Fixes #1463
- Adds a prop to `DataTableRow` to disable it correctly
N/A
=> #1463 Editable when finalised

dev_scripts/clean.sh, dev_scripts/deploy.sh, dev_scripts/keygen.sh, dev_scripts/upload.sh, package.json
Fixes #1480
Just clean up and adding a few useful scripts.
May be worth committed the debug key to the repo, although it may still be useful to have the ability to generate keys for testing some functionality (e.g. hardware IDs etc.)
=> #1480 update dev scripts

src/widgets/DataTable/DataTable.js
Fixes #1475 
- Adds a check that a ref exists before trying to focus
Essentially this occurs in the edge case in a stocktake batch modal window where the table is smaller, and the keyboard covers some rows. When the keyboard covers rows, rows aren't rendered, and therefore dont have a ref to focus. 
I'm not sure of a nother work around. Doesn't occur on a normal table, only on stocktake batch which is smaller as explained above
* This is very edge case, I think I would need to show someone how to have it occur*
N/A
=> #1475 Focus crash

src/widgets/DataTable/DataTable.js
Fixes #1510 
- Just adjusts the index to scroll to leave the last row 
N/A
=> #1510 Focus, submit and scrolling

src/navigation/actions.js
Fixes #1505 
- Uses the correct variable
*Setup: Have a program ready. Have `monthsLeadTime` set to a value in `[store]custom_data`
N/A
=> #1505 Months lead time crash

src/pages/dataTableUtilities/reducer/rowReducers.js
Fixes #1518 
- When selecting all, all items are actually selected. This is the behaviour I would expect.
I think we are looking to change this page anyway (Or at least I would like to!), but probably not before the next version?
=> #1518 Corrected select all state

src/database/DataTypes/Item.js, src/database/DataTypes/ItemBatch.js
Fixes #1519 
- Changes `Item.addedDate` and `ItemBatch.addedDate` methods so that the added date is the earliest confirm date, of all incoming `TransactionBatch` records.
I tried to mimic the previous behaviour while just fixing the bug between `null` and dates.
I understand that we use the earliest date for the added date. I don't fully understand why we would use this in the usage calculation. It seems to be trying to account for using large amounts when an item is 'added'. If so, should this look for the earliest confirmed, incoming batch, with stock? Currently this logic would only account for the first ever incoming batch.
I'm missing a little bit of knowledge here I think!
*Internal, hard to test change..*
Related PR: #1520
=> #1519 usage dates

src/widgets/modals/DataTablePageModal.js
Fixes #1513 
- Adds the items code to `ITEM_SELECT` modal
**Info: `ITEM_SELECT` modal is used in `SupplierRequisitionPage` (no programs), `CustomerInvoicePage`, `SupplierInvoicePage`
N/A
=> #1513 Add code to item select

src/pages/dataTableUtilities/reducer/tableReducers.js
Fixes #1479 
- Just changes the way state is mutated. I'm 90%, but not 100% there is no edge case where this would not cause a problem, so putting it into develop rather than master as a patch so we can have time to play
Not really a check list of testing, more of a story sorry 🤷‍♂ 
*This PR just changes the way state is held, such that when adding a new row to a table, the row is added to the top of the table, and the remaining rows do not change order, but the current filtering and sorting is removed (as it is possibly not correct anymore).*
Create a list of a few items in a supplier invoice. Easiest to number the quantities `1,2,3` etc. Add an item. It should be added to the head and the order of the remaining rows should be stable when adding more items - whether there is a filtering …
=> #1479 Strange ordering when adding rows

src/widgets/DataTable/Row.js
Fixes nothing, just a dev tweak. I believe it can be a performance issue if it gets into a release APK though.
Develop is logging stuff to metro bundler
Run develop branch. See no more console logs in the metro bundler terminal output
=> #xxxx row debug prop default to false

README.md
Fixes #1555.
Just some minor tidyups to `README.md` and a few additions to review in combination with some updates of the wiki as part of prep for upcoming mobile presentation. 
The update to the description/functionality is just me trying to make mobile sound cool to newcomers, not really relevant :). Main changes are to restructure to make the `README.md` more of a self-contained installation and development "quickstart", with the wiki covering broad stuff like configuration (mSupply setup etc.), design and code conventions, and learning resources.
Copy and paste [here](https://jbt.github.io/markdown-editor/) to get a better idea of what things look like.
Proposed wiki changes:
- Fix up home page (broken links).
- Update setup sidebar (out-of-date with current wiki page).
- Remove stuff …
=> #1555 update mobile docs

src/database/DataTypes/MasterList.js, src/database/DataTypes/Requisition.js, src/database/DataTypes/Transaction.js, src/localization/modalStrings.js, src/mSupplyMobileApp.js, src/pages/CustomerInvoicePage.js, src/pages/SupplierRequisitionPage.js, src/pages/dataTableUtilities/actions/pageActions.js, src/pages/dataTableUtilities/actions/tableActions.js, src/pages/dataTableUtilities/getPageDispatchers.js, src/pages/dataTableUtilities/reducer/pageReducers.js, src/utilities/getModalTitle.js, src/widgets/MultiSelectList.js, src/widgets/ResultRow.js, src/widgets/index.js, src/widgets/modals/DataTablePageModal.js
Fixes #1212
- CustomerInvoice and SupplierRequisition may have multiple MasterLists.
- Previously `add from masterlist` button added all items from all the masterlists combined.
- We want a feature to be able to Select one or more Master list of our choosing and have only the items in the masterlists show up in the invoices.
=> #1212 Make Master list Multiselectable

src/localization/authStrings.js, src/localization/syncStrings.js, src/sync/Synchroniser.js
Fixes #879 
'Pushing changes to server' was hard-coded, now it's properly declared in authStrings.js. Anyway, for other languages rather than English, this is still the default message.
Then:
Repeat this process with all languages.
This solution is related with issue [#484](https://github.com/openmsupply/mobile/issues/484)
=> #879 Localise 'Pushing changes to Server'

src/database/DataTypes/InsurancePolicy.js, src/database/DataTypes/Name.js, src/database/DataTypes/StocktakeBatch.js, src/database/DataTypes/Transaction.js, src/database/UIDatabase.js, src/database/utilities/createRecord.js, src/sync/incomingSyncUtils.js, src/sync/outgoingSyncUtils.js, src/sync/syncTranslators.js
Fixes #1565 
Minor changes, big impact
- Previously `TransactionBatch` had no type. As we were only really handling `ci`/`si` `Transaction`s, could just use the `Transaction.type` to determine the `type` of a batch (i.e. all si `TransactionBatch` are `stock_in`. Since cc `TransactionBatch` can be either a `stock_in` or a `cash_in`, this assumption is no longer valid, so `type` was added to `TransactionBatch`. This means we can just set this directly on the batch, which means when creating, we need to set it.
Pretty smelly with all the parameters already on this method - I'm going to say that refactoring this can be a part of replacing realm and won't do too much now. See below for info on creating other types for rc/cc
N/A
For creation of `TransactionBatch`s for `cc`/`rc` `Transaction`s, …
=> #1565 transaction types

src/database/DataTypes/InsurancePolicy.js, src/database/DataTypes/InsuranceProvider.js, src/database/DataTypes/Name.js, src/database/DataTypes/StocktakeBatch.js, src/database/DataTypes/Transaction.js, src/database/DataTypes/TransactionBatch.js, src/database/DataTypes/index.js, src/database/UIDatabase.js, src/database/schema.js, src/database/utilities/createRecord.js, src/sync/incomingSyncUtils.js, src/sync/outgoingSyncUtils.js, src/sync/syncTranslators.js
Fixes #1564 
- Adds, as per the issue, change to the schema for payments
- Bumps schema
- Have left out a couple of `InsuranceNameJoin` fields i.e. `isActive` where they can be derived easily (I think this just is `insuranceProvider.isActive` and renamed a couple things.
- `InsuranceNameJoin.enteredById` I think is for a `User` not a `Name`? It is never set in desktop/not used and isn't a foreign key 🤷‍♂ 
N/A
N/A
=> #1564 payments schema additions

src/pages/StocktakesPage.js, src/pages/SupplierRequisitionsPage.js
Fixes #1573 
- The condition variable was accidentally declared as a function for some reason 🤷‍♂ 
With no programs defined:
N/A
=> #1573 ByProgramModal when no programs

src/localization/modalStrings.js, src/pages/CustomerInvoicePage.js, src/pages/SupplierRequisitionPage.js, src/pages/dataTableUtilities/actions/tableActions.js, src/widgets/MultiSelectList.js
Fixes #1575 
- Adds a toast when there are no master lists
**This PR is concerned with when there are no master lists. For Customer invoices, this is when the CUSTOMER has no master lists. For a Supplier requisition, this is when YOUR STORE has no master lists**
We need to make a custom toast. I think we should make it come from the top the full width and height of the navigation bar and bright orange (not joking) I think it would be obvious for users and also would look good.
@alainsussol can you tell me french for these pretty please:
- "This customer has no master lists!"
- "Your store has no master lists!"
=> #1575 toast when no masterlist

src/hooks/useNavigationFocus.js, src/hooks/usePopover.js, src/pages/CustomerInvoicesPage.js, src/pages/CustomerRequisitionsPage.js, src/pages/MenuPage.js, src/pages/StocktakeEditPage.js, src/pages/StocktakesPage.js, src/pages/SupplierInvoicesPage.js, src/pages/SupplierRequisitionsPage.js, src/widgets/Badge.js, src/widgets/InfoBadge.js
Fixes #1580 
- Turns out it was because of the badge being unmounted and the ref being reset. Which is what the changes in `MenuPage` were from. So the popover was trying to reference a null pointer.
- When this was fixed, there was an issue that the popover would not dissapear after navigating away. So this is where the change to `usePopover` using `useNavigationFocus` and the addition of `willBlur` in `useNavigationFocus` comes from.
You could also fork/pr into this repo to add a simple line here:  https://github.com/SteffeyDev/react-native-popover-view/blob/6b2c0dea3529f5dd821d6dd98394a45a096d79f2/src/Utility.js#L32-L36
`if (!ref) return false` to 'fix' this 
TIL: `defaultProps` and `propTypes` are not compatible with `forwardRef`
=> #1580 Badges crash on navigating

README.md
Fixes #1560 
Just tidying up wiki and moving some stuff out of the `README.md`.
Still a bit more to add to the wiki, but think this should be all the changes to `README.md` (subject to feedback).
Most wiki changes are uncontroversial. Only one that might require some feedback is the docs on our [Gitflow]( https://github.com/openmsupply/mobile/wiki/Git-workflow). It might be too much of my "ideal" case, so might need some tweaking as to what we realistically are doing or want to do.
=> #1560 move readme to wiki

src/database/DataTypes/Transaction.js, src/database/utilities/createRecord.js, src/utilities/modules/dispensary/pay.js
Fixes #1586 
- utility method to pay a prescription off - adding credit for overpayments or using credit for underpayments
- Still not setting exactly all the fields that should be - for example time should probably be set
- Excessive errors is mainly for development - can be cut down possibly a bit later
N/A
N/A
=> #1586 Utility method: pay

src/database/DataTypes/MasterList.js
Fixes #1611 
Makes comparing store tags case insensitive
Set up a program such that the `[store]tags = test1` and a `program.storeTag = TEST1`
N/A
=> Add toLowerCase() for store tag checks

src/hooks/useNavigationFocus.js
Fixes #1613 
- Just a wrong condition causing the listener to not get attached. `willFocusSub` will always be true, so the condition evaluates to false. But `willFocusSub.current` is only true when the listener is attached
*Described better in the issue*
N/A
=> #1613 Add corrected useNavigationFocus condition

src/mSupplyMobileApp.js, src/navigation/selectors.js, src/reducers/PagesReducer.js
Fixes #1615 
Bug was that after navigating back, the `currentRoute` wasn't being set correctly. Solution is to pass the previous route name in the `BACK` navigation, so you can set the `currentRoute` in state when navigating back
Navigate to `CustomerInvoices page - create a new invoice. Go back, try and delete.
I think `PagesReducer` has gotten to hacky for it to work 'correctly'. Probably should be refactored
=> #1615 deleting doesnt work

src/database/utilities/createRecord.js, src/utilities/modules/dispensary/pay.js, src/utilities/modules/dispensary/refund.js
Fixes #1592 
- Adds refund() utility
- Added a `createRecord` for a `refundLine` - there's really just one more method to write - `cancel`, and that should cover all our use cases. Then it will be very easy to see where the shared/duplicated code is and can revert a few things. Finding it much easier this way
N/A
N/A
=> #1592 refund utility

src/widgets/Stepper.js
Fixes #1604 
- Adds a `Stepper` component
- Another ugly component that needs a stylist. I think easier when it's on a page but the basic idea is there.
- Not sure about the holding down.. I think I really like it but not 100% sure. Possibly need to adjust the frequency of increments but I'm really not the best person to find the most optimal amount, would be good to get user feedback or at least a few peoples opinions on a real physical tablet
- Pretty heavy use of `useRef` which I don't like, but ended up being the most fluid with the UI, otherwise you get strange values - i.e. from 10->17 then 17->29 in one go due to the component re-rendering with React batch updating
- Possibly a better implementation is to add more of a delay to the start of the 'long press incrementing'. Use the …
=> #1604 stepper input

src/localization/navStrings.js
Fixes misspelt stocktake
Correct misspelt "stockake" to "stocktake" at navStrings. 
=> #1626 correct misspelt title of manage stock take

src/database/DataTypes/Requisition.js, src/pages/dataTableUtilities/actions/tableActions.js
Fixes #1640 
- This was a regression from this PR: https://github.com/openmsupply/mobile/pull/1551 - where a new parameter was added to handle adding from master lists via the `Add from MasterList` button. The call from this button was not accounted for
- This is a quick fix for the runtime error and potentially for the release if #1576 is not completed before then.
*This PR relates to the `Create Automatic Order` Button on `SupplierRequisitionsPage`*. An automatic order will add all items to the requisition which have a suggested quantity > 0, and will set the `requested quantity` to the `suggested quantity`.
Other calls to the `Requisition.addFromMasterLists` and `Transaction.addFromMasterLists` buttons - but there are no others.
=> Add fix for regression from parameter additions

package.json, src/utilities/formatters.js, src/utilities/index.js, src/widgets/Slider.js, src/widgets/index.js, yarn.lock
Fixes #1634 
- Adds a `Slider` component, a wrapper around the react native community edition of a native slider - the `Slider` component from `react-native` has been deprecated and extracted out in favour of this component.
- Potentially the `TextInput` would be replaced by a component made from #1632  when that is complete.
- Should you rename props that are american spelling to english spelling? Dunno! But I did
- Don't want to conflict with diego's localizing so will do that later.
- Overall this could be more dynamic and extensible, especially with styles, but will leave it for now
N/A
N/A
=> #1634 Slider component

package.json, src/utilities/formatters.js, src/utilities/index.js, src/widgets/Slider.js, src/widgets/TableShortcuts.js, src/widgets/index.js, yarn.lock
Fixes #1635 
- Adds a simple `TableShortcuts` component, basically a layout component, which is just going to basically stack some components on top of each other with a gesture handler
Basic code could look like:
```
export const TestPage = () => (
<View style={{ flexDirection: 'row', flex: 1 }}>
<TableShortcuts>
<TableShortcut onPress={() => console.log(':)')}>Favs</TableShortcut>
<TableShortcut onPress={() => console.log(':)')}>A-F</TableShortcut>
<TableShortcut onPress={() => console.log(':)')}>G-L</TableShortcut>
<TableShortcut onPress={() => console.log(':)')}>M-Z</TableShortcut>
</TableShortcuts>
<View style={{ flex: 19 }}>
<SimpleTable data={testData} columns={[{ key: 'col1' }]} />
</View>
</View>
);
```
But each `TableShortcut` can also have it's own children, and icon for …
=> #1635 table shortcuts

src/database/DataTypes/Requisition.js, src/database/DataTypes/Transaction.js, src/pages/dataTableUtilities/actions/tableActions.js
Fixes #1645 
- Corrected the parameters being passed to `AddFromMasterList` in `Transaction`.
- `Requisition` and `Transaction` both have this method - only certain calls need the optional parameter `thisStore`, others `selected` - so turned the arguments to an object.
N/A
=> #1645 Add from MasterList runtime error

src/pages/dataTableUtilities/actions/cellActions.js
Fixes #1621 
- Parses the number entered, the same as every other quantity input.
N/A
=> #1621 Validate stocktake batch input

src/database/DataTypes/RequisitionItem.js
Fixes #1647 
When having two master lists related with a mobile store, all items were taking the same max price. This issue was solved adding an extra filter to select the corresponding MasterListItem before applying max('price'). 
=> #1647 Incorrect pricing

src/utilities/dailyUsage.js
Fixes #1666 
- Corrects the usage return value, which was returning `1`, instead of `0`
**[ You can check monthly usage by going to `Current Stock` page - and clicking on an item. A popup will open from the bottom of the screen, which will display monthly usage ]**
example:
**Usage calculation can be found in `dailyUsage.js`. It is the sum of all usage within the lookback period (defined through store custom data `monthlyConsumptionLookBackPeriod` field, defaults to 30 if not defined in store custom data), over the number of days in the lookback period.**
However, if the item was added (earliest stock in transaction batch confirm date for that item) more recently than the lookback period, the usage is calculated only since the item was added. UNLESS the store custom data …
=> #1666 Corrected usage calculation

src/pages/dataTableUtilities/getPageDispatchers.js
Fixes #1663 
- Adds debouncing of filtering
*debouncing ensures a function is invoked only once when called consecutively (in this case within 75 ms)
N/A
=> #1663 Debounced callback

src/database/DataTypes/MasterList.js, src/database/DataTypes/Requisition.js, src/localization/modalStrings.js, src/localization/programStrings.js, src/utilities/finalisation.js, src/widgets/modals/ByProgramModal.js
Fixes #1557
- Adds the maximum number of lines functionality to program requisitions.
- Change is just a few helpers to determine order types/max lines and add a condition in the finalisation validation.
- Bit spaghetti, but returning a string from the requisition finalisation validation method will display this in a modal
- Currently in desktop you can set the max number of lines to 0. This implementation just ignores the max number of lines if it's 0
- Displays the max lines when selecting an order type
*This PR is related to this PR in desktop: https://github.com/sussol/msupply/issues/4557 - which adds a configuration to an `Order Type`, which limits the number of items that can be ordered, when a requisition is created when created with that `OrderType`. 
e.g. with the setup below, …
=> #1557 item limit for emergency orders

src/database/utilities/createRecord.js
Fixes #976 
Main intention is change sortIndex to start from 1 instead of 0. This is important because on desktop it is expected that line numbers start from 1.
=> #976 sortIndex modified to start from 1

src/utilities/finalisation.js
Fixes #1681 
- Forgot realm objects which aren't defined are null, not undefined. Default destructuring only occurs when something is undefined
N/A
=> #1681 Corrected nested object usage

src/pages/dataTableUtilities/getPageInitialiser.js
Fixes #1042 
When opening a finalised program requisition, the toggle was set `Hide over stocked` as default, causing confusions when opening to see its items. Now it is `Show over stocked` as default, and anyway it can by toggle to hide/show as before (option remains enable).
Attention: Remember to add items that are over stocked, otherwise the toggle will not make any sense (all items will be shown either hide/show is pressed).
=> #1042 Change `Show over stocked` as default in program requisitions

src/localization/validationStrings.js, src/widgets/ValidationTextInput.js, src/widgets/index.js
Fixes #1632 
- Adds `ValidationTextInput` component which should make validation and form control a little easier.
- Primary use will be for creating/editing patients and insurance policies
- If we use patient editing as the example: I am progressing toward the parent having a some sort of `formValid` property (maybe multiple, for each input and some aggregated valid property also), which will control the `SAVE` button on a form. This will be updated by the call back of each input which will call back when the validity changes. When an input is finished being edited, it will callback it's updated values.
- Could potentially use some X and ✓ icons to be a bit more classy 🎩 but can come later I think!
- Could potentially callback to the parent everytime the text changes to save the value. …
=> #1632 TextInput with Validation

src/Store.js, src/navigation/actions.js, src/pages/DispensingPage.js, src/pages/PrescriptionPage.js, src/pages/dataTableUtilities/getColumns.js, src/pages/dataTableUtilities/getPageInitialiser.js, src/pages/index.js, src/reducers/DispensaryReducer.js, src/reducers/PrescriptionReducer.js, src/reducers/index.js, src/widgets/DataTable/HeaderCell.js, src/widgets/SimpleTable.js, src/widgets/Stepper.js, src/widgets/TableShortcuts.js, src/widgets/constants.js, src/widgets/icons.js, src/widgets/index.js
Fixes #1662 
- Adds the basic structure for the prescriptions Wizard for to enable more focused iterations
- Adds a `PrescriptionReducer`  - Not sure on this. I think having a reducer and state for this flow is good and there will many more actions/reducer cases/state to hold when there is full functionality, but not sure if it should be split up more. For example, a `TabsReducer` which handles the state of the tabs, which would be re-used elsewhere. Also an `ItemsReducer` which handles interactions with the items. a `PaymentsReducer` which handles payments. Seems over the top right now, but possibly this would be the way to go.
- Couple other minor offroad adventures: added a star icon, added forwarding of a ref to `SimpleTable` to control the scrolling, changed a few propTypes in order …
=> #1662 Prescriptions Wizard

src/widgets/AutocompleteSelector.js, src/widgets/MultiSelectList.js, src/widgets/ResultRow.js, src/widgets/index.js, src/widgets/modals/ByProgramModal.js, src/widgets/modals/DataTablePageModal.js
Fixes #1540
- Refactor code 
- Autocomplete selector should use hooks api
- Move `ResultRow` component out of `AutocompleteSelector` component
- User `ResultRow` already present in code, hence sharing the component among `AutocompleteSelector` and `MultiSelectList`.
None
=> #1540 Fix autocomplete selector should use hooks api

src/database/DataTypes/Report.js, src/database/DataTypes/index.js, src/database/schema.js
Fixes #1708
Report class was added to the realm schema with the structure suggested in #1708.
No sure. Same as #1706 maybe?
Less fields than suggested as first option here #441 were added to Report schema, so maybe later it needs to by checked and adjusted in consequence.
=> #1708 Report class added to Realm schema

src/database/DataTypes/Report.js, src/utilities/checkIsObject.js, src/utilities/index.js
Fixes #1709?
Getter and setter added to handle data in Report class. Mainly since the data field on the Report object will be a stringified JSON object, no will have getters/setters to help save these fields. 
Not sure (Same as #1706 maybe?)
Check #1709 for more details.
=> #1709 Add report class getters and setters

src/sync/incomingSyncUtils.js
Fixes #1710
Report class was added to list of record types to check in `incomingSyncUtils`
Not sure by now. Same as #1706 ?
@joshxg @andreievg 
Should I use `checkIsObject()` here as well? In that case, it is not useful to have it in `Report.js`. Once might be enough (as far as I understand), please correct me if I am wrong. Thanks!
=> #1710 Add Report to incoming sync utils

src/pages/MenuPage.js
Fixes #1696 
Incorrectly never-update-memoizing components!
This relates to the following flow: Go to your store and add to custom data `usesDispensaryModule: true`. Sync on mobile. Your MenuPage should then look like this:
N/A
=> #1696 Non-updating styles on MenuPage

src/pages/DispensingPage.js, src/pages/MenuPage.js, src/widgets/SearchBar.js
Fixes #1697 
- `SearchBar` `TextInput` was flexing, so I made the container flexing to fit on the dispensary page, but this made every other page crazy. Oops
N/A
N/A
=> #1697 Corrected flexing of SearchBar

src/widgets/PieChart.js
Fixes #1740
Add `PieChart` to show the pie chart graphs on the dashboard. 
- It shares a similar skeleton than future components `LineChart` and `BarChart`
Many lines of code were taken from this [branch](https://github.com/openmsupply/mobile/blob/49d8ab764c85ec5e35699661da92aad8c3e1b03a/src/widgets/ReportChart.js). Further changes may be taken into consideration.
=> #1740 Add PieChart component 

src/widgets/LineChart.js
Fixes #1742 
Add `LineChart` component to show line chart graphs on the dashboard. 
- It shares a similar skeleton than `LineChart`, `BarChart` and `ReportTable`
=> #1742 Create Line chart component

src/widgets/ReportTable/ReportCell.js
Fixes #1755 
Add `ReportCell` component to use together with `ReportRow` and `ReportTable` components for showing Table reports on the feature/dashboard. 
- Needed in conjunction with `ReportRow` and `ReportTable` components.
=> #1755 Create ReportCell component

src/widgets/ReportTable/ReportRow.js
Fixes #1754
Add `ReportRow` component to use together with `ReportCell` and `ReportTable` components for showing Table reports on the feature/dashboard. 
- Needed in conjunction with `ReportCell` and `ReportTable` components.
=> #1754 Create ReportRow component

src/widgets/ReportTable/ReportTable.js
Fixes #1755 
Add `ReportTable` component to use together with `ReportRow` and `ReportCell` components for visualising Table reports on the feature/dashboard. 
- Needed in conjunction with `ReportRow` and `ReportCell` components.
=> #1744 Create ReportTable component

src/widgets/ReportSideBar/ReportSideBarItem.js
Fixes #1761 
A new component named `ReportSideBarItem` was created in order to render each report (item) to be selected to visualise.
- Needed in conjunction with `ReportSideBar`
=> #1761 Create ReportSideBarItem component

src/widgets/ReportSideBar/ReportSideBar.js, src/widgets/ReportSideBar/index.js
Fixes #1714 
This component manages the list of items available to be render, using its children `ReportSideBarItem` component.
=> #1714 Create ReportSideBar component

src/pages/PrescriptionPage.js, src/widgets/DetailRow.js, src/widgets/NumberLabelRow.js, src/widgets/PrescriptionSummary.js, src/widgets/PrescriptionSummaryRow.js, src/widgets/SimpleLabel.js
Fixes #1739 
- Adds `NumberLabel` component. Little odd but will be used in the pricing/payment section also.. so will possibly be relying on the value being a number for some things.
- Adds `PrescriptionSummary`/`PrescriptionSummaryRow` components
looks like this at the moment:
Or a little smaller:
- Obviously still needs tidying!
- Might need prices, units or other values.. will go in the smaller middle row
N/A
N/A
=> #1739 prescription summary

src/pages/PrescriptionPage.js, src/pages/dataTableUtilities/getColumns.js, src/widgets/CircleButton.js, src/widgets/DetailRow.js, src/widgets/DropdownRow.js, src/widgets/NumberLabelRow.js, src/widgets/PrescriptionCart.js, src/widgets/PrescriptionCartRow.js, src/widgets/PrescriptionSummary.js, src/widgets/PrescriptionSummaryRow.js, src/widgets/SimpleLabel.js, src/widgets/StepperInput.js, src/widgets/StepperRow.js, src/widgets/icons.js
Fixes #1748 
- Adds quite a few components..
`CircleButton`:
`StepperRow`:
`DetailRow`:
`DropdownRow`:
None are really 100% right, but in general I think they're minor style adjustments that can be iterated on when pulling together
N/A
- Really need better ways to create things .. more smaller components to use I think.. like `<FlexRow flex={2}> ...` which is just a `View` with `flexDirection: "row", flex: flex` .. same with colums etc!
=> #1748 misc dispensing components

src/pages/PrescriptionPage.js, src/pages/dataTableUtilities/getColumns.js, src/widgets/CircleButton.js, src/widgets/DetailRow.js, src/widgets/DropdownRow.js, src/widgets/NumberLabelRow.js, src/widgets/PrescriptionCart.js, src/widgets/PrescriptionCartRow.js, src/widgets/PrescriptionSummary.js, src/widgets/PrescriptionSummaryRow.js, src/widgets/Separator.js, src/widgets/Seperator.js, src/widgets/SimpleLabel.js, src/widgets/StepperInput.js, src/widgets/StepperRow.js, src/widgets/icons.js
Fixes #1737 
- Adds a `SimpleLabel` component:
[This is three `SimpleLabel`'s]
- Also trying to sneak in a `Seperator` component 
N/A
- Trying to break components down to more basic parts
- Will need in the future a better project layout - `widgets` is getting a bit nutty!
=> #1737 SimpleLabel & Seperator components

src/pages/MenuPage.js
Fixes #1777 
- Adds correct proptype for `isAdmin` 
- Adds some comments!
N/A
=> #1777 Corrected isAdmin propType

src/pages/CustomerInvoicePage.js, src/pages/CustomerInvoicesPage.js, src/pages/MenuPage.js, src/pages/StocktakeManagePage.js, src/pages/StocktakesPage.js, src/pages/SupplierInvoicePage.js, src/pages/SupplierInvoicesPage.js, src/pages/SupplierRequisitionPage.js, src/pages/SupplierRequisitionsPage.js, src/widgets/TextEditor.js, src/widgets/bottomModals/BottomModalContainer.js, src/widgets/index.js, src/widgets/modalChildren/AutocompleteSelector.js, src/widgets/modalChildren/GenericChoiceList.js, src/widgets/modalChildren/MultiSelectList.js, src/widgets/modalChildren/NewConfirmModal.js, src/widgets/modalChildren/TextEditor.js, src/widgets/modalChildren/ToggleSelector.js, src/widgets/modalChildren/index.js, src/widgets/modals/ByProgramModal.js, src/widgets/modals/DataTablePageModal.js, src/widgets/modals/LoginModal.js, src/widgets/modals/StocktakeBatchModal.js, src/widgets/modals/index.js
Fixes #1547 
- Went a little offroad.. - I messed up another import in another refactor, so I have changed that in each of the pages. This is the `BottomConfirmModal` import in each of the `...pages` components. Oops
- I made a folder `widget/modalChildren` which now contains all of the components which are designed to be children of `ModalContainer`
- Refactored `TextEditor` to be functional and use hooks
**This PR is a refactor, so behaviour should mimic the old behaviour. This is a vague test case, so please check the current MASTER branch behaviour, and see that the behaviour is the same on THIS branch**
`TextEditor` Component used:
This will complete all the refactors aimed at `3.2`
=> #1547 text editor refactor

src/actions/FinaliseActions.js, src/database/DataTypes/Item.js, src/database/DataTypes/ItemDirection.js, src/database/DataTypes/TransactionItem.js, src/database/UIDatabase.js, src/database/utilities/createRecord.js, src/mSupplyMobileApp.js, src/pages/PrescriptionPage.js, src/reducers/FinaliseReducer.js, src/reducers/index.js, src/widgets/Tabs/PrescriptionConfirmation.js
Fixes #1801 
This has created two further issues: 
- #1808 - to "finish off" moving finalise logic into redux
- #1809 - to implement the 'locking' of the script after finalising
- Added a `Finalise` reducer.
- Finalise logic is extremely convoluted..but the `finaliseItem` comes from `pages/index` and is added to in `mSupplyMobileApp.mapStateToProps`. It's then(was) controlled by the state in `mSupplyMobileApp` which a callback was passed to `NavigationBar`
- It becomes more complicated to handle finalising if we use the navigation bar. I think we should put it back there eventually, but for now I have shifted some of this logic (handling the modal) into redux (which would be needed in any case) and just added a button in the bottom right
- Otherwise, would be looking into various things …
=> #1801 Prescription finalization

src/actions/FinaliseActions.js, src/database/DataTypes/Item.js, src/database/DataTypes/ItemDirection.js, src/database/DataTypes/TransactionItem.js, src/database/UIDatabase.js, src/database/utilities/createRecord.js, src/mSupplyMobileApp.js, src/pages/PrescriptionPage.js, src/pages/dataTableUtilities/getColumns.js, src/reducers/FinaliseReducer.js, src/reducers/PrescriptionReducer.js, src/reducers/index.js, src/selectors/prescription.js, src/widgets/FlexColumn.js, src/widgets/PrescriptionCart.js, src/widgets/PrescriptionCartRow.js, src/widgets/PrescriptionSummaryRow.js, src/widgets/SimpleTable.js, src/widgets/StepperRow.js, src/widgets/Tabs/ItemSelect.js, src/widgets/Tabs/PrescriptionConfirmation.js, src/widgets/index.js
Fixes #1799 
The problem wasn't that the summary wasn't displaying the quantities, but rather quantities being added to items which were greater than available stock. It wasn't that the summary wasn't displaying only 0, rather I was adding quantity to items which had no stock, so it wasn't being updated in the actual transaction.
- Extracted `ItemSelect` from `PrescriptionPage`
- added a `TotalQuantity` column to `ItemSelect`
- Added some disabling logic to `SimpleTable` so that rows can have their `onPress` removed, and grey text when they're disabled -- This fixes the problem. No more items with 0 available quantity being added and causing confusion
- Added a `FlexColumn` component
N/A
N/A
=> #1799 prescription summary to show quantities

src/reducers/PatientReducer.js, src/reducers/PrescriberReducer.js
Fixes #1826 
- Changed the state changes of prescriber and patient to correctly reset when required. When creating a patient/prescriber (CREATION), reset to no current. When navigating to a prescription, reset to no prescriber. And when closing the prescriber modal, don't clear the current prescriber, just the same as patient.
N/A
Possibly should clear the `currentPatient` and `currentPrescriber` when closing the modal.. Not doing that at the moment because of prescriptions, but could use the underlying `Transaction` customer and prescriber rather than having them stored in state for that.
=> #1826 Updated Prescriber and Patient reducer state transitions

src/sync/incomingSyncUtils.js, src/sync/syncTranslators.js
Fixes #1828.
Adds incoming sync stubs for indicator tables.
NOTE: the below tests are duplicated in #1837.
- Add `console.log` statements to `createOrUpdateRecord` case blocks for `ProgramIndicator`,, `IndicatorAttribute`, `IndicatorValue`.
- Make an internal order to the mobile store for an indicator program.
- Add some values and finalise the requisition.
- New indicator values should be created and synced to mobile. 
See #1837 for added indicator tables.
=> #1828 add indicator incoming sync

src/pages/SupplierRequisitionPage.js, src/pages/dataTableUtilities/actions/constants.js, src/pages/dataTableUtilities/actions/tableActions.js, src/pages/dataTableUtilities/getPageDispatchers.js, src/pages/dataTableUtilities/getPageInitialiser.js, src/pages/dataTableUtilities/reducer/tableReducers.js
Fixes #1829.
Branches off #1831.
Adds actions, reducers for toggling indicators. No data table logic.
Next steps are to add column swapping logic, which I think will probably be the most tricky part of this functionality. Discussion will follow on this in new issue.
=> #1829 add indicator toggle logic

src/database/DataTypes/IndicatorAttribute.js, src/database/DataTypes/ProgramIndicator.js, src/sync/incomingSyncUtils.js
Fixes #1842.
Branches off #1829.
- Adds  `ProgramIndicator.rows`, `ProgramIndicator.columns` links.
- Adds related `ProgramIndicator`, `IndicatorAttribute` helpers.
- Adds related incoming sync logic.
- Create a new indicator program and sync to mobile.
- Navigate to the Realm Explorer to view synced data.
N/A.
=> #1842 add indicator row column relations

src/widgets/modalChildren/AutocompleteSelector.js
Fixes #1866 
Now `onChangeText` is directly calling `setQueryText` and setting up the new value of `queryText`. 
=> #1866 Modify setQueryText argument

src/database/DataTypes/TransactionBatch.js, src/reducers/PaymentReducer.js, src/selectors/patient.js, src/selectors/user.js, src/widgets/PaymentSummary.js, src/widgets/Tabs/PrescriptionConfirmation.js
Fixes #1858 
- Disables editing payment values when the transaction is finalised
- Disables the confirm button for the prescription when the payment is invalid or the transaction is finalised.
N/A
- The `paymentValid` field is pretty redundant at the moment, but feel it might become neccessary!
=> #1858 disable payments

src/localization/generalStrings.json, src/pages/DashboardPage.js
Fixes #1847
A message added (`No reports to show`), which is mainly feedback needed to advise the user that there is no reports to show. This was added to `DashboardPage.js`, and the returned view depends on `reports.length`
Further testing will be taking place later on together with the whole dashboard/feature branch.
=> #1847 Message added when no reports to show

src/sync/incomingSyncUtils.js, src/widgets/BarChart.js, src/widgets/LineChart.js, src/widgets/PieChart.js
Fixes #1880 and #1878 
According to the data structure obtained from the desktop version, the actual data needed is more nested than we thought. This changes are intending to solve that wrong assumption.
So here we destructure `data` to get the actual values.
Aclaration: No need to do it in `ReportTable`
Further testing will be taking place all together for the feature/dashboard branch.
`ReportDemoData` should be updated to can test with the new structure.
=> #1880 Get values from data object

src/widgets/BarChart.js, src/widgets/LineChart.js, src/widgets/PieChart.js
Fixes #1899 
Based on the data structure received from dashboard reports, the correct way to read what to graph should be accessing to `values`, which can be one or more array with `x` and `y` values.
Further testing will be taking place when the dashboard feature is ready.
=> #1899 Change the way values are being obtained from data

src/database/DataTypes/IndicatorAttribute.js, src/database/utilities/createRecord.js, src/pages/SupplierRequisitionPage.js, src/pages/dataTableUtilities/actions/cellActions.js, src/pages/dataTableUtilities/getPageDispatchers.js, src/pages/dataTableUtilities/reducer/cellReducers.js, src/sync/incomingSyncUtils.js, src/utilities/getIndicatorTableData.js, src/utilities/index.js
Fixes #1877. 
Add actions, reducers for editing, saving and re-rendering indicator values.
N/A.
=> #1877 edit indicator values

src/sync/SyncQueue.js, src/sync/outgoingSyncUtils.js
Fixes #1913. Branches off #1903.
Adds `IndicatorValue` to outgoing sync.
Easiest way to test that a value is synced to desktop is to place a breakpoint into desktop mSupply incoming sync logic. If on a build, record browser can be used.
N/A.
=> Add indicator attributes to outgoing sync

src/widgets/BarChart.js, src/widgets/LineChart.js, src/widgets/PieChart.js
Fixes #1898
Graphs were needed to have its corresponding labels showing related data, specially for `LineChart` with more than one line per graph.
`label` information is part of the data received from desktop. For`LineChart` graphs with more than one line, the intention is to explicitly show what information each line represents.
Examples:
Further testing will take place when the dashboard feature is ready.
=> #1898 Add labels to charts

src/database/DataTypes/Requisition.js, src/pages/SupplierRequisitionPage.js, src/pages/dataTableUtilities/getPageInitialiser.js
Fixes #1902.
Adds `usingIndicators` prop to `SupplierRequisition` to prevent error when creating non-indicators requisitions.
N/A.
=> #1902 fix supplier requisition no indicator error

src/widgets/SearchBar.js
Fixes #1873 
- Changes the `placeholderTextColor` and font size 
**Might be different on different size emulators?**
N/A
=> #1873 SearchBar placeholder

src/sync/incomingSyncUtils.js
Fixes #1930.
Hotfix sync issue caused by bad merge.
N/A.
=> Fix ProgramIndicator incoming sync error

src/localization/generalStrings.json, src/pages/CustomerInvoicePage.js, src/pages/CustomerInvoicesPage.js, src/pages/CustomerRequisitionPage.js, src/pages/CustomerRequisitionsPage.js, src/pages/StockPage.js, src/pages/StocktakeEditPage.js, src/pages/StocktakeManagePage.js, src/pages/StocktakesPage.js, src/pages/SupplierInvoicePage.js, src/pages/SupplierInvoicesPage.js, src/pages/SupplierRequisitionPage.js, src/pages/SupplierRequisitionsPage.js, src/pages/dataTableUtilities/getPageInitialiser.js
Fixes #1952 
- Changed the placeholders to be consistent and correct with the columns they're filtering on
I made new strings because it was easier. They're lower case because it's LESS SHOUTY AND DISTRACTING
@alainsussol  is my french correct? It might be different in the region I learnt french in:
```
"no_reports": "Aucun rapport à afficher",
"invoice_number": "numéro de facture",
"requisition_number": "numéro de réquisition",
"item_name": "nom de l'article",
"item_code": "code de l'article",
"customer": "cliente",
"code": "code",
"name": "nom",
"or": "ou"
```
=> #1952 searchbar placeholder text

src/pages/SupplierRequisitionPage.js, src/pages/dataTableUtilities/getPageInitialiser.js, src/sync/incomingSyncUtils.js
Fixes #1951.
Also includes a hotfix for #1958, which was found during replication.
Fixed up some incorrect booleans in `SupplierRequisitionPage` and `getPageInitialiser`. Still needs tidying up a bit, but the error is no longer replicable. 
Related prop type fixes to follow (see #1950).
N/A.
=> #1951 app crash on non indicators requisition

src/database/DataTypes/Requisition.js, src/pages/SupplierRequisitionPage.js, src/pages/dataTableUtilities/getPageInitialiser.js
Fixes #1950. Branches off #1959.
Fixes supplier requisition warnings caused by undefined indicator props.
N/A.
=> #1950 fix supplier requisition prop types

src/database/DataTypes/MasterList.js, src/database/DataTypes/Requisition.js
Fixes #1954. Branches off #1960.
Fixes inactive indicators being displayed. 
N/A.
=> #1954 fix supplier requisition showing inactive indicators

src/pages/dataTableUtilities/actions/cellActions.js, src/widgets/modals/StocktakeBatchModal.js
Fixes #1994 
- Connects `StocktakeBatchModal` to redux. Could just pass a prop for the dispatch, but this modal should be changed a bit to use redux anyway as we move closer to using redux for a lot more, so it is the easier and more long term solution
- Connected so that it has access to the redux dispatch function, which means we can dispatch a refresh on the underlying `StocktakeItem` when we edit within the modal.
- The `Batch` from redux uses `react` api to force the interface to update once for both dispatches, rather than twice
This is a pretty dirty hack, but moves forward to a way to easily change up the modal to be a bit nicer and stop using `usePageReducer`
=> Add refresh to editing in stocktakebatchmodal

src/pages/dataTableUtilities/actions/cellActions.js, src/widgets/modals/StocktakeBatchModal.js
Fixes #1992 
- This actually occurs when you're mid-editing a cell and navigate back.
- You basically have to be spamming a cell with text and clicking back at the same time, so not tooo bad
I mean, the codes not pretty but 🤷‍♂ 
Ideally, there would be a `ERROR` action which would be dispatched in the else - which wouldn't do anything, but potentially logs in the future
=> #1992 undefined objects in cell actions

src/database/utilities/createRecord.js, src/pages/dataTableUtilities/actions/tableActions.js, src/utilities/modules/dispensary/constants.js, src/widgets/modals/CashTransactionModal.js
Fixes #2006
Adds basic functionality for adding new cash transactions. Completes the MVP functionality, but lot left to tidy up and bits of `CashRegisterPage` UI and functionality still remaining. 
- `CashRegisterPage`:
- Add searchbar. 
- Add toggle bar for receipts/payments.
- Add total cash balance.
- `CashRegisterModal`
- Add "cash in/cash out" toggle.
- Update bottom modal components (size, keyboard etc.).
- Disable reasons for cash in transactions. 
- Cash reconcilation functionality:
- Sync out `payment` and `receipt` records.
=> #2006 add new cash transaction functionality

.eslintrc, src/database/DataTypes/IndicatorValue.js, src/database/utilities/constants.js, src/database/utilities/createRecord.js, src/database/utilities/getIndicatorData.js, src/database/utilities/indicatorConstants.js, src/pages/CustomerRequisitionPage.js, src/pages/SupplierRequisitionPage.js, src/sync/incomingSyncUtils.js, src/widgets/DataTable/DataTable.js, src/widgets/DataTable/TextInputCell.js, src/widgets/DataTable/constants.js, src/widgets/DataTable/index.js
Fixes #1906.
Adds type enforcement to indicator data entry.
Currently, indicators only supports string and numerical (interpreted as positive integer) data. Would be good in future to add support for negative integers, real numbers, booleans etc.
=> #1906 enforce indicator types

src/pages/DispensingPage.js
Fixes #2031 
- Removes the `onPress` for patients and prescribers as they have a column with a button for this now and this `onPress` was crashing the app
N/A
N/A
=> #2031 Remove patient/prescriber row onPress

src/actions/PatientActions.js, src/actions/PrescriberActions.js, src/context/LoadingIndicatorContext.js, src/database/DataTypes/Transaction.js, src/database/DataTypes/TransactionBatch.js, src/database/DataTypes/TransactionItem.js, src/database/utilities/createRecord.js, src/hooks/useLoadingIndicator.js, src/localization/currency.js, src/mSupplyMobileApp.js, src/pages/DispensingPage.js, src/sync/outgoingSyncUtils.js, src/utilities/modules/dispensary/pay.js, src/widgets/CurrencyInputRow.js, src/widgets/NumberLabelRow.js, src/widgets/PaymentSummary.js, src/widgets/Tabs/PrescriptionConfirmation.js
Fixes #2021 
- Makes a few changes to `outgoingSyncUtils` to allow for `TransactionBatch` records to sync if they don't have an `ItemBatch`. Was using `safeGet` and it wasn't safe.
- Also added the `total` field being used when setting a quantity on a batch.
- Added `price_extension` and `foriegn_currency_..` to come from the `total` field. This is so it's historic and not changing with the `ItemBatch` and also because the payment lines don't have an `ItemBatch`!
- Removed the `safeGet` method because it wasn't used anymore and there doesn't seem to be any point to it now with optional chaining and null coals
N/A
N/A
=> #2021 TransactionBatch outgoing sync

package.json, src/sync/incomingSyncUtils.js, src/utilities/index.js, src/utilities/validateReport.js
Fixes #1982
Because `dashboard_store_reports` coming from desktop can have a different data structure or report type as the expected, a report validation was added. Basically here we use the report type to contrast the data structure with a known validated json schema (using an external dependency named [ajv](https://www.npmjs.com/package/ajv)).
Instructions to generate reports:
1. Make Dashboard feature visible in main page:
2. Add reports
3. Edit json structures of each generated report
Many more test cases can be added in order to test this properly, but anyway I _think_ the following are the main ones:
Test 1 - Edit json structure to make the invalid
Example: remove "label" and its value of TableReport, delete one "x" or "y" …
=> #1982 Validate dashboard's reports

src/pages/dataTableUtilities/actions/tableActions.js, src/utilities/modules/dispensary/constants.js, src/widgets/modals/CashTransactionModal.js
Fixes #2020.
Replaces type choice list bottom modal with toggle bar.
N/A.
=> #2020 add cash register transaction type toggle

src/pages/dataTableUtilities/constants.js, src/pages/dataTableUtilities/getColumns.js, src/widgets/DataTable/DataTableRow.js, src/widgets/bottomModals/BottomCurrencyEditor.js, src/widgets/bottomModals/index.js, src/widgets/modals/CashTransactionModal.js
Fixes #2037.
Updates cash register input to use `currency` module. Still a pretty basic input, but looking better.
Still a lot of room for improvement here, ideally expanding `BottomCurrencyModal` to use a similar component to `CurrencyRowInput`.
=> #2037 fix cash register amount input

src/actions/PrescriptionActions.js, src/mSupplyMobileApp.js, src/navigation/actions.js, src/reducers/PagesReducer.js, src/reducers/PaymentReducer.js, src/reducers/PrescriptionReducer.js, src/selectors/prescription.js, src/utilities/underscoreMethods.js, src/widgets/PrescriptionCart.js, src/widgets/PrescriptionSummary.js, src/widgets/Tabs/ItemSelect.js, src/widgets/Tabs/PrescriberSelect.js, src/widgets/Tabs/PrescriptionConfirmation.js
Fixes #2050  
- Adds a delete prescription action and defensive code against possible re-renders without a `Transaction` in state
- Added code which will delete the prescription when 1) new cancel button is clicked 2) hardware back button is pressed 3) navigation bar back button is pressed 4) navigating to the dispensary page or Customer invoices page
N/A
N/A
=> #2050 Delete unfinalised prescriptions

src/sync/outgoingSyncUtils.js
Fixes #2063.
Updated outgoing sync to correctly handle totals for  `payment` and `receipt` transactions (i.e. cash transactions with no associated `TransactionItem` or `TransactionBatch` records).
N/A.
=> Fix outgoing sync for payment and receipt transactions

src/pages/dataTableUtilities/constants.js, src/pages/dataTableUtilities/getColumns.js, src/pages/dataTableUtilities/getPageInfoColumns.js
Fixes #2047.
Removes redundant cash register `"status"` column.
N/A.
=> Remove finalised column from cash register page

src/database/DataTypes/Transaction.js, src/sync/outgoingSyncUtils.js, src/utilities/modules/dispensary/pay.js, src/widgets/DetailRow.js, src/widgets/Tabs/PrescriberSelect.js, src/widgets/Tabs/PrescriptionConfirmation.js
Fixes #2099 
- Correctly assigns insurance details to a finalise prescription. I've made #2104 to refactor this code to be less weird/horrible as the amount of parameters is very msupplyesque but it works so going with it for now
- Added insurance stuff to outgoing sync including the historic insurance details
- Fixed a couple of prop type and key warnings
Basically, this makes syncing prescriptions with insurance correct
I.e. I can now get this in desktop after syncing a prescription with a payment of $10, with 25% insurance 🎉 
N/A
N/A
=> #2099 Store insurance details

src/mSupplyMobileApp.js, src/selectors/payment.js, src/widgets/PrescriptionSummary.js, src/widgets/PrescriptionSummaryRow.js
Fixes #2112 
- In the summary, display all batches and the total cost for that batch, rather than just an item by itself, for cases where you need to dispense over multiple batches
N/A
N/A
=> #2112 list all batches not items

src/actions/PrescriptionActions.js, src/selectors/prescription.js, src/widgets/PrescriptionCart.js, src/widgets/StepperInput.js, src/widgets/Tabs/PrescriptionConfirmation.js
Fixes #2128 
- Memo'd `StepperInput`
- Added selectors which keep the item array for the table consistently more stable to avoid re-renders
- Changed `StepperInput` to trigger the callback only when on long press ends
N/A
N/A
=> #2128 stepper updates

src/pages/CashRegisterPage.js, src/pages/dataTableUtilities/getPageInitialiser.js
Fixes #2077.
Add cash register sorting functionality.
N/A.
=> #2077 add cash register sorting

src/database/DataTypes/Transaction.js, src/sync/outgoingSyncUtils.js
Fixes #2062 
- Save the transaction total amount on a Transaction rather than trying to use the derived value for anything other than a `ps` or `rc`, 'sc', 'cc' when finalising. Avoiding regressions by keeping the same behaviour for the existing types. The only problem is for the `ci` created for a cash out which would technically get through and have it's `total` reset, but the finalise method isn't used for that type. I don't think that's a good enough reason, so I think this still needs some thinking - it is working for now though.. :(
- Can then use `total` field in `outgoingSync` for all cases.
- Using `total` field in all cases fixes this for the `cc` and `ci`
N/A
- There's probably so more nicer cleanup to do here. I think using a different method to determine the total for cash …
=> #2062 cash in cash out totals incorrect

src/selectors/prescription.js, src/widgets/PrescriptionExtra.js
Fixes #2138
Changed from saving a string to the `transactionCategory` to an object
=> change prescriptioncategory from string to object

src/database/DataTypes/Transaction.js, src/database/utilities/createRecord.js, src/sync/incomingSyncUtils.js, src/sync/outgoingSyncUtils.js, src/utilities/modules/dispensary/pay.js
Fixes #2134
Aligning with desktop here in the wiki: https://wiki.sussol.net/doku.php/msupply:specifications:customers:receipts_payments where `subtotal` is the real subtotal and `total` is the subtotal less tax and discounts. Since we only use insurance discount and no tax in mobile, the total is really just `subtotal - insuranceDiscountAmount`. Saving both `subtotal` and `total` and `insuranceDiscountAmount` is overkill - so decided to go with just `subtotal`. I think removing `insuranceDiscountAmount` is probably a good idea also. `insuranceDiscountRate` is also not needed - but "keeping for now".. (My new motto ? :( )
- Renamed `Transaction.total` -> `Transaction.subtotal`
- Added a `total` getter calculating the new total value
N/A
N/A
=> #2134 align total subtotal with desktop

src/actions/PaymentActions.js, src/database/DataTypes/PaymentType.js, src/database/DataTypes/Transaction.js, src/database/DataTypes/index.js, src/database/UIDatabase.js, src/database/schema.js, src/sync/incomingSyncUtils.js, src/sync/syncTranslators.js, src/widgets/PaymentSummary.js
Fixes #2140 
- Adds `PaymentType` to schema and sync
- Adds use of `PaymentType` object over `Options` in `PaymentSummary`
N/A
N/A
=> #2140 Payment types aligning with desktop

src/widgets/PageButton.js, src/widgets/PageButtonWithOnePress.js, src/widgets/Tabs/ItemSelect.js, src/widgets/Tabs/PrescriberSelect.js, src/widgets/Tabs/PrescriptionConfirmation.js, src/widgets/index.js
Fixes #2164 
Problem was pressing the button twice+. Can't just debounce, as the component is unmounted and collected, so the debounce functionality doesn't work as there is no reference to the previously invoked debounce, so for the cancel button, you need the one press functionality, which works well. Wouldn't work for the next tab buttons as you can go back to them constantly and the state doesn't reset.
N/A
N/A
=> #2164 cancelling throws

src/database/UIDatabase.js, src/widgets/modals/CashTransactionModal.js
Fixes #2162.
Fixes cash register reason filtering.
N/A.
=> #2162 fix cash register not filtering reasons

src/pages/dataTableUtilities/constants.js, src/pages/dataTableUtilities/getColumns.js, src/utilities/sortDataBy.js
Fixes #2162 
- Removed the type column
- Added rest of the columns except for comments to be sortable.
- Moved comment column to the end to be consistent with other pages
N/A
N/A
=> #2162 Add additional sortable columns

src/sync/incomingSyncUtils.js
Fixes #2183 
- Name visibility was being overridden for everyone, not just patients
- I think this only started being a problem recently - maybe the order of `[Name]` records and `[NameStoreJoin]` from the server swapped? Regardless it should be changed
N/A
=> #2183 Override visibility only when record is for a patient

src/sync/outgoingSyncUtils.js
Fixes #2195 
- Sync a clinicians store ID in outgoing sync
- Only sync out patients
N/A
N/A
=> #2195 Clinicians not syncing storeID

src/pages/dataTableUtilities/reducer/tableReducers.js
Fixes #2191.
FIxes cash register page sorting bug.
=> Fix cash register sorting after new transaction

src/sync/incomingSyncUtils.js
Fixes #2211.
Fixes indicator attribute incoming sync.
N/A.
=> #2211 fix indicator attribute incoming sync

src/database/DataTypes/Requisition.js, src/database/utilities/getIndicatorData.js
Fixes #2213.
Fixes response requisition indicator getters.
N/A.
=> #2213 fix incorrect customer requisition indicators

src/utilities/modules/dispensary/pay.js
Fixes #2219 
- Adds an extra parameter 
- Was a regression from https://github.com/openmsupply/mobile/pull/2187/files
- Confirming a prescription does not cause an error
N/A
=> #2219 Promise rejection on paymnet

src/database/DataTypes/Name.js, src/database/schema.js, src/localization/formInputStrings.json, src/utilities/formInputConfigs.js
Fixes #2227 
Added a toggle for male/female - a strictly non-pc implementation of gender, in line with the current mSupply option. Uses the boolean *female* field
Created the PR because I made the changes during UAT. feel free to discard this PR and implement it properly
Should really be a drop down with more options, this should do for now though.
=> #2227 add gender to patient registration

src/database/utilities/createRecord.js, src/utilities/modules/dispensary/pay.js
Fixes #2246 
- Correctly apply an items note to a batch
N/A
=> #2246 Correctly apply TransactionItem's note to TransactionBatch

src/database/utilities/createRecord.js, src/selectors/dispensary.js, src/utilities/modules/dispensary/pay.js
Fixes #2251 
- Corrected boolean for ascending
N/A
=> Add correct isAscending

src/database/utilities/createRecord.js, src/pages/dataTableUtilities/getColumns.js, src/reducers/InsuranceReducer.js, src/selectors/cashRegister.js, src/selectors/dispensary.js, src/utilities/modules/dispensary/pay.js
Fixes #2253 
- Correctly resets insurance policies when navigating to a prescription (ignore navigating away, doens't matter)
N/A
=> Add resetting of insurance

dev_scripts/upload.sh, src/localization/pageInfoStrings.json, src/pages/CashRegisterPage.js, src/pages/CustomerRequisitionPage.js, src/pages/dataTableUtilities/getPageInfoColumns.js, src/pages/dataTableUtilities/getPageInitialiser.js, src/selectors/cashRegister.js, src/sync/incomingSyncUtils.js, src/utilities/modules/dispensary/constants.js
Fixes #2232.
Makes mobile cash register behaviour consistent with desktop.
N/A.
=> #2232 cash register balance filter payment types

src/actions/SupplierCreditActions.js, src/localization/dispensingStrings.json, src/localization/tableStrings.json
Fixes #2218 
- Attempt #2!
- Pushing returns the count.. not the array.. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push :) heheehe.....
Where to start...........
=> #2218 SupplierCredit crash

src/database/UIDatabase.js, src/localization/tableStrings.json, src/pages/SupplierInvoicePage.js, src/pages/dataTableUtilities/constants.js, src/pages/dataTableUtilities/getColumns.js, src/pages/dataTableUtilities/getPageInitialiser.js, src/utilities/formatStatus.js, src/utilities/sortDataBy.js, src/widgets/DataTable/DataTableRow.js, src/widgets/DropdownRow.js
Fixes #2309
- SI's page now shows SC's also
- Added a `TYPE` column to differentiate
- Only shows finalised SC's (they're auto-finalised when creating in mobile)
- I don't like this implementation. The column is redundant.
- Need to add code to only use the `TYPE` column when using supplier credits (should they just be available to everyone...?)
- I think just having a `Supplier Credit` page is better
=> #2309 show scs in si list

src/widgets/PageButton.js
Fixes #2189 
- https://github.com/facebook/react-native/issues/24000
- Can't pass `null` to `backgroundColor` with RN & KitKat
N/A
=> #2189 Null background colour

src/sync/outgoingSyncUtils.js, src/widgets/modals/StocktakeBatchModal.js
Fixes #2273 
- Steps to reproduce the error:
1. Create a Stocktake with > 1 line.
2. Go to the batch editing of a line, and add a batch.
3. Edit the quantity of the batch.
4. Leave the Stocktake and Sync.
5. Go back to the Stocktake, and go to the batch you edited previously
6. ONLY edit the expiry date [NOTE: This cell saves on LOSING FOCUS]
7. Leave the Stocktake and go sync again.
Why:
- Used the wrong action for updating the `ExpiryDate`. All this did was make the `database.save()` method, use `database.save("TransactionBatch", ...)` rather than `database.save("StocktakeBatch", ...)`. 
- When `.save()` is called, we trigger the `SyncQueue` event handler for the pass parameters (In this instance, `recordType = "TransactionBatch`, and the actual record is the `StocktakeBatch`. 
- The …
=> #2273 Missing TransactionBatch when syncing

src/pages/dataTableUtilities/actions/cellActions.js
Fixes #2318 
- Adds the correct parameter to the `.save()`
*Setup*
1. Create a stocktake - add some batches if none
2. Sync to desktop
3. Edit a stocktake batch
4. Try to sync
N/A
=> #2318 Corrected countedQuantityEdit parameter

src/pages/dataTableUtilities/reducer/rowReducers.js
Fixes #2221 
- Checks if there is any selection before unsetting `hasSelection`
N/A
=> #2221 Correct hasSelection field

src/sync/incomingSyncUtils.js
Fixes #2330 
- Adds use of `databaseGetOrCreate` so that when there is no ID, null is returned
N/A
=> #2330 Use database getOrCreate

src/reducers/ModulesReducer.js
Fixes #2332 
- Display the `ModuleLayout` on the `MenuPage` only when there are buttons to display (Vaccines, dispensary, cashregister, dashboard)
N/A
N/A
=> #2332 Display MenuPage Grid only when theres buttons to show

src/pages/dataTableUtilities/getColumns.js, src/selectors/supplierCredit.js
Fixes #2333 
- Removed the item code column for a supplier credit modal opened from a particular item.
- Added the code into the title
N/A
N/A
=> #2333 Remove item code column for supplier credits

src/pages/dataTableUtilities/actions/cellActions.js, src/utilities/index.js, src/utilities/parsers/index.js, src/utilities/parsers/interfaceParsers.js
Fixes #2338 
- Ensures no input can exceed `999999999999`
This method name is BAD - any ideas are welcome
=> #2338 Entering infinity

src/database/DataTypes/Prescriber.js, src/sync/incomingSyncUtils.js, src/sync/outgoingSyncUtils.js
Fixes #2339 
- Adds `fromThisStore` to `Prescriber`
- Disallows outgoing syncing of `Prescribers` from other stores
- Thought this was a better overall solution than the one described in the issue
N/A
N/A
=> #2339 store id to prescriber

src/sync/outgoingSyncUtils.js
Fixes #2345.
Adds `amount_outstanding` to outgoing sync.
Following desktop behaviour, the `payment` and `receipt` transactions always have `amount_outstanding == 0`.
=> #2345 add amount_outstanding to transaction outgoing sync

src/reducers/ModulesReducer.js
Fixes #2355.
Disables cash register if no payment types defined.
Possibly needed for prescription functionality also?
=> #2355 disable cash register if no payment types defined

src/sync/incomingSyncUtils.js
Fixes #2360 
- Silently ignores any record type which isn't supported by mobile earlier in the call chain.
- Does get ignored in `createOrUpdateRecord` but not in `deleteRecords` or `mergeRecords`!
N/A
=> #2360 Silently ignoring record types which can't be translated

src/database/DataTypes/Prescriber.js, src/database/utilities/createRecord.js, src/pages/DispensingPage.js, src/selectors/prescriber.js, src/sync/incomingSyncUtils.js, src/sync/outgoingSyncUtils.js, src/utilities/formInputConfigs.js, src/widgets/FormControl.js, src/widgets/FormInputs/FormDateInput.js, src/widgets/FormInputs/FormDropdown.js, src/widgets/FormInputs/FormSlider.js, src/widgets/FormInputs/FormToggle.js, src/widgets/FormInputs/FromTextInput.js, src/widgets/Slider.js, src/widgets/ToggleBar/ToggleBar.js, src/widgets/index.js
Fixes #2340 
- Adds `fromThisStore` to `Prescriber` following the same pattern as `NameStoreJoin`
- Disables editing of a prescriber if the prescriber is not `fromThisStore`
- In the unlikely event of trying to sync a prescriber out: don't!
N/A
=> #2340 prescribers editable only from this store

src/database/DataTypes/Name.js, src/pages/DispensingPage.js, src/selectors/patient.js, src/sync/incomingSyncUtils.js, src/widgets/FormInputs/FormToggle.js, src/widgets/ToggleBar/ToggleBar.js
Fixes #2341 
- Makes patients editable only if theyre from the mobile store.
- Rejects any patients not from the mobile store in incoming sync.
N/A
=> #2341 only allow editing of patients from this store

src/database/DataTypes/Currency.js, src/database/DataTypes/index.js, src/database/schema.js, src/database/utilities/createRecord.js, src/sync/incomingSyncUtils.js, src/sync/outgoingSyncUtils.js, src/sync/syncTranslators.js
Fixes #2375 
- Add currency to sync to access the default currency. needed for transactions aswell
- Adds `charge code`, `barcode`, `currency_ID` and address' to outgoing sync
N/A
=> #2375 Patient creation diff

src/sync/outgoingSyncUtils.js
Fixes #2377 
- Adds `entry_time` and `Date_order_written` to `outgoingSyncUtils`
- ignoring colour 🤷‍♂ 
N/A
=> Add missing entry time and date order written fields to outgoing sync

src/localization/dispensingStrings.json, src/sync/outgoingSyncUtils.js, src/utilities/modules/dispensary/pay.js
Fixes #2378 
- Adds `currency_id` and `currency_rate` to transactions when syncing - the default for the data file.
- Adds a comment to the receipt for a prescription
N/A
=> #2378 missing rc fields

src/database/utilities/createRecord.js, src/sync/outgoingSyncUtils.js
Fixes #2379 
- Removes the linked transaction from the CC/CI's to the receipt - doesn't happen on desktop
- Adds the payment type to the CC/CI offsets
*Cash in transaction*
*Cash out transaction*
N/A
=> #2379 cash transaction missing fields

src/localization/utilities.js
Fixes #2274 
- Bit of a tricky one - only crashed on an APK
- `moment` does a require internally which is async. When using RN, it does doesn't bubble correctly if the file isn't found and just throws an error instead of handling it correctly. I.e. tries to require `'gb'` instead of `'en-nz'` - instead of being caught and discarding (intended behaviour), the error isn't caught and crashes the app!
The other languages we support (Kiribati, Tetum, Laos) don't seem to be in the locales supported by `moment` which is sucks a bit - https://github.com/moment/moment/tree/develop/src/locale  however maybe I'm wrong! Also would be cool to contribute !
=> #2274 Corrected locale support for languages

src/database/DataTypes/Name.js, src/database/DataTypes/Transaction.js, src/database/utilities/createRecord.js, src/sync/incomingSyncUtils.js, src/sync/outgoingSyncUtils.js, src/utilities/modules/dispensary/pay.js
Fixes #2395 
- Main change here is that we do no longer make customer credit lines when using credit.
- There was also a change on desktop, where cancelled customer invoices now become sources of credits. So have made the needed changes to handle that case.
- Also updated comments - hoping it's clearer
*Note: Does not address #2104 where I hope to do some refactoring on this method - just makes the logic 'correct'*
*Correct behaviour for paying for a prescription is that there is a receipt where the total is equal to any amount paid (non-credit), with a receipt line for any non-credit amount paid. The receipt line links to the prescription. Then, there is a receipt line for the total amount of credit amount paid - this links to the prescription. Then, for any credit source used, another …
=> #2395 Stop making offset CC lines

src/database/DataTypes/TransactionBatch.js, src/sync/SyncQueue.js
Fixes #2414 
- Just saves a `TransactionBatch` after editing..!
N/A
=> #2414 Save a TransactionBatch after editing

src/globalStyles/buttonStyles.js
Fixes #2424 
- Adds white text on disabled buttons so you can actually read them
N/A
=> #2424 White text on disabled buttons

src/database/utilities/createRecord.js
Fixes #2429 
- Correctly adds the field being checked to see if a patient is a home store
N/A
=> Add correct fields to patient creation

src/pages/dataTableUtilities/getPageInitialiser.js
Fixes #2440 
- Removed the columns in a previous PR accidentally. This adds them back!
N/A
=> #2440 Correct fetching of columns

dev_scripts/translation.js
Fixes #2409
Added comments in file `dev_scripts\translation.js` of example to import and export translations 
@joshxg 
Is this what you had in mind? Otherwise please let me know 😄
=> Add comments of example to import/export

src/widgets/PrescriptionInfo.js, src/widgets/SimpleLabel.js
Fixes #2467 
Reduced `numberOfLines` from 2 to 1, so now the patient's name is not longer taken 2 lines when too long. Anyway, the ellipse mode is still active and will act in case we are in presence of a name that is larger than the No. de chars allowed per line.
Example:
N/A.
=> #2467 Reduce 'numberOfLines' to avoid text overlapping

src/widgets/modals/DataTablePageModal.js, src/widgets/modals/ModalContainer.js
Fixes #2478 
Enabled specification of number of lines in a modal title and set this based on the number of line breaks in the title.
=> multiline modal title

src/utilities/formInputConfigs.js, src/widgets/FormControl.js
Fixes #2433.
This prevents policy numbers from being edited after saved, which is a constraint currently enforced on desktop.
Still to do:
- Lock down provider and policy type. 
- Prevent duplicate policy numbers.
=> #2433 fix insurance policy number editing

src/utilities/formInputConfigs.js, src/widgets/FormControl.js, src/widgets/FormInputs/FormDropdown.js
Fixes #2456.
Branched off #2433.
Brings mobile in-line with desktop by disabling editing of provider for saved insurance policies.
Still to do:
- Lock down policy type.
- Prevent duplicate policy numbers.
=> #2456 fix insurance policy provider editing

src/actions/InsuranceActions.js
Fixes #2471.
Update insurance policy `update` thunk to also dispatch `select` action, ensuring prescription record is updated with new policy. 
- Create a new prescription.
- Create a new insurance policy.
- Save the prescription without updating insurance policy dropdown.
- Sync to desktop.
- Open the synced prescription transaction in desktop. 
- Navigate to the `"Payment"` tab.
N/A.
=> #2471 fix prescription record not saving new insurance policy

src/database/DataTypes/Stocktake.js
Fixes #2448.
Prevents creating a new `StocktakeItem` for an `undefined` item.
- Not completely sure how best to replicate this without using corrupted data. Suggest a quick regression test of existing stocktake logic.
N/A.
=> #2448 fix error on creating stocktake item for undefined item

src/pages/dataTableUtilities/getPageInfoColumns.js, src/pages/dataTableUtilities/getPageInitialiser.js
Fixes #2490 
Added program name to the top row of program based stocktakes.
I didn't want to add `STOCKTAKE_EDITOR_WITH_PROGRAM` and `STOCKTAKE_EDITOR_WITH_REASONS_WITH_PROGRAM` as that would give us four variants for the stocktake edit page. Instead I've added the parameter to allow insertion of the program name. Feel free to rip apart this approach.. and if you have better options I'd love to hear them.
=> #2490 show program name

src/sync/outgoingSyncUtils.js
Fixes #2501.
Adds `is_edited` to `stocktakeBatch` outgoing sync.
- Using mobile, create a new stocktake.
- Enter a quantity different than its snapshot quantity. 
- Sync to desktop.
- Open the stocktake in desktop.
N/A.
=> #2501 add is_edited field to outgoing stocktake batch sync

src/localization/navStrings.json, src/widgets/modals/ModalContainer.js
Fixes #2476 
Centred. Took the issue on so that I could fix a French translation - we had the `Supplier Requisitions` button showing `Invoices requisitions`
=> #2476 modal titles not centred

src/selectors/insurance.js, src/selectors/patient.js, src/selectors/payment.js, src/widgets/PaymentSummary.js
Fixes #2523.
- Update insurance policy selectors to display if policies active or not. 
- Do not apply discount rate for inactive policies.
N/A.
=> #2523 prevent applying inactive policies

src/widgets/modalChildren/SupplierCredit.js
Fixes #2525.
Just a small tweak to the `FlexRow` at the bottom of `SupplierCredit` component.
- Make a new supplier invoice with a large number of item batches (>= 15).
- Add a quantity to each item batch.
- Finalise the invoice.
- Click `"New supplier credit"`.
N/A.
=> #2525 reduce size of supplier credit bottom flex row component

src/localization/dispensingStrings.json, src/localization/modalStrings.json, src/localization/navStrings.json
Fixes #2549 
Just a few translations.
After it happened the first time, I couldn't recreate the wizard non-translating. Perhaps it memoed while I was logged in with an English user? 
Check that the following changes have been made:
=> translations

src/widgets/modals/DemoUserModal.js
Fixes #2546.
Fixes demo store `ModalContainer` prop `isVisible`. Was preventing users from entering details to request demo store.
N/A.
=> #2546 fix demo store error message

src/widgets/modals/CashTransactionModal.js
Fixes #2561.
Quick fix for modal button UI bug.
N/A.
=> #2561 hide cash transaction confirm button on open modal

src/widgets/modals/ModalContainer.js
Fixes #2554.
Branched from #2561.
Just a small style change to centre modal titles.
N/A.
=> #2554 fix modal strings not centred

src/widgets/modals/CashTransactionModal.js
Fixes #2556 
Branched off #2556 
Small style adjustment to increase vertical space between toggle and title.
N/A.
=> #2556 fix cash transaction toggle margin

src/utilities/dailyUsage.js
Fixes #2572.
Minor fix to lookback date conditional logic. 
The correct lookback logic as as follows:
- If the enforce lookback period preference is enabled, monthly consumption is always calculated as far back as that period (e.g. if the lookback period is six months, even if an item was first used last month, the consumption will be calculated as if the usage since then was actually over six months of dispensing).
- Otherwise, monthly consumption is calculated based on the most recent of the lookback period or the date when the item was first added (so that if an item has only recently been added, it's consumption will not be underrepresented). 
N/A.
=> #2572 fix incorrect daily usage conditional

src/utilities/dailyUsage.js, src/widgets/modals/CashTransactionModal.js, src/widgets/modals/ModalContainer.js
Release candidate for v4.0.3.
- Modal strings not centred. #2556 
- Cash transaction confirm button overlap. #2562.
- Cash transaction toggle too close to modal text. #2568.
- Incorrect conditional in lookback period logic. #2572.
See v4.0.X release discussion for more info: #2444.
=> Release v4.0.3

src/navigation/RootNavigator.js, src/navigation/utilities.js
@mark-prins 
Was going to merge your PR but thought I'd have another quick look and realized this was a pretty nice fix to be able to navigate back?
So when you navigate back or click cancel, the stack navigator will go back, rather than the tab navigator which was the previous behaviour
=> Add use of stack action over goBack

package.json, src/globalStyles/pageStyles.js, src/navigation/RootNavigator.js, src/navigation/utilities.js, src/pages/PrescriptionPage.js, src/widgets/TabNavigator.js, src/widgets/Tabs/PrescriberSelect.js, src/widgets/Wizard.js, yarn.lock
Fixes #2537 
Replaces the call to `createAppContainer` with the declarative `Tab.Navigator`
This is working for the tabbing - but there is a subsequent problem with the `PrescriptionPage` which is now not receiving the `transaction` prop.
Have also modified the shape of the `tabs` supplied to the `TabNavigator` to bring in the title and pass in a name which is required by the `Tab.Screen` component.
No, I think that's about it.
=> replace createAppContainer

src/actions/DispensaryActions.js, src/localization/dispensingStrings.json, src/pages/DispensingPage.js, src/reducers/DispensaryReducer.js, src/selectors/dispensary.js, src/widgets/modals/DispensaryLookup.js, src/widgets/modals/index.js
Fixes #2540.
Branches off #2567. 
Just a rough start to get things going. UI looks like this:
Still to do:
- Add modal: #2541.
- Add lookup logic: #2542.
=> #2540 add patient api ui

src/pages/DispensingPage.js, src/widgets/modals/SearchForm.js
Fixes #2609.
Branched off #2612.
Adds basic search form for retrieving and displaying patient/prescriber records. 
Uses a combo of `FormControl` and `FlatList` to provide a search interface and list for rendering results. Still just minimal functionality and UI, but gives a good idea of the basic design.
N/A.
N/A.
=> #2609 add patient api search form

src/utilities/network/lookupApi.js
Fixes #2616.
Branched from #2612.
Just a bunch of helpers for patient API HTTP requests/responses.
Main methods are `queryPatientApi`, `queryPrescriberApi` which:
1. Transform object parameters (e.g. `completedForm`) into requests to the API endpoint.
2. Queries the server API endpoint.
3. Processes the response and returns an array of objects in a format suitable for rendering as a list.
N/A.
These methods are currently called directly from the `SearchForm` component. This is mostly for convenience, idea is to update this soonish such that API calls are only performed within dedicated actions/thunks.
=> #2616 add lookup api network helpers

src/localization/pageInfoStrings.json, src/pages/dataTableUtilities/getPageInfoColumns.js
Fixes #2590 
- Adds page info rows for supplier requisitions and breach modal
N/A
N/A
=> #2590 vaccine pageinfo rows [B1]

src/database/utilities/createRecord.js
Fixes #2603
- Adds two `createRecord` cases for `LocationMovement` and `VaccineVialMonitorStatus`
N/A
N/A
=> #2603 createLocationMovement and createVvmStatusLog cases [D11]

src/database/DataTypes/Item.js, src/database/DataTypes/ItemBatch.js, src/database/DataTypes/Location.js, src/database/DataTypes/Stocktake.js, src/database/DataTypes/StocktakeBatch.js, src/database/DataTypes/StocktakeItem.js, src/database/DataTypes/TemperatureBreach.js, src/database/DataTypes/Transaction.js, src/database/DataTypes/TransactionBatch.js, src/database/DataTypes/TransactionItem.js, src/database/utilities/createRecord.js, src/localization/modalStrings.json
Fixes #2579 
- Adds `Item` methods!
N/A
- Don't like the use of reduce but since this should always be a pretty small amount of transactions (since the most recent requisition, so either monthly - or if not ordering monthly, should probably have a small amount of transactions), it should be ok. Would be possible to just use `UIDatabase` but I think leaving it like this and seeing if there is a performance problem later is the better decision
- I think it might be better to use only finalised requisitions however the last implementation didn't, so have left it
=> #2579 Item methods [D4]

src/database/DataTypes/Item.js, src/database/DataTypes/ItemBatch.js, src/database/DataTypes/Location.js, src/database/DataTypes/Sensor.js, src/database/DataTypes/Stocktake.js, src/database/DataTypes/StocktakeBatch.js, src/database/DataTypes/StocktakeItem.js, src/database/DataTypes/TemperatureBreach.js, src/database/DataTypes/Transaction.js, src/database/DataTypes/TransactionBatch.js, src/database/DataTypes/TransactionItem.js, src/database/utilities/createRecord.js, src/localization/modalStrings.json
Fixes #2580 
- Adds methods to call the physical bluetooth sensor
N/A
- Have tested all of these methods and they do work.
- The previous methods were a little more intense, having try catches and updating the database etc. I think that is better left to the callers (which will be redux thunks), which we can then handle all of the other logic there, which I think is a far better place to do it
- In regards to the manufacturer id and commands: I think a discussion might need to be had to the best way to handle this (also not looking to use anything other than blue maestro at the moment, so possibly just a discussion on ensuring this is all in a way that can be iterated on in the future), so I didn't want to do anything here. I think it might be best to use a `manufacturerID` field and then …
=> #2580 Sensor native module methods [D3]

src/actions/TemperatureSyncActions.js, src/database/DataTypes/Sensor.js, src/database/DataTypes/TemperatureBreach.js, src/database/DataTypes/TemperatureBreachConfiguration.js, src/database/utilities/createRecord.js, src/globalStyles/buttonStyles.js, src/localization/syncStrings.json, src/mSupplyMobileApp.js, src/reducers/TemperatureSyncReducer.js, src/reducers/index.js, src/selectors/temperatureSync.js, src/utilities/chunk.js, src/utilities/constants.js, src/utilities/index.js, src/widgets/modalChildren/TemperatureSync.js
Fixes #2638 
- Adds `TemperatureBreach.willContinueBreach` method : This will be used when creating a `TemperatureLog` - if the `Location` is currently in a breach, can simply call this with the created `TemperatureLog` to check if the breach should continue.
- Adds `TemperatureBreachConfiguration.createBreach` method : currently this will be used on a `TemperatureLog` where the current location is not in breach. Couple q's on opinions below!
N/A
The config `createBreach` method could be broken up into three methods:
```
`temperatureWithinBreachRange = (temperatureLog) => *checks if temperature within breach temperature range*`
`temperatureOfProximalLogsWithinBreachRange = (temperatureLog) => *checks if proximal logs duration and are all in the breach temperature range*
`createBreach = …
```
=> #2638 additional breach methods

src/database/utilities/createRecord.js, src/database/utilities/index.js, src/database/utilities/parsers.js, src/sync/incomingSyncUtils.js, src/utilities/network/lookupApi.js
Fixes #2664
Updated `createRecord` cases and reduced network API creators to being wrappers over these cases. Tricky to find an optional solution that handles all use cases, but think this is a pretty decent compromise which will look OK once methods moved into thunks rather than utility methods.
Initial thinking was to consolidate all creation logic (including incoming sync), but after spending a bit of time on this, realised its potentially a bit of a bigger job than thought and has quite a lot of surface area for regressions. Thinking is its probably going to be best to do this in parts rather than trying to refactor everything in one go. 
N/A (tests in feature PR).
N/A.
=> #2664 extract record creation logic

src/utilities/network/lookupApi.js
Fixes #2651.
Adds authorization header to patient and prescriber API requests.
Note: to view requests, breakpoints can be placed in `routes_api_v4_patient` and `routes_api_v4_prescriber` (examine `$obRouteInfo.headers`).
N/A.
=> #2651 add authorization header to lookup requests

src/widgets/modals/SearchForm.js
Fixes #2658.
Add logic to handle invalid/default dates.
N/A.
=> #2658 add lookup list date null check logic

src/widgets/FormControl.js
Fixes #2676.
Fixes `formControl` `onCancel` callback.
N/A.
=> #2676 fix form control cancel callback

src/sync/lookupApiUtils.js, src/widgets/modals/SearchForm.js
Fixes #2681.
Adds logic for handling:
- Connection errors.
- Timeout errors.
- Authentication errors.
- No matching records.
Basically just a spinner and a confirm modal. Not the nicest from a UI point of a view, but does the job!
Replicates a bit of sync, epic still has an issue for updating sync constants so I suggest using that to modularise some of the shared lookup/sync logic.
N/A.
=> #2681 update lookup response logic

src/sync/outgoingSyncUtils.js
Fixes #2494.
Not 100% on this one, so feedback appreciated!
Updates outgiong sync logic for prescriptions:
- Only sync out prescription `Transaction` (`[transact]`) records if finalised.
- Only sync out prescription `TransactionBatch` (`[trans_line]`) records if prescription is finalised.
From issue:
With the usesPaymentModule and usesDispensaryModule turned on:
1. Create a prescription on mobile
2. Add items that have a cost, but don't make a payment for them
3. Click ok.
4. Sync to desktop
5. Make a new prescription for the same patient
6. Click history - the goods from the prescription in Step 1 will show
7. Search for prescriptions on desktop - the confirmed invoice will show up initially
N/A.
=> #2494 sync only finalised prescriptions

src/selectors/modules.js, src/selectors/pages.js, src/widgets/modals/StocktakeBatchModal.js
Fixes #2509.
Really should have made a new issue, but a bit of time pressure on `v5`.
- Follows up on #2524 by adding column hiding logic to stocktake batches.
Initial idea was to migrate this back to a user pref, but have bumped that to desktop `v11`.
For next steps, see desktop and mobile PRs: #2700 and https://github.com/sussol/msupply/pull/6023.
=> #2509 add hide snapshot pref logic to stocktake batch modal

src/database/DataTypes/Sensor.js, src/localization/generalStrings.json, src/localization/navStrings.json, src/localization/tableStrings.json, src/localization/vaccineStrings.json, src/navigation/Navigator.js, src/navigation/actions.js, src/navigation/constants.js, src/pages/VaccineAdminPage.js, src/pages/VaccinePage.js, src/pages/dataTableUtilities/actions/cellActions.js, src/pages/dataTableUtilities/actions/constants.js, src/pages/dataTableUtilities/actions/tableActions.js, src/pages/dataTableUtilities/constants.js, src/pages/dataTableUtilities/getColumns.js, src/pages/dataTableUtilities/getPageDispatchers.js, src/pages/dataTableUtilities/getPageInitialiser.js, src/pages/dataTableUtilities/reducer/tableReducers.js, src/pages/index.js, src/selectors/fridge.js, src/utilities/sortDataBy.js
Fixes #2596 
- Adds an admin page for vaccines to be able to edit locations and sensors, as well as scan for new sensors (next PR).
- This PR adds basic functionality (stopped to PR to have it be a bit smaller, so not fully complete).
- This is just adding a table with a toggle for sensors/locations, where the table will be editable.
N/A
- Next PR will include: editable sensors. 
- A button to create a `Location`. [Right of the search bar]
- A button to scan for new sensors. [Right of the search bar]
- Conditional logic to only allow admin access with admin preference on.
=> #2596 VacicneModuleAdmin page

src/actions/FormActions.js, src/reducers/FormReducer.js, src/widgets/FormControl.js
Fixes #2717,
Fixes the insurance confirmation modal popup not cancelling.
N/A.
=> #2717 fix confirm modal cancellation

src/utilities/modules/dispensary/pay.js, src/widgets/Tabs/PrescriptionConfirmation.js
Fixes #2720.
Cash register filters by payment types, so receipts created from prescriptions were not displaying.
Wondering if it would be worth adding an `"All"` option to the cash register dropdown for filtering by payment type?
=> #2720 add payment types to prescription receipts

src/selectors/patient.js
Fixes #2721.
Patient `isEditable` was incorrectly defaulting to `false`, locking the form for making a new patient.
N/A.
=> #2721 fix new patient form defaulting to not editable

src/hooks/useFetch.js, src/widgets/modals/SearchForm.js
Fixes #2755.
- Fixes error code typo preventing error modal on no matching records.
- Fixes data not reset on error.
Just a quick fix, reminded me of a lot of stuff I don't like about how I've done the current form/hook... but forcing myself to not do any refactoring until after release :cry:.
=> #2755 fix lookup form buggy behaviour on no matching records

src/localization/formInputStrings.json, src/sync/lookupApiUtils.js, src/utilities/formInputConfigs.js
Fixes #2749.
Simplifies patient lookup search by policy functionality (replaces person and family number with single policy field). 
NOTE: does not include wildcard changes (#2776), so make sure to manually prepend/append `@` wildcard to match policy numbers "greedily".
N/A.
=> #2749 update patient search by policy

src/actions/FinaliseActions.js, src/navigation/actions.js, src/reducers/FinaliseReducer.js
Fixes #2780.
- Adds `resetFinaliseItem` to `FinaliseActions`.
- Dispatches `resetFinaliseItem` on `goBack` from a finalisable page. 
Not sure if piggybacking onto the `goBack` action is the right way to do this, but seems consistent with other navigation actions. Might need to add some checks to ensure the item is only reset when navigating to `CustomerInvoicesPage`, etc?
=> #2780 reset finalise modal item on go back navigation

src/sync/lookupApiUtils.js
Fixes #2713.
Wraps all query parameters in "wildcard" symbol (`"@"`). Trade-off of more records being returned, but easier to find matches and closer to existing desktop search functionality.
This PR only ensures that all records which should be matched are matched, another PR coming soon to ensure that no records are matched which shouldn't be matched :rofl:.
=> #2713 add wildcard to lookup query parameters

src/navigation/utilities.js
Fixes #2752.
Adds truthy return to navigation `backHander` to prevent event being double handled.
NOTE: when testing back handling, make sure to include cases where navigation stack has more than one page (e.g. navigate to customer invoices -> customer invoice).
N/A.
=> #2752 fix hardware back button being double handled

src/pages/CustomerRequisitionPage.js
Fixes #2758.
Fixes error caused by missing `useLoadingIndicator` hook.
N/A.
=> #2758 add loading indicator hook to customer requisition page

src/sync/PostSyncProcessor.js
Fixes #2756.
Auto-finalises customer credit on incoming sync.
- Create a supplier credit for mobile store.
- Manually sync mobile.
- Navigate to customer invoices and toggle to `"Past"`.
Not too sure about existing finalisation logic, so played it safe and just replicated the existing logic for manually finalising a customer credit.
=> #2756 update post sync to ensure all incoming customer credits are finalised

src/pages/dataTableUtilities/getPageInfoColumns.js, src/widgets/DataTable/DataTableRow.js, src/widgets/modals/StocktakeBatchModal.js
Fixes #2779.
Not the most elegant fix, but gets the job done. 
Might need to revist `DataTableRow` disabling logic (maybe I've added workarounds where should be using `dataState`?)
=> #2779 fix stocktake batch icon

src/pages/dataTableUtilities/getColumns.js, src/utilities/sortDataBy.js
Fixes #2773.
Updates program columns to be sortable.
N/A.
=> #2773 fix program column not sortable

src/database/utilities/createRecord.js, src/selectors/dispensary.js
Fixes #2747.
Fixes date inconsistencies when adding patients via lookup.
N/A.
=> #2747 fix patient lookup incorrect date of birth

src/navigation/utilities.js, src/pages/dataTableUtilities/getPageInitialiser.js, src/reducers/PagesReducer.js, src/widgets/BackButton.js
Fixes #2735.
Prescription page shape is shallower than, e.g. customer invoice, so `pageObject` was not being passed to `getTitle`
May be that better option is to update the prescription page shape to be consistent with the other pages? Would require adding to initialisers, which I felt might be a bit OTT. Open to suggestions!
=> #2735 fix prescription undefined title

src/sync/PostSyncProcessor.js
Fixes #2801.
Added missing parameter to customer credit finalisation function... took me forever to trace this!
- To sync a customer credit to mobile, create a supplier credit for the mobile store on desktop. 
- Customer credits can be viewed in customer invoices (should be finalised, so will have to toggle to `"Past"`.
N/A.
=> #2801 add missing parameter to post sync credit finalisation

src/pages/SupplierRequisitionPage.js
Fixes #2802.
- `onApplyMasterLists` parameters correctly ordered.
N/A.
=> #2802 fix supplier requisition apply master list parameters

src/pages/MenuPage.js
Fixes #2764
- Adds `isFocused` hook to `MenuPage`, triggers rerender on focus.
- Returns `null` if not focused, smoother re-render on back navigation.
N/A.
=> #2764 refresh menu page on navigation focus

src/globalStyles/toggleBarStyles.js, src/widgets/modalChildren/ToggleSelector.js
Fixes #2805.
- Fixes months of stock overriding default toggle styles.
- Small increase in months of stock toggle font size.
N/A.
=> #2805 fix months of stock toggle bar styles

src/database/utilities/parsers.js
Fixes #2800.
One last one before `rc3` :tada:!
Fix `Invalid date` error caused by `parseDate` missing case for default `ISO GMT` date.
Caught by bugsnag, so no test case to replicate here! 
N/A.
=> #2800 fix ISO GMT date parsing

src/globalStyles/toggleBarStyles.js, src/widgets/modalChildren/ToggleSelector.js
Fixes #2826.
Reverts font size changes to toggle bar styles (see #2807).
N/A.
=> #2825 revert increase default toggle font size

src/sync/lookupApiUtils.js
Fixes #2817.
Lookup queries for more than one field were returning no records due to typo in query string `"&"` constant.
N/A.
=> #2817 fix missing lookup query string separator

src/widgets/SyncState.js
Fixes #2666.
Fixes last sync date displaying as `null`.
N/A.
=> #2666 fix null last sync

src/navigation/constants.js, src/navigation/utilities.js, src/pages/dataTableUtilities/getPageInfoColumns.js
Fixes #2821.
Fixes supplier credit page title/page info.
N/A.
=> #2821 fix supplier credit page info

src/pages/dataTableUtilities/getColumns.js
Fixes #2822.
Minor tweak to `BATCH_NAME` column config.
N/A.
=> #2822 update supplier invoice batch column

src/pages/dataTableUtilities/reducer/tableReducers.js
Fixes #2825.
Indicators reducer was calling a realm method on a plain JS array (throws an error on develop, but just silently fails on build).
N/A.
=> #2825 fix error on updating indicator selection

src/sync/incomingSyncUtils.js
Fixes #2841.
Adds support for GMT timezone offset to date parsing logic.
N/A.
=> #2841 update date parsing to handle timezone offsets (v3)

src/sync/incomingSyncUtils.js
Fixes #2842.
Adds support for GMT timezone offset to date parsing logic.
N/A.
=> #2842 update date parsing to handle timezone offsets (v4)

src/sync/outgoingSyncUtils.js
Fixes #2851.
Hotfix for sync throwing error on name merge.
- Create two names on desktop (customers or suppliers).
- Associate each name with a master list.
- Sync to mobile.
- Merge the two names.
- Sync to mobile (if needed press manual sync twice, ensure no records are waiting).
N/A.
=> #2851 fix sync error on name merge

src/sync/Synchroniser.js
Fixes #2845.
Hotfix for `v5.0.2`.
- Get version header desktop structure [here](https://github.com/sussol/msupply/pull/6230).
Note: log `parseDate` inputs and check for the timezone offset, e.g. `"Z"` (not sure how this can be tested in production!)
N/A.
=> #2845 add mobile version header

src/actions/TemperatureSyncActions.js, src/database/DataTypes/Sensor.js, src/database/utilities/createRecord.js, src/pages/dataTableUtilities/reducer/tableReducers.js, src/sync/incomingSyncUtils.js, src/sync/outgoingSyncUtils.js
Fixes #2742 
- Auto applies the lowest level VVM status to item batches when created.
- Auto applies the underlying item batches current vvm status to a `TransactionBatch` when created.
- Auto applies the underlying item batches current vvm status to a `StocktakeBatch` when created.
N/A
N/A
=> #2742 auto apply vvm status to batch

src/actions/TemperatureSyncActions.js, src/selectors/fridge.js
Fixes #?
- extracts the saving of sensorlogs and only saves thema fter having reset a sensor. This is because if we don't reset the sensor, the logs aren't cleared so next time you read it you would have double the sensor logs.
- This is pretty tricky and there's no real solution to being able to do this atomically without having timestamps on the logs on the sensor, so going with this for now (for example, what if you reset the sensor and dont write the logs. So ok, switch around the reset/write - what if you write before resetting...).
- The other option is to try and wrap this all in a `write`, however that means if its running in the background you might have issues with starting multiple writes with normal user tasks
N/A
N/A
=> #2767 single transaction sensor logs

src/actions/FridgeActions.js, src/actions/TemperatureSyncActions.js, src/hooks/useDatePicker.js, src/localization/generalStrings.json, src/localization/vaccineStrings.json, src/reducers/FridgeReducer.js, src/selectors/fridge.js, src/widgets/DatePickerButton.js, src/widgets/DateRangeSelector.js, src/widgets/FridgeDisplay.js, src/widgets/FridgeDisplayInfo.js, src/widgets/icons.js
Fixes #2739 
- Adds date pickers to choose from a range of dates. Have tested with 10,000 logs and the performance is fine (7 months worth).
- Fixed the bug when the SVG has no data to render
N/A
I wonder if rather than having a list of fridges a drop down would be nicer:
=> #2739 date pickers on charts

src/hooks/useDatePicker.js, src/reducers/FridgeReducer.js
Fixes #2882 
- My solution in the issue I think was flawed. Instead, changed it to make the custom hook just pass the timestamp, and made the alterations to the date where I needed it for this particular use case.
- the fromDate is from the start of the day, where as the toDate is the end of the day
N/A
Not 100% on dates, so if there's a better way more then happy to hear it!
=> #2882 datepicker returning times

src/actions/InsuranceActions.js
Fixes #2916.
Fixes insurance provider not being created for patients added via lookup API.
=> #2916 fix patient lookup insurance provider logic

src/reducers/FormReducer.js, src/utilities/formInputConfigs.js
Fixes #2918.
Update family policy number to be optional.
N/A.
=> #2918 update insurance policy number config

src/localization/validationStrings.json
Fixes #2974.
Adds Burmese/Myanmar validation string translations.
N/A.
=> #2974 add myanmar validation string translations

src/localization/authStrings.json
Fixes #2950,
Adds Burmese/Myanmar auth string translations.
Not sure how to go about this, as don't think we have anyone on team who can speak Burmese!
Instead of writing exhaustive tests for all translations, might be easier to do a test run with a user?
N/A.
=> #2950 add myanmar auth string translations

src/sync/outgoingSyncUtils.js
Fixes #2946.
Updates outgoing date string format to ISO + UTC.
N/A.
=> #2946 update outgoing sync date format

src/pages/DispensingPage.js, src/sync/incomingSyncUtils.js
Fixes #2943
- Removed statement `if (isPatient && !thisStoresPatient) break` that wasn't allowing the new incoming sync record proceed to change the Patient home store (aka supplyingStoreId).
- Added the hook to refresh the Dispensary page after an incoming sync record to change a `Name` (Patient) is processed.  
- Patient created on Mobile:
- Patient created on Central server:
- Dispensary refreshing after receiving `Name` sync records. Which includes: Changes on visible Customers, Suppliers, Patients, Stores.
- Patient with different home store incoming syncing. Now that the break was removed.
=> #2943 fix patient not editable after home store is transferred

src/localization/pageInfoStrings.json
Fixes #2968.
Adds Burmese/Myanmar page info string translations.
N/A.
=> #2968 add myanmar page info string translations

src/widgets/FormInputs/FormDateInput.js
Fixes #2957.
Minor change, calls `onUpdate` callback after submitting date input. Ensures submitted values are formatted consistently and prevents error on submitting date without date picker.
- Create a new patient. Add a first and last name and date of birth. Press date of birth input field and press enter (triggers `onSubmit` callback).
@joshxg knows this functionality best, so would be good to get some feedback just to check that this won't cause any unexpected side-effects?
=> #2957 add formatting to date input on submit callback

src/sync/outgoingSyncUtils.js
Fixes #2989
Adds `female` field to outgoing sync for `Name` records.
Only concern is whether this could effect non-patient name records. I'm guessing the field is irrelevant for those records, so not really an issue either way?
=> #5989 add patient gender to outgoing sync

src/actions/InsuranceActions.js, src/actions/PaymentActions.js, src/reducers/PaymentReducer.js, src/selectors/insurance.js, src/selectors/payment.js, src/widgets/PaymentSummary.js, src/widgets/Slider.js
Fixes #2994.
Fixes a few errors with insurance rate, including a few redux changes to make payment and insurance logic a bit clearer. 
Depending on turn-around, this will be the last PR for `v5.1.0` or a patch `v5.1.1` (planning to release `v5.1.0` this arvo).
=> #2994 fix payment summary discount rate

src/database/utilities/deleteRecord.js, src/sync/incomingSyncUtils.js
Fixes #2991.
Adds `Prescriber` merge logic. 
- Create two prescribers (`prescriber_a` and `prescriber_b`) on a non-local store.
- Make both prescribers visible on mobile store using lookup API.
- Create a prescription associated with `prescriber_b` on mobile.
- Merge `prescriber_b` into `prescriber_a`.
N/A.
=> #2991 add prescriber merge logic

src/database/DataTypes/Transaction.js, src/sync/SyncDatabase.js, src/sync/SyncQueue.js, src/sync/outgoingSyncUtils.js
Fixes #2997.
Adds validation logic to database listener to prevent unintended records being added to sync out queue.
- Clear sync out queue on mobile.
N/A.
=> #2997 fix outgoing record null data

src/database/utilities/parsers.js, src/sync/lookupApiUtils.js
Fixes #3008.
Minor fix to boolean parse helper.
N/A.
=> #3008 fix insurance policy lookup is active field

src/selectors/prescription.js
Fixes #2945.
Fixes patient name from briefly displaying as `undefined` when navigating back to menu page.
N/A.
=> #2945 fix undefined patient name on back

src/database/DataTypes/InsurancePolicy.js, src/database/schema.js, src/sync/outgoingSyncUtils.js
Fixes #3015.
Fixes formatting of policy numbers synced from mobile to desktop.
N/A.
=> #3015 fix insurance policy outgoing sync formatting

src/database/DataTypes/InsurancePolicy.js
Fixes #3016.
Fix incorrect formatting of personal and family policy numbers.
N/A.
=> #3016 fix incorrect policy number formatting

src/database/DataTypes/Period.js
Fixes #3034.
Update period date formatting for consistency with desktop.
N/A.
=> #3034 update period date formatting

src/sync/incomingSyncUtils.js
Fixes #3056 
Adds missing `Transaction` fields to incoming sync:
- `insurancePolicy`
- `linkedTransaction`
- `subtotal`
- `outstanding`
- `insuranceDiscountAmount`
- `insuranceDiscountRate`
Note: the above fields were isolated by cross-referencing `incomingSyncUtils` with `outgoingSyncUtils` (excluding `Transaction` fields defined by getters). Idea is to ensure all fields which are synced out are also synced in, so that no transaction fields are overwritten or "blanked out".
N/A.
=> #3056 fix missing fields transaction incoming sync

src/reducers/FormReducer.js, src/utilities/formInputConfigs.js
Fixes #3072.
Enforces family policy number on creating new insurance policy.
As discussed with @joshxg, at some point may need to revisit the form config design, as the current implementation splits validation responsibility between the form reducer and the config + `FormTextInput` component (violation of the SRP principle). May want to look at how we can refactor to manage validation across multiple input fields (but not high priority).
=> #3072 fix insurance family policy not enforced

src/database/DataTypes/Transaction.js, src/sync/SyncQueue.js
Fixes #3085.
Updates transaction finalisation logic and sync queue sorting to ensure transaction lines are always synced before parent transaction (prevent transactions without lines).
@joshxg @anildahalsussol Hard to replicate without access to same data. Do we want to do a draft `v5.1.2` release for testing this?
=> #3085 fix transaction lines syncing before parent transaction

src/pages/dataTableUtilities/reducer/tableReducers.js
Fixes #3081 
- Correctly makes `data` field an array after toggling stockouts
- Exact steps to recreate the bug are:
- Toggle to not show stock outs
- Toggle to show them
- sort a column
N/A
=> #3081 Sorting crash

src/sync/SyncQueue.js
Fixes #3084.
Phew, took a while to track this down... looks like a combination of two bugs!
- Fixes duplicate sync out records due to incorrect duplicate matching logic.
- Updates sync out queue ordering to ensure child records are synced before parents.
@anildahalsussol Replicated the above bugs and this fixes it for me. Can you check that it fixes the original bug before merging (or do you need an `rc` build)?
Hoping this might fix a few of the bugsnag errors too (e.g. any cleanup logic based on the expectation that only one sync out record exists per `recordId` will have been broken!).
=> #3084 fix requisition sync no lines

src/navigation/actions.js, src/reducers/FinaliseReducer.js
Fixes #3099.
After a lot of dead ends (most caused by logging!), it looks like this is the culprit (@bijaySussol could you confirm?).
- Update back navigation to always reset finalise item.
From looking at the logic, it looks like it's safe to `resetFinaliseItem()` on all back navigation... but if I'm missing something, may need to revert back to a conditional (with an added edge case to handle this error)?
=> #3099 Fix deleted stocktake in finalise state

src/navigation/actions.js, src/reducers/FinaliseReducer.js, src/sync/SyncQueue.js
Fixes #3103.
Branches off #3101.
Fixes incorrect updating of sync queue due to use of `database.save` instead of `database.update`.
I think this is probably responsible for a lot of the missing record errors being thrown up by bugsnag, so hopefully we can close them all out after this and see if any pop up again!
=> #3103 fix sync queue update bug

src/dataMigration.js
Fixes #3109.
Adds migration code to delete invalid sync out records.
Tested locally by injecting invalid sync out records before upgrading. 
@bijaySussol Would be good if you could test this in production. Subject to approval will do a `v5.1.2` build and notify you. To ensure migration code runs correctly, will have to do a proper `v5.1.2` release (no more rcs).
@joshxg Any comments re. above? This patch has got quite big already, so I don't think there's any issue with bumping any other bugs to another patch, i.e. `v5.1.3`?
N/A.
=> #3109 Add invalid sync queue migration code

src/sync/SyncQueue.js
Fixes #3107.
Reverts sync queue ordering by record type.
NOTE: these tests should be done against the `v5.1.2` build. @bijaySussol @anildahalsussol will notify you when build is ready.
N/A.
=> Revert sync queue ordering by record type

src/selectors/prescription.js
Fixes #3130 
Allow searching for an item by name or code
=> allow filtering by code

src/database/DataTypes/Period.js, src/database/DataTypes/PeriodSchedule.js, src/localization/programStrings.json, src/reducers/ByProgramReducer.js, src/utilities/byProgram.js, src/utilities/getModalTitle.js, src/utilities/index.js, src/widgets/Step.js, src/widgets/modals/ByProgramModal.js
Fixes #3132
**Implemented differently to the issue describes**
- Initially thought it would be far too complex to add customers over suppliers into `ByProgramModal`. Turned out to be quite quick and simple (If you were the one to write it originally. Sorry).
- This should *still* be refactored into: Customer requisition `ByProgramModal`, Supplier Requisition and Stocktake variants as the logic in *general* is convoluted and extremely hard to follow.
- Essentially, this allows for passing `transactionType="customerRequisition"` as a prop which will have the steps "Customer -> Program -> Order type -> period"`.
- Not hooked up - can create a branch for testing if needed, otherwise can be tested in the next 'hook it up' PR
*Internal changes, shouldn't be tested*
- At this point I am not sure …
=> #3132 Customer Requisitions ByProgramModal *A3

src/pages/dataTableUtilities/actions/cellActions.js, src/reducers/FridgeReducer.js
Fixes #3128 
- Corrected case when navigating back
N/A
=> #3127 Re-render fridges on navigation

android/app/src/main/res/drawable/edit_text.xml, android/app/src/main/res/values/styles.xml
Fixes #3154 
- As the issue describes, applies this very random fix so that the app doesn't crash instantly when there are too many text inputs mounted
🤷 
*Internal change, can set `windowSize` of `DataTable` to a much larger number and render the table*
N/A
=> #3154 Too many text inputs

src/widgets/BarChart.js
Fixes #3167
- Code the headed and axis labels in with code
- We also want names to be shown more clearly so we replace names with codes but that bit is done in mSupply side.
Related to https://github.com/sussol/msupply/issues/6762, the changes there has to go in first.
=> #3167 Add header, axis labels to bar chart in mobile dashboard

android/app/src/main/AndroidManifest.xml
Fixes #3174 
Changes `supports-screens` android manifest option.
https://developer.android.com/guide/topics/manifest/supports-screens-element#compat-mode
Seems `requiresSmallestWidthDp` only allows for googly play store to apply filter. But google play store does not filter by it. 🤷 
Stab in the dark.. no idea if it'll work!
=> #3174 Add xlargescreens support

src/widgets/Step.js, src/widgets/modals/ByProgramModal.js
Fixes #3181 #3180 #3171 
Removes some prematurely optimized caching which just made things harder while saving some 1ms queries.. 🤷 
You live you learn - what I've learned: Avoid `useMemo` and `useCallback` unless it's causing actual performance issues that you want to solve. Not just to avoid potential or perceived performance issues!
For this particular issue: Removing the `getModalData` callback and just putting the data in the object straight up would probs be a better solution (But requires more work and, well.. )
=> #3181 memoization issues by program modal

src/widgets/PageInfo/PageInfoDetail.js, src/widgets/PageInfo/PageInfoRow.js, src/widgets/PageInfo/PageInfoTitle.js
Fixes #3179 
- Just correct prop drill/pass. This was a mistake in a recent refactor in develop
N/A
=> #3179 Not disabled when finalised

src/database/utilities/deleteRecord.js
Fixes #3185 
- Oops!
There's a few other record types missing here 😢
=> Add NameTag and NameTagJoin to deleteRecord

src/database/utilities/getIndicatorData.js
Fixes #?
A program indicator is optional, so a indicator value may not have a related program indicator (??)
Odd
=> Add safe ID checking

src/sync/PostSyncProcessor.js
Fixes #3051 
- Adds auto-finalise of prescriptions on incoming sync
- Create a prescription on desktop, don't finalise.
- Make the store a mobile store
- initialise the mobile store
- Sync with desktop
- Check on desktop: The prescription should be finalised 
N/a
=> #3051 auto finalise prescriptions

src/sync/incomingSyncUtils.js
Fixes #3218
- Fixes a field name such that the sanity check passes again
*Have a stocktake with some lines on a mobile store*
This area is ironically (I think I use this word here) trying to prevent errors (the sanity check) but it's pretty error prone itself! Worth a refactor/look at, imo!
=> #3218 Fixed sync bug preventing stocktake lines from syncing

src/database/DataTypes/Stocktake.js
Fixes #1680
- Create a basic `StocktakeBatch` when creating a `StocktakeItem`
N/A
=> #1680 Create a stocktake batch when creating a StocktakeItem

src/actions/FinaliseActions.js, src/mSupplyMobileApp.js, src/pages/CustomerInvoicePage.js, src/pages/CustomerRequisitionsPage.js, src/pages/StocktakesPage.js, src/pages/SupplierRequisitionPage.js, src/pages/SupplierRequisitionsPage.js, src/pages/dataTableUtilities/actions/tableActions.js, src/widgets/modals/FinaliseModal.js
Fixes #2294
- Makes Spinners work for supplierREquisition creating from program and adding from master lists
- Makes spinners work for adding items from master list for customer invoice page
- Makes spinners work for creating a stocktake
- Fixes a type bug in customer invoice `mapDispatchToProps`
N/A
=> #2294 Making Spinners great again

src/utilities/formInputConfigs.js
Fixes #3082 
- removes the lowerbound character length check of personal policy numbers
N/A
=> #3082 Dont enforce personal policy numbers

src/utilities/byProgram.js
Fixes #3227
- Adds additional filtering to filter out those programs which are not visible to the mobile store.
N/A
=> #3227 Additional filtering on programs

src/database/DataTypes/Requisition.js
Fixes #3225 
- Just add to the boolean to stop pruning requisition items which are from a remote order.
N/A
=> #3225 Stop pruning remote customer requisitions

src/widgets/FormControl.js, src/widgets/FormInputs/FormDateInput.js, src/widgets/FormInputs/FormTextInput.js
Fixes #2725 
- AutoFocus on the form input components which can be focused when they're the first input
N/A
=> Add autoFocus of first form input

src/widgets/modals/ModalContainer.js
Fixes #646
- Handles hardware back press for modals
N/A
=> Add handling of hardware back press for modals

src/database/DataTypes/TransactionBatch.js, src/database/utilities/createRecord.js, src/sync/incomingSyncUtils.js, src/sync/outgoingSyncUtils.js
Fixes #2995
- Adds sent pack size to the schema
N/A
=> #2995 Add populating of sentPackSize

package.json, src/database/DataTypes/MasterList.js, src/utilities/byProgram.js, src/widgets/modals/ByProgramModal.js
Fixes #3242 BRANCHED FROM #3239
=> #3242 Show max lines

package.json, src/database/DataTypes/MasterList.js, src/database/DataTypes/Name.js, src/database/DataTypes/Requisition.js, src/utilities/byProgram.js, src/widgets/modals/ByProgramModal.js
Fixes #3238
- Adds a check for max lines when finalizing
N/A
=> Add check for maxlines

src/widgets/modals/ByProgramModal.js
Fixes #3235
- Hides thresholdMOS for customer requisitions
N/A
=> #3235 Add hiding of thresholdMOS for customer requisitions

src/localization/authStrings.json, src/widgets/modals/LoginModal.js
Fixes #3050 
- Adds store name to the login screen under the site name and some labels to distinguish between the two
- Removed a now unused local style, unsure about styling but seems reasonably clear/usable(?)
- Don't know translations for these words so English only for now
- Unsure - maybe check the rest of the login page still looks acceptable and it still looks ok on different sized tablets?
=> #3050 login screen should show store name

src/widgets/modals/LoginModal.js
Fixes #3254
Linter rules didn't like it being a one liner, but also didn't like trailing spaces! So couldn't get a space in without rearranging, but this is a bit more readable anyway 🙂
=> factor out retrieving store name to not be in the render code

src/navigation/actions.js
Fixes #3247
- Batch calling dispatch updates the state correctly.
N/A
=> #3247 General Stocktake Crash

src/pages/dataTableUtilities/getPageInfoColumns.js
Fixes #3256 
https://github.com/openmsupply/mobile/blob/6421878e4e68aff5f06c1d78b4fa2f44f4caf1d8/src/widgets/DataTable/DataTableRow.js#L257
Makes the monthly usage shown in the row detail popup consistent with the column, code above
Should use a getter on `RequisitionItem`, probably
=> #3256 consistent monthly usage

android/app/build.gradle, android/app/src/main/java/com/msupplymobile/MainApplication.java, android/app/src/main/java/com/msupplymobile/ReactNativeFlipper.java, android/build.gradle, android/gradle.properties, android/gradle/wrapper/gradle-wrapper.properties, android/gradlew, android/gradlew.bat, package.json, src/widgets/InfoBadge.js, src/widgets/KeyboardSpacing.js, yarn.lock
Fixes #3258 
Bumps RN
Technically flipper works now, but it doesn't work well with realm, still - for me, anyway!
=> #3258 react-native bump

android/app/src/debug/AndroidManifest.xml, android/app/src/main/AndroidManifest.xml
Fixes #3288?
We need handle android 9 API changes for dev builds:
https://reactnative.dev/docs/_integration-with-exisiting-apps-java#cleartext-traffic-api-level-28
I stole the solution from the official RN template project:
https://github.com/facebook/react-native/blob/master/template/android/app/src/debug/AndroidManifest.xml
I think the bug may only occur if your emulator is on Android 9 or higher.
1. `yarn start`
2. The app is installed on your emulator and works.
=> Add debug/AndroidManifest.xml

src/bluetooth/BleService.js, src/bluetooth/DevBleManager.js, src/mSupplyMobileApp.js
Fixes #3298 
- Added copy of https://github.com/openmsupply/msupply-cold-chain/blob/develop/src/common/services/Bluetooth/DevBleManager.js 
- Modified BleService into singleton (if causes problems later - investigate passing instance into thunk(?))
- Added [isEmulator()](https://github.com/react-native-device-info/react-native-device-info#isemulator) check and Initialise BleService Singleton in mSupplyMobileApp 
- Done inside `usingVaccines` check, as it looks like we only request BT Permissions right now if this module is enabled
Make `componentDidMount` async, and add some methods into it on both emulator and real device and compare/observe results. e.g
```
await this.initialiseBtService();
await …
```
=> #3298 development ble manager

package.json, yarn.lock
Fixes #3308
- Adds the package `react-native-text-input-mask`
- I tried a bunch of packages out and this was the best. It stops at the native component level a lot of jank. For example, if you were to use a `TextInput` as a controlled component and passed it `value` prop - you can actually type in the `TextInput` and NOT update the `value` and it will enter into the component. This is hard to explain but the `TextInput` basically has it's own internal state and if it's not in sync it causes odd behaviour, like if I had a mask which only allowed two digits and that was enforced through JS `onChangeText` prop, then I could type an `a` and it would be rendered for .5second, and then reverted back. This package however does the masking at the native level and this jank didn't seem to happen. …
=> #3308-2 Add react-native-text-input-mask

package.json, src/widgets/TextInputs/TextInputWithAffix.js, src/widgets/TextInputs/index.js, src/widgets/index.js, yarn.lock
Fixes #3308 **Wrong branch name- oops**
*Note* I named a prefix or a suffix 'affix'. I have no idea if that is correct english. I also don't know if what I am calling a prefix or suffix is a prefix or suffix. It's what I came up with 🤷 
- Adds `TextInputWithAffix` Component
- Essentially this is to fill the role of having an input with, for example: `10 C` or `10 Mins`
- Creating an input with the affix within the editable input area would be a lot more work than you'd think (Or, at least, from what I can figure out)
N/A - internal code only white box testing
N/A
=> #3308-1 TextInputWithAffix component

src/pages/MenuPage.js, src/widgets/CircleButton.js, src/widgets/DateRangeSelector.js, src/widgets/IconButton.js, src/widgets/icons.js, src/widgets/index.js, src/widgets/modals/LoginModal.js
Fixes #3303.
Fixes #3304 too.
I'm not super happy with it but want it on the table regardless. While not used as a model, actual implementation is similar to idea of [Icon.Button](https://github.com/oblador/react-native-vector-icons/blob/master/lib/icon-button.js)
- Added `IconButton` component. Ended up making it work for text on left and/or right; On the off chance we use it for sync status, which has left text.
- Some size constants baked in.
- Refactored some existing `Icon.Button` usage to use `IconButton`
- End result made some lacking fonts be adjusted to the app font:
- Perhaps rethink how we structure `Text` styles... `globalStyles.authWindowButtonText` contextually isn't accurate but is what I'm using.
- Could think …
=> #3303 icon button

src/database/DataTypes/Transaction.js, src/widgets/DataTable/DataTableRow.js
Fixes #3291
- Disables a row when its finalised
- Disables a row when its a remote order - I think??
I synced an SI in - it had no linked req, but did have a linked transct - I think this is right??
=> #3291 Correct disabling of a row

src/database/DataTypes/Requisition.js, src/database/utilities/createRecord.js
Fixes #3290
- I think this is mainly cause of the rounding of the days to supply when creating a requisition. The changing of floor and ceil is probably not needed, technically, cause it should be some multiple of 365/12, always?
Nice find.
Need unit tests.
Putting this into a patch so based on master
=> Add remove rounding days to supply

src/widgets/Paper.js, src/widgets/PaperSection.js, src/widgets/index.js
Fixes #3336 
- Adds two components `Paper` and `PaperSection`.
- Two components because there are some areas with a header and some without.
- Thought abstracting the `Paper` away from the component with the dedicated header gave more flexibility.
- Unsure about `PaperSection` naming.
Internal
N/A
=> #3336 Paper component

src/widgets/CardDetail.js, src/widgets/index.js
Fixes #3306 
- Adds `CardDetail` component
Internal
Was going to make a `BreachCardDetail` abstraction over the top but couldn't think of a good implementation
=> #3306 CardDetail

src/widgets/modals/StocktakeBatchModal.js
Fixes #3330 
I don't think anyone is using payments and nothing else.
=> #3330 Add correct constant

src/widgets/Typography/TextWithIcon.js, src/widgets/Typography/index.js
Fixes #3304 
- Adds `TextWithIcon` component
Internal
Bit controversial implementation or actual neccessititity of the component. Things to keep in mind
- There's a lot of text+and icon coming up in the work
- I've done this a bunch and its pretty annoying to constantly right code for it
- Yes some better typography components would make for a better implementation, but it's a bit out of scope
=> #3304 TextWithIcon

src/widgets/DatePickerButton.js, src/widgets/DateRangeSelector.js, src/widgets/icons.js, src/widgets/modals/LoginModal.js
Fixes #3305 
Adjusts `DateRangeSelector` to look as it does in the designs as specified in issue.
- New DateRangeSelector look: 
- New DateRangeSelector has a background, default is white. Here it is with `backgroundColor="red"`: 
- Old DatePickerButton work fine:
=> #3305 date range selector update

src/actions/VaccineActions.js, src/reducers/VaccineReducer.js, src/reducers/index.js, src/selectors/vaccine.js
Fixes #3351
- Have added actions to start/stop scanning and adds found sensors to the store (not sure if `stop` was needed but thinking if 'connect' is clicked on the UI or someone navigates away scanning should stop?)
- Used the toasts from `TemperatureSyncActions` when BT/Locations are not available, not sure if appropriate or not
N/A
=> #3351 bluetooth scan start/stop thunks

src/globalStyles/colors.js, src/pages/NewSensorPage.js, src/widgets/Circle.js, src/widgets/CircleButton.js, src/widgets/Stepper.js, src/widgets/Wizard.js, src/widgets/icons.js, src/widgets/index.js
Fixes #3348 
- Added a `Circle` component - was sick of dealing - used it in `CircleButton`
- Added a bit of a cheap hack to the stepper to choose between this new variant and the old one. I am hoping to change the old one to the new one.. 
- Added this stepper as an option to the WIZARD which "just works" and you can click on past steps and call the callback `switchTab` to change tabs
- Think this is sufficient enough for a PR even though there's not much real content yet
Internal
=> Add Circle component

src/bluetooth/BreachManager.js, src/bluetooth/BreachManager.test.js, src/bluetooth/VaccineDataAccess.js, src/database/DataTypes/Sensor.js, src/database/utilities/createRecord.js, src/pages/SettingsPage.js
Doesn't really fix #3277, as that wanted more of a framework.
But as discussed in the issue linked above, for doing vaccines a button under settings to generate some data would do to get us going.
Makes some locations, some configs, some sensors, some logs, then generates breaches using `breachManager`...
I added a few fixes and am now a `breachManager` scientist.
I also made `Sensor.log` link to `TemperatureLog` rather than `SensorLog` (deprecated).
- Go to settings
- Press the new button
- Realm explorer check for `TemperatureBreach` records
=> #3277 generate vaccine data, fix things

src/actions/PrescriptionActions.js
Fixes #3323?
This was originally #3362 but we figured it'd be better for master, in case this is an issue in particular setups in the wild. Maybe.
Realm doesn't like object spreading on `Realm.Objects`. https://github.com/realm/realm-js/issues/2640 and/or https://github.com/realm/realm-js/issues/2844
=> fix prescriber select crash (master)

package.json, src/actions/PrescriptionActions.js, src/database/DataTypes/Requisition.js, src/database/DataTypes/Transaction.js, src/database/utilities/createRecord.js, src/widgets/DataTable/DataTableRow.js, src/widgets/StepperInput.js, src/widgets/modals/StocktakeBatchModal.js
**See the release discussion here: https://github.com/openmsupply/mobile/issues/3263**
*Please note, this version requires an mSupply server v4.13 or greater*
v6.0.1
This release has some minor bug fixes for v6.0.1.
- #3291 - Selecting finalised rows.
- #3292 - Incorrect rounding of days of supply in requisitions.
- #3345 - Incorrect keyboard when issuing quantities in a prescription.
- #3344 - App crashes when opening a stocktake batch modal when (only) payment customisation is enabled
- #3362 - App crashes when selecting a prescriber, sometimes.
=> Release v6.0.1

src/actions/VaccineActions.js, src/bluetooth/BleService.js, src/localization/vaccineStrings.json, src/reducers/VaccineReducer.js
Fixes #3354 
Adds actions and reducers for setting the log frequency. I've added the option to call with only the mac address, which will reset the frequency to the default of 300. Don't know if that will be useful or not?
Also not sure if you want to continue with the term 'frequency' or use 'interval' which is what BlueMaestro are using
tested with a couple of sensors 
- E7:F6:88:07:03:DA which is working nicely and is now set to 200s
- FC:C0:EE:9D:80:A3 which is not playing ball and throws an error. Good for error testing 😉
=> #3354 update logging interval

src/actions/VaccineActions.js, src/mSupplyMobileApp.js, src/selectors/vaccine.js
Fixes #3375
- Swap over the existing temperature sync scheduler to use the newly created temperature download action
- Got rid of macAddress param on `downloadAllLogs()` method as it wasn't needed
- Add check to not start download process if one is already in progress
- There is a UI component that looks like it was tied into the previous scheduler which also allows manual sync. Not sure about whether to keep it, get rid of it, or rework it. I think it's currently a little bit vague about what exactly is being synced, but probably a useful indicator to keep?
=> #3375 passively downloading temperatures

src/bluetooth/BreachManager.js, src/database/DataTypes/Location.js, src/database/DataTypes/Sensor.js, src/database/DataTypes/TemperatureBreach.js, src/database/DataTypes/TemperatureBreachConfiguration.js, src/database/utilities/createRecord.js, src/pages/SettingsPage.js, src/sync/incomingSyncUtils.js, src/sync/outgoingSyncUtils.js
Fixes #3395 
- Link `location.sensors`
- Link `sensor.breaches` and `breach.sensor`
- update sync utils
- update `breachManager` to use realm more (it already does to some degree, but further losing keeping it DB agnostic 😕 we'll try and unwind it later I guess?)
- Also bonus update the vaccine test data generator to link locations and temp configs so that navigation to FridgeDetailPage works.
=> #3395 object link sensors and breaches

src/widgets/DataTable/DataTableRow.js
Fixes #3407?
We changed how we were exporting `ChevronRightIcon` presumably, causing any data table using it to cause a cryptic crash.
=> Make ChevronRightIcon usage in DataTableRow consistent with other icons

src/actions/VaccineActions.js, src/mSupplyMobileApp.js, src/reducers/VaccineReducer.js, src/selectors/vaccine.js, src/widgets/modalChildren/TemperatureSync.js
Fixes #3378 
Downloads battery status for all configured and enabled sensors, at the same time as downloading logs.
Have renamed the download methods - and at the same time updated the 'isDownloading' flag and handled an error. The manual sensor sync has been updated to use the new method and correctly displays status. Will show an error (briefly in the case of the final sensor)
=> update battery level when syncing

src/pages/VaccinePage.js, src/widgets/DataTablePageView.js
Fixes #3431 
- `DataTablePageView` captures the gesture event and handles it, the flat list doesn't get a chance to handle it.
N/A
=> #3431 Remove DataTablePageView from capturing gestures to enable scrolling

src/pages/NewSensor/NewSensorStepThree.js, src/pages/NewSensor/NewSensorStepTwo.js, src/widgets/TextEditor.js
Fixes #3449 ?
- Sets heights of paper to be similar across them. Preempts height based on children, so should solve the issue for stepTwo
- TextEditor width reverted so to not overlap with label on small screens.
=> #3449 new sensor UI tweaks

src/database/DataTypes/Item.js, src/globalStyles/colors.js, src/pages/FridgeDetailPage.js, src/selectors/fridge.js, src/widgets/VaccineBarChart.js, src/widgets/VaccineChart.js, src/widgets/VaccineLineChart.js, src/widgets/icons.js
Fixes #3464 
Have added three bars to display the hot-mid-cold colour bars.
To do so, I've added a selector to grab the upper and lower breach values - it was unclear what, from the mockup, should be used out of the consecutive and cumulative options. ideas?
This version replaces the current line chart - should we have both options available?
This is how it looks with the generated data:
=> #3464 display data on bar chart

src/actions/Bluetooth/SensorUpdateActions.js, src/actions/Entities/SensorActions.js
Fixes #3427 
Updating `location.description` from `sensor.name` when saving sensors
Bonus task - when saving a sensor, skip trying to disable the button and set the log interval if the sensor has an invalid mac address, otherwise you cannot test this change when using an actual tablet and the generated dummy data.
=> update location name when saving

src/actions/Bluetooth/SensorDownloadActions.js, src/actions/Entities/SensorActions.js, src/database/DataTypes/Sensor.js, src/localization/vaccineStrings.json, src/pages/NewSensor/NewSensorStepThree.js, src/reducers/Entities/SensorReducer.js, src/selectors/Entities/sensor.js, src/sync/incomingSyncUtils.js, src/sync/outgoingSyncUtils.js, src/widgets/LastSensorDownload.js
Fixes #3374 
- Adds logDelay to schema
- Adds programmedDate to schema - Offroad
- Adds setting the log delay 'better' in `SensorActions`/`SensorReducer`.
- prevents download logs for the sensor when the logging delay is greater than the time now.
- Not sure if this will display nicely on all screens
- Probably need to allow for users to change the logging delay after its been set... we are adding a remove button also, so maybe just make them remove it .. i dunno
=> #3374 dont download before log delay

src/sync/incomingSyncUtils.js
Fixes #3480
Added a default for the two new dates when sync is incoming.
=> add defaults for new dates

src/actions/Bluetooth/SensorScanActions.js, src/actions/Entities/SensorActions.js, src/hooks/useConditionalAnimationRef.js, src/localization/generalStrings.json, src/localization/modalStrings.json, src/localization/navStrings.json, src/pages/NewSensor/NewSensorStepOne.js, src/pages/NewSensor/ScanRow.js, src/pages/SensorEditPage.js, src/pages/VaccinePage.js, src/reducers/Entities/SensorReducer.js, src/selectors/Entities/sensor.js, src/widgets/AfterInteractions.js, src/widgets/PaperModal/PaperConfirmModal.js, src/widgets/PaperModal/PaperModalContainer.js, src/widgets/SensorHeader/LastSensorDownload.js, src/widgets/SensorPicker.js, src/widgets/WithFlash.js
Fixes #3273 
- Adds replace sensor functionality
- Adds remove sensor functionality
- I think there might be something here with "last sensor download" - do we want that to actually be last download from the location...? I am not sure!
=> #3273 Remove/Replace functionality

src/widgets/Step.js, src/widgets/modalChildren/AutocompleteSelector.js
Fixes #3477 
- Removes the use of the regex - safest option 🤷 
- Changed icon name. Uhh.. I dunno what's going on but couldn't open the modal without this. Unsure if this is happening in prod ooooops?
N/A
=> #3477 regex used from user input non defensively

src/pages/NewSensor/NewSensorStepThree.js, src/pages/SensorEditPage.js
Fixes #3475 
- Adds dividing by 60 when showing in the UI 
I just like branching apparently
=> #3475 Adjusting LogInterval to be saved as seconds, displayed as minutes

src/actions/Bluetooth/SensorDownloadActions.js, src/actions/Entities/SensorActions.js, src/database/DataTypes/Sensor.js, src/database/schema.js, src/localization/vaccineStrings.json, src/pages/SensorEditPage.js, src/pages/SettingsPage.js, src/reducers/Entities/SensorReducer.js, src/sync/incomingSyncUtils.js, src/sync/outgoingSyncUtils.js, src/widgets/LastSensorDownload.js, src/widgets/icons.js
Fixes #3463 
Ability to pause temperature log download for a specific sensor.
- A play/pause icon button on the sensor settings page which toggles the state
- Saved to a new field ( `isPaused` )
- Sensor header shows the disabled wifi icon if the sensor is paused, with the text `PAUSED` ( found that having a pause icon here was confusing, to me at least )
- A sensor that is paused does not download temperature logs
- Couple of offroad fixes ( e.g. saving a sensor wasn't working )
=> #3463 ability to pause temperature downloading

package.json, src/actions/PermissionActions.js, src/localization/modalStrings.json, src/reducers/PermissionReducer.js, src/selectors/permission.js, src/widgets/HeaderRight.js, src/widgets/PaperModal/PaperModalContainer.js, src/widgets/PermissionSettingsIcon.js, src/widgets/SettingsIcon.js, src/widgets/icons.js, yarn.lock
Fixes #3376 
Adds a wee icon to the top right - showing an exclamation if there's a problem:
..or a settings icon if everything is fine:
Pressing the icon shows a modal giving the status of the permission and services required. If something is disabled, pressing that line will prompt to enable:
One extra item is whether we need to display location services - which we currently don't have in the permissions checks. Was looking at `react-native-connectivity-status` - don't know if we need to do this though? seems to work ok as it is?
Also - I've only shown this when vaccines are enabled, as the permission checks are tied to vaccine enabled also. Should this be changed?
=> show permissions & services status

src/selectors/fridge.js
Fixes #3488 
- Adjusts cumulative breach calculation 
- Might be a separate issue that the card doesn't update when a download has occurred in background, to investigate separately
=> #3488 adjust cumulative breach units

src/database/DataTypes/Sensor.js, src/utilities/temperature.js
Fixes #3495 
- Shows the temperature of a sensor with no logs is N/A instead of `0` by not assigning `0` as a default temperature, and returning the invalid pattern in `.temperature()`
N/A
=> #3495 Show temperature is n/a not 0 on vaccine module page

src/sync/incomingSyncUtils.js, src/sync/outgoingSyncUtils.js
Fixes #3492 
- Removes `is_paused` from sync - not gonna get the field into desktop before the release
N/A
=> Remove is_paused from sync

src/pages/FridgeDetailPage.js, src/widgets/HazardPoint.js, src/widgets/VaccineLineChart.js, src/widgets/modalChildren/BreachDisplay.js
Fixes #3501 
- Seems the `dataComponent` was previously being passed the `datum` component which was a real breach object, and it is now only an object `{x: .., y: ..}`, so, it doesn't have an `id` to pass back to find the breach. So instead, pass the full data set to the icon component as it is passed the `idx` of which data element it is... 
- Also simplified `BreachDisplay` and removed the weird logic which was trying to limit the number of data points and displaying a spinner with `AfterInteractions`
- Also made the hazard icon more clickable by chucking a bigger rect around it, sort of. 
There's plenty wrong with the `breachmodal` itself but.. for another issue, I think
=> #3501 HazardIcon to use the full dataset

src/bluetooth/SensorManager.js, src/database/DataTypes/Sensor.js
Fixes #3493 
- Adds a default of 100 for the battery level of a sensor. It's not ideal, ideally we'd scan straight away and pick up the real battery level, but that went in the too hard basket - in reality, it won't really be too long before a download occurs and the battery level is picked up correctly
N/A
=> #3493 Default of 100 for battery level

src/database/DataTypes/Location.js, src/main.js, src/pages/FridgeDetailPage.js, src/pages/NewSensor/NewSensorStepThree.js, src/selectors/Entities/sensor.js, src/widgets/BreachCard.js
Fixes #3505 
Removed the cause of some errors and suppressed the non-serializable state one. As far as I could make out, that doesn't affect us and my attempts at creating a plain object instead of the realm object were a little more complicated than I think is needed.
  : this was on returning to the vaccine page after adding a sensor. A number is given when viewing the list i.e. after fetching from db, but that page was formatting as a date
 fridgeDetail > params.fridge.locationMovements() : this can be seen when viewing any vaccine detail page
  : View any vaccine page
  : View a vaccine page with a cumulative breach
 Add a sensor, page two
  : Add a sensor, page two and on the  Vaccines page
  : Vaccine Detail page when no …
=> #3505 remove warnings

src/database/DataTypes/Stocktake.js
Fixes #3328 
- Uses the correct field. Can see it should be `message` in `Requisition.canFinalise` and `Transaction.canFinalise`, used in `FinaliseModal`/`finalise.js`
N/A
=> #3328 Add Stocktake correct field

src/database/DataTypes/Transaction.js, src/pages/CustomerInvoicePage.js, src/pages/SupplierInvoicePage.js
Fixes #3513 
- Only show vaccine columns on SI/CI when theres a vaccine item present
N/A
=> #3513 Only show vaccine columns with a vaccine item

src/actions/Entities/SensorActions.js
Fixes #3517 
- When removing/replacing, explicitly set state correctly.
N/A
=> #3517 is paused state is saved

src/reducers/Entities/LocationReducer.js, src/reducers/Entities/SensorReducer.js, src/reducers/Entities/TemperatureBreachConfigReducer.js
Fixes #3523 
- Update the `SensorReducer`/`LocationReducer`/`ConfigReducer` states after a sync
N/A
=> #3523 Sensor list to update after sync

src/actions/InsuranceActions.js, src/actions/PaymentActions.js, src/actions/PrescriptionActions.js, src/database/DataTypes/RequisitionItem.js, src/database/DataTypes/StocktakeBatch.js, src/pages/dataTableUtilities/actions/cellActions.js, src/pages/dataTableUtilities/actions/pageActions.js, src/selectors/newSensor.js, src/selectors/patient.js, src/widgets/PrescriptionInfo.js
Fixes #3528 #3541 
- Can't spread realm objects, so I did a global search and searched for `...` and then checked if they were a a realm object and changed it. Was super fun
N/A
=> #3528 Cant spread realm objects

src/database/DataTypes/Sensor.js
Fixes #3553 
- Adds `locationID` to the sensor model which is the field which is on the plain object, which is what the sensor is when navigating from the `VaccinePage`.
N/A
=> #3553 Unable to save a sensor

src/actions/BreachActions.js, src/bluetooth/BreachManager.js, src/bluetooth/VaccineDataAccess.js, src/database/DataTypes/TemperatureBreach.js
Fixes #3569 
- Fair few changes. Primarily this was to ensure breaches are being continued rather than only created. To do this required mainly date format changes, which revealed a few other issues which i'll comment in the PR
Set up a new sensor
Trying to share the logic between the apps needed more thinking through, this is a bit of a mess sorry :(
=> #3569  Breaches only create, never continue

src/pages/SensorEditPage.js
Fixes #3562 
- Technically not quite correct - you could resume while there was a log delay and bring the logdelay forward. Could also set a logdelay when the sensor was never actually paused. I think you very rarely set a sensor up and these edge cases won't hoping practically so I didn't bother accounting for them....... is that bad?
N/A
=> #3562 Set a logdelay when resuming a sensor

src/actions/Entities/SensorActions.js, src/database/DataTypes/Location.js, src/database/DataTypes/Sensor.js, src/database/DataTypes/TemperatureBreachConfiguration.js, src/reducers/Entities/LocationReducer.js, src/reducers/Entities/SensorReducer.js, src/reducers/Entities/TemperatureBreachConfigReducer.js
Fixes #3572 #3571 
- Added `toJSON` to `Location`/`Sensor`/`TemperatureConfig` classes, which is used to 'refresh' the state from a realm object.
N/A
=> #3572 battery level not updated

src/reducers/Entities/LocationReducer.js, src/reducers/Entities/SensorReducer.js, src/reducers/Entities/TemperatureBreachConfigReducer.js
Fixes #3557 
- Added merged state rather than overwriting in Location/Sensor/Config reducers
N/A
=> #3557 Merge state ratehr than overwriting after a sync occurs

src/widgets/bottomModals/ItemDetails.js
Fixes #3533 
- Sorts by `expiryDate` cause Rowena was complaining
N/A
=> #3533 Sort batches by expiry date

src/hooks/useKeyboardIsOpen.js, src/widgets/PageInfo/PageInfoColumn.js, src/widgets/RowDetail.js
Fixes #3531 
- Only try and open the `RowDetail` component when the keyboard is closed.
N/A
=> #3531 Janky row detail opening

src/database/DataTypes/Transaction.js, src/pages/SupplierRequisitionsPage.js, src/widgets/DataTable/DataTableRow.js
Fixes #3585  #3207
- Corrects the conditional on deleting remote orders
N/A
=> #3585 Correct the conditional on deleting remote orders

src/actions/Entities/SensorActions.js, src/pages/NewSensor/NewSensorStepThree.js, src/pages/SensorEditPage.js
Fixes #3529 
Adds validation to the new sensor and sensor edit pages.
Defaults the code of the new location to be the name of the sensor, if no code is specified.. open to better suggestions on that one.
Side note: was amused to find that you can use emojis as the name..
=> #3529 should force sensor name and code

src/localization/generalStrings.json, src/widgets/modals/DataTablePageModal.js, src/widgets/modals/StocktakeBatchModal.js
Fixes #3527 
Added placeholder when no vvm statuses are available. In supplier invoices and stocktake batches.
Slight detour: also handled the 'isActive == false' state, as that helped me test.
Diversion: noticed that the requisition lines were not handling the placeholder either
Full offroad: added the `isActive` check for reasons too
Note: when testing, you have to have a supplier invoice with a vaccine in it; and the vaccines enabled; AND the payment module disabled; otherwise the payment columns show in supplier invoices, and not the vaccine columns 🙄 
=> #3527 no vvm status records handling

src/widgets/SensorHeader/BlinkSensorButton.js
Fixes #3587 
Disabled the blink button when a sensor is currently downloading. 
Resolves the problem, and why would anyone want to blink while it was actively downloading?
The blink button disabling logic wasn't clear - so I changed it. There's no reason to include `isBlinking` as this is already handled in the implementation - and I couldn't see why `!isBlinking` == disabled. Surely it should be disabled if it is already blinking?
=> disable blink when downloading

src/selectors/Entities/temperatureBreachConfig.js
Fixes #3626 
- Super tiny tweak to min/max thresholds so hot > cold when creating and editing breach configs for a sensor
Creating new sensor was allowing hot/cold to be equal, adjusted to align with edit flow (min diff of 0.1)
=> #3626 Update temperatureBreachConfig thresholds

src/widgets/JSONForm/JSONForm.js, src/widgets/JSONForm/fields/Description.js, src/widgets/JSONForm/fields/Title.js, src/widgets/JSONForm/templates/Field.js, src/widgets/JSONForm/templates/ObjectField.js, src/widgets/JSONForm/testJSON.js, src/widgets/JSONForm/widgets/Text.js
Fixes #3634 
- Added a Text widget for string types
- Tried to handle focusing the next widget, seems to work OK when you use the virtual keyboard, using enter on my keyboard on the emulator has odd behaviour 🤷 
- Altered description/title fields
- The `FormTextInput` is coupled to tightly to the implementation and can't really be used for this, so just used the style and pretty much most of the same props
- The error messages are the inbuilt ones and need a bit of work to change them
- Open to style suggestions, feel free to commit
N/A
=> #3634 JSON Schema TextInput Widget

src/widgets/JSONForm/JSONForm.js, src/widgets/JSONForm/templates/Field.js, src/widgets/JSONForm/testJSON.js, src/widgets/JSONForm/widgets/Checkbox.js
Fixes #3639 
- Simple 'checkbox' component. This is for boolean values so a `Checkbox` is probably the correct choice for this regularly, but we use this `ToggleBar` component in a lot of places and it's kinda easier for now? Although just adding https://github.com/react-native-checkbox/react-native-checkbox would also be easy? I just took the styles and stuff from `FormToggle`
Internal
=> #33639 Form schema Toggle component

src/widgets/JSONForm/JSONForm.js, src/widgets/JSONForm/testJSON.js, src/widgets/JSONForm/widgets/Select.js
Fixes #3640 
- Adds a select widget
- Just really tested with some basic enums and it seems to work well.
- Went with the built in react-native picker even though it's deprecated because that's just what we have been using. Didn't use the `dropdown` component because it has a funny `header` thing implemented which was being annoying with implementing 'default/placeholder' values, with having the 'header' being selectable, which I didn't want to have to regression test.
- The `react-native-picker` package available to replace the built-in has exactly the same API, just didn't want to add native packages which can make building the app be funny
- I actually like the `mode="dialog"` a little better than "dropdown"?
Internal?
=> #3640 Select widget

src/bluetooth/BreachManager.test.js, src/selectors/fridge.js
Fixes #3623
- Tiny adjustment to filter expression so only breaches for the current location are shown on the line graph
- Snuck in offroad to fix breach manager tests as there were some timestamping updates made
N/A
=> #3623 breach filtering by location

src/database/utilities/createRecord.js
Fixes #3666 (partially)
- When auto assigning VVM status to items, filter out inactive ones.
- Historic records will not be updated (e.g. unfinalised SI or Stocktakes), a separate issue will be created for this
=> #3666 Filter for active VVM Status

src/pages/VaccinePage.js, src/selectors/Entities/temperatureBreachConfig.js
Fixes #3673.
Minor UI fix to prevent `FridgeDisplay` date string overlapping chevron icon.
N/A.
=> #3673 fix fridge date string overlapping chevron icon

src/pages/dataTableUtilities/constants.js, src/pages/dataTableUtilities/getColumns.js, src/widgets/DataTable/DataTableRow.js
Fixes #3364,
- Disables location cell for non-vaccine items.
- Fixes `CURRENT_LOCATION` column key typo.
N/A.
=> #3364 disable location for non-vaccine items

src/actions/Entities/SensorActions.js, src/database/DataTypes/TemperatureBreachConfiguration.js
Fixes #3627.
Took me a while to figure this one out! TLDR is that location edits are being overwritten by old location state persisted in the sensor configs. When the config locations are persisted to the database, the previous location updates are "reverted" back to the old state. This can be seen by examining `updatedLocation` after the configs are updated (as it is a live realm object, it reflects the most recent state of the database).
Note: what made this super confusing (for me) was the way concerns overlap between multiple live objects (e.g. as opposed to only updating config fields on the `TemperatureBreachConfiguration` object, linked location objects are also updated). I think some minor refactoring to only update certain fields rather than whole objects could make this code a …
=> #3627 fix sensor config reverting location updates

src/pages/FirstUsePage.js, src/widgets/modals/LoginModal.js
Fixes #233?
- Added `autoCompleteType` to textInputs. Didn't actually fix the issue unfortunately. Presumably what should be done for android at least.
- Added trimming of strings when submitting server url, site name and user name.
**Initialisation/FirstUsePage**
**Login Page**
This is contentious haha. There are conceivably existing users that have a spaces leading or trailing their user name.
Creating patients or prescribers, we could/should(?) trim their names too. Though I think we enter "first" and "last" names separately, should still trim them?
=> #233 trim white space off site and user names

src/actions/Entities/NameNoteActions.js, src/database/DataTypes/Name.js, src/pages/DispensingPage.js, src/widgets/FormControl.js, src/widgets/Tabs/PatientEdit.js, src/widgets/modalChildren/PatientEditModal.js
Fixes #3616 
- Adds a `PatientEditModal` component to encapsulate some of the code a little
- Adds `JSONForm` into `PatientEditModal` in a somewhat crude way
- Adds creating new name notes from the `PatientEditModal`
Few issues to come out of this
- Tidy up UI of this modal
- Create some sort of `touched` state which gets set after an `update` action, and only save/create a new name note if the form has been touched (Could check if the actual diff is different also, but a simple `touched` is gonna catch the majority of cases and is a bit simpler. Although could just do a `JSON.stringify` compare of the new name note data and the old name note data to see if anything has changed to check also.
- I don't really like the implementation in general, but I think we are gonna do more work in …
=> #3613 JSONForm in PatientEditModal

package.json, src/actions/Entities/VaccinePrescriptionActions.js, src/localization/dispensingStrings.json, src/reducers/Entities/VaccinePrescriptionReducer.js, src/selectors/Entities/vaccinePrescription.js, src/sync/outgoingSyncUtils.js, src/widgets/DataTable/Cell.js, src/widgets/Tabs/VaccineSelect.js, yarn.lock
Fixes #3683, #3692
Adds a 'checkbox' to the third step, allowing the user to choose 'Refuse' or 'Accept' (default)
If refused, no prescription is created, instead a name note is added to the patient with the event type 'Refused vaccine' or whatever has the code `RV` ( yes, that linking is not ideal )
Some footrunner code to create the required `patient_event`:
```
C_OBJECT($obSurveyPatientEvent)
$obSurveyPatientEvent:=ds.patient_event.new()
// event_type field has these options used elsewhere in the code:
// "DS" : Description / Text
// "NU" : Numeric
// "BO" : Boolean
$obSurveyPatientEvent.ID:=UUID_generate
$obSurveyPatientEvent.code:="RV"
$obSurveyPatientEvent.description:="Refused vaccination" …
```
=> UI changes

src/actions/Entities/NameActions.js, src/reducers/Entities/NameReducer.js, src/selectors/Entities/name.js, src/utilities/constants.js, src/utilities/formInputConfigs.js, src/widgets/FormControl.js, src/widgets/FormInputs/FormDateInput.js, src/widgets/StepperInputs/DateEditor.js, src/widgets/Tabs/PatientSelect.js, src/widgets/modals/CashTransactionModal.js
Fixes #3711 
Removes the search button from the patient form again.. adds in a debounced onChange filter instead
The debounce on the date field is making it s-u-p-e-r-s-l-o-w when typing. Still works though, and that's outside of these changes, so won't address it here.
=> filter patient search form on change

src/actions/Bluetooth/SensorDownloadActions.js, src/mSupplyMobileApp.js, src/reducers/Bluetooth/SensorDownloadReducer.js, src/selectors/Bluetooth/sensorDownload.js
Fixes #3705 (or at least improves it)
Have found that if the app is left running long enough the app schedules lots and lots of `startDownloadAll` actions (one job is created each time the main `mSupplyMobileApp` component updates) which eventually gets the app to the point that it's always 'downloading' and will be very difficult to update a sensor's logging interval 😆 . 
https://github.com/openmsupply/mobile/blob/4a79db0e40092612a8eeaacc5d66e084884d99ac/src/mSupplyMobileApp.js#L114
This PR just adds a small update to add some state to track if the passive download has been scheduled at least once.
If there are lots of sensors (and especially if one is out of range) it may still be a little difficult to update the sensor …
=> #3705 download state improvements

src/localization/modalStrings.json
Fixes #3633.
Nit fix for permission modal intro string.
@RowenaN has suggested a few other minor changes, but I think this one is the highest priority for the upcoming release!
=> #3633 fix permissions modal intro string

src/database/DataTypes/Item.js, src/database/DataTypes/StocktakeBatch.js, src/database/DataTypes/TransactionBatch.js
Fixes #3720
- Fixes a bug where the reason applied to a stocktake batch was not being copied over to the inventory adjustment
- Uses open vial wastage reasons to calculate open vial wastage
=> #3720 Calculate open vial wastage from openVialWastage options

src/pages/SettingsPage.js
Fixes #3739
- Don't display 'Generate vaccine data' button unless in DEV mode
N/A
=> #3739 hide vaccine button behind DEV env check

src/localization/reportStrings.json, src/utilities/vaccineReport.js
Fixes #3742 
- Fix breach config duration units
- Fix breach type strings
- Fix logging section to use correct headers/keys
N/A
=> #3742 fix breach report details

src/sync/incomingSyncUtils.js, src/sync/outgoingSyncUtils.js
Fixes #3732
- Add log interval to sync utils
1. - [ ] Add a sensor in mobile - note log interval
2. - [ ] Sync
3. - [ ] Check Desktop for Sensor record and verify log interval matches what was set up in mobile (I can see the schema but not sure how to verify the record)
4. - [ ] Uninstall mobile (or if there is another way to clear all saved data 🤷 )
5. - [ ] Reinstall mobile 
6. - [ ] Sync
7. - [ ] Check the sensor exists in mobile with the log interval that was originally set up in step 1
=> #3732: Add logInterval to incoming and outgoing sync utils

src/database/DataTypes/Requisition.js
Fixes #3738.
Fixes incorrect conditional logic preventing requisition items from being correctly pruned.
These changes should only effect automatic orders and requisition finalisation.
=> #3738 fix remote requisition item pruning

src/actions/Entities/VaccinePrescriptionActions.js
Fixes #3778 
Some defaults to protect the destructuring calls.
=> #3778 Defaults when no transactions

src/database/UIDatabase.js, src/localization/vaccineStrings.json, src/pages/MenuPage.js, src/selectors/Entities/vaccinePrescription.js
Fixes #3774 
- Updated a callback deps list to ensure the menu page is updated correctly after a sync (jeez there's a lot of memoization here)
- Added a toast when a user has no vaccine stock for the vaccination button
N/a
=> #3774 Ensure vaccine dispensing button is enabled+warn when no stock

src/bluetooth/TemperatureLogManager.js, src/bluetooth/TemperatureLogManager.test.js
Fixes #3759
- Implemented proposed solution in the original issue (tested and works as expected)
N/A
=> #3759 temperature log calculation inaccuracy

src/actions/Bluetooth/SensorDownloadActions.js, src/bluetooth/BleService.js, src/bluetooth/constants.js
Fixes #3758.
Resets sensor logs after saving them locally to device.
N/A.
=> #3758 reset log interval on log download

src/mSupplyMobileApp.js
Fixes #3767 
- The last prop to remove to stop the root re-rendering constantly during sync woo (this has been like 2 years of removing props from this component 🤣 
- It's use to stop the synchronise func being executed - but it can't be executed if not initialised and the button is disabled if already syncing so it's redundant
Internal
N?A
=> #3767 Remove isSyncing prop from root container

src/actions/Entities/VaccinePrescriptionActions.js, src/widgets/Tabs/VaccineSelect.js
Fixes #3807 
- Ensures there's a vaccine selected, always
N/a
=> #3807 No vaccine selected

src/database/utilities/createRecord.js
Fixes #3811 
- When creating a patient these values were empty strings, not null/undefiend so defaults weren't used
N/A
=> #3811 Patient defaults whenever a field is falsey not just null

src/actions/Entities/NameActions.js
Fixes #3812 
- Add missing `new`
N/A
=> #3812 Patient DOB incorrect

src/actions/Entities/VaccinePrescriptionActions.js, src/database/DataTypes/NameNote.js
Fixes #3813 
- Actually start creating name notes for refused vaccines when you're refusing a new patient [The name wasn't saved yet, so not picked up by the query]
- Prevent name notes being created if the patient event is not defined (Should the checkbox be hidden also....?]
- Prevent crashes when a name note doesn't have a patient event
Not sure what to do about patient events not be defined. I don't like hiding/showing things based on the presence of a record but also don't really want a pref
=> #3813 Fixing crashes when refusing vaccines

src/utilities/formInputConfigs.js
Fixes #3810 
- Was not correcting filtering the configs so was calling ref a variable number of times.
N/A
=> #3810 Fix crashing when navigating back

src/database/DataTypes/Name.js
Fixes #3831
- Adds these fields which the patient input config is looking for, for initial values
N/a
=> #3831 Address inconsistencies between dispensing pages

src/sync/outgoingSyncUtils.js
Fixes #3834 
- Don't override the home store!
N/a
=> #3834 Remove overriding of home store

src/actions/Entities/NameNoteActions.js, src/sync/lookupApiUtils.js, src/widgets/modals/SearchForm.js
Fixes #3824 
- Saves name notes when theyre searched for and added in vaccine dispensing and normal dispensing
This is Hard to test because you need to have a patient which has clinical data form that is not from the mobile store.
You can use the following code to create one with footrunner:
```
$nn:=ds.name_note.new()
$nn.ID:=UUID_generate
$nn.data:=data
$nn.name_ID:="SOME PATIENT ID YOU CAN FIND IN RECORD BROWSER"
$nn.patient_event_ID:="295C2B7E53264C1B98ADD57B720F3AF6"
$nn.save()
```
=> #3824 Save NameNote records from remote patients

src/sync/outgoingSyncUtils.js
Fixes #3829 
- really just to avoid some confusion..
N/A
=> #3829 Send boolean_value with refused vaccine name notes

src/actions/PatientActions.js, src/widgets/modals/SearchForm.js
Fixes #3847 
- Move the create visibility fetch to the search form not the action used when creating a new patient
N/a
=> #3847 Don't create visibility for new patients created on mobile

src/actions/DispensaryActions.js, src/actions/PatientActions.js, src/database/UIDatabase.js, src/database/utilities/createRecord.js, src/localization/modalStrings.json, src/pages/DispensingPage.js, src/reducers/DispensaryReducer.js, src/reducers/PatientReducer.js, src/selectors/patient.js, src/widgets/modalChildren/ADRInput.js
Fixes #3803 
- Adds an ADR modal to create new ADRs
**NOTE: Need some footrunner for an ADR form- will becoming soon**
=> #3803 ADR Modal

src/widgets/DatePickerButton.js, src/widgets/JSONForm/JSONForm.js, src/widgets/JSONForm/widgets/TimePicker.js, src/widgets/JSONForm/widgets/index.js, src/widgets/icons.js
Fixes #3852 
- Quick time picker widget
Internal, no testing yet
Used this schema to check it out:
```
const schema = {
jsonSchema: {
title: 'A registration form',
description: 'A simple form example.',
type: 'object',
required: ['firstName', 'lastName'],
properties: {
firstName: {
type: 'string',
title: 'First name',
default: 'Chuck',
pattern: '^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$',
errorMessage: 'Must be a time following the pattern hh:mm, such as 11:01 or 23:01',
},
lastName: {
type: 'string',
title: 'Last name',
},
telephone: {
type: 'string',
title: 'Telephone',
minLength: 10,
},
},
},
uiSchema: { firstName: { 'ui:widget': 'TimeWidget' } },
};
```
=> #3852 time picker widget

src/widgets/JSONForm/widgets/Text.js
Fixes #3857 
- An empty string is apparently valid for a required string field. Undefined isn't!
N/A
=> #3857 Set undefined rather than an empty string

src/database/DataTypes/StocktakeBatch.js, src/database/DataTypes/StocktakeItem.js, src/database/DataTypes/TransactionBatch.js, src/database/DataTypes/TransactionItem.js, src/utilities/formatters.js, src/utilities/index.js, src/widgets/DataTable/DataTableRow.js, src/widgets/bottomModals/ItemDetails.js, src/widgets/modals/DataTablePageModal.js
Fixes #3865 
- So.. just removed all the handling of doubles and only try and handle it at the interface ...??  Think this is better
N/a
=> #3865 Add different double handling as quantities behaviour

src/database/utilities/dataGenerators.js, src/widgets/modalChildren/BreachDisplay.js
Fixes #3768 
- After interactions needs to be nested within the stack navigator, the breach modal is at the root and so isn't in a stack nav, so causes a crash. Not the best solution, but a solution..
Also quick fix to the vaccine generated data
=> #3768 Remove afterinteractions from breach display

src/database/utilities/deleteRecord.js
Fixes #3866 
- Means you can now delete records properly from the server (system data mainly)
N/A
=> #3866 delete record missing types

src/actions/Entities/NameNoteActions.js
Fixes #3880 
- Adds a quick check before creating a name note to see if anythings changed
N/A
=> #3880 Add check before creating a name note

src/selectors/dispensary.js
Fixes #3875 
- Stops patientlookup crashing the app
N/A
=> #3875 Add updated selectors

src/widgets/modals/StocktakeBatchModal.js
Fixes #3899 
- dispatches and action to refresh the stocktake item when editing a stocktake batch dose
N/A
=> #3899 Dispatch StocktakeItem refresh when editing StocktakeBatch doses

src/utilities/dailyUsage.js
Fixes #3736
Adjust divisor to have min value of 1.
- E.g. Before fix with usage of 5 over <= day, expected monthly usage was 6319.84 (or even higher depending on how soon the SR was created)
- E.g. After fix with usage of 5 over <= 1 day, expected monthly usage is 152.08
- Ran code formatter, it edited `programDailyUsage` but no functional changes
=> #3736 Adjust numberOfUsageDays calculation

src/database/utilities/createRecord.js, src/utilities/formInputConfigs.js
Fixes #3770
- Updated createRecord to include the female boolean field
Not really sure of any
=> #3770 Update createRecord to save prescriber gender

src/pages/SensorEditPage.js
Fixes #3787 
- A super minor update to make the app navigate to the vaccine/cold chain page whenever a sensor is removed (as opposed to previously where if the settings page was navigated to from the `fridgeDetail` page, the app would navigate back to that instead and display sensor details for a sensor that was just removed.
Don't think there are other places where a sensor can be removed in the app?
=> #3787 Make sensor removal navigate to vaccine page

src/actions/Entities/VaccinePrescriptionActions.js, src/localization/dispensingStrings.json, src/reducers/Entities/VaccinePrescriptionReducer.js, src/selectors/Entities/vaccinePrescription.js, src/widgets/VaccinePrescriptionInfo.js
Fixes #3921
- I know this is not a good spot. I didn't know where to put it..
N/A
=> Add bonus dose checkbox to vaccine prescription

src/sync/lookupApiUtils.js
Fixes #3911 
- Saves ethnicity/nationality of a patient when looking up
N/A
=> Add nationality/ethnicity to patient lookup

src/utilities/vaccineReport.js, src/widgets/SensorHeader/ExportTemperatureDataButton.js
Fixes #3747
- Display a user-friendly toast if they attempt to export temperature logs before any logs exist
- Setup a new sensor with a log delay of 5min and try to export temperature logs before logging is started (from vaccines page).
Might have been better to make the icon in the sensor header trigger the toast instead? Or disable the download icon? I thought this was at least one step better than having to close the app at least
=> #3747 export temperature logs with no logs

src/reducers/FormReducer.js
Fixes #3859 
- There's no form config when exiting the modal, so if there's an update queued up it crashes
Not ideal ..
=> #3859 form reducer crash

src/reducers/Entities/VaccinePrescriptionReducer.js, src/reducers/FormReducer.js, src/widgets/VaccinePrescriptionInfo.js
Fixes #3939 
- Was not able to bonus dose as there was no item selected, so no batch to add a bonus dose to. So just remove bonus dosing while refusing
@ArpitaSussol Amazing testing- thanks so much!
=> #3939 can refuse and bonus dose

src/actions/Entities/VaccinePrescriptionActions.js, src/reducers/Entities/VaccinePrescriptionReducer.js, src/widgets/Tabs/VaccineSelect.js
Fixes #3955
- Always try to select a deafult vaccine when navigating to select vaccine tab
N/A
=> #3955 Avoid creating prescriptions with no lines

src/database/DataTypes/ItemBatch.js
Fixes #3948 
- I could recreate some variant of the bug by adding some quantity of an item with 12 doses / vial then dispensed all except for the last quantity. Then I dispensed the very last dose to a patient, and that patient got an extra line with some very tiny amount which seems to be just some 'leftover' quantity from adding/subtracting n stuff.
- So, made the assumption that 1 dose is the absolute minimum quantity an item batch should have (greater than zero) and after having set the quantity of the item batch, if there is still some tiny amount left that is less then one dose, just set it to zero.
- The assumption doesn't work if the doses per vial <1
N/A
=> Add safety around dose setting on an item batch

src/bluetooth/BreachManager.js, src/bluetooth/BreachManager.test.js
Fixes #3757
- Added new test for edge case of temperature logs crossing two breach boundaries (e.g. Too cold for one log, then too hot for 3 logs)
- Implemented logic to track which config the stack of 'potentially breach causing logs' is associated with, if a new log comes in associated with a different config to the stack, reset the stack 
- Makes the breach calculation logic even more confusing than before 😿 
- Previous breach calculation logic should work as before
- There's probably a nicer way of doing this 😆
=> #3757 fix breach boundary crossing detection

package.json, src/localization/buttonStrings.json, src/localization/modalStrings.json, src/pages/SettingsPage.js, src/utilities/getModalTitle.js, src/widgets/modals/DataTablePageModal.js, yarn.lock
Fixes #3968 
Adds a button to settings: `Factory Reset` which prompts for the user's password and gives a small warning
If confirmed, the database is cleared and the app reloaded.
=> add reset option

src/actions/Entities/NameActions.js, src/actions/PatientActions.js, src/database/DataTypes/Name.js, src/database/schema.js, src/database/utilities/createRecord.js, src/reducers/PatientReducer.js, src/sync/incomingSyncUtils.js, src/sync/outgoingSyncUtils.js, src/widgets/modalChildren/PatientEditModal.js
Fixes #3977 
Added a created date to patients created using the **Dispensing** or **Vaccinations** routes.
Checked that it doesn't mess with patients who are created locally after looking them up
There was an issue with the state of created patients. The state isn't cleared after creating through dispensing - so if you looked up a patient after previously creating one, the `createdDate` was set to today's date and the patient updated incorrectly on the server.
This has been addressed with the addition of a 'refresh' action after creation.
=> add created date

src/selectors/prescriber.js
Fixes #3972 
- Default to empty string if no first or last name provided when searching for prescribers (was undefined when going from patient -> prescriber selection. (Maybe making it not undefined is a better fix?)
- Other areas where prescribers are searchable (checked prescriber lookup)
=> #3972 Fix dispensing RSOD

src/actions/Entities/NameActions.js
Fixes #3992
- Casts `createdDate`
=> Add casting of created date

src/reducers/PatientReducer.js
Fixes #3975 
- As per the issue, you can get an error state for this reducer if you click history then really quickly open the ADR modal, then close the ADR modal. This fixes that
Someone actually did this in prod!
=> #3975 Add state resetting

src/actions/Entities/NameActions.js
Fixes #3996 
When createdDate is null, which happens for looked-up patients, the `Date` created is `Invalid Date` which throws an error during `saveEditing`
=> update created date

src/database/DataTypes/ItemBatch.js
Fixes #4010 
- Just checks that dosesPerVial exists before setting newNumberOfPacks to 0
Targetted `master` just because that's where I found it and thought it would be pretty annoying behaviour people might want fixed, can retarget `develop` if preferred for 8.1.0 (but that might be a while away?)
=> #4010 Add check for dosesPerVial before setting newNumberOfPacks to 0

src/pages/FirstUsePage.js, src/widgets/FormInputs/FormPasswordInput.js, src/widgets/modals/DemoUserModal.js, src/widgets/modals/LoginModal.js
Fixes #4026 
- Workaround to update `secureTextEntry` input field styles for consistency with other input fields
Check that the font for password fields looks consistent with other text input fields on the following pages:
- If RN fixes this, we might want to get rid of this stuff since it's a bit confusing?
=> #4026 Workaround RN password input text style

.eslintrc, package.json, src/pages/FirstUsePage.js, src/settings/index.js, src/widgets/modals/LoginModal.js, yarn.lock
Fixes #426 
- In `FirstUsePage` and `LoginModal` read the version from `package.json` rather than trying to access `AsyncStorage`, which doesn't get updated in time when an app is freshly installed to a device.
- Removed `getAppVersion()` from `settings/index.js` as it wasn't used anywhere else (contemplated moving the `package.json` reading to a separate helper under utilities but it's like 1 line so seems redundant?)
- Offroad, migrated a deprecated package `babel-eslint` to `@babel/eslint-parser` as I kept running into the same issue as this guy https://github.com/eslint/eslint/issues/13542 on `FirstLoginPage` when the pre-commit hook runs... as a sidenote, saw a bunch of linting errors running `eslint src` but left them to try not to explode the PR.
Steps to reproduce or otherwise …
=> #426 incorrect version number on install/update

package.json, src/actions/Bluetooth/SensorDownloadActions.js, src/bluetooth/BleService.js
Fixes #4055 ( but in master, so we can release it )
fixes an issue with the sensor connection that was preventing logs from downloading.
=> #4055 sensor logs patch

src/database/utilities/parsers.js
Fixes #3925
Tested out the proposed solution for #3925 🤣 . Things seem to work as expected.
Record created after syncing requisition with `date_order_received` of 00/00/00:
Not sure
=> #3925 Update date parser

src/localization/modalStrings.json, src/widgets/modalChildren/SupplierCredit.js
Fixes #2795 
- Disable confirm button, hide supplier credit dropdown and hide table on supplier credit page if no stock available
- When no stock available for return display message "No batches with stock" (as suggested in the issue by @joshxg)
Don't know if there's any UI convention, made the text big, black and centred? 🤷‍♀️
=> #2795 supplier credits 0 stock misleading

src/widgets/InfoBadge.js
Fixes #3279 
Update the badge numbers after a sync has occurred. Doesn't happen instantly but eventually updates if someone is sitting on the Menu Page and not doing anything.
https://user-images.githubusercontent.com/65875762/120135509-84f21180-c224-11eb-86dd-ab2e877029b9.mp4
Not sure
=> #3279 Update the badge count on sync

src/bluetooth/BleService.js, src/localization/vaccineStrings.json
Fixes #4075 
Removed the option to `autoconnect` as this was causing issues with connecting.
Targeted Master as I thought to push out to Vanuatu ( who are having an issue with sensors, possibly this one? )
=> remove autoconnect option

package.json, src/pages/DispensingPage.js
Fixes #4069
- Add check for patient transactions before attempting to filter for history
- Not sure why eslint's `ignoreTemplateLiterals` doesn't seem to be working correctly so there's a weird comment added 🤔
- Also another offroad because of:
Not sure
=> #4069 Add check for patient transactions before attempting to filter

src/actions/PatientActions.js, src/database/DataTypes/Name.js, src/database/schema.js, src/database/utilities/createRecord.js, src/sync/incomingSyncUtils.js, src/sync/lookupApiUtils.js, src/sync/outgoingSyncUtils.js
Fixes #4068
- Add `[name]barcode` to realm schema. 
- Already exists in desktop with placeholder values (in the format `*[name]code*`)
Not sure
=> #4068 Add barcode field to mobile schema

package.json, yarn.lock
Fixes #4040
- Bump React-Native version to 0.64.2 and tested vaccine dispensing. 
- 🎉  selecting the vaccinator no longer crashes the app
- Didn't do a full regression or anything (did a stocktake?) but seems like a pretty small patch.
=> #4040 Remove app crashing feature from vaccine dispensing

src/widgets/Tabs/PatientSelect.js
Fixes #4089
- Temporarily hide QR scan button until it is ready for release
Possibly could look into implementing an actual feature flag config if this type of thing comes up more frequently.
=> #4089: Hide QR Scan button behind DEV flag

src/widgets/modals/DataTablePageModal.js, src/widgets/modals/StocktakeBatchModal.js
Fixes #4097
- Changed query from `UIDatabase.objects('VaccineVialMonitorStatus').filtered('isActive == True')` to  `UIDatabase.objects('VaccineVialMonitorStatus').filtered('isActive == true')`
- No idea why the capitalisation matters now but didn't before (couldn't see anything in realm release notes? 🤷‍♀️ )
N/A
=> #4097 stocktake batch modal crash

src/database/DataTypes/Item.js
Fixes #4095
- Check filtered transactions before summing doses for openVialWastage
- Not sure why lots of random realm things seem to be breaking 😿 
Not sure
=> #4095 Check for transactions before summing doses

src/widgets/FormInputs/FormPasswordInput.js, src/widgets/modals/LoginModal.js
Fixes #4105
- The issue this component was solving has been fixed here: https://github.com/facebook/react-native/releases/tag/v0.64.2
- Not sure if removing the style thing was a good idea, can revert
- Not sure if the component is needed now, but I guess why not!
- Added `forwardRef` to pass the ref through the custom component
N/A
=> #4105 password not focused

src/pages/FridgeDetailPage.js, src/widgets/VaccineLineChart.js
Fixes #4053
If the `<Svg>` renders more than once, the lines don't show 🤷‍♂️ 
Have changed the line chart, so that it only renders the svg component if the dimensions are set. It was rendering twice due to the `onLayout` event.
A side issue is that this invalidates the functioning of `AfterInteractions` so I've added the loading indicator directly into the chart component.
=> Reduce svg renders

src/pages/RealmExplorer.js
Fixes #4092 #3048 
Always thought it odd that the table search wasn't debounced.
Added some debounce, and prevented searching for tables with name < 3 chars
Also caught and toasted the error, if there is one.
Now looking at #3048 to actually show data
=> Fix realm explorer crash

_config.yml
Fixes #?
Updating the Jekyll theme used by Github Pages to build the static site for the docs. 
Check out https://openmsupply.github.io/mobile/ 
=> Updating Github Pages theme to Just the Docs

android/app/build.gradle, android/app/src/main/java/com/msupplymobile/MainApplication.java, android/settings.gradle, package.json, src/widgets/Tabs/PatientSelect.js, yarn.lock
Fixes #4071
- Adds some code to do some sort of local searching and select the patient if there is a match
Some test codes (needs to exist in mobile for lookup to work):
`placeHolderBarcode`:
`*asdasdasd*` (matches Jose Abad):
=> #4071 QR code patient lookup - local search implementation

src/pages/FirstUsePage.js
Fixes #4124 
Add the ref which allows focus of password field
=> add ref to FirstUsePage

src/pages/CashRegisterPage.js, src/selectors/cashTransaction.js
Fixes #4126 
Resolve a warning when loading the screen and when submitting a payment.
In develop mode:
=> resolve type warnings

src/actions/PatientActions.js, src/database/utilities/createRecord.js, src/widgets/modalChildren/ConfirmForm.js
Fixes #4138 
Two issues with the addresses on looking up patients ( and prescribers )
- If all the fields are undefined then none of the address fields are strings, so the first address in the database is assigned to the incoming patient
- The properties on the incoming patient were incorrect
=> save addresses correctly

src/localization/generalStrings.json, src/sync/lookupApiUtils.js, src/widgets/Tabs/PatientSelect.js, src/widgets/modals/SearchForm.js
Fixes #4072 
- Adds remote patient searching by QR code (needs https://github.com/sussol/msupply/pull/8914 to actually work)
- Adds crude validation to reject QR codes that are longer than `50` chars long (sample Vanuatu National ID we have seen is 21 characters long)
- Small side quest to remove the extra `getAuthorizationHeader` method in `SearchForm`
Might need to look into different parsers for different countries at some point (instead of storing whole thing, depending on what their National ID QR codes look like...). Either coded in mobile or some kind of store pref in Desktop?
=> #4072 remote patient lookup via qr code

src/reducers/Entities/LocationReducer.js, src/reducers/Entities/SensorReducer.js, src/reducers/Entities/TemperatureBreachConfigReducer.js, src/sync/incomingSyncUtils.js
Fixes #4151 
- Adds sensor to temperature log for incoming sync, ensuring temperature logs are related to a sensor when reinitialized.
- Offroad: Added hydrating of the entity stores after a reinit - currently on a full init the entity stores and refreshed, so you for example, get an empty sensor page- work around of some navigating can get you the state back but I don't want to have to explain more "Oh just navigate to this page and then that page and then presto boomo" or "have you tried restarting the app?"
N/A
=> Add sensor to TemperatureLog incomingSync

src/widgets/DatePickerButton.js, src/widgets/DateRangeSelector.js
Fixes #4139
Pass label through to the `IconButton` to be used inside `TouchableHighlight` container. 
Not sure (maybe it's weird to have a label that's only used for the non-circle button?)
=> #4139 Include text in touchable bit of the date picker

src/pages/FirstUsePage.js
Fixes #4154 
Will disable `Import Data` button while setup initializing from the scratch
Setup the mobile connection from the scratch to the desktop mSupply
=> #4154 Disable import data button while initializing

src/database/utilities/constants.js, src/database/utilities/createRecord.js
Fixes #4166 
Generate a patient code independently of the `NumberSequence` as this doesn't guarantee uniqueness
=> change code generation method

src/utilities/getBadgeData.js
Fixes #4182
Added `sensor.isActive` check when calculating cold chain badge count
Targetting `release/8.1.1` because I think we would like it patched before the demo tomorrow.
Now I am unsure about `isPaused` as well but I think it's a little more obvious from the UI at least if a sensor is paused.
N/A
=> #4182 Update getBadgeData.js

src/authentication/SyncAuthenticator.js, src/pages/SettingsPage.js
=> #4179 - Clicking check connection the sync URL is changed

src/database/UIDatabase.js, src/pages/MenuPage.js, src/pages/SettingsPage.js
Doesn't fix #4186 
The export method wasn't displaying error messages, though there was some detail available. 
This doesn't fix the error, but might help diagnose.
=> Fix export messaging

android/app/src/main/AndroidManifest.xml
Fixes #4186 
Actually fixes it this time!
The error on the demo tablet was `ENOENT: open failed: EACCES (Permission denied), open '/storage/emulated/0/Download/...`
and that lead to a suggestion for updating the manifest. Doing so, fixed the problem for me.
=> fix export

src/selectors/Entities/sensor.js, src/widgets/SensorHeader/LastSensorDownload.js, src/widgets/SensorHeader/SensorIsInDangerCircle.js, src/widgets/SensorStatus.js
Fixes #4191 
In the scenario given, multiple Sensor objects were using the same macAddress, with one enabled and the others disabled.
One of the disabled ones was in a current breach - and that resulted in the `SensorIsInDangerCircle` showing the breach.
The badge however, was correctly checking `isActive` for each sensor and showing no active breaches.
I've changed all of the status elements to use the sensor id just in case other scenarios come up.
=> replace mac with id

src/localization/modalStrings.json, src/selectors/Entities/name.js, src/widgets/PaperModal/PaperConfirmModal.js, src/widgets/Tabs/VaccineSelect.js
Fixes #4174
- Pop up a modal asking the user to confirm if they want to proceed if a patient has already received a vaccine in the same day. Originally had a check if vaccine with the same item id as the vaccination in the history was selected but thought it might be too restrictive (sometimes it's bad to have more than 1 shot even if they are different shots? 🤷‍♀️ )
- Also I think this is a bit hacky so I would be keen to hear if there is a better way to do this without creating two modals 😭 , had some struggles trying to make the confirm button function conditional on which button (Confirm vs OK & Next was pressed)
- Also some weird stuff with the Confirm and OK & Next buttons because the `withOnePress` meant if the user cancelled out of the modal they wouldn't be able to press it …
=> #4174 alert if patient already vaccinated in same day

package.json, src/widgets/BarChart.js, src/widgets/PieChart.js, src/widgets/ReportTable/ReportRow.js
Fixes #4200 
Using the demo JSON or generated data from mSupply (_this month's transactions_) resulted in this error, which crashes the app.
The schema validation isn't checking for the optional `axis_label`. Rather than updating mSupply to provide these, I went with avoidance instead, to work around the problem.
Before testing, you'll need to set up a dashboard:
- enable the dashboard module for your store
- configure a report:
- dashboard admin: edit 'this months transactions' and add
- isMobile: True
- reportType: BarChart
- ensure it is active
- Click on 'run report' on the JSON tab to speed up the process
- sync the tablet
Have tested the other chart types, this is the only one with an issue
=> #4200 dashboard crashes app

src/actions/Entities/VaccinePrescriptionActions.js, src/database/DataTypes/Transaction.js, src/database/schema.js, src/database/utilities/createRecord.js, src/selectors/Entities/vaccinePrescription.js, src/sync/incomingSyncUtils.js, src/sync/outgoingSyncUtils.js, src/widgets/Tabs/VaccineSupplementalData.js
Fixes #4198
- Adds `Transaction.customData` to mobile schema/sync utils
- Save siteData into `Transaction.customData` when creating a vaccinePrescription if it exists
Dispensing without siteData (and regular customer invoices) should not create any `customData` for the transactions
=> #4198 save site data on vaccine dispense

src/actions/Entities/NameNoteActions.js, src/actions/Entities/VaccinePrescriptionActions.js, src/database/DataTypes/Transaction.js, src/reducers/Entities/VaccinePrescriptionReducer.js, src/selectors/Entities/vaccinePrescription.js, src/selectors/formSchema.js, src/utilities/ajvValidator.js, src/widgets/Tabs/PatientSelect.js, src/widgets/Tabs/VaccineSupplementalData.js
Fixes #4210
- Looks in realm to try to find the last customData entry against a vaccine transaction and prepopulate supplemental data form with it
- Technically (at the moment anyway) these values _shouldn't_ change very often between jabs (might not be true later if some obscure fields are requested...)
...
=> #4210 Auto populate form with previously entered values

package.json, src/bluetooth/BleService.js, src/utilities/logging/Engine.js, src/utilities/logging/Logger.js, src/utilities/logging/Service.js, src/utilities/logging/Transport.js, src/utilities/logging/index.js, yarn.lock
Fixes #4189 
OK..
- I added a logging mechanism
- I wanted to use the same thing in cold chain
- Possibly use the same thing for omsupply
- The idea is to do `const logger = LoggerService.createLogger("some key for searching")` in a file and then use that logger throughout the file like in `BleService.
- The `bunyan` thing is awesome and great, but seems to be relatively unmaintained so I wanted to ensure we can replace `bunyan` if needed. Since logging can get so widely spread, I wanted to ensure there was a single place to replace bunyan, so I put it in `engine`..
- I wanted to have an easy and consistent way to log to different streams - i.e. bugsnagging, consoles for debugging, flipper for cold chain, files etc
- I wanted a way to adjust the log levels during runtime and also provide …
=> #4189 improved logging

package.json, src/widgets/JSONForm/widgets/Checkboxes.js, src/widgets/JSONForm/widgets/Radio.js, yarn.lock
Fixes #4229 
Adds the checkboxes component, so it is now possible to add this into the JSON form schema:
```
"causes": {
"title": "Possible causes",
"description": "Select which vaccinations you think may have caused this reaction",
"type": "array",
"items": {
"type": "string",
"enum": ["Option One", "Option Two", "Other"]
},
"uniqueItems": true
},
```
with the UI schema:
```
"causes": { "ui:widget": "checkboxes" },
```
and get this in the form:
There's one glitch - a warning is thrown because the form is passing in a text value for the `value` prop, when the component should receive an array. I've found that ignoring this works for me 🤷‍♂️ 
If there are any general areas of the codebase your changes might have side affects on, …
=> support for checkoxes

src/localization/generalStrings.json, src/widgets/JSONForm/templates/ArrayField.js
Fixes #4248 
- Adds support for arrays. Didn't add reordering.
- Looks terrible. Not sure how to make it look better :(
```
const schema = {
definitions: {
patient: {
type: 'object',
properties: {
patientType: {
title: 'Patient type',
type: 'string',
enum: ['Passport', 'Drivers License', 'Other'],
default: 'Passport',
},
patientID: {
title: 'Patient identification',
type: 'string',
},
},
dependencies: {
patientType: {
oneOf: [
{
properties: {
patientType: {
type: 'string',
enum: ['Other'],
},
otherPatientType: {
title: 'What is the identification type?',
type: 'string',
},
},
},
{
properties: {
patientType: {
type: 'string',
enum: ['Passport', 'Drivers License'],
},
},
},
],
},
},
},
},
type: 'object',
properties: {
patientIdentification: {
type: 'array',
title: 'Patient identification', …
```
=> Add ArrayFieldTemplate implementation

src/hooks/useLocalAndRemoteHistory.js, src/pages/DispensingPage.js, src/widgets/JSONForm/JSONForm.js, src/widgets/modalChildren/ADRInput.js
Fixes #4238 
Modifies an ADR JSON schema in order to inject vaccinations for the current patient.
I'm very sorry.
Not an ideal approach, as it relies on knowledge of the JSON schema by the codebase, however it gives us:
- somewhere to store one-to-many vaccinations against an ADR record
- control to the client about how to present the question (wording, placement, form component)
- as well as whether to display the question
To test, you will need this in the ADR JSON schema:
```
"causes": {
"title": "Possible causes",
"description": "Select which vaccinations you think may have caused this reaction",
"type": "array",
"items": { "type": "string", "enum": ["No vaccination history"] },
"uniqueItems": true
},
```
and I have this in the UI schema for the ADR:
```
"causes": { "ui:widget": …
```
=> #4238 show vaccination history when creating an ADR

android/app/src/main/java/com/msupplymobile/MainActivity.java
Fixes #4164 - maybe
The bugsnag [error](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/60a2e05739beba00077b18ff?event_id=60d381f7007f57f947be0000&i=gh&m=ci) has a link to this github comment https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-424704067 where we find out our `MainActivity` is configured incorrectly!
- I can't reproduce the error, but the people said to do this so..
=> #4164 RN cant reload old state

android/app/src/main/AndroidManifest.xml, src/actions/PermissionActions.js
Maybe Fixes #4256
Updates Android permissions to FINE_LOCATION from COARSE_LOCATION
This excerpt from: https://developer.android.com/guide/topics/connectivity/bluetooth/permissions might mean we need ACCESS_BACKGROUND_PERMISSIONS:
- `Services running on Android 10 and higher cannot discover Bluetooth devices unless they have the ACCESS_BACKGROUND_LOCATION permission. For more information on this requirement, see Access location in the background. `
But that is API level 29 (and our minSdk version is 21) so unsure how that works yet - maybe we test this first?
=> #4256 Cold chain sensors not showing up on Android 10

src/widgets/Tabs/PatientSelect.js
Fixes #4269
- Don't dispatch an action to prepopulate supplemental data form 
- Prepopulation code is still there (just not called) in case it is needed later (happy to also remove it if that's tidier) 
N/A
=> #4269 Remove supplemental data pre-population

src/sync/lookupApiUtils.js
Fixes #4216
- Populates some default data in if there is no `itemLine` present in the transaction
N/A
=> #4216 Update patient history lookup to handle empty itemLines

src/widgets/modalChildren/ADRInput.js
Fixes #4288 
Stores the `[trans_line]ID` instead of the display value, when selecting cause of ADR
=> use trans_line.ID as the cause record

src/widgets/Tabs/VaccineSupplementalData.js
Fixes #4280
Switch on live validation for this form
- With this enabled the initial form can't have "required" defined for fields that don't exist until parent fields are selected (e.g. "island", "village" at the top level) ... or it will crash 💥 . I think that is another issue to investigate - why so much crashing when the schema is not 100% 😿
=> #4280 Turn on live validation for the supplemental data form

src/hooks/useLocalAndRemoteHistory.js
Fixes #4277
- When remote records are fetched, con🐱enate them to the local records instead of replacing 
N/A
=> #4277 Add remote entries to local entries when populating patient history

src/actions/Entities/VaccinePrescriptionActions.js, src/database/DataTypes/MedicineAdministrator.js
Fixes #4296 
Note: I haven't tested sync yet, sorry- will do soon. I am in the middle of creating 9million sync out records for testing and it's taking awhile.
- Just changes from creating a refusal name note when refused to creating a vaccination name note, everytime.
- Too much info? :)
=> #4296 name note for all vaccinations

src/widgets/Tabs/VaccineSelect.js
Fixes #4302 
- closes the modal before confirm
- Didn't end up debouncing- I can't trigger multiple invocations so didn't bother 
N/A
=> Add closing of modal before spinning

src/localization/generalStrings.json, src/widgets/JSONForm/JSONForm.js
Fixes #4239 
- The original error was from `json-pointer` using an invalid reference. So, Catch that and set an error state.
- Wanted to use an error boundary with `componentDidCatch` but 1) event handlers does get caught (can be worked around with `setState`, though) and the nail in the coffin for that idea 2) it's working super funky on react-native. I believe it's not catching in development builds from what I can google.
Use this schema:
```
const invalid = {
type: 'object',
title: 'Extra information',
required: ['patientDemographicData', 'island', 'x'],
};
```
- Looks like this:
- Looks like this with the keyboard up.. I thought it was kinda cool looking... but 🤷 
- Had no idea what to put as the error message, so feel free to change/suggest changes..
- At the moment you'll be able …
=> #4239 catch invalid json schemas

src/actions/Entities/VaccinePrescriptionActions.js
Fixes #4310 
- Adds `refusalReason`  into the vaccination event.
N/A
=> #4310 Add refusalReason into vaccination event name note

src/widgets/FormInputs/FormDOBInput.js
Fixes #4327 
As per the issue - rounding down the age value rather than a numerical rounding. So patients who are `23.9` years old show as `23`
=> round down age value

src/sync/incomingSyncUtils.js
Fixes #4328 
`[name]female` was not being set for incoming sync requests
=> sync patient female field

android/app/build.gradle, package.json, yarn.lock
Fixes #4253 - doubt it!
- Bugsnag bump: https://github.com/bugsnag/bugsnag-js/releases - seem to be a lot of bug fixes, some crashes 🤷 
- JSC new version for the first time in like 3 years https://github.com/react-native-community/jsc-android-buildscripts/releases/tag/v250230.2.1 - need to wait for RN to start using it, usually, but can force it. It has this fix which looks promising, to me! https://github.com/Kudo/jsc-android-buildscripts/pull/1 - Can check the JSC loaded on your app using `adb logcat | grep "JavaScriptCore.Version"`
- Do `yarn clean-mac-cache` before running this as theyre native module bumps
=> #4253 upgrade jsc

src/widgets/BreachCard.js
Fixes #3981
- Adds °C to the 'Average Temperature' breach card
N/A this is quite a small change...
=> #3981 Add °C to Average Temperature Breach Card

src/selectors/Entities/temperatureBreachConfig.js
Fixes #3966
- When a temperature approaches a threshold (i.e. cold temperature threshold = hot temperature threshold), make the offset 0.5 degrees celsius, rather than 0.1. This matches the step amount configured in the `TemperatureEditor` component.
Pretty lazy change (could have tried some fancy rounding maths), but it doesn't really make sense to have or allow the hot and cold temperature thresholds to be within 0.1 degrees of each other, I think (that would be a really fragile vaccine?!? 💉 )
=> #3966 Adjust threshold temperatures to match the step amount

src/widgets/VaccineBarChart.js, src/widgets/VaccineLineChart.js
Fixes #3984
As per the title (see below with dodgy test data):
Didn't do anything about cumulative breaches (though it was mentioned in the original issue) as I think it could get quite cluttered with 4 similar looking lines on the chart - esp if the cumulative/consecutive limits are very close to each other ... 
Maybe could use different colours/line styles (e.g. a broken line?). Would probably need some kind of legend 🤔
=> #3984 Replace min/max domain lines with hot/cold consecutive breach lines

src/utilities/formInputConfigs.js, src/widgets/FormInputs/FormDOBInput.js
Fixes #4350 ?
The date of birth is defaulting to the current date and that was causing issues with the validation for me - strangely, it was validation in the wrong direction: the `FormDOBInput` was valid, though the data in it was out of sync internally.
It did result in the observed effect though, that the form was invalid even though there was something in the age field and therefore a calculated value in the dob text field.
Default the DOB value to blank - if this field is required the validation is handled correctly now, with the validation error shown on form load.
=> DOB Defaults

src/widgets/JSONForm/widgets/DatePicker.js
Fixes #4348
- Update JSON Form DatePicker format to align with other areas of mobile
Not sure if this impacts any reporting/dashboards...etc
=> #4348 Update JSONForm DatePicker format to align with rest of mobile

src/widgets/JSONForm/widgets/DatePicker.js
Fixes #4367
- Adds the ability in mobile to disable past/future dates via uiSchema config
`"date": { "ui:widget": "DateWidget", "ui:options": { "dateRange": "past" } },`
`"date": { "ui:widget": "DateWidget", "ui:options": { "dateRange": "future" } },`
`"date": { "ui:widget": "DateWidget" },`
- The patient hub requires a separate update/PR
- Lots of ways to do this change, alternative suggestion: https://github.com/openmsupply/mobile/issues/4367#issuecomment-901670153 - went with UISchema update as I thought of it as more of a UI/widget specific concern rather than an underlying data thing (although could work either way)
=> #4367 Add dateRange option to JSONForm DatePicker

src/reducers/ModulesReducer.js
Fixes #4047
- Removes the presence of dispensary menu item from triggering module section to appear (as the Dispensary was moved into the same menu section as Customer Invoices / Customer Requisitions).
Is the dispensary actually a module? 🤔
=> #4047 Remove dispensary from usingModules check

src/authentication/SyncAuthenticator.js
Fixes #4380
As per PR title
N/A
=> #4380 Re-throw error if error occurred during authentication

src/sync/outgoingSyncUtils.js
Fixes #4334
- Adjust the date format to not include offset when syncing to server
- e.g.
Send `1991-12-24T11:00:00.000Z` instead of `1991-12-25T00:00:00+13:00`
I'm kind of undoing a change in https://github.com/openmsupply/mobile/pull/2101 ... not sure if something else has changed since then, but testing locally (where both mobile and mSupply Desktop are running in NZT) this change stops the days from appearing a day in the past on the server.
=> #4334 Update dates for nameRecords

src/pages/DispensingPage.js, src/selectors/Entities/name.js, src/widgets/modalChildren/ADRInput.js
Fixes #4414
Update ADRInput to pull all local vaccinations (from name_note records) instead of filtering on transactions (as the filter doesn't work anymore).
=> #4414 Update ADRInput to look in correct place for vaccinations

src/pages/CustomerRequisitionPage.js
Fixes #4416
- One line update to pass in a rowState
Probably none - took me longer than I think it should have to spot, lol.
=> #4416 Customer requisition row not updating immediately on edit

src/localization/authStrings.json, src/pages/FirstUsePage.js, src/pages/SettingsPage.js
Fixes #4424
- Super minor change to trim extraneous '/' characters at the end of an otherwise valid url. See issue for history. 
- Minor offroad for grammar (side note: the 'Make sure you know what you are doing' prompt always makes me hesitate, feels like such a bold claim).
- FirstUsePage does whitespace trimming `onBlur()`, didn't put this there because that might be weird for users to see it being edited for them. Thought it was better to let them think it was fine and just clean it up in the background.
=> #4424 trim trailing '/' chars from sync url

src/sync/incomingSyncUtils.js
Fixes #4484
Adds updates to tables linked to retained `Name` records when merged.
Doesn't fix Realm problem with deleting records that are currently being edited or viewed (going to log as a separate issue).
- Can't be working with a patient when it is merged or deleted via sync (although if you happen to be and see the crash, when relaunching the app after the initial crash it will be fine)
=> #4484 Add Name linked objects to merge

src/widgets/Tabs/PatientSelect.js
Fixes #4511
Very weird bug 😖 
- Offroad: Some docstring updates (just came across while debugging)
- Handle `handleUpdate` (for some reason this function would often be holding onto an incorrect version of the '`completedForm`', especially when swapping between form fields). The `PatientSelect` component re-renders a few times every time it gets loaded or the form is modified... so suspect it was picking the value up before the form was updated properly? (and subsequently wiping out the old form data 🤔 ). Honestly, I didn't get to the very bottom of it but this seems to stop the bizarre search behaviour I was seeing from happening.
- I've not actually been able to replicate the **exact** issue in Adam's original video (i.e using …
=> #4511 Patient search in Vaccination Module returning bad results

src/actions/Entities/NameActions.js
Fixes #4516
- When saving a patient after a vaccination - refresh `name.name` (as `firstName` and/or `lastName` may have been modified)
Patients edited in the Dispensing module appear to be fine (name editing code is different depending on which module you are in...)
=> #4516 Update name.name on patient edit (in vaccine module)

src/actions/Bluetooth/SensorDownloadActions.js, src/actions/BreachActions.js
Fixes #4549 (I think!?)
- Filters breach configs so that only consecutive configs are used when calculating consecutive breaches
- Have reordered operations so that the app will attempt to record consecutive breaches before trying to clear logs (I think I saw log clearing fail causing consec breach creation to be skipped, although now I can't replicate so I'm not 100% sure I saw what I thought I saw - think the change is safe enough anyway).
Have created this issue to try to clear logs more times before giving up: https://github.com/openmsupply/msupply-ble-service/issues/4
=> #4549 missing consecutive breaches

package.json, src/Store.js, src/actions/Bluetooth/SensorDownloadActions.js, src/mSupplyMobileApp.js, src/reducers/Bluetooth/SensorDownloadReducer.js
Fixes #4568 ???
- The flow which causes *an* issue is that 'minimising' or sending to the app to the background 'regularly', doesn't trigger an unmount. But using the `back` button does (on the menu page), so the scheduler get's removed. When entering the foreground again, `onUpdate` isn't called, so the scheduler is not started again.
- Added a call to start the download scheduler on mount and left it also in the on update lifecycle method. This is because the passive download needs to potentially start after having synced from the server, also.
=> Add restarting scheduler on mount

package.json, src/globalStyles/buttonStyles.js
Fixes #4525
- Widens the menu button by the minimum amount possible to make the text appear on a Samsung T500 device.
- Tried shrinking the fontSize down by 1 unit which also fixes the problem, but then the text looks a bit small on other devices.
- Had another super hacky idea to check if DeviceInfo.getModel() returned 'SM-T500' or 'SM-T505' to shrink the font. But that's super ick. Am open to other/better suggestions
=> #4525 Make the menu button a tiny bit wider

android/app/src/main/AndroidManifest.xml, android/app/src/main/res/xml/network_security_config.xml
Fixes #4567
- This PR would add android device policy to allow not ssl connection which is by default disabled for android devices.
- User would be able to connect to http url apis after this change.
=> #4567 allow all http connection

src/database/DataTypes/Requisition.js, src/pages/CustomerRequisitionsPage.js
Fixes #4592 
- The deletion sync was not syncing back to sever, resulting in sever still retaining the requisition that was deleted on mobile.
Suggested Customer Requisition deletion should delete its corresponding CI too.
None
=> #4592 Fix Response requisition rouge CI problem

src/database/DataTypes/Requisition.js, src/database/DataTypes/RequisitionItem.js, src/localization/modalStrings.json
Fixes #4562
- Disable finalisation of Customer requisition with all of the lines with 0 supplied quantity.
- In desktop, this has always been disallowed so replicating desktop behavior.
None
=> #4562 Customer Requisition with no Supplied quantity creates blank CI when finalised

dev_scripts/translation.js
Fixes #4618
Noticed while translating Pt strings for issue #4613. When one of the localization files is missing the language. i.e: `pt: {...}` the script `yarn translations export pt` was failing. Not it would simply add all strings mentioned on the main language with empty values to be added on the language exported. 
Also when importing checks for empty string and add the main language instead. To prevent from no string presented in the UI.
N/A
=> #4618 fix translation script export non existing lang

src/actions/UserActions.js, src/mSupplyMobileApp.js, src/pages/MenuPage.js, src/reducers/UserReducer.js, src/widgets/modals/LoginModal.js, src/widgets/modals/index.js
Fixes #4625
new `currentLanguage` added to user state which gets set with the language store in settings. Also needed to add to the MenuPage mapPropsToState so it get triggered by a change on this state = reason why I added the flag showing on the bottom of the main Menupage. Hope you will like it : 9
The second time wasn't taking effect. Should be sorted now.
Sync modal, settings, other pages and Menu.
=> #4625 fix language effect on menu app

src/utilities/formatters.js
By default take date format to 'MM/DD/YYYY'
Fixes #4640 
Change date format to 'MM/DD/YYYY'
=> #4640 Showing invalid date

src/widgets/modals/LoginModal.js
Fixes #4644
- Tiny adjustment to use the selected language rather than the previously saved one (thought I'd just fix while passing through for the Kiribati updates - and was also curious about the recent localisation updates)
N/A
=> #4644 Update to use selected language rather than previous language

src/widgets/StepperInputs/DurationEditor.js, src/widgets/StepperInputs/TemperatureEditor.js
Fixes #4665
A super tiny change to format the temperature breach configs to 1dp instead of 2dp (temperature readings are 1dp only, and configs can only be incremented/decremented in steps of 0.5). 
Problem will still probably occur if anyone tries to configure a breach threshold of -100 degrees celsius or lower.
=> #4665 Remove last digit from temperature breach config

src/selectors/Entities/name.js, src/utilities/formatters.js, src/utilities/parsers/index.js, src/utilities/parsers/vaccinationDateParser.js, src/utilities/parsers/vaccinationDateParser.test.js
Fixes #4724
- Best effort attempt to read dodgily entered vaccination dates based on what Kiribati have in their database (🙀 )
- In cases where it's impossible to determine (e.g. 04/03/2022 could be read either as 4th of March, or 3rd of April), we use these defaults:
- D/M/YYYY (if the year is at the end - we assume they are using the standard mobile format)
- YYYY-MM-DD (if the year is at the beginning - we assume they were using the ISO format)
Some users may get strange results - but there's realistically no real way to completely fix this properly without a manual review of a lot of the dates.
I'm really sorry to anyone who has to read this, and if there is a better solution, all 👂 !
=> #4724 Try a wider variety of formats when parsing vaccination dates

package.json, src/actions/Entities/NameNoteActions.js, src/localization/vaccineStrings.json, src/widgets/modals/VaccinationEvent.js
Fixes #4691
https://user-images.githubusercontent.com/65875762/168718354-494d5a41-d6c9-4405-b5a8-1f583d2c0489.mp4
- Adds the ability to edit the PCD linked to a vaccination event via the vaccination event modal.
- This just overwrites the historical PCD, it doesn't create a new one, due to the complexity of linking multiple dependent name_notes. This has a few implications:
- If the same PCD was used for two vaccinations (a new PCD is only created if there were updates to the form during vaccination) - when the PCD is edited, both of the vaccination records will be linked to the updated data.
- No continuous audit trail within mobile (although speaking with some 4D experts it seems like the changes can (if needed, and with …
=> #4691 edit pcd via vaccination event modal

src/hooks/useLocalAndRemoteHistory.js
Fixes #4743
- Correct incorrect duplicate detection
- Previous filter was incorrectly looking for records without ids, name_notes still have ids so this was failing every time
- Adjusted to account for date discrepancy between the name note and the date returned via the mSupply api
N/A
=> #4743 Fix broken name note duplicate filter

src/widgets/Tabs/ItemSelect.js
Fixes #4394
- Update useEffect hook to dispatch `PrescriptionAction.reloadItems()` to store, everything else was already in place.
N/A
=> #4394 Items not showing up when dispensing to patients

src/widgets/JSONForm/widgets/Checkbox.js, src/widgets/ToggleBar/ToggleBar.js
Fixes #4755
- Trying to get it out of the way so it doesn't clutter the incoming functional changes :X
rather than 
Unsure
=> #4755 Style updates to Checkbox/Togglebar

src/authentication/DemoSiteRequest.js
Fixes #4759
- Allow email TLD to have more than 3 chars
N/A
=> #4759 Allow length of > 3 for email TLD when requesting demo store

src/actions/Entities/NameNoteActions.js, src/localization/buttonStrings.json, src/localization/vaccineStrings.json, src/widgets/Tabs/PatientSelect.js, src/widgets/modals/VaccinationEvent.js
Fixes #4714
- Butchered the UI in an attempt to allow easier data editing:
- ![image](https://user-images.githubusercontent.com/65875762/173726328-5633bb7b-75bd-490e-ae44-01b38fca5b48.png)
- Updated modal to grab the actual name note - it was previously working with data mapped for the history view 
- Added 'isDirty' check to not update if the contents are the same
Prerequisites:
- Update VaccinationEvent JSON schema:
- [VaccinationEvent.txt](https://github.com/openmsupply/mobile/files/8905265/VaccinationEvent.txt)
- [VaccinationEvent-UI.txt](https://github.com/openmsupply/mobile/files/8905267/VaccinationEvent-UI.txt)
- Too many buttons? 🤔 Bit awkward because the data is stored in 3 different places though conceptually to users …
=> #4714 Add ability to edit supplemental data form

src/database/DataTypes/Name.js, src/database/DataTypes/NameNote.js, src/database/schema.js, src/hooks/useLocalAndRemotePatients.js, src/selectors/Entities/name.js, src/selectors/dispensary.js, src/sync/incomingSyncUtils.js, src/sync/outgoingSyncUtils.js
Fixes #4775
- Changes to include the soft delete flag on `name` and `name_note` objects
- Check flags when rendering patient lists and vaccination history lists on Kiribati datafile and hide `is_deleted` ones.
N/A
=> #4775 Flags to allow soft deletion of name notes and patients

src/actions/Entities/NameNoteActions.js, src/actions/Entities/VaccinePrescriptionActions.js, src/database/DataTypes/NameNote.js, src/database/utilities/createRecord.js, src/localization/buttonStrings.json, src/localization/modalStrings.json, src/reducers/Entities/NameNoteReducer.js, src/widgets/modals/VaccinationEvent.js
Fixes #4796 
- Added "Delete button":
Before anyone asks - the color of this button is DANGER_RED. Yes, it looks orange but I guess this is a part of the design code (I don't know honestly)
- Clicking "Delete button" makes it impossible to implement further changes to the form.
- The vaccination associated with the deleted NameNote will not be visible in the UI anymore. The only way to get the information about the deleted Name Notes is to look into the data base.
=> #4796 Kiribati: soft delete of vaccinations 

src/localization/modalStrings.json, src/widgets/CircleButton.js, src/widgets/FormInputs/FormToggle.js, src/widgets/Tabs/PatientEdit.js, src/widgets/Tabs/PatientSelect.js, src/widgets/ToggleBar/ToggleBar.js
Fixes #4792 (and small bug fixed #4783)
My first PR here YAY
Added an alert to the patient select and patient edit tabs to prevent vaccine dispensing if a patient is deceased.
Also, fixed a bug in the toggle styling so now "Gender" and "Is deceased" are shown correctly. Did it here as currently it is very broken and would be quite confusing for the clients.
1.
2. 
3. 
4.
- I'm not sure why we are able to change patient status to "Deceased" during the vaccination -> probably we should disable it in the future
=> #4792 Kiribati: Prevent giving vaccine to deceased patient

src/localization/modalStrings.json, src/widgets/modals/VaccinationEvent.js
Fixes #4801
If store name is saved on vaccination event, the alert containing store name is shown.
=> #4801 Kiribati: a pop-up message to contain the name of the store where vaccination was made

src/widgets/JSONForm/widgets/DatePicker.js
Fixes #4785
- Previously the datepicker, when pulling date from sever, was getting the date in wrong format, saving this date, if the date was converted to dd/mm/yyyy format would show wrong date.
- if you click the datepicker button, the date selected would be today's date not the date in input box.
- If you try to edit the date in input box mid-way or make it blank, and open datepicker button the app would error out.
- if you add date in correct format and save, the saved date would be in wrong format, that is day and month swaped.
This datepicker is not limited to vaccination event details page so we have to look at other pages where this datepicker is used too.
Save or edit might bug out by taking invalid date if this code …
=> #4785 Update date-picker to properly set initialValue

src/widgets/modals/VaccinationEvent.js
Fixes #4823
Removed vaccines out of stock from the dropdown list
=> #4823 mSupply crashes when changing the vaccine to the one that is not in stock currently

src/widgets/FormControl.js, src/widgets/JSONForm/widgets/Checkbox.js, src/widgets/JSONForm/widgets/DatePicker.js
Fixes  #4838
- Stop triggering of redux state update for patient list when the window closes. 
- There are some other checkbox and datepicker error fixes too which is actually not related to the issue linked.
This issue fixes a bug in FormControl component, which is one of the most generic components in the application. This effects all FormControls including input boxes, date of birth, date controls, dropdown and sliders. Maybe we should generally test them to see if they work properly.
=> #4838 Fix PatientSelectComponent bugs out when closed

src/widgets/modalChildren/PatientEditModal.js
Fixes #4849
- Update canSave conditional logic logic.
- Add button disable option for delete button
=> #4849 Fix save and delete button was still showing for remote patients

src/widgets/modals/VaccinationEvent.js
Fixes #4844
Disabled button after clicking
=> #4844 kiribati Vax: Editing vaccination event, clicking save buttons multiple times quickly is crashing apps and which is corrupting the record

src/hooks/useButtonEnabled.js, src/widgets/Tabs/PatientEdit.js, src/widgets/Tabs/VaccineSelect.js, src/widgets/Tabs/VaccineSupplementalData.js
=> #4820 Disabled next button during submission enable it afterwards

src/widgets/modalChildren/MultiSelectList.js
Fixed chopping of label `Done` in model window
Fixes #4847 
On modal window, the confirm button is `Done` which should be visible accurately without any chopping of text.
=> #4847 Fixed chopping of label Done

src/widgets/Tabs/VaccineSelect.js
Fixes #4871
disabled the "Confirm" button after clicking.
=> #4871 App hangs/keeps on loading forever when OK button is clicked multiple times while entering a vaccination event 

src/actions/PatientActions.js, src/globalStyles/dataTableStyles.js, src/hooks/useLocalAndRemotePatients.js, src/localization/dispensingStrings.json, src/localization/generalStrings.json, src/reducers/PatientReducer.js, src/sync/lookupApiUtils.js, src/widgets/SimpleTable.js, src/widgets/modals/SearchForm.js
Fixes #4842
Adds two xliffs
- "no_records": "No record(s) found."
- "patient_already_deleted": "'The patient has already been deleted. You cannot sync this patient back."
=> #4842 Fix Deleted patients again shows up

package.json, src/actions/PatientActions.js, src/globalStyles/dataTableStyles.js, src/hooks/useLocalAndRemotePatients.js, src/localization/buttonStrings.json, src/localization/dispensingStrings.json, src/localization/generalStrings.json, src/pages/StockPage.js, src/pages/dataTableUtilities/actions/constants.js, src/pages/dataTableUtilities/actions/tableActions.js, src/pages/dataTableUtilities/getPageInitialiser.js, src/pages/dataTableUtilities/reducer/tableReducers.js, src/reducers/PatientReducer.js, src/sync/lookupApiUtils.js, src/widgets/SimpleTable.js, src/widgets/Tabs/VaccineSelect.js, src/widgets/modalChildren/MultiSelectList.js, src/widgets/modals/SearchForm.js
Fixes #4647 
Added a toggle on `Current stock` having label `Hide zero stocks`
=> #4647 current stock add toggle to hide zero stock

src/widgets/Tabs/PatientSelect.js
=> #4887 New patient button should only go to tab 2 in Vaccine dispensing

src/actions/Entities/VaccinePrescriptionActions.js
Fixes #4913
Steps to reproduce the behaviour:
1. This may not be reproducible easily as our code is stopping the editing of patient detail section of vaccination event through UI restriction. But we know the unnecessary sync queue happens.
3. So to test this condition do this:
1. Use two tablets
2. In tablet 1 create a patient and its vaccine event. Sync it.
3. In tablet 2 pull the changes.
4. In tablet 1 again edit the patient details, dob or something and sync it too.
5. In tablet 2 without syncing in the step `iv` updates, create a vaccine event. Since the patient is from Tablet 1 you would not be allowed to edit the patient so you have made no changes to the patient details but since you have not synced tablet 1 changes from step `iv` you would still see the old dob which is ok.
6. …
=> #4913 Vax event creation and editing should not trigger patient update if the current store is not patient's home store

src/widgets/modals/VaccinationEvent.js
Fixes #4909
- Previously a variable customDataObject was being set that never changes with form changes.
- In subpage 3 vax event save, subpage 2 additional details are also saved.
- Now subpage 2's save uses the state object updatedSupplementalDataForm which does change with form change.
- We needed to pass in updatedSupplementalDataForm to the subpage 3 save method instead of customDataObject to have this issue fixed.
=> #4909 Subpage 2 Additional details' changes are overridden by Subpage 3 Vax Event changes

src/widgets/JSONForm/widgets/Checkboxes.js, src/widgets/JSONForm/widgets/Select.js, src/widgets/modals/VaccinationEvent.js
Fixes #4925
Gray out form control and buttons of Vaccination Events detail edit page when the page is not editable.
=> #4925 Event details subform save buttons are not behaving consistently 

src/pages/dataTableUtilities/reducer/tableReducers.js
Fixed toggle failure on Current stock and Stocktake by undo the code changes on `toggleStockOut` reducer function
Fixes #4894 
Just undo the refactored code changes on `toggleStockOut` reducer function
=> #4894 fixed toggle failure of current stock and stocktake

src/widgets/FormInputs/FormDOBInput.js, src/widgets/JSONForm/widgets/DatePicker.js
Fixes #4892 #4932
- Datepicker had legacy bugs
- When you add date with wrong (malformatted) date in text input of datepicker the app would crash
- Adding date in any other format than MM/DD/YYYY would cause problems. Including M/D/YYYY, MM/D/YYYY format etc.
- Add M/D/YYYY, MM/D/YYYY format date would validate JSON schema but fail in datepicker open.
=> #4892 Fix dob field issues

android/build.gradle
Fixes #4987
What [this fix](https://stackoverflow.com/a/74334163) will do is apply an exclusiveContent resolution rule that will force the resolution of React Native Android library, to use the one inside node_modules. 
=> #4987 Fix React-native failed to build

src/widgets/modals/LoginModal.js
Fixes #4997 
Setting button on Login window moved to left to Language button.
Just add Icon for settings, ignore its label.
=> #4997 setting moved to left to language button on login form

src/pages/dataTableUtilities/actions/rowActions.js
Fixes #4678 
Aiming to stop crashing the App upon deletion like this:
=> #4678 - Stopping app to crash

src/database/DataTypes/Stocktake.js, src/database/DataTypes/StocktakeItem.js, src/localization/modalStrings.json
Fixes #4974 
Check if reason is activated in desktop and not set to at least one stock take batch then gives alert when finalizing. 
=> #4974 stocktake reason should be mandatory

src/sync/incomingSyncUtils.js, src/sync/outgoingSyncUtils.js
Fixes #5037
- Option field from Requistion line (RequisitionItem) was not being synced. I added option id to the sync in and out code and it worked.
=> 5037 Fix reason would not show on Requisition on Remote desktop

src/widgets/FormInputs/FormSlider.js
Fixes #5043 
- In `src/widget/FormInputs/FormSlider.js`, the proptype for isDisabled was set to PropTypes.isDisabled which not an available prop-type so React native thought it was a function and when it got boolean it freaked out and crashed.
None
=> App crashes while creating policy in prescription dispensing

src/widgets/modalChildren/PatientEditModal.js
Fixes #5044
- Only check for surveySchema && surveyForm && nameNoteIsValid if vaccine module is enabled
The vaccine module for Kiribati has added surveySchema && surveyForm && nameNoteIsValid checks.
=> 5044 not able to create a patients

src/database/utilities/createRecord.js
Fixes #5061
While creating or viewing supplier requisition with program that has indicators.
If you click on indicators button to see the indicator tab the app crashes
None
=> 5061 Viewing indicators app crashes

src/database/DataTypes/Stocktake.js, src/database/DataTypes/StocktakeItem.js
Stocktake reasoning issue fixed
Fixes #5039 
One should set reason to a valid batch if reasoning is activated
- It looks at only counted items, then check all batches of that items.
- If the batch has counted and there is quantity difference then look at its valid reason.
- If reason is not set then don't allow to finalize otherwise finalize
=> #5039 Stocktake reasoning resolved

src/pages/StocktakeManagePage.js, src/utilities/checkIsObject.js, src/utilities/index.js
Fixes #5068
This issue was introduced by code here https://github.com/openmsupply/mobile/commit/f5f3b612728adec9ccd2ec9c31ed81397933ad94.
Previously StocktaakeManagerPage was expecting an object as prop but was getting undefined and that gave this warning:
I made the changes in the commit f5f3b612728adec9ccd2ec9c31ed81397933ad94 to fix this warning and it spawned this error because now that the default value is empty object it is no longer undefined and the methods that had undefined checks were getting called.
I fixed with by adding an checkIsObjectValuesEmpty check method instead of object cheack.
=> 5068 Fix New Stock take crashes

src/widgets/modals/StocktakeBatchModal.js
If reason is active (if both negative and positive reasons are enabled) then reason column must be visible to all items including vaccines.
Fixes #5086 
Reason column is visible to vaccine items too even `Open vial wastage` reason is disabled
=> #5086 Reason column should be visible to all items

src/pages/DispensingPage.js, src/pages/PrescriptionPage.js, src/widgets/FormControl.js, src/widgets/FormInputs/index.js, src/widgets/index.js, src/widgets/modalChildren/ADRInput.js, src/widgets/modalChildren/PatientEditModal.js, src/widgets/modalChildren/index.js, src/widgets/modals/InsurancePolicyModel.js, src/widgets/modals/PrescriberModel.js, src/widgets/modals/index.js
Fixes #5080
In FormControl, which is shared by all, there is a useIsFocused check that sets isFocused to true when the form control comes in focus. But the problem is in case case of Dispensing > Prescription Page the page are loaded as Wizard pages. The pages take focus but the models are intitialised way below in the hirirarchiy, in Dispensing page iteself and when the models are activated from a button click in any of the Wizard tab page the thus loaded model do not take focus.
This stops initialisation of the FormControl and cause the UI to be unresponsive or submit blank values if saved (since whatever you typed is not stored or tracked).
I did some extensive testing and realised that we do not really need the page be on foucs before initialising the FormFields. In fact we can start …
=> #5080 Fix crash when Entering The Details of Insurance Policy in Mobile App

src/widgets/modalChildren/PatientEditModal.js, src/widgets/modals/InsurancePolicyModel.js, src/widgets/modals/PrescriberModel.js
Fixes #5097
Use useIsFocused to check if the model is in focus. The background one would have this value returned to false and foreground one has it to true. Add this isFocused check in model visible prop of the model.
=> 5097 Fix Instances of same model in different nested routes opens multiple  models in background

src/pages/dataTableUtilities/actions/cellActions.js, src/widgets/modals/StocktakeBatchModal.js
Fixes #5099
If the user submits wrong format number the system should be wise enough to stop taking input when the format is wrong.
None
=> 5099 Stocktake batch sell price crash

src/database/utilities/createRecord.js, src/widgets/PrescriptionInfo.js
Fixes #5101
Survey data needs to be loaded for it to show up in the edit patient window. It is loaded on the edit button click. The button at the front patient select table in dispensing page does load survey data. The button inside does not. Make sure the button inside loads it too.
None
=> 5101 Patient survey demographic data does not load

src/localization/modalStrings.json, src/selectors/patient.js, src/utilities/formInputConfigs.js, src/widgets/FormInputs/FormDOBInput.js, src/widgets/Tabs/PatientEdit.js, src/widgets/modalChildren/PatientEditModal.js
Fixes #5132 
Check for local duplicity of patient when creating new.
If patient already exists with same lastName, firstName, and dateOfBirth then we need a confirmation modal.
Either we can cancel the duplicity or can create duplicate patient.
@bijaySussol once the above confirmation title `Are you sure you want to duplicate this patient?` approved, we could need its Chinese translation.
=> #5132 check for local duplicity of patient

src/database/DataTypes/RequisitionItem.js, src/pages/SupplierRequisitionPage.js, src/utilities/prediction/macroEyes.js
Fixes #? n/a
Updates the way we fetch predictions from the ME API:
- Update `SupplierRequisitionPage` request object to use default `data` variable to get requisition info
- Remove need for `requestedItems` to be greater than 0 to make API call. Will fetch from the server any time Use Suggested Quanitities button is clicked
- Update `Requisition` item `predictedQuantity` field default to -1
- ME prediction calculation supports suggested quantity = 0
- Added logging function
- Open any requisition
- Click Use Suggested Quantity button
n/a
=> Fetch all predictions

src/database/DataTypes/RequisitionItem.js, src/pages/SupplierRequisitionPage.js, src/utilities/prediction/macroEyes.js
Fixes #5212 
Fixes error that causes crashing when `Use Suggested Quantities` button is clicked
- Go to Requisition page
- Click `Use Suggested Quantities`
=> Fix undefined in fetching requisition

src/selectors/Entities/name.js, src/selectors/patient.js, src/widgets/Tabs/PatientEdit.js, src/widgets/Tabs/PatientSelect.js, src/widgets/modalChildren/PatientEditModal.js
Fixes #5215 
Mobile > In the vaccination module > Name duplicity check alert should be generated for new patient.
Check for local duplicity of patient when creating new.
If patient already exists with same lastName, firstName, and dateOfBirth then we need a confirmation modal.
Either we can cancel the duplicity or can create duplicate patient.
=> #5215 fixed alert issue for name duplicity check

src/utilities/formInputConfigs.js
Fixes #5223 
Able to dispense vaccine to existing patient without playing with dob.
=> #5223 fixed dob issue and dispense vaccine

src/selectors/patient.js
Case sensitive should be ignored to check name duplicity
Fixes #5237 
Creating duplicate name will be checked and alert generated by ignoring the case sensitive of name.
=> #5237 Case sensitive should be ignored to check name duplicity

src/actions/PatientActions.js, src/selectors/patient.js, src/widgets/PaymentSummary.js
#5220 Fixed app crashing after editing patient
Fixes #5220 
Now, app won't crash after editing patient during dispensing process.
=> #5220 Fixed app crashing after editing patient

src/widgets/FormInputs/FormDOBInput.js
Fixes #5308 
If age below 1 year then it would be shown with months and days e.g. 3 months 23 days.
=> #5308 display age in years months days

src/sync/incomingSyncUtils.js
#5406 don't create blank supplier requisitions
Fixes #5406 
For an existing transaction if there is linkedRequisition, just get it if exist don't try to create new requisition.
=> #5406 don't create blank supplier requisitions

src/widgets/FormInputs/FormPasswordInput.js, src/widgets/icons.js
Fixes #5394
Adds a button to toggle the password visibility. This applies to both the login and initialisation screens:
https://github.com/msupply-foundation/mobile/assets/9192912/e866acf4-4ba5-4263-b6f4-ba3adf62681a
=> Show password button

src/widgets/modalChildren/PatientEditModal.js
=> #5271 fix annoying alert to confirm duplicate patient

package.json, src/sync/incomingSyncUtils.js
Fixes #5539 
Creates blank requisition in case requisition lines get synced before its requisition to the mobile.
[v8.7.1-rc1](https://store3.gofile.io/download/web/618cc9eb-3222-4cbf-94a9-fd684319aff4/mSupplyMobile-8_7_1-rc1-universal-release.apk)
=> 5539 fix lines disappearing in customer requisition

package.json, src/dataMigration.js, src/database/DataTypes/Item.js, src/database/DataTypes/Requisition.js, src/database/DataTypes/Stocktake.js, src/database/DataTypes/StocktakeBatch.js, src/database/DataTypes/StocktakeItem.js, src/database/utilities/createRecord.js, src/utilities/dailyUsage.js
Fixes #5544 
- Handles creating stocktake for broken master list items (i.e items with no linked to them)
- Handles other broken item batch undefined error while viewing existing broken stocktake (most probably for existing civ stocktake)
- Creates version upgrade message record to notify mSupply central server to re-sync all broken master list items' proper information from the server to the mobile app.
=> 5544 fix app crashing when creating stocktake
